feat: add custom submit endpoint option
input-output-hk/lace pull request #1000
Opened 2024-03-27 16:31 UTC by greatertomi

# Checklist

- [x] JIRA - LW-10025, LW-10052, LW-10121
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

This PR adds the ability to submit transaction to a submit tx endpoint running in a local node.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots
<img width="956" alt="Screenshot 2024-04-08 at 15 25 36" src="https://github.com/input-output-hk/lace/assets/48496855/4bdce36c-beda-44d9-9dd1-4a5393bac9c9">

<img width="688" alt="Screenshot 2024-04-17 at 17 20 08" src="https://github.com/input-output-hk/lace/assets/48496855/a9bf9d04-86ad-46eb-b723-536629ffec1c">

<img width="679" alt="Screenshot 2024-04-08 at 15 29 25" src="https://github.com/input-output-hk/lace/assets/48496855/6756665d-5713-4d80-8b0f-28e73142951e">

<img width="682" alt="Screenshot 2024-04-17 at 17 38 59" src="https://github.com/input-output-hk/lace/assets/48496855/3b79ce35-0f5a-4a6e-a525-b28e565c5930">

2024-04-08 11:39 UTC, shawnbusuttil reviewed
Left a small comment.

2024-04-08 14:11 UTC, szymonmaslowski commented
@greatertomi Please update the PR description 🙏

2024-04-08 15:09 UTC, szymonmaslowski requested changes
GJ!

2024-04-09 12:15 UTC, greatertomi commented on apps/browser-extension-wallet/webpack-utils.js
> +          : 'http://localhost:8090'
I would look into whitelisting the entered URL only or worse case whitelisting all the ports on localhost.

2024-04-09 14:25 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/Form.tsx
> +          customIcon={<ExclamationIcon style={{ height: '72px' }} />}
`className` does not work on `<ExclamationIcon />`, so the changes I added on the .module.scss does not take effect

2024-04-09 14:26 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +import PauseIcon from '../../../../../assets/icons/pause-icon.component.svg';
Fixed on ced8b25

2024-04-09 14:26 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +        enableCustomSubmitApi(!!storage.customSubmitTxUrl);
Fixed on ced8b25

2024-04-09 14:26 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +      enable && void analytics.sendEventToPostHog(PostHogAction.SettingsCustomSubmitApiEnableClick);
Fixed on ced8b25

2024-04-09 14:26 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +            />
Fixed on ced8b25

2024-04-09 14:33 UTC, pczeglik-iohk commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +        void analytics.sendEventToPostHog(PostHogAction.SettingsCustomSubmitApiEnableClick);
SonarCloud reported issue with this line: https://sonarcloud.io/project/issues?resolved=false&pullRequest=1000&id=input-output-hk_lace&open=AY7DOzkDRsRAzljgLQUl

2024-04-09 14:36 UTC, pczeglik-iohk commented on packages/cardano/src/wallet/lib/providers.ts
> +  // TODO: Add support for custom providers
Here is another one issue pointed out by SonarCloud: https://sonarcloud.io/project/issues?resolved=false&pullRequest=1000&id=input-output-hk_lace&open=AY6AwaCXnx2I7S9bJbCA

Instead of leaving `TODO:` in code I would recommend creating real task in JIRA with the description. Who, What, How and When. Otherwise this `TODO` will be in the code base till the end like any other from **202 todos we already have** :)

2024-04-10 10:50 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/Form.tsx
> +          customIcon={<ExclamationIcon style={{ height: '72px' }} />}
Take a look at `ExpandButton.tx` it seems to have a similar example.

2024-04-11 18:29 UTC, szymonmaslowski commented
Did we think about whether the custom node submission should be set for lace globally (all restored wallets) or per specific wallet?

2024-04-12 10:39 UTC, szymonmaslowski requested changes

2024-04-12 10:39 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +      await reloadWallet();
IMO all of those three actions should not be under the responsibility of the UI. They should be moved to the `useWalletManager` as a new method and UI should call that method.

```
const { enableCustomSubmitApi } = useWalletManager();
...
await enableCustomSubmitApi(customSubmitTxUrl);
```

2024-04-15 08:41 UTC, greatertomi commented on apps/browser-extension-wallet/webpack-utils.js
> +          : 'http://localhost:8090'
Whitelisted on d06ec1f

2024-04-15 10:49 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +      await reloadWallet();
Fixed on 613cc05

2024-04-15 10:49 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/CustomSubmitApiDrawer.tsx
> +  }, [enableCustomSubmitApi]);
Fixed on 613cc05

2024-04-15 10:49 UTC, greatertomi commented on packages/cardano/src/wallet/lib/providers.ts
> +  // TODO: Add support for custom providers
Removed on 613cc05

2024-04-15 11:34 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/Form.tsx
> +          customIcon={<ExclamationIcon style={{ height: '72px' }} />}
Fixed on 0a3c06e

2024-04-15 16:54 UTC, shawnbusuttil approved these changes
✅

2024-04-16 07:56 UTC, szymonmaslowski approved these changes
GJ!

2024-04-16 07:56 UTC, szymonmaslowski commented on apps/browser-extension-wallet/webpack-utils.js
> +          ? 'http://localhost:3000 http://localhost:3001 http://localhost:8080 http://localhost:* ws://localhost:3000 ws://0.0.0.0:3000/ws wss://localhost:3000  ws://localhost:3001 ws://0.0.0.0:3001/
```suggestion
          ? 'http://localhost:* ws://localhost:3000 ws://0.0.0.0:3000/ws wss://localhost:3000  ws://localhost:3001 ws://0.0.0.0:3001/ws wss://localhost:3001'
```

2024-04-16 08:03 UTC, greatertomi commented on apps/browser-extension-wallet/webpack-utils.js
> +          ? 'http://localhost:3000 http://localhost:3001 http://localhost:8080 http://localhost:* ws://localhost:3000 ws://0.0.0.0:3000/ws wss://localhost:3000  ws://localhost:3001 ws://0.0.0.0:3001/
Fixed on 0e14164

2024-04-17 22:55 UTC, szymonmaslowski requested changes

2024-04-17 22:55 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/components/CustomSubmitApiWarningBanner/CustomSubmitApiWarningBanner.tsx
> +import React from 'react';
Please export this component in the `components/index.ts` so its imports can be shorter.

2024-04-17 22:55 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/components/CustomSubmitApiWarningBanner/CustomSubmitApiWarningBanner.tsx
> +/* eslint-disable unicorn/no-null */
Since the same banner is rendered also in staking I would suggest moving this component to `@lace/common` to avoid duplication.

2024-04-17 22:55 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +      walletType: state.walletType,
Could you please remove unnecessary properties from the selector function? Only 5 properties are accessed but there are many more selected 😕

2024-04-17 22:55 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +      <Staking currentChain={currentChain} theme={theme.name} isCustomSubmitApiEnabled={isCustomSubmitApiEnabled} />
IMO it would be better if you pass this information through the `OutsideHandlesProvider`. Then you wouldn't need any changes in the `DelegationPortfolio` store or other components in the middle because this information could be just accessed using a `useOutsideHandles` hook.

2024-04-18 12:47 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +      <Staking currentChain={currentChain} theme={theme.name} isCustomSubmitApiEnabled={isCustomSubmitApiEnabled} />
Fixed on 39a837f

2024-04-18 12:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +      walletType: state.walletType,
Fixed on 39a837f

2024-04-18 12:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/CustomSubmitApiWarningBanner/CustomSubmitApiWarningBanner.tsx
> +/* eslint-disable unicorn/no-null */
Fixed on 39a837f

2024-04-19 08:18 UTC, szymonmaslowski approved these changes

2024-04-24 15:29 UTC, emiride approved these changes
I tested it on preview and everything works as expected.

2024-04-24 17:47 UTC, merged