[LW-9597] Transaction expiry date
input-output-hk/lace pull request #1008
Opened 2024-04-01 16:50 UTC by lucas-barros

# Checklist

- [x] JIRA - https://input-output.atlassian.net/browse/LW-9597
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Add expiry date for send flow and dapp transaction confirmation.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-04-03 07:09 UTC, VanessaPC requested changes
A few small comments, also, what does it happen when a transaction validity interval is expired?

2024-04-03 07:09 UTC, VanessaPC commented on packages/core/src/ui/components/DappTransaction/DappTransaction.tsx
> +        <div className={styles.depositContainer}>
Is it possible to move this to it's own component in package UI, most of the data in this component gets passed down to the UI and it's more clear.

2024-04-03 07:09 UTC, VanessaPC commented on packages/core/src/ui/components/OutputSummaryList/OutputSummaryList.tsx
> +        <RowContainer>
Then you can reuse here.

2024-04-03 07:09 UTC, VanessaPC commented on packages/ui/src/design-system/dapp-transaction-summary/dapp-transaction-field.component.tsx
> +import type { ReactNode } from 'react';
'transactionField' could be any field in the transaction, can we be more specific in this one?

2024-04-03 08:13 UTC, VanessaPC commented on packages/core/src/ui/components/OutputSummaryList/OutputSummaryList.tsx
> +                <span>{expiresBy.utcTime} UTC</span>
UTC is string, let's move it to translations :)

2024-04-03 14:50 UTC, lucas-barros commented on packages/core/src/ui/components/OutputSummaryList/OutputSummaryList.tsx
> +                <span>{expiresBy.utcTime} UTC</span>
Fixed here: https://github.com/input-output-hk/lace/pull/1008/commits/aeba5afe56fd05b746a775dc8e3d22b240edeb95

2024-04-03 14:50 UTC, lucas-barros commented on packages/ui/src/design-system/dapp-transaction-summary/dapp-transaction-field.component.tsx
> +import type { ReactNode } from 'react';
Fixed here: https://github.com/input-output-hk/lace/pull/1008/commits/3e1a2cb1512e6c6e8e5b8fb70f7ec92be1b09a01

2024-04-03 14:55 UTC, lucas-barros commented on packages/core/src/ui/components/OutputSummaryList/OutputSummaryList.tsx
> +        <RowContainer>
There are some styling diferences between send flow confirmation and dapp confirmation. In my opnion, to use the UI components here we need to remove all the local components here and replace with TransactionSummary components.

2024-04-03 14:56 UTC, lucas-barros commented
> A few small comments, also, what does it happen when a transaction validity interval is expired? currently the dapp-connector doesn't open.

I'm not sure. The submitted transaction should fail, but I don't know why dapp connector doesnt open.

2024-04-03 15:25 UTC, VanessaPC commented
> > A few small comments, also, what does it happen when a transaction validity interval is expired? currently the dapp-connector doesn't open.
> 
> I'm not sure. The submitted transaction should fail, but I don't know why dapp connector doesnt open.

It does fail.. but silently. That's on your branch. If you want to see it yourself, I can tell you where the dapp connector is.. 
<img width="576" alt="Screenshot 2024-04-03 at 16 24 55" src="https://github.com/input-output-hk/lace/assets/4052063/a0b8f1ac-612a-41de-8855-6428f2ef9bbe">

2024-04-04 07:10 UTC, VanessaPC commented on packages/core/src/ui/components/DappTransaction/DappTransaction.tsx
> +        <div className={styles.depositContainer}>
I saw it now, then I'd say either extract this out so it's clear and it reads nice, 
```
const  getExpireByText = expiresBy ? (
                <Flex flexDirection="column" alignItems="flex-end">
                  <span>{expiresBy.utcDate}</span>
                  <span>{expiresBy.utcTime} UTC</span>
                </Flex>
              ) : (
                t('core.outputSummaryList.noLimit')
              )
     ```

2024-04-04 10:02 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/utils/__tests__/summary-slot-datetime.test.ts
> +    expect(summarySlotDatetime(undefined, testSlot)).toEqual(undefined);
Let's add the second case where slot is undefined here

2024-04-04 10:05 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/utils/summary-slot-datetime.ts
> +export const summarySlotDatetime = (
```suggestion
export const eraSlotDateTime
```

2024-04-04 10:09 UTC, DominikGuzei approved these changes

2024-04-04 13:23 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/summary-slot-datetime.ts
> +export const summarySlotDatetime = (
https://github.com/input-output-hk/lace/pull/1008/commits/4a57cf1788f4cb683cafbbcbfef3c8be255840b9

2024-04-04 13:23 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/__tests__/summary-slot-datetime.test.ts
> +    expect(summarySlotDatetime(undefined, testSlot)).toEqual(undefined);
https://github.com/input-output-hk/lace/pull/1008/commits/0b842caa2a2d5183eceabb06fe198f11a932c4a3

2024-04-04 13:24 UTC, lucas-barros commented on packages/core/src/ui/components/DappTransaction/DappTransaction.tsx
> +        <div className={styles.depositContainer}>
https://github.com/input-output-hk/lace/pull/1008/commits/9b5efa1135dbd9d932acba3605a23bcceb3c99ff

2024-04-04 14:04 UTC, VanessaPC approved these changes
Nice 🚀 !

2024-05-08 14:52 UTC, ljagiela approved these changes

2024-05-08 18:44 UTC, merged