test(extension): LW-10167 add from/to section dapp tx and new ui elem…
input-output-hk/lace pull request #1011
Opened 2024-04-02 15:23 UTC by bslabiak

2024-04-03 08:00 UTC, wklos-iohk requested changes

2024-04-03 11:22 UTC, bslabiak commented on packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx
> +        testId="dapp-transaction-from-section-expander"
I do not see the issue on my side. Please rebuild

2024-04-03 11:22 UTC, bslabiak commented on packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx
> +                      testId="dapp-transaction-from-row"
as above

2024-04-03 11:22 UTC, bslabiak commented on packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx
> +        testId="dapp-transaction-to-section-expander"
as above

2024-04-03 11:22 UTC, bslabiak commented on packages/core/src/ui/components/DappAddressSections/DappAddressSections.tsx
> +                      testId="dapp-transaction-to-row"
as above

2024-04-03 11:22 UTC, bslabiak commented on packages/core/src/ui/components/DappTransaction/DappTransaction.tsx
> +                testId="dapp-transaction-summary-row"
as above

2024-04-03 11:22 UTC, bslabiak commented on packages/core/src/ui/components/DappTransactionHeader/DappTransactionHeader.tsx
> +      <SummaryExpander title={t('package.core.dappTransaction.origin')} testId="dapp-transaction-origin-expander">
as above

2024-04-03 11:26 UTC, bslabiak commented on packages/e2e-tests/src/assert/dAppConnectorAssert.ts
> +  adjustAssetList = async (assetsList: string[]) =>
This adjustment is specific for dappconnector asset list using in cucumber, it wont be utility for other places. Maybe I can change name to `adjustDappCucumberAssetList` to make it more clear?

2024-04-03 11:33 UTC, bslabiak commented on packages/e2e-tests/src/assert/dAppConnectorAssert.ts
> +  subtractFee = async (entry: string) => {
subtractFee and shortenAddress are also very tight to adjustmentList. I will suggest to use more specific name like:
`subtractFeeFromCucumberListElement` `shortenAddressFromCucumberListElement`

2024-04-03 11:33 UTC, bslabiak commented on packages/e2e-tests/src/assert/dAppConnectorAssert.ts
> +  shortenAddress = (wallet: string) => {
as above

2024-04-03 11:34 UTC, bslabiak commented on packages/e2e-tests/src/elements/dappConnector/confirmTransactionPage.ts
> +  get transactionDepositTitle() {
Yes it will be for further coverage

2024-04-03 11:34 UTC, bslabiak commented on packages/e2e-tests/src/elements/dappConnector/confirmTransactionPage.ts
> +  get transactionDepositValueAda() {
Yes it will be for further coverage

2024-04-03 11:34 UTC, bslabiak commented on packages/e2e-tests/src/elements/dappConnector/confirmTransactionPage.ts
> +  get transactionReturnedDepositValueAda() {
Yes it will be used for further test coverage

2024-04-03 11:34 UTC, bslabiak commented on packages/e2e-tests/src/elements/dappConnector/confirmTransactionPage.ts
> +  get transactionReturnedDepositTitle() {
Yes it will be used for further test coverage

2024-04-03 11:37 UTC, bslabiak commented on packages/e2e-tests/src/pageobject/dAppConnectorPageObject.ts
> +  async expandSectionInDappTransactionWindow(section: 'Origin' | 'From address' | 'To address') {
How we should tell which one should be in ConfirmTransactionPage and dAppConnectorPageObject ? What is reasoning behind the decision?

2024-04-03 11:37 UTC, bslabiak commented on packages/e2e-tests/src/pageobject/dAppConnectorPageObject.ts
> +  async getTransactionToAssetsRows() {
as above

2024-04-03 11:38 UTC, bslabiak commented on packages/e2e-tests/src/pageobject/dAppConnectorPageObject.ts
> +    await browser.pause(1000);
I think it should be stable enough to work even without this pause. I will remove it

2024-04-03 11:38 UTC, bslabiak commented on packages/e2e-tests/src/pageobject/dAppConnectorPageObject.ts
> +  async getTransactionFromAssetsRows() {
as above

2024-04-04 06:52 UTC, wklos-iohk commented on packages/e2e-tests/src/pageobject/dAppConnectorPageObject.ts
> +  async expandSectionInDappTransactionWindow(section: 'Origin' | 'From address' | 'To address') {
Well, despite the (misleading) name `dAppConnectorPageObject` is not a POM, hence it would be good to not use it at all and put relevant web element definitions and actions related to them together, in real POMs.

For instance:
```
  async expandSectionInDappTransactionWindow(section: 'Origin' | 'From address' | 'To address') {
    await ConfirmTransactionPage.transactionOriginSectionExpanderButton.waitForDisplayed();
    await browser.pause(1000);
    switch (section) {
      case 'Origin':
        await ConfirmTransactionPage.transactionOriginSectionExpanderButton.click();
        break;
      case 'From address':
        await ConfirmTransactionPage.transactionFromSectionExpanderButton.click();
        break;
      case 'To address':
        await ConfirmTransactionPage.transactionToSectionExpanderButton.scrollIntoView();
        await ConfirmTransactionPage.transactionToSectionExpanderButton.click();
        break;
      default:
        throw new Error(`Unsupported section name: ${section}`);
    }
  }
```

As you can see above, all actions triggered by this method are within `ConfirmTransactionPage` scope, hence it fits better into `ConfirmTransactionPage` POM. 

https://martinfowler.com/bliki/PageObject.html
https://webdriver.io/docs/pageobjects/

2024-04-04 07:06 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/dAppConnectorAssert.ts
> +  adjustAssetList = async (assetsList: string[]) =>
The suggested name looks much better. However we use the files with name `...Assert.ts` to store assertions, and this one does not look like an assertion, even if it's tightly related to some assertion, hence imho it is not the best place for it.

The same applies to remaining comments for this file.

2024-04-08 09:36 UTC, ljagiela approved these changes

2024-04-09 09:00 UTC, wklos-iohk approved these changes

2024-04-09 11:45 UTC, merged