feat(extension) add FOOR buy ADA button to Banxa
input-output-hk/lace pull request #1016
Opened 2024-04-03 10:03 UTC by tommayeliog

# Checklist

- [X] JIRA - [LW-5104](https://input-output.atlassian.net/browse/LW-5104)
- [-] Proper tests implemented
- [X] Screenshots added.

---
## Proposed solution
But ADA button added for Tokens page on the side bar (or under portfolio ballance, when no sidebar visible).
Hidden behind a feature flag USE_BANXA_TOPUP
If user agrees T&C and click "Continue" a new Tab opens with Banxa url.

## Testing
For testing please change locally USE_BANXA_TOPUP=true 

## Screenshots
<img width="1237" alt="Screenshot 2024-04-03 at 11 02 22" src="https://github.com/input-output-hk/lace/assets/143514860/13a66a61-f642-46f7-8b06-5537792139a6">
<img width="1249" alt="Screenshot 2024-04-03 at 11 02 33" src="https://github.com/input-output-hk/lace/assets/143514860/c758aa42-dd5d-4cba-ad75-03c91f66c1bb">
<img width="544" alt="Screenshot 2024-04-03 at 11 02 43" src="https://github.com/input-output-hk/lace/assets/143514860/e905c18f-7213-419f-8abf-2d03e364723f">
<img width="520" alt="Screenshot 2024-04-03 at 11 02 59" src="https://github.com/input-output-hk/lace/assets/143514860/ef645ee0-b064-47cc-ae7f-c84133fbc0f1">

2024-04-03 12:25 UTC, vetalcore requested changes

2024-04-03 12:25 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx
> +          open={open}
this one will always be true

2024-04-03 12:25 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWallet.module.scss
> +  color: var(--White, #FFF);
could you please use proper color from _light/_dark.scss

2024-04-03 20:30 UTC, pczeglik-iohk commented on apps/browser-extension-wallet/.env.defaults
> +USE_BANXA_TOPUP=true
Are we sure we would like to have this feature turned on by default?

2024-04-03 20:37 UTC, pczeglik-iohk commented
@tommayeliog when you will have this feature ready to be merge, please remember to put JIRA ticket ID like `LW-xxxx` into the commit message. This helps to identify JIRA task by the commit message. You can check commit from main to get some inspiration ;) https://github.com/input-output-hk/lace/commits/main/

2024-04-03 20:40 UTC, pczeglik-iohk commented on apps/browser-extension-wallet/.env.defaults
> +USE_BANXA_TOPUP=true
Oh, and I would consider using the feature toggle's name which does not contain the provider name. Maybe something like `USE_FOOR_TOPUP` or just `USE_FOOR`. But this is only suggestion :)

2024-04-04 06:30 UTC, mchappell commented on apps/browser-extension-wallet/.env.defaults
> +USE_BANXA_TOPUP=true
yeh best turn this off once you're ready for final review @tommayeliog

2024-04-04 09:25 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx
> +export const TopUpWalletButton = (): React.ReactElement => {
Thanks @przemyslaw-wlodek, yes,  it's a button and a modal. It's not stated on the JIRA ticket but maybe at some point a new requirement will be added for the modal to be visible just once. Then Button will be  much more relevant. TBO I don't know - maybe TopUpWalletButtonConfirmation?

2024-04-04 09:53 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletCard.tsx
> +    <div>
Thanks, it's leftover - removed.

2024-04-04 09:53 UTC, tommayeliog commented on apps/browser-extension-wallet/.env.defaults
> +USE_BANXA_TOPUP=true
> Thanks @mchappell @pczeglik-iohk it's off now, and renamed.

2024-04-04 09:54 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWallet.module.scss
> +  color: var(--White, #FFF);
Thanks @vetalcore I've change it to  --color-white. This color will always be white regardless of theme because it's on specific background

2024-04-04 09:54 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWallet.module.scss
> +}
Thanks! added

2024-04-04 09:54 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx
> +  const gotoBanxa = useCallback(() => tabs.create({ url }), [url]);
Thanks

2024-04-04 09:54 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx
> +      {open && (
This was to prevent `agreed` state to persists if open the modal again, but after we discussed it I'm resetting the `agreed` back to false on close.

2024-04-04 09:54 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx
> +          open={open}
Thanks, fixed

2024-04-04 10:00 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletDialog.tsx
> +        onClick={() => setAgreed(!agreed)}
Thanks @przemyslaw-wlodek, it's fixed. 

As a side note I would prefer if Checkbox exposes onCheckedChange instead of onClick and we can use the real checkbox.checked state instead of flipping the local state.

2024-04-04 13:01 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/views/browser-view/components/TopUpWallet/TopUpWalletButton.tsx
> +export const TopUpWalletButton = (): React.ReactElement => {
I'd consider `TopUpWallet` then 😃 WDYT?

2024-04-04 13:02 UTC, przemyslaw-wlodek approved these changes
I've left 1 minor comment about naming. Thank you @tommayeliog! GJ 🚀 Feel free to proceed when you resolve other comments.

2024-04-08 15:52 UTC, vetalcore approved these changes

2024-05-20 14:27 UTC, vetalcore approved these changes

2024-05-21 08:21 UTC, merged