feat(extension,cardano,core): LW-9808 revamp hardware wallet onboarding
input-output-hk/lace pull request #1020
Opened 2024-04-03 23:35 UTC by szymonmaslowski

# Checklist

- [x] JIRA - [\<link>](https://input-output.atlassian.net/browse/LW-9808)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-04-05 10:32 UTC, szymonmaslowski commented on packages/cardano/src/wallet/lib/hardware-wallet.ts
> +export const ledgerDescriptor = { vendorId: ledgerUSBVendorId };
FIlter also by the product id in order to avoid accepting untested device

2024-04-05 10:35 UTC, szymonmaslowski commented on packages/cardano/src/wallet/lib/hardware-wallet.ts
> +const trezorModelTProductId = 0x53c1;
Double check if this value is exported from some trezor package

2024-04-08 07:36 UTC, danielmain requested changes
Requested some changes due typescript errors

2024-04-08 07:36 UTC, danielmain commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  const createHardwareWalletRevamped = useCallback<CreateHardwareWalletRevamped>(
I get here a typescript error
```
Argument type ({accountIndex, connection, name}: {accountIndex: any, connection: any, name: any}) => Promise<{wallet: object & Shutdown, name: string, source: {wallet: {walletId: string, metadata: Wallet.WalletMetadata, accounts: Bip32WalletAccount<Wallet.AccountMetadata>[], type: WalletType.Ledger | WalletType.Trezor}, account: Bip32WalletAccount<Wallet.AccountMetadata>}, signingCoordinator: SigningCoordinator<Wallet.WalletMetadata, Wallet.AccountMetadata>}> is not assignable to parameter type CreateHardwareWalletRevamped  
```

I solved one of the issues below as suggestion. Similar can be applied here

2024-04-08 07:36 UTC, danielmain commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  const createHardwareWallet = useCallback(
I get here a typescript error
```
Argument type {accountIndex: number, name: string, connection: {type: WalletType.Trezor | WalletType.Ledger, value: _LedgerConnection}} is not assignable to parameter type CreateHardwareWalletRevampedParams 
```

This solves the issue
```typescript
  const createHardwareWallet = useCallback(
  async ({
  accountIndex = 0,
  deviceConnection,
  name,
  connectedDevice
  }: CreateHardwareWallet): Promise<Wallet.CardanoWallet> => {
  const connection;
  if (typeof deviceConnection !== 'boolean' || connectedDevice === WalletType.Ledger) {
  connection.value = deviceConnection as LedgerConnection;
  }
  return createHardwareWalletRevamped({
  accountIndex,
  connection,
  name
  });
  },
  [createHardwareWalletRevamped]
  );
```

2024-04-08 11:51 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/HardwareWalletFlow.tsx
> +          <Redirect from="/" to={route('connect')} />
Can we have variables for route names here?

2024-04-08 11:55 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/StepConnect.tsx
> +  const [discoveryState, setDiscoveryState] = useState<'idle' | 'requested' | 'running'>('requested');
Could use a formal `type` here and use variables to refer to them throughout the file.

2024-04-08 11:55 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/StepConnect.tsx
> +        if (error.innerError?.innerError?.message === 'The device is already open.') {
Why do we have `innerError` twice?

2024-04-08 11:58 UTC, shawnbusuttil reviewed
Left some comments, will have a second look later on.

2024-04-08 13:40 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/StepConnect.tsx
> +        if (error.innerError?.innerError?.message === 'The device is already open.') {
This is how it is done in the SDK. The actual error gets two times caught and is wrapped with SDK error that exposes the caught error under the innerError property. It could be improved next time we work on that piece of code.

2024-04-08 13:54 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  const createHardwareWallet = useCallback(
Sorry, I don't get those errors, same as two other devs I asked to check it. Could you ensure your dev env is up to date?

2024-04-09 08:22 UTC, danielmain requested changes
Requests small changes. Pls overall avoid eslint-ignore. Thank you!

2024-04-09 08:22 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/HardwareWalletFlow.tsx
> +    setConnection(undefined);
why not setConnection() - so you can remove the eslint disable in top.

2024-04-09 08:22 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/HardwareWalletFlow.tsx
> +/* eslint-disable unicorn/no-useless-undefined */
remove all `undefined` so you can remove this eslint disable

2024-04-09 08:22 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/StepConnect.tsx
> +        new Promise<'timeout'>((resolve) => setTimeout(() => resolve('timeout'), threeSecondsTimeout))
you can avoid the eslint-disable if you create a separate function

```typescript
const timeoutPromise = (duration: number): Promise<'timeout'> => 
  new Promise<'timeout'>(resolve => setTimeout(() => resolve('timeout'), duration));
```

And you call it here:
```typescript
timeoutPromise(threeSecondsTimeout);
```

2024-04-09 08:48 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/HardwareWalletFlow.tsx
> +/* eslint-disable unicorn/no-useless-undefined */
I can't. Typescript requires an argument to the `useState`'s set functions, so I have to pass an `undefined` there. Alternatively, I could turn the `useState`'s type to accept `null` (`useState<Type | null>`) as an empty value but `null`s are also forbidden by the eslint. Banning this rule here is the lesser evil.

2024-04-09 08:49 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/HardwareWalletFlow.tsx
> +    setConnection(undefined);
https://github.com/input-output-hk/lace/pull/1020#discussion_r1557241278

2024-04-10 07:50 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/HardwareWalletFlow.tsx
> +/* eslint-disable unicorn/no-useless-undefined */
I understand ;)

2024-04-11 09:33 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/helpers.ts
> +export const isMultidelegationSupportedByDevice = async (walletType: Wallet.HardwareWallets): Promise<boolean> => {
Added the unit tests here: https://github.com/input-output-hk/lace/pull/1020/files#diff-6badb31cccaf60732e05f3e2c0d16f56659314e2577f6163c844bf8bcdbc99ca

2024-04-11 09:38 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/isMultidelegationSupportedByDevice.ts
> +export const isMultidelegationSupportedByDevice = async (walletType: Wallet.HardwareWallets): Promise<boolean> => {
This function was here before, [here is the original file](https://github.com/input-output-hk/lace/pull/1020/files#diff-1d3a40adf553fd869f0136e68016f75bbb7e39fc2ab95b693183a77716b26510). I moved the interactions with SDK's HW implementation to the `cardano` package and fixed the bug of incorrect version comparison.

2024-04-11 10:33 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow/makeErrorDialog.tsx
> +export const makeErrorDialog =
This component is used in two different flows for different error codes, so I allowed it to accept a error type

2024-04-11 10:34 UTC, szymonmaslowski commented on packages/cardano/src/wallet/lib/hardware-wallet.ts
> +const ledgerNanoXWithCardanoAppOpenProductId = 16_405;
We support 3 ledger models (S, S+, X) and for each of them, there is a different `productId` if they have cardano app open or no app open. In order to properly guide the user we need to handle both states.

2024-04-11 12:36 UTC, shawnbusuttil approved these changes
Gj. All good from my side.

2024-04-11 14:06 UTC, danielmain approved these changes
LQTM awesome job!

2024-04-15 07:30 UTC, emiride approved these changes
I tested this to check if nothing is broken.
I additionally tested multidelegation with Trezor and Ledger.
Everything works as expected.

2024-04-15 09:25 UTC, merged