fix(extension): make the address book sorting case insensitive
input-output-hk/lace pull request #103
Opened 2023-06-08 13:46 UTC by vetalcore

# Checklist

- [x] https://input-output.atlassian.net/browse/LW-6092
- [x] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

sort the items using localCompare util in the storage helpers

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-08 13:58 UTC, mchappell approved these changes

2023-06-26 12:58 UTC, lgobbi-atix commented on apps/browser-extension-wallet/src/features/address-book/context/__test__/context.test.tsx
> +  (dbIntance: WalletDatabase): FunctionComponent =>
```suggestion
  (dbInstance: WalletDatabase): FunctionComponent =>
```

2023-06-27 06:38 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/address-book/context/__test__/context.test.tsx
> +  (dbIntance: WalletDatabase): FunctionComponent =>
resolved

2023-06-29 15:39 UTC, miorsufianiohk requested changes
Hi @vetalcore ,

When I tested, I wasn't able to get the names to sort naturally. Could you have a look please. [This is how it should have been sorted](https://input-output.atlassian.net/browse/LW-6092?focusedCommentId=185288) and [Here is the screenshot of what I saw in Lace](https://drive.google.com/file/d/1-d4PkXxluoisZcAk9ie7J09YxMo9vZcz/view?usp=sharing) . Thank you

2023-07-05 10:25 UTC, closed without merging