feat: add search functionality to NFTs
input-output-hk/lace pull request #1039
Opened 2024-04-08 11:15 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<LW-10023>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Added search functionality to NFTs (when user has 10+). 
Logging events to PostHog when user is searching.
Breadcrumbs added for NFT directory path.

## Testing

Note: Enable the Post Hog environment variable when testing events unless you are using an account that is opted in. Use an account with 10 or more NFTs.

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/27725122/de52b672-9b1a-439a-9421-b456b0fb169e)

![image](https://github.com/input-output-hk/lace/assets/27725122/f613293e-43b5-467c-971a-b9817e190ae0)

![image](https://github.com/input-output-hk/lace/assets/27725122/8ea3cc41-8ef3-49da-b167-367e11bb861e)

2024-04-09 14:28 UTC, szymonmaslowski requested changes
GJ! I left a few comments.

2024-04-09 14:28 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +      item.name.toLowerCase() === searchValue.toLowerCase() ||
IMO it would have better experience if we searched for a partial string
```suggestion
      item.name.toLowerCase().includes(searchValue.toLowerCase()) ||
```

2024-04-09 17:18 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +    }, DEBOUNCE_TIME)();
But I don't want it to work for every keystroke. It's not about server calls.

2024-04-09 17:20 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/nfts/selectors.ts
> +  const selectedFolder: Partial<NftFoldersSchema> | undefined = list?.find((folder: NftFoldersSchema) =>
We need to pass in the attribute. I agree that it might be a bit unconventional - where else would you suggest?

2024-04-09 17:22 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +      item.name.toLowerCase() === searchValue.toLowerCase() ||
How did we leave it on assets?

2024-04-09 17:26 UTC, shawnbusuttil commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            id={`$copy-${value}`}
The only option I can think of is also checking that `showCopyIcon` is set to true.

2024-04-09 17:28 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/NftsLayout.tsx
> +                <>
We are already grouping the duplicated logic in a hook. The right approach here would be to unify the Nft screens into a responsive one but it falls out of scope. I don't think filters should be components.

2024-04-10 09:12 UTC, shawnbusuttil commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            <CopyToClipboard text={document.querySelector(`#copy-${value}`).textContent}>
It's not risky after checking for copy icon. The value cannot be a string before the items start iterating as `value` is not a prop.

2024-04-10 09:27 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +    }, DEBOUNCE_TIME)();
Ok makes sense. The UX with the debounce is nice :+1:

2024-04-12 12:16 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/NftsLayout.tsx
> +                <>
The `handleNftSearch` functions are identical and it is the same for the markup here. It increases the duplication rate which was here before your changes. IMO the correct approach is to at least not increase the duplication.

2024-04-12 12:36 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/nfts/selectors.ts
> +  const selectedFolder: Partial<NftFoldersSchema> | undefined = list?.find((folder: NftFoldersSchema) =>
Sorry, I don't get your comment. What argument do you mean? I was wondering if this code should perform a nested search, but it seems lace doesn't support nesting directories, right?

2024-04-12 12:47 UTC, szymonmaslowski commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            <CopyToClipboard text={document.querySelector(`#copy-${value}`).textContent}>
Risky was not an accurate word. IMO this is not a correct react way 😉. It would be better if you passed raw data and constructed the breadcrumb markup inside with that data.

2024-04-12 12:51 UTC, szymonmaslowski commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            id={`$copy-${value}`}
https://github.com/input-output-hk/lace/pull/1039#discussion_r1562503257
Please pass the value as a string and then it will be correct to use it for the id string.

2024-04-12 13:02 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +      item.name.toLowerCase() === searchValue.toLowerCase() ||
Good question. IMO we should use `includes` in both places.

2024-04-15 19:00 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/nfts/selectors.ts
> +  const selectedFolder: Partial<NftFoldersSchema> | undefined = list?.find((folder: NftFoldersSchema) =>
I meant the `directory` attribute a bit more down from this line.

2024-04-15 19:02 UTC, shawnbusuttil commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            id={`$copy-${value}`}
Check the updated solution. We need to pass in the tabs somehow and this presentational component should be kept generic.

2024-04-17 23:25 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +    }, DEBOUNCE_TIME)();
Please fix the debounce :wink:

2024-04-17 23:25 UTC, szymonmaslowski commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            id={`$copy-${value}`}
Ah sorry, I didn't pay enough attention to how this component is built. Right, we cannot have a breadcrumb rendered inside. What we can do is keep the type of the `value` property as a string and add an additional property called `valueMarkup` or similar that will be optional but if provided it will be rendered instead of the `value` but the `value` will be still used for an id and value of copy to clipboard feature. WDYT?

2024-04-17 23:27 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +    }, DEBOUNCE_TIME)();
Please fix the debounce usage 😉

2024-04-18 12:09 UTC, shawnbusuttil commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            id={`$copy-${value}`}
We can also assume that if the value is not going to be copied, then we know that we don't have to pass in a string because we are not using the id for that case. Adding another prop seems a little extra.

2024-04-18 17:33 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +    }, DEBOUNCE_TIME)();
This is not a fix. Have you tried what you suggested?

2024-04-22 11:48 UTC, szymonmaslowski commented on packages/common/src/ui/components/InlineInfoList/InlineInfoList.tsx
> +            id={`$copy-${value}`}
IMO such an interconnection of two props is very implicit and would have to be described somewhere because another dev won't be aware of it and might want to pass a markup as value and have a copy-paste feature at the same time. IMO adding an additional prop makes the API clear and flexible. Moreover, it makes it possible to have a custom markup and copy-paste feature at the same time.

2024-04-22 11:52 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useNftSearch.ts
> +    }, DEBOUNCE_TIME)();
No, I didn't, I just scratched my thoughts with a code, it might not work 1:1. Let's tackle it on a call.

2024-04-23 13:50 UTC, szymonmaslowski approved these changes

2024-05-07 09:49 UTC, merged