feat: set nft as user profile avatar
input-output-hk/lace pull request #1048
Opened 2024-04-09 21:20 UTC by greatertomi

# Checklist

- [x] JIRA - LW-10051
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Set NFT as user profile avatar

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="693" alt="Screenshot 2024-04-09 at 22 13 18" src="https://github.com/input-output-hk/lace/assets/48496855/561730aa-3c9f-4d49-a149-e3ed6314e082">

### On single address wallet
<img width="508" alt="Screenshot 2024-04-09 at 22 15 27" src="https://github.com/input-output-hk/lace/assets/48496855/608bac7c-0d12-49a5-8b17-b0d1694c4a51">

### On multi-address wallet

<img width="531" alt="Screenshot 2024-04-09 at 22 14 00" src="https://github.com/input-output-hk/lace/assets/48496855/1a8bc61c-ec66-4f95-95a5-fa237b6bace5">

2024-04-12 11:44 UTC, szymonmaslowski requested changes

2024-04-12 11:44 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/DetailsDrawer.tsx
> +    setUserAvatar({ ...userAvatar, [environmentName]: image });
According to the ACs avatar should be set per wallet not per network

2024-04-16 08:10 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/nfts/components/DetailsDrawer.tsx
> +    setUserAvatar({ ...userAvatar, [environmentName]: image });
I should add that it should be per network and wallet combined.

2024-04-16 08:42 UTC, szymonmaslowski requested changes

2024-04-16 08:42 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +    (handleImage && getAssetImageUrl(handleImage));
This logic is duplicated. Please create a hook `useWalletAvatar` that will read the localstorage, handle, address and return a profile avatar.

2024-04-16 08:42 UTC, szymonmaslowski commented on packages/core/src/ui/components/Nft/NftDetail.tsx
> +  handleSetAsAvatar?: (image: string) => void;
Nitpick, you can ignore it. I think the common pattern for UI component's callback names is `on[Action]` so in this case it would be `onSetAsAvatar`

2024-04-16 11:09 UTC, greatertomi commented on packages/core/src/ui/components/Nft/NftDetail.tsx
> +  handleSetAsAvatar?: (image: string) => void;
Fixed on df099ef

2024-04-16 11:10 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +    (handleImage && getAssetImageUrl(handleImage));
Fixed on df099ef

2024-04-16 12:32 UTC, szymonmaslowski approved these changes
Bellissimo 👌

2024-04-17 14:35 UTC, emiride approved these changes

2024-04-24 11:40 UTC, merged