refactor: revamp multi wallet stages for mnemonics
input-output-hk/lace pull request #1074
Opened 2024-04-16 15:54 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<LW-10249>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

- Revamping mnemonic stages of multi wallet.
- Deprecating unused screens.

## Testing

Full acceptance criteria on LW-10249 ticket. Go through create and restore multi wallet flows.

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-04-17 10:36 UTC, greatertomi requested changes

2024-04-17 10:36 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
> +        }
We should use a different analytics event from the onboarding. Maybe we can create stubs of analytics constants with no events. There is a ticket to address analytics later and can just fill in these.

2024-04-17 10:36 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/SelectRecoveryPhraseLength.tsx
> -    wordPassphrase: t('core.walletSetupRecoveryPhraseLengthStep.wordPassphrase')
We should delete these from the translations file

2024-04-17 10:36 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
> +            : analytics.sendEventToPostHog(postHogOnboardingActions.create.ENTER_RECOVERY_PHRASE_NEXT_CLICK);
Same analytics comment as here.

2024-04-17 11:25 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
> +        }
Yes arent these in scope of another ticket?

2024-04-18 13:09 UTC, greatertomi approved these changes

2024-04-22 10:41 UTC, oldGreg5 approved these changes

2024-04-22 12:49 UTC, szymonmaslowski requested changes
Great job!

2024-04-22 12:49 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
> +import { postHogOnboardingActions } from '@providers/AnalyticsProvider/analyticsTracker';
I am not 100% sure about that, but I don't think we should use the onboarding events for the multiwallet flows. There are dedicated multiwallet events, and they should be rather adjusted to be aligned with the onboarding events. Could you please double check that? 🙏

2024-04-22 12:49 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
> -      <WalletSetupMnemonicStep
Please remove the `WalletSetupMnemonicStep` as it is not used anywhere now.

2024-04-22 12:49 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/RestoreRecoveryPhrase.tsx
> -    <WalletSetupMnemonicVerificationStep
Please remove the old component as it is no longer used.

2024-04-22 12:49 UTC, szymonmaslowski commented on packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.tsx
> +        <Modal open={videoModalOpen} centered footer={undefined} closable={false} destroyOnClose maskClosable={false}>
`Dialog.Root` has a `zIndex` prop. Modal from antd applies a `z-index` of 1000 so we need to set it to a higher number.
```suggestion
        <Dialog.Root open={videoModalOpen} setOpen={setVideoModalOpen} zIndex={1001}>
```
I don;t like that it is being passed in the markup but this is how it is implemented now :/. Despite that I would still prefer to use lace ui as the goal is to introduce it gradually and eliminate antd at some point.

We could also change the root modal of the multiwallet to lace-ui's one and that would also eliminate a problem without setting the zIndex, but I don't request it here 😉

2024-04-23 13:38 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/NewRecoveryPhrase.tsx
> +import { postHogOnboardingActions } from '@providers/AnalyticsProvider/analyticsTracker';
They will be addressed in the follow up tasks we have regarding posthog.

2024-04-23 13:46 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/components/index.ts
> -export { Home } from './Home';
There aren't any export issues. It seems like the dependents are still managing to import it.

2024-04-24 09:06 UTC, shawnbusuttil commented on packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.tsx
> +        <Modal open={videoModalOpen} centered footer={undefined} closable={false} destroyOnClose maskClosable={false}>
Resolved

2024-04-25 07:37 UTC, szymonmaslowski approved these changes
GJ 🚀 Approving, but please apply the last comment.

2024-04-25 07:37 UTC, szymonmaslowski commented on packages/core/src/ui/components/WalletSetupRevamp/WalletSetupMnemonicStepRevamp/WalletSetupMnemonicStepRevamp.tsx
> +        {/* <Modal open={videoModalOpen} centered footer={undefined} closable={false} destroyOnClose maskClosable={false}>
Please remove this commented code.

2024-05-07 10:37 UTC, merged