refactor(staking): refactor staking state hydration
input-output-hk/lace pull request #1075
Opened 2024-04-17 20:50 UTC by tommayeliog

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-04-18 11:10 UTC, przemyslaw-wlodek requested changes

2024-04-18 11:10 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +          .catch(() => null);
What will happen with `view` and other properties when it fails? We also may experience an infinite loop due to `hydrated` being always `false`.

Note: I think it's possible to have async actions in Zustand but if not then you can always set the state in `catch`.

```suggestion
        const selectedStakePools = await getPoolInfos({
          poolIds,
          preserveOrder: true,
          stakePoolProvider,
          status: [
            Wallet.Cardano.StakePoolStatus.Activating,
            Wallet.Cardano.StakePoolStatus.Active,
            Wallet.Cardano.StakePoolStatus.Retiring,
          ],
        }).catch(() => []);
        
        set((state) => {
              Object.assign(state, {
                ...atomicStateMutators.selectPools({ stakePools: selectedStakePools, state }),
                browsePoolsView: poolsView,
                hydrated: true,
                view,
              });
            });
```

2024-04-18 11:10 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolioStore/useSyncDelegationPortfolioStore.ts
> +    if (![delegationDistribution, delegationRewardsHistory, currentEpoch].every(Boolean)) return;
Is it worth checking `currentChain` and `delegationPortfolio`? I guess it was checking all the streams.

2024-04-18 11:25 UTC, mchappell commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
>      poolsView: store.browsePoolsView || DEFAULT_BROWSE_POOLS_VIEW,
where would you initially set the default if it doesn't exist (fresh install or first update) @przemyslaw-wlodek ?

2024-05-14 08:53 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
> +        stakingBrowserPreferencesPersistence?.selectedPoolIds.map((poolId) => Wallet.Cardano.PoolId(poolId)) ?? [],
thanks
try/catch added

2024-05-14 08:57 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
> +    stakingBrowserPreferencesPersistence?.selectedPoolIds,
@przemyslaw-wlodek @mchappell I'm not sure I get it.
here I'm using browsePoolsView from LocalStore and defaulting only if i
s undefined
(line 15):
poolsView: store.browsePoolsView || DEFAULT_BROWSE_POOLS_VIEW,

2024-05-14 08:58 UTC, tommayeliog commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +          .catch(() => null);
I've change this so we have empty array for browsePoolsView and hydrated in case of failed request

2024-05-14 08:59 UTC, tommayeliog commented on packages/staking/src/features/store/delegationPortfolioStore/useSyncDelegationPortfolioStore.ts
> +    if (![delegationDistribution, delegationRewardsHistory, currentEpoch].every(Boolean)) return;
thanks, I've added currentChain and delegationPortfolio to the checks

2024-05-22 11:35 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
> +    stakingBrowserPreferencesPersistence?.selectedPoolIds,
I am not sure what I was referring to, but maybe in the outdated code there were missing dependencies in the array. :)

2024-05-23 11:58 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
>      poolsView: store.browsePoolsView || DEFAULT_BROWSE_POOLS_VIEW,
fix now

2024-05-23 12:14 UTC, przemyslaw-wlodek approved these changes
Great work @tommayeliog, thank you! I added 2 minor comments, please fix them and let's move forward 😁

2024-05-24 10:57 UTC, wklos-iohk approved these changes

2024-06-03 10:29 UTC, tommayeliog commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +import { DEFAULT_BROWSE_POOLS_VIEW, DEFAULT_SORT_OPTIONS } from 'features/BrowsePools/constants';
done!

2024-06-06 06:54 UTC, przemyslaw-wlodek approved these changes
I feel sorry that you faced this weird dependency issue. Please add some comments that we want to improve at some point. Thanks! 🍻

2024-06-06 06:54 UTC, przemyslaw-wlodek commented on packages/staking/.storybook/__mocks__/cardano.tsx
> +import { Cardano, util } from '@cardano-sdk/core';
AFAIR these changes are not needed. If that's true -> please revert. 🙏🏻

2024-06-06 13:33 UTC, merged