refactor(core): refactor activityDetails to use dApp components [LW-10281]
input-output-hk/lace pull request #1085
Opened 2024-04-22 12:24 UTC by tommayeliog

# Checklist

- [x] JIRA - [LW-10281](https://input-output.atlassian.net/browse/LW-10281)
- [x] Proper tests implemented
- [x] Screenshots added.

---
## Proposed solution
In this PR I'm making a refactoring that will use core dApp components for both dApp modal and for TransactionDetails screen, more specifically: certificates, proposalProcedures and voteProcedures.

Core and Extension packages are using shared functions for raw data mapping and test/storybook mocks.

Note: DappInfo has been removed from core certificates/proposal components and it's on the containers in extenstion package. 

## Testing
Use storybook and `yarn test` for testing both extension and core.
If you are able to test the application, then check is it correct when switching networks.

## Screenshots
<img width="1021" alt="Screenshot 2024-05-02 at 12 11 11" src="https://github.com/input-output-hk/lace/assets/143514860/43b267ba-26ea-4806-a469-d6091fb28b44">
<img width="1211" alt="Screenshot 2024-05-02 at 12 10 40" src="https://github.com/input-output-hk/lace/assets/143514860/b04246f4-434d-4a61-a4fd-6a1f5517847d">
<img width="1215" alt="Screenshot 2024-05-02 at 12 10 59" src="https://github.com/input-output-hk/lace/assets/143514860/f67f003e-87ba-4b83-b339-e6b04b0b1a01">

[LW-10281]: https://input-output.atlassian.net/browse/LW-10281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-05-06 14:13 UTC, przemyslaw-wlodek requested changes
Great refactor @tommayeliog! 🚀 Please take a look if my comments are helpful. We can catch up :)

2024-05-06 14:13 UTC, przemyslaw-wlodek commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsCertificates/CertificateView.tsx
> +}: CertificateViewProps): React.ReactElement => {
[optional] Can we somehow reduce the duplication here? I see there are no common props across all certificates 🤔

2024-05-06 14:13 UTC, przemyslaw-wlodek commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsCertificates/TxDetailsCertificates.tsx
> +  // metadata copy
🤔 what's the meaning of this comment?

2024-05-06 14:13 UTC, przemyslaw-wlodek commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsProposalProcedures.tsx
> +        })}
Please extract this mapper outside of the render body e.g. `renderProposalProcedure`

2024-05-07 10:33 UTC, tommayeliog commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/TransactionDetailsProxy.tsx
> +        explorerBaseUrl={explorerBaseUrl} // test for network switch
Thanks, I removed the comment and added a note in the description

2024-05-07 10:34 UTC, tommayeliog commented on packages/core/src/ui/components/ProposalProcedures/components/ProcedureTransactionDetails.tsx
> +export const ProcedureTransactionDetails = ({ txTitle, deposit, rewardAccount, translations }: Props): JSX.Element => {
thanks, component renamed

2024-05-07 10:35 UTC, tommayeliog commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +  // );
thanks, comment removed

2024-05-07 10:36 UTC, tommayeliog commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsCertificates/TxDetailsCertificates.tsx
> +  // metadata copy
removed

2024-05-07 10:53 UTC, tommayeliog commented on packages/cardano/src/wallet/util/voter.ts
> +export const votingProceduresRawToViewMap = (
thanks, changed

2024-05-07 10:56 UTC, tommayeliog commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsCertificates/CertificateView.tsx
> +      console.error('Not supported certificate:', certificate);
changed to throw and error

2024-05-07 12:32 UTC, tommayeliog commented on packages/cardano/src/wallet/util/voter.ts
> +};
yeah, we need this because we are using it for translate concatenation

2024-05-07 12:37 UTC, tommayeliog commented on packages/core/src/ui/utils/governance-action.ts
> +export const parameterChangeActionDataMap = ({
thanks, renamed!

2024-05-07 12:46 UTC, tommayeliog commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmStakeVoteRegistrationDelegationContainer.tsx
> +      <TransactionSummary.Metadata label={t('core.StakeVoteDelegationRegistration.metadata')} text="" />
empty
it's a required parameter in UI package

2024-05-07 13:24 UTC, tommayeliog commented on packages/core/src/ui/utils/governance-action.ts
> +export const updateCommitteeActionDataMap = ({
renamed

2024-05-07 13:26 UTC, tommayeliog commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmDRepRegistrationContainer.tsx
>    // TODO: might be changed in scope of https://input-output.atlassian.net/browse/LW-9034
I'm removing this comment LW-9034 is completed.

2024-05-07 13:26 UTC, tommayeliog commented on packages/core/src/ui/utils/governance-action.ts
> +export const hardForkInitiationActionDataMap = ({
all mappers I've renamed to get....

2024-05-07 13:28 UTC, tommayeliog commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsCertificates/CertificateView.tsx
> +}: CertificateViewProps): React.ReactElement => {
as we discussed we will leave this as it is

2024-05-07 13:28 UTC, tommayeliog commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsProposalProcedures.tsx
> +        })}
a new component has been made

2024-05-07 13:29 UTC, tommayeliog commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmStakeVoteDelegationContainer.tsx
> +        // dappInfo={dappInfo}
yes, a leftover - thanks (removed)

2024-05-07 13:35 UTC, tommayeliog commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsCertificates/CertificateView.tsx
> +  console.debug(`unknown certificate: ${certificate.__typename}`);
thanks, throw new Error added

2024-05-07 13:36 UTC, tommayeliog commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsCertificates/CertificateView.tsx
> +      console.error('Not supported certificate:', certificate);
@mchappell please let me know if ErrorBoundry required

2024-05-08 08:49 UTC, przemyslaw-wlodek commented on packages/core/src/ui/components/ActivityDetail/components/TxDetailsVotingProcedures.tsx
> +          Wallet.util.mapVotingProceduresToView(votingProcedure, explorerBaseUrl)
`mapVotingProceduresToView` -> `mapVotingProcedureToView`

2024-05-08 09:43 UTC, tommayeliog commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +  const data = hardForkInitiationActionDataMap({
Thanks, I've added useMemo to all ...ActionContainers

2024-05-08 09:44 UTC, tommayeliog commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/ParameterChangeActionContainer/ParameterChangeActionContainer.tsx
> +  // TODO: consider encapsulating it inside the component itself, check if all the translations have the fallback to the parent int provider (LW-9920)
removed (actually moved to the component where translations are used)

2024-05-08 09:44 UTC, tommayeliog commented on packages/core/src/ui/components/ProposalProcedures/ParameterChangeAction/ParameterChangeAction.tsx
> +  const translations: Types.Translations = {
thanks, restored

2024-05-08 11:34 UTC, przemyslaw-wlodek approved these changes
Great work! :)

2024-05-21 07:50 UTC, wklos-iohk approved these changes

2024-05-21 11:59 UTC, mchappell approved these changes

2024-05-21 12:48 UTC, merged