feat(extension): implement fuzzy search in fetch stake pool slice and…
input-output-hk/lace pull request #1120
Opened 2024-05-01 10:33 UTC by vetalcore

… utils

# Checklist

- [ ] JIRA - [LW-10378](https://input-output.atlassian.net/browse/LW-10378)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-05-01 12:17 UTC, mchappell requested changes

2024-05-01 12:17 UTC, mchappell commented on apps/browser-extension-wallet/src/stores/slices/stake-pool-search-slice.ts
> +          _condition: 'or',
there shouldn't be a need for this `or` as it's the only possible field, you can probably safely remove this

2024-05-01 12:17 UTC, mchappell commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/utils.ts
> +        _condition: 'or',
same comment about removing this one

2024-05-01 12:27 UTC, vetalcore commented on apps/browser-extension-wallet/src/stores/slices/stake-pool-search-slice.ts
> +          _condition: 'or',
done here a917106da9d9c0643cf82fbc7d45e226e2960b6d

2024-05-01 12:28 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/utils.ts
> +        _condition: 'or',
done here https://github.com/input-output-hk/lace/commit/a917106da9d9c0643cf82fbc7d45e226e2960b6d

2024-05-02 14:46 UTC, mchappell approved these changes
Great change 💪

2024-05-03 09:06 UTC, mchappell approved these changes

2024-05-07 15:19 UTC, wklos-iohk approved these changes

2024-05-13 10:09 UTC, merged