Chore/lw 10534 translation package
input-output-hk/lace pull request #1154
Opened 2024-05-11 10:06 UTC by vetalcore

# Checklist

- [ ] JIRA -[LW-10534](https://input-output.atlassian.net/browse/LW-10534)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Move all the translations files and i18n instance into the separate package.

## Testing

All the translations should work the same.

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-05-13 09:24 UTC, tommayeliog approved these changes
LGTM!

2024-05-13 10:23 UTC, mchappell commented
@vetalcore `packages/e2e-tests/src/utils/translationService.ts` will need updating to point at the correct `browser-extension-wallet` and `core` translation files, this should get the e2e tests running

2024-05-14 08:18 UTC, mchappell requested changes
Once storybook changes have been corrected, happy to pass this on, looks like that's the only remaining change left. Great work 🎉

2024-05-14 12:15 UTC, mchappell approved these changes
Great job on the refactor, much easier to have all this in one place. Did you ever consider moving all translations into a single file?

2024-05-14 12:29 UTC, DominikGuzei commented
Yeah i also wonder why the translations are still split up 🤔 since they are already namespaced it would make sense to merge them? (although we would have to namespace some of the extension translations i think)

2024-05-14 12:31 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/TermsDrawer.tsx
> +import { useTranslation } from 'react-i18next';
im not sure if that's the correct import?

2024-05-15 09:12 UTC, vetalcore commented
> Yeah i also wonder why the translations are still split up 🤔 since they are already namespaced it would make sense to merge them? (although we would have to namespace some of the extension translations i think)

it's just easier to handle the changes this way, we could easily handle that as a next iteration.

2024-05-17 06:40 UTC, wklos-iohk approved these changes

2024-05-17 06:41 UTC, merged