feat: add creation flow layout for shared wallet [DRAFT]
input-output-hk/lace pull request #1174
Opened 2024-05-22 12:02 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-05-27 13:57 UTC, szymonmaslowski requested changes
GJ

2024-05-27 13:57 UTC, szymonmaslowski commented on apps/browser-extension-wallet/.env.defaults
> +USE_SHARED_WALLET=true
We should not enable it on master until it is done

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SetupSharedWallet/SetupSharedWallet.module.scss
> +}
Please add a new line

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SetupSharedWallet/SetupSharedWallet.tsx
> +    return sharedWalletName ? validationError : translations.nameRequiredMessage;
```suggestion
    const valid = !validateNameLength(sharedWalletName);
    return valid ? translations.nameMaxLength : translations.nameRequiredMessage;
```

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SetupSharedWallet/SetupSharedWallet.tsx
> +    nameRequiredMessage: t('core.walletNameAndPasswordSetupStep.nameRequiredMessage')
```suggestion
    nameMaxLengthErrorMessage: t('core.walletNameAndPasswordSetupStep.errorMessage.nameMaxLength'),
    nameRequiredMessageErrorMessage: t('core.walletNameAndPasswordSetupStep.errorMessage.nameRequiredMessage')
```

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.module.scss
> +}
Please add a new line

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +  toolTipText?: string;
not used

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +  customAction?: React.ReactNode;
I would remove it. We don't have a use case for it in a shared wallet. I prefer to follow YAGNI and add something only if it is needed and don't maintain (e.g. consider when changing styles of this area) code that is not used.

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +  skipLabel?: string;
not used

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +    { key: SharedWalletTimelineSteps.WALLET_DETAILS, name: i18n.t('core.sharedWalletStep.walletDetails') }
```suggestion
    { key: SharedWalletTimelineSteps.WALLET_NAME, name: i18n.t('core.sharedWalletLayout.timelineStep.walletName') },
    { key: SharedWalletTimelineSteps.ADD_COSIGNERS, name: i18n.t('core.sharedWalletLayout.timelineStep.addCosigners') },
    { key: SharedWalletTimelineSteps.DEFINE_QUORUM, name: i18n.t('core.sharedWalletLayout.timelineStep.defineQuorum') },
    { key: SharedWalletTimelineSteps.WALLET_DETAILS, name: i18n.t('core.sharedWalletLayout.timelineStep.walletDetails') }
```

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +export interface SharedWalletStepLayoutRevampProps {
Can we make `children`, `description` and `currentTimelineStep` required?

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +  return walletSteps.map((step) => ({ ...step, active: false }));
```suggestion
  return walletSteps.map((step, index, self) => {
    const previousStepActive = self[index-1]?.active || false;
    return {
      ...step,
      active: step.key === currentStep || previousStepActive
    };
  });
```

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +  const nextButtonContainerRef = useRef(null);
not used

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +    { key: SharedWalletTimelineSteps.WALLET_NAME, name: i18n.t('core.sharedWalletStep.walletName') },
```suggestion
const getTimelineSteps = (currentStep: SharedWalletTimelineSteps, t: TFunction) => {
  const walletSteps = [
    { key: SharedWalletTimelineSteps.WALLET_NAME, name: t('core.sharedWalletStep.walletName') },
```

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +  backLabel?: string;
```suggestion
  customNextLabel?: string;
  customBackLabel?: string;
```

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.tsx
> +    skip: t('core.walletSetupStep.skip')
not used

2024-05-27 13:57 UTC, szymonmaslowski commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletNameInput.tsx
> +      data-testid="wallet-name-input-error"
With this change element is always visible even if there is no error. This will probably break the automated tests

2024-05-27 14:42 UTC, greatertomi commented on packages/core/src/ui/components/SharedWallet/SetupSharedWallet/SetupSharedWallet.tsx
> +/* eslint-disable sonarjs/no-identical-functions */
This `eslint-disable` serves no purpose. it can be removed.

2024-05-27 14:42 UTC, greatertomi commented on packages/core/src/ui/components/SharedWallet/SharedWalletLayout/SharedWalletLayout.stories.tsx
> +// import { QuorumOption } from "../Quorum";
This comment can be removed

2024-05-27 19:46 UTC, szymonmaslowski commented on packages/core/src/ui/components/SharedWallet/SetupSharedWallet/SetupSharedWallet.tsx
> +    return sharedWalletName ? validationError : translations.nameRequiredMessage;
I just realized my suggestion doesn't work.

2024-05-27 20:39 UTC, szymonmaslowski commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletNameInput.tsx
> +      data-testid="wallet-name-input-error"
Another thing is that IMO this should be rather fixed by removing the `shouldShowErrorMessage` prop and showing the `p` if `errorMessage` is provided.

2024-05-27 23:12 UTC, szymonmaslowski approved these changes

2024-05-28 08:23 UTC, greatertomi approved these changes

2024-05-29 15:11 UTC, merged