fix/unblock  analytics tests + move create_alias event to 'enter wallet' button click
input-output-hk/lace pull request #1183
Opened 2024-05-23 15:14 UTC by oldGreg5

Unblock tests LW-8311,LW-7365 [here](https://input-output.atlassian.net/browse/LW-10488).
After discussion with @vhulchenko-iohk and @szymonmaslowski I moved create_event sending to 'enter wallet' button click

2024-05-23 15:22 UTC, szymonmaslowski approved these changes

2024-05-23 15:45 UTC, bslabiak commented on packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
>        | $create_alias                                                                                |
Should we sent $merge_dangerously event on normal onboarding? I tough it is just for multiwallet feature when we merging 2 wallets together.

2024-05-23 21:55 UTC, szymonmaslowski commented on packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
>        | $create_alias                                                                                |
I didn't know that. Then this is a bug 😉

2024-05-24 14:43 UTC, oldGreg5 commented on packages/e2e-tests/src/features/analytics/AnalyticsOnboardingEvents.feature
>        | $create_alias                                                                                |
Bug registered LW-10635 but it's simple change and will be fixed by this PR

2024-05-24 21:15 UTC, szymonmaslowski requested changes

2024-05-24 21:15 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/hardware-wallet/context.tsx
> +    }
Please add `mergeEventRequired` to the array in line 219

2024-05-27 10:25 UTC, szymonmaslowski requested changes

2024-05-27 10:25 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/hardware-wallet/context.tsx
> +    if (mergeEventRequired) {
Could we please keep the order of events in the HW and restore/create flows (useHotWalletCretion) the same? In the restore/create we send them in the order of: alias, merge, hd, but in here HW it is: merge, hd, alias. Should we change the order here to the same as in the restore/create?

2024-05-27 12:48 UTC, szymonmaslowski approved these changes

2024-05-27 15:04 UTC, merged