test(extension): implement test for nft search
input-output-hk/lace pull request #1189
Opened 2024-05-24 12:47 UTC by emiride

# Checklist

- [x] JIRA - [\<link>](https://input-output.atlassian.net/browse/LW-10610)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Implement the following tests:
- https://input-output.atlassian.net/browse/LW-10457
- https://input-output.atlassian.net/browse/LW-10456
- https://input-output.atlassian.net/browse/LW-10454
- https://input-output.atlassian.net/browse/LW-10455

2024-05-24 14:50 UTC, ljagiela requested changes

2024-05-24 14:50 UTC, ljagiela commented on packages/e2e-tests/src/elements/NFTs/nftDetails.ts
> +    try {
maybe instead of try/catching you could just check: `await this.folderPathPart2.isDisplayed()` ?

2024-05-24 14:50 UTC, ljagiela commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  const actualFolderPath = await NftDetails.getFolderValue();
I know it's super simple, but I'd move it to assertion class.

2024-05-27 06:44 UTC, wklos-iohk requested changes

2024-05-27 06:44 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  NftAssert.assertSeeNFTDetailsForlderPath(folderPath);
`await` keyword is missing

2024-05-27 06:44 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +Then(/^I see NFTs Folder value: "([^"]*)"$/, async (folderPath: string) => {
How about replacing `value` with `path`?

2024-05-27 06:44 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/NFTs/nftDetails.ts
> +  get folderLabel() {
This one seems to be unused, will it be used in a future?

2024-05-27 06:44 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/nftAssert.ts
> +  async assertSeeNFTDetailsForlderPath(folderPath: string) {
typo: `Forlder`

2024-05-27 06:44 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/NFTs/nftDetails.ts
> +  async getFolderValue(): Promise<string> {
Ho about `getFolderPath()` ?

2024-05-27 08:29 UTC, emiride commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +Then(/^I see NFTs Folder value: "([^"]*)"$/, async (folderPath: string) => {
replaced

2024-05-27 08:29 UTC, emiride commented on packages/e2e-tests/src/elements/NFTs/nftDetails.ts
> +  get folderLabel() {
removed

2024-05-27 08:30 UTC, emiride commented on packages/e2e-tests/src/assert/nftAssert.ts
> +  async assertSeeNFTDetailsForlderPath(folderPath: string) {
fixed

2024-05-27 08:30 UTC, emiride commented on packages/e2e-tests/src/elements/NFTs/nftDetails.ts
> +  async getFolderValue(): Promise<string> {
renamed

2024-05-27 08:30 UTC, emiride commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  NftAssert.assertSeeNFTDetailsForlderPath(folderPath);
added

2024-05-27 08:30 UTC, emiride commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  const actualFolderPath = await NftDetails.getFolderValue();
moved

2024-05-27 08:38 UTC, wklos-iohk approved these changes

2024-05-27 11:56 UTC, ljagiela approved these changes

2024-05-27 13:11 UTC, merged