test(extension): lw-10603 add multiwallet onboarding wallets / automation own address
input-output-hk/lace pull request #1192
Opened 2024-05-27 16:49 UTC by bslabiak

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-05-28 08:23 UTC, wklos-iohk commented on packages/e2e-tests/src/utils/parseWalletAddress.ts
> +    case 'main':
How about using enums for address types?

2024-05-28 08:24 UTC, wklos-iohk commented on packages/e2e-tests/src/utils/parseWalletAddress.ts
> +      return String(getTestWallet(wallet).address as string);
`as string` is not needed as we wrap the whole value with `String(...)` method

2024-05-28 08:31 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/sendTransactionSimpleSteps.ts
> +  async (bundleIndex, receivingAddress, addressType, options) => {
Nitpick: it would be nice to define types for those params

2024-05-28 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/dAppConnectorSteps.ts
> +  async (addressTag, section: 'From address' | 'To address') => {
Nitpick: please add a type for `addressTag`

2024-05-28 09:05 UTC, wklos-iohk requested changes

2024-05-28 09:54 UTC, bslabiak commented on packages/e2e-tests/src/utils/parseWalletAddress.ts
> +export const parseWalletAddress = async (wallet: string, addressType = 'main'): Promise<string> => {
Added custom step for copied address `And I fill bundle with copied address and "15" ADA` as it was just filling one bundle with ada and removed `copied` from parser and enum

2024-05-28 11:32 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/sendTransactionSimpleSteps.ts
> +When(/^I fill bundle with copied address and "([^"]*)" ADA$/, async (adaValue: string) => {
I'd remove double quotes from here as we pass numerical values

2024-05-28 11:34 UTC, wklos-iohk commented on packages/e2e-tests/src/utils/parseWalletAddress.ts
> +export const parseWalletAddress = async (wallet: string, addressType = 'main'): Promise<string> => {
Please remove double quotes as we pass numerical values here and we're good to go

2024-05-29 10:37 UTC, wklos-iohk approved these changes

2024-06-03 15:10 UTC, ljagiela approved these changes

2024-06-03 15:45 UTC, merged