fix(extension): fix asset item sizings
input-output-hk/lace pull request #120
Opened 2023-06-13 15:12 UTC by vetalcore

# Checklist

- [x] [JIRA - \<link>](https://input-output.atlassian.net/browse/LW-6138)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

apply proper stylings (**_width would be a bit different in case the scrollbar is there*_**)

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="363" alt="Screenshot 2023-06-13 at 18 05 45" src="https://github.com/input-output-hk/lace/assets/7934077/54eb992d-5075-49d2-8c9c-bc23b09da670">

<img width="361" alt="Screenshot 2023-06-13 at 18 08 18" src="https://github.com/input-output-hk/lace/assets/7934077/799a7811-030b-44a4-9bd4-61761e190692">

2023-06-13 15:46 UTC, mchappell requested changes
A few typos to fix and looks good to hand off

2023-06-13 15:46 UTC, mchappell commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +  infinitScrollContainerClass,
```suggestion
  infiniteScrollContainerClass,
```

2023-06-13 15:46 UTC, mchappell commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +}: Omit<InfiniteScrollProps, 'loader'> & { loaderConfig?: SkeletonProps; infinitScrollContainerClass?: string }) => (
```suggestion
}: Omit<InfiniteScrollProps, 'loader'> & { loaderConfig?: SkeletonProps; infiniteScrollContainerClass?: string }) => (
```

2023-06-13 15:46 UTC, mchappell commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +    className={cn(styles.infinitScrollContainer, { [infinitScrollContainerClass]: infinitScrollContainerClass })}
```suggestion
    className={cn(styles.infiniteScrollContainer, { [infiniteScrollContainerClass]: infiniteScrollContainerClass })}
```

2023-06-13 15:46 UTC, mchappell commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +  infinitScrollContainerClass,
```suggestion
  infiniteScrollContainerClass,
```

2023-06-14 07:55 UTC, vetalcore commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.module.scss
>  .infinitScrollContainer {
resolved

2023-06-14 07:56 UTC, vetalcore commented on packages/core/src/ui/components/AssetTable/AssetTable.tsx
> +  const [hasScollBar, setHasScrollBar] = useState<boolean>(false);
resolved

2023-06-14 07:56 UTC, vetalcore commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +    infinitScrollContainerClass={infinitScrollContainerClass}
resolved

2023-06-14 07:56 UTC, vetalcore commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +  infinitScrollContainerClass,
resolved

2023-06-14 07:56 UTC, vetalcore commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +    {...infitineScrollProps}
resolved

2023-06-14 07:56 UTC, vetalcore commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +}: Omit<InfiniteScrollProps, 'loader'> & { loaderConfig?: SkeletonProps; infinitScrollContainerClass?: string }) => (
resolved

2023-06-14 07:56 UTC, vetalcore commented on packages/common/src/ui/components/Table/InfiniteScrollableTable.tsx
> +  infinitScrollContainerClass,
resolved

2023-06-15 09:12 UTC, mchappell approved these changes

2023-06-15 14:21 UTC, wklos-iohk approved these changes

2023-06-16 09:03 UTC, merged