feat: add keys option to the add shared wallet modal main page
input-output-hk/lace pull request #1227
Opened 2024-06-18 11:41 UTC by szymonmaslowski

# Checklist

- [x] JIRA - [\<link>](https://input-output.atlassian.net/browse/LW-10709)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/9270461/ebdbb09d-e686-45ac-8fef-b08f06a8c414)
![image](https://github.com/input-output-hk/lace/assets/9270461/a055832a-ea17-4fad-b4f9-790e73bd4ecf)
![image](https://github.com/input-output-hk/lace/assets/9270461/bef79c43-ee72-49e2-9aab-bc726737fc68)

2024-06-18 12:31 UTC, szymonmaslowski commented on packages/shared-wallets/src/add-shared-wallet/creation-flow/SharedWalletCreationStore.tsx
> +const makeState = defineStateShape<{
All the changes in this file are unrelated to the main goal. Initially, I took a path of creating a dedicated store for the add modal main page so I created `defineStateShape` util so it could be reused in both stores. Later on I dropped the new store, but since I found those changes beneficial, I decided to keep them. I hope you think the same. However it that is not the case I am happy to revert.

2024-06-18 12:31 UTC, szymonmaslowski commented on packages/shared-wallets/src/state-utils.ts
> +type StateObject = Record<string, unknown>;
https://github.com/input-output-hk/lace/pull/1227/files#r1644386388

2024-06-19 08:33 UTC, danielmain requested changes
Great job, Szymon. I like how you make the most of TypeScript generics. Just left small suggestions.

2024-06-19 08:33 UTC, danielmain commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStarted.tsx
> +    keysCopyToastText: 'Shared keys copied to clipboard',
should this not be placed in the translations?

2024-06-19 08:33 UTC, danielmain commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStarted.tsx
> +      duration: toastDuration,
use SNAKE_CASE for constant 🙏🏻

2024-06-19 08:34 UTC, danielmain commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStarted.tsx
> +  copyKeysToClipboard?: () => Promise<void>;
you could use typescript conditional types depending of `keysMode` maybe?

```
type BaseProps = {
  onCreateSharedWalletClick: () => void;
  onImportSharedWalletClick: () => void;
  onKeysGenerateClick: () => void;
  createAndImportOptionsDisabled: boolean;
};

type GenerateModeProps = BaseProps & {
  keysMode: 'generate';
};

type CopyModeProps = BaseProps & {
  keysMode: 'copy';
  copyKeysToClipboard: () => Promise<void>;
};

type SharedWalletGetStartedProps = GenerateModeProps | CopyModeProps;
```

2024-06-20 08:06 UTC, szymonmaslowski commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStarted.tsx
> +  copyKeysToClipboard?: () => Promise<void>;
I can do that. I just find that discriminated unions sometimes unnecessarily complicate the implementation in trivial places like here - multiple times you have to check the value of the discriminator (`keysMode` in this case) in order to access a particular key (`copyKeysToClipboard` in this case) without TS error.

2024-06-20 08:20 UTC, szymonmaslowski commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStarted.tsx
> +  copyKeysToClipboard?: () => Promise<void>;
This is an example of what I mean. I defined the discriminated union
<img width="569" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/9073c949-dce4-4bfc-9ffa-9530a01aa62d">

I cannot anymore destructure `copyKeysToClipboard` from props
<img width="750" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/9230132d-a8fc-47d7-a3ba-9535d71e0b5c">

Instead, I have to use rest operator to wrap the `copyKeysToClipboard` and `keysMode` in a object
<img width="344" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/f2ffed4f-66a8-4d34-aea3-f7fc029aee2b">

So that it is possible to access the `copyKeysToClipboard` later on.
<img width="405" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/00f574c8-60af-4bf4-9701-75357bcd7b0b">

2024-06-20 08:44 UTC, danielmain commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStarted.tsx
> +  copyKeysToClipboard?: () => Promise<void>;
Then I have the feeling we are trying to squeeze two different animals in one. Probably make two child components for copy and generate instead of one covering both.

2024-06-20 08:45 UTC, danielmain approved these changes

2024-06-20 09:27 UTC, shawnbusuttil commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/AddSharedWalletMainPageFlow.tsx
> +const makeCopyKeysToClipboard = (sharedKeys: string) => async () => {
Can be just `copyKeysToClipboard`?

2024-06-20 09:46 UTC, szymonmaslowski commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/AddSharedWalletMainPageFlow.tsx
> +const makeCopyKeysToClipboard = (sharedKeys: string) => async () => {
I would prefer to stick to the `make` prefix as it indicates the function produces the target thing 🙏

2024-06-20 09:47 UTC, vetalcore approved these changes

2024-06-20 09:47 UTC, vetalcore commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStartedOption.tsx
> +    <Icon className={cn(styles.icon, { [`${styles.disabled}`]: disabled })} data-testid={`${testId}-icon`} />
```suggestion
    <Icon className={cn(styles.icon, { [styles.disabled]: disabled })} data-testid={`${testId}-icon`} />
```

2024-06-20 09:47 UTC, vetalcore commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStartedOption.tsx
> +        { [`${styles.disabled}`]: disabled },
```suggestion
        { [styles.disabled]: disabled },
```

2024-06-20 09:47 UTC, vetalcore commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStartedOption.tsx
> +      className={cn(styles.description, { [`${styles.disabled}`]: disabled })}
```suggestion
      className={cn(styles.description, { [styles.disabled]: disabled })}
```

2024-06-20 09:52 UTC, szymonmaslowski commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/SharedWalletGetStarted/SharedWalletGetStarted.tsx
> +  copyKeysToClipboard?: () => Promise<void>;
Maybe, but I am not sure. Those two states of this components are almost identical. I don't think it is a better way to create two separate components in this case...
![image](https://github.com/input-output-hk/lace/assets/9270461/6173e494-2cfd-42d3-b46a-9f773b34b74c)
![image](https://github.com/input-output-hk/lace/assets/9270461/8e11b9be-6f23-4eae-8a61-ef7198bb1cc9)

2024-06-20 10:03 UTC, shawnbusuttil commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/AddSharedWalletMainPageFlow.tsx
> +type AddSharedWalletMainPageFlowPrps = SharedWalletGetStartedSharedProps & {
Small thing: Correct the typo here.

2024-06-20 10:04 UTC, shawnbusuttil commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/AddSharedWalletMainPageFlow.tsx
> +type AddSharedWalletMainPageFlowPrps = SharedWalletGetStartedSharedProps & {
```suggestion
type AddSharedWalletMainPageFlowProps = SharedWalletGetStartedSharedProps & {
```

2024-06-20 10:05 UTC, shawnbusuttil commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/AddSharedWalletMainPageFlow.tsx
> +const makeCopyKeysToClipboard = (sharedKeys: string) => async () => {
Sorry maybe it's a bit too early in the day for me :D - why are we making a function for this and not directly invoking it in the component using it?

2024-06-20 10:05 UTC, shawnbusuttil reviewed
Left small questions/suggestions.

2024-06-20 11:17 UTC, szymonmaslowski commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/AddSharedWalletMainPageFlow.tsx
> +const makeCopyKeysToClipboard = (sharedKeys: string) => async () => {
It is a good question 😛  I guess it is a matter of taste. I could inline it, define it in the component body right before the `return`, or do it the way I did it. I just find it cleaner this way :wink:. But I am happy to move it to the component body. Would you like me to do it?

2024-06-20 12:28 UTC, shawnbusuttil commented on packages/shared-wallets/src/add-shared-wallet/main-page-flow/AddSharedWalletMainPageFlow.tsx
> +const makeCopyKeysToClipboard = (sharedKeys: string) => async () => {
Yes please.

2024-06-20 13:22 UTC, oldGreg5 approved these changes

2024-06-20 13:40 UTC, merged