Update lint script to not tolerate warnings during linter runs
input-output-hk/lace pull request #1236
Opened 2024-06-21 00:52 UTC by ce0la

# Checklist

- [x] JIRA - \<link> https://input-output.atlassian.net/browse/LW-10614

---

## Proposed solution

This PR configures the CI to fail if one or more warnings are thrown in the linting job.

## Testing

1. Go to the actions tab here: https://github.com/input-output-hk/lace/actions/workflows/build-dev-preview.yml
2. Click on the `Run workflow` button and select `fail-linter-on-warning` from the branch selector dropdown
3. Click on `Run workflow` and wait for a few seconds while the workflow gets scheduled
4. Go into the workflow run and see the logs to confirm that the job would fail if any warnings are detected during linting

2024-06-21 11:12 UTC, michalrus approved these changes

2024-06-21 11:12 UTC, gytis-ivaskevicius approved these changes

2024-06-21 11:17 UTC, michalrus commented
@ce0la you can check where eslint is used in other places:

```
❯ find -name 'package.json' -not -path '*/node_modules/*' | xargs grep -F eslint
```

2024-06-25 10:15 UTC, pczeglik-iohk requested changes
Hi @ce0la, 

If you like to proceed with this PR, you need to fix estlint warnings in apps/browser-extension-wallet.

Smoke Tests job fails on linting it. Check this output: https://github.com/input-output-hk/lace/actions/runs/9654217184/job/26628262898

2024-06-25 12:48 UTC, pczeglik-iohk approved these changes
Looks good. Thank you @ce0la

2024-06-25 12:52 UTC, merged