[LW-6743] lace-blockchain-services installers – Linux
input-output-hk/lace pull request #124
Opened 2023-06-14 12:24 UTC by michalrus

# Checklist

- [ ] JIRA - https://input-output.atlassian.net/browse/LW-6743
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

It's a simple system tray icon that lets once control various cardano services needed as Lace's backend.

For now we can only do `tx-submit`. And we only have a Linux installer. (macOS coming next, and then Windows)

## Testing

Install (run) the `lace-blockchain-services-…-x86_64-linux.bin` file, and either follow the instructions displayed on the terminal, or use the `.desktop` entry (Start Menu → Lace Blockchain Services)

Note: before we configure proper CI, assuming you have Nix installed, you can test this by checking out this branch, and running this on Linux:
```
nix run -L .#lace-blockchain-services
```

The Ubuntu/Arch/… (non-Nix) installer can be obtained using (it will appear under `result/`):
```
nix build -L .#lace-blockchain-services-installer
```

## What was done (what to test):

1. Installer that works on a fresh & clean Ubuntu VM without Nix (should work on any other Linux distro, too)

1. After installing, you can launch the app with its `.desktop` file, i.e. Start menu → Lace Blockchain Services

1. It has proper icons everywhere (`.desktop` entry, system tray icon)

1. Once launched, it starts the services for `mainnet `

1. You can see in system process manager that there is `cardano-node`, `ogmios`, and `node` (Node.js) running the `provider-server` µ-service

1. It self-heals if you kill `ogmios` (or any other part) (e.g. `sleep 5 && pkill ogmios` in terminal, and observe the behavior in the tray menu)

1. You can switch networks from the menu (at almost any stage) – all subcomponents exit gracefully (see the log)

1. You can force-restart from the menu (at almost any stage) – all subcomponents exit gracefully (see the log) 

1. Copying backend’s URL works (paste it into a web browser, perhaps appending `/health` at the end)

1. You can open the current log file – using the default system app for opening `*.log` files

1. You can open the directory containing all log files.

1. The log file is not garbled, and contains all lines from all controlled processes' `stdout`s and `stderr`s, interleaved chronologically

1. At the beginning of the log file you can see your machine parameters

1. You can open Ogmios Dashboard from the menu – a default web browser window/tab is opened

1. You can quit – the last lines in the log file suggest this is a graceful exit of all subcomponents.

1. When starting after some time of syncing, you can see progress of replaying the ledger, and then of pushing ledger state

1. The parent process handles `SIGTERM` and `SIGINT` gracefully. Run this `pkill lace-blockch` – all subcomponents exit gracefully (see the log) 

1. `cardano-node` output is cleaned w.r.t. excessive timestamps and hostname

1. You cannot launch more than a single instance of this app – an error is shown if it’s already running

1. The log contains system health (total/free mem, load average) logged periodically (every minute)

## Screenshots

![Screenshot-20230613-133759](https://github.com/input-output-hk/lace/assets/4366292/504d367a-bead-4c4e-8a7c-c523943c5242)

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/397/5267052081/index.html) for [4e1ee9c0](https://github.com/input-output-hk/lace/pull/124/commits/4e1ee9c0b134f4133a2fb397e513a578f9836916)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 12     | 7      | 0       | 0     | 19    | ❌     |

2023-06-16 11:36 UTC, gytis-ivaskevicius requested changes
Please remove all the IFD by moving them to inputs. Also I would really like it if large inline bash scripts were in separate file so its easier to inspect/edit them

2023-06-16 11:36 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +  };
How about adding these as flake inputs?

2023-06-16 11:36 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +  })).platform.amd64;
IFD :/

2023-06-16 11:36 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +      gtk3-x11
Not actionable as of right now but in the future we should test this on wayland

2023-06-16 11:36 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +    bundled = (import nix-bundle-exe {
IFD...

2023-06-16 11:36 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +  };
Lets add this as an input as well :))

2023-06-16 11:36 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +    scriptTemplate = ''
Consider moving this to separate bash file

2023-06-16 11:36 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +  debug-servers = pkgs.writeShellScriptBin "debug-servers" ''
Consider moving this to the bash file. Also, I believe `pkgs.writers.writeBash` OOTB supports files

2023-06-16 12:02 UTC, michalrus commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +  };
Yeah, will do. In preparing macOS (an upcoming PR), it turned out, we'll need to use our own haskellNix and iohkNix – I'll reuse the ones in `inputs.cardano-node.inputs`

As for `cardanoPkgs`,  (CHaP), hmmm. If we move that to flake.nix, we won't get automatic updates. But I can add a check that makes sure that our rev is the same as Ogmios wants? What do you think?

2023-06-16 12:02 UTC, michalrus commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +  })).platform.amd64;
This will be dropped, I'll use my own haskellNix incantation =)

2023-06-16 12:03 UTC, michalrus commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +  debug-servers = pkgs.writeShellScriptBin "debug-servers" ''
This is no longer needed, I missed it! Will delete

2023-06-16 15:12 UTC, michalrus commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +      gtk3-x11
@dmitrii-gaico did, and the segfault happened on Wayland (Ubuntu 22.04.2 LTS).

Or did you mean on wayland without x11 backwards compatibility?

2023-06-16 15:21 UTC, gytis-ivaskevicius approved these changes

2023-06-16 15:21 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/common.nix
> +  # XXX: they don’t enable aarch64-darwin builds yet:
Im okay with this for the time being but can you quickly upstream this little change?

2023-06-16 15:21 UTC, gytis-ivaskevicius commented on nix/lace-blockchain-services/internal/x86_64-linux.nix
> +      gtk3-x11
I think x11 compatibility is enabled everywhere

2023-06-16 15:26 UTC, michalrus commented on nix/lace-blockchain-services/internal/common.nix
> +  # XXX: they don’t enable aarch64-darwin builds yet:
Not into 1.35.4, but it was enabled on master until yesterday (temp. change), see https://github.com/input-output-hk/cardano-node/commit/b0765fbfcad0f64afcd855a7eed3a306115e6b92

2023-06-19 10:24 UTC, dmitrii-gaico approved these changes

2023-06-20 09:02 UTC, rhyslbw approved these changes
Looks good @michalrus 🎉 

Please backlog the ability to connect to a custom network, by pointing to a local directory containing configuration. The network should be identified by reading the `networkMagic` property from genesis files.

2023-06-20 09:02 UTC, rhyslbw commented on nix/lace-blockchain-services/internal/linux-self-extracting-archive.sh
> +# XXX: Be *super careful* changing this!!! You WILL DELETE user data if you make a mistake. Ping @michalrus
What's the intent of `Ping @michalrus` ?

2023-06-20 09:03 UTC, michalrus commented on nix/lace-blockchain-services/internal/linux-self-extracting-archive.sh
> +# XXX: Be *super careful* changing this!!! You WILL DELETE user data if you make a mistake. Ping @michalrus
So that they make sure to add me as a reviewer, but this would probably happen anyway – I can remove it

2023-06-20 09:05 UTC, merged