feat: isolate network addresses between testnet
input-output-hk/lace pull request #126
Opened 2023-06-14 16:02 UTC by greatertomi

# Checklist

- [x] JIRA - LW-6813
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Previously, the address book content is shared between preview and preprod. This PR isolates the address book content based on the network. It uses `Cardano.NetworkMagics` instead of `Cardano.NetworkId`

2023-06-14 22:32 UTC, rhyslbw requested changes

2023-06-14 22:32 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const checkForDuplicateAddress = (
```suggestion
export const hasAddressBookItem = (
```

2023-06-14 22:32 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +  describe('checkAddressForDuplicate', () => {
```suggestion
  describe('hasAddressBookItem', () => {
```

2023-06-14 22:32 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +    test('has an already existing name', () => {
```suggestion
    test('has item with same name', () => {
```

2023-06-14 22:32 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +    test('has an already existing address', () => {
```suggestion
    test('has item with same address', () => {
```

2023-06-14 22:32 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +    test('has a unique name and address', () => {
```suggestion
    test('doesn't have an item with same name and address', () => {
```

2023-06-14 22:32 UTC, rhyslbw commented on packages/e2e-tests/src/features/SettingsPagePopup.feature
> +  Scenario: Popup View - Settings - Addresses are not shared when switching Test Preprod to Test Preview
```suggestion
  Scenario: Popup View - Settings - Addresses entered in Preprod context are not available when switching to Preview
```

2023-06-15 10:17 UTC, greatertomi commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const checkForDuplicateAddress = (
fixed on 0da2e3c

2023-06-15 10:17 UTC, greatertomi commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +  describe('checkAddressForDuplicate', () => {
fixed on 0da2e3c

2023-06-15 10:18 UTC, greatertomi commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +    test('has an already existing name', () => {
fixed on 0da2e3c

2023-06-15 10:18 UTC, greatertomi commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +    test('has a unique name and address', () => {
fixed on 0da2e3c

2023-06-15 10:18 UTC, greatertomi commented on packages/e2e-tests/src/features/SettingsPagePopup.feature
> +  Scenario: Popup View - Settings - Addresses are not shared when switching Test Preprod to Test Preview
fixed on 0da2e3c

2023-06-15 18:45 UTC, gabriela-ponce commented
@greatertomi Here are a few issues/inconsistencies on this PR that I was not able to reproduce in the main branch

1 - Remove an address from the list, then complete the fields to add a new one and press "Enter".
**Result:** The "Address Removed" notification is displayed again at the bottom.
Check [this](https://drive.google.com/file/d/19KGAATgrItnljnPRCb-mtNXjoYNF7x-F/view?usp=drive_link) video

2 -  Remove an address from the list. Click on another address and press "Enter".
**Result:** The "Address Removed" notification is displayed again at the bottom. Changes are not applied.
Check [this](https://drive.google.com/file/d/1l-R_LQLzdKjy8Qyp-fJyi4kwXWhxnlb2/view?usp=drive_link) video

3 - Remove an address from the list. Click on another address and press "Edit". On the edition screen, change the name and press "Enter".
**Result:** The "Address Removed" notification is displayed again at the bottom. Changes are not applied.
Check [this](https://drive.google.com/file/d/1qONNmEcnjpG1JTdUg4-nmXikDNf24FtH/view?usp=drive_link) video

2023-06-16 12:49 UTC, rhyslbw approved these changes
Great work @greatertomi :rocket:

2023-06-16 12:51 UTC, dmitrii-gaico approved these changes

2023-06-16 13:01 UTC, gabriela-ponce approved these changes

2023-06-16 13:01 UTC, merged