feat: add one more field to cosigners
input-output-hk/lace pull request #1260
Opened 2024-07-02 12:20 UTC by greatertomi

# Checklist

- [x] JIRA - LW-10725
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Add one more cosigner to the cosigners on the create shared wallet flow.

2024-07-02 15:56 UTC, vetalcore approved these changes

2024-07-02 16:00 UTC, vetalcore commented
@szymonmaslowski @greatertomi would you be able to approve the snapshots generated by chromatic? some of them seem to have sizing issues*

2024-07-04 11:04 UTC, szymonmaslowski requested changes
GJ! Leaving some comments.

2024-07-04 11:04 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/SharedWalletCreationStore.tsx
> +        prevState.coSigners[2] || createEmptyCosignerObject(),
No related to this line, but we need to make the keys input of the first object disabled so the user cannot modify it. It should also have a different label. [Here is the design](https://www.figma.com/design/RPN3V4Et7hMbXkV5ZIF75i/[deprecated]-Lace-Browser---Full-view-UI-Design?node-id=42863-479308&t=K7kLEOAFepjr1nhe-0).

2024-07-04 16:10 UTC, danielmain approved these changes

2024-07-05 13:15 UTC, shawnbusuttil approved these changes

2024-07-10 14:28 UTC, szymonmaslowski approved these changes

2024-07-10 19:48 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSigners.tsx
> +            }}
```suggestion
            labels={{
              keys: t(`sharedWallets.addSharedWallet.addCosigners.${index === indexOfCoSignersDataOfCurrentUser ? 'yourKeysInputLabel' : 'coSignerKeysInputLabel'`),
              name: t(`sharedWallets.addSharedWallet.addCosigners.${index === indexOfCoSignersDataOfCurrentUser 'yourNameInputLabel' : 'coSignerNameInputLabel'`),
            }}
```

2024-07-10 19:48 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/SharedWalletCreationStore.tsx
> +  createCosignerObject,
could we please follow single approach, eg:
```suggestion
  createCoSignerObject,
```

2024-07-10 19:48 UTC, vetalcore approved these changes

2024-07-15 11:07 UTC, merged