fix: tokens metadata is now resolved from more than one source/metadata standard
input-output-hk/lace pull request #1263
Opened 2024-07-03 07:37 UTC by AngelCastilloB

# Checklist

- [X] JIRA - [LW-10829](https://input-output.atlassian.net/browse/LW-10829)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

TBD

## Testing

TBD

## Screenshots

TBD

2024-07-03 07:43 UTC, mkazlauskas requested changes

2024-07-03 07:43 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/utils/get-token-list.ts
> +  const name = info.nftMetadata?.name || info.tokenMetadata?.name || `SingleNFT${environmentName || ''}`;
`SingleNFTMainnet` is gibberish
```suggestion
  const name = info.nftMetadata?.name || info.tokenMetadata?.name || tryEncodeToUtf8(info.assetName) || "Unnamed"`;
```

2024-07-03 07:48 UTC, AngelCastilloB commented on apps/browser-extension-wallet/src/utils/get-token-list.ts
> +  const name = info.nftMetadata?.name || info.tokenMetadata?.name || `SingleNFT${environmentName || ''}`;
@mkazlauskas this was in the original implementation, can/will change if everyone agrees tho

2024-07-03 08:14 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6014/9773774112/index.html) for [e342260f](https://github.com/input-output-hk/lace/pull/1263/commits/e342260f4e48165824e73aac4884c1b0ea07587d)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 1      | 0       | 0     | 33    | ❌     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-03 08:17 UTC, AngelCastilloB commented on apps/browser-extension-wallet/src/utils/get-token-list.ts
> +  const name = info.nftMetadata?.name || info.tokenMetadata?.name || `SingleNFT${environmentName || ''}`;
preemptively done here https://github.com/input-output-hk/lace/pull/1263/commits/41a4749f818e4fce65496b7a61ea36ac826d911d

2024-07-04 09:22 UTC, rhyslbw approved these changes
Great work @AngelCastilloB 💪

2024-07-04 09:22 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/get-token-list.ts
> +export const getTokenDisplayMetadata = (
Nice name for these functions 😎

2024-07-04 15:58 UTC, mkazlauskas commented on packages/core/src/ui/components/ImageWithFallback/ImageWithFallback.tsx
> +  defaultSrc: string;
Matching name of the component would make it more intuitive
```suggestion
  fallbackSrc: string;
```

2024-07-05 04:35 UTC, AngelCastilloB commented on packages/core/src/ui/components/ImageWithFallback/ImageWithFallback.tsx
> +  defaultSrc: string;
done here https://github.com/input-output-hk/lace/pull/1263/commits/bbc30a91464477195fc51e1564e9b11e6c0295ce

2024-07-08 12:05 UTC, mkazlauskas approved these changes
Nice work!

2024-07-09 06:59 UTC, pczeglik-iohk approved these changes
Nicely done @AngelCastilloB 💪

2024-07-12 12:12 UTC, merged