feat: create shared wallet
input-output-hk/lace pull request #1268
Opened 2024-07-04 05:02 UTC by greatertomi

# Checklist

- [ ] JIRA -LW-10578
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-04 05:29 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6037/9788760079/index.html) for [7dd7736b](https://github.com/input-output-hk/lace/pull/1268/commits/7dd7736b3d92fc49e0bc531fabe34eb88fde3860)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 1      | 0       | 0     | 33    | ❌     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-04 09:30 UTC, mkazlauskas requested changes

2024-07-04 09:30 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +    mnemonic,
The mnemonic will be the same as in `ownSignerWalletId`:
```ts
    const wallets = await firstValueFrom(walletRepository.wallets$);
    const ownWallet = wallets.find(({walletId}) => walletId === ownSignerWalletId)
    // you can create the key agent with this (I think in a constructor), instead of from mnemonic
    ownWallet.encryptedSecrets.rootPrivateKeyBytes
```

Also best to pass account index as an argument to a utility function at this level
```suggestion
    accountIndex
```

2024-07-04 09:30 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +    publicKeys,
This name would imply that you don't have to include your own key
```suggestion
    otherCoSignerXPubKeys,
```

2024-07-04 09:30 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +    const multiSigParticipants = publicKeys.sort();
The script has to also include own key, or else whoever creates the wallet won't be part of it.
```suggestion
    const multiSigParticipants = [ownXPub, ...publicKeys].sort();
```

2024-07-04 09:30 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          },
Would be better to have a variable for this, and also pass full path to `buildScript` so that if/when we want to use a different index, it only has to be modified in a single place. Same for staking key path.
```suggestion
          paymentScriptKeyPath,
```

2024-07-04 09:30 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          getPassphrase: async () => Buffer.from('password', 'utf8'),
it's a good practice to overwrite the secret in buffer once it's no longer needed, so at the end of this function. Same in the `createWallet` function. 
```suggestion
const buffer = Buffer.from(password, 'utf8');
...
          getPassphrase: async () => buffer,
...it's a good practice to overwrite the secret in buffer once it's no longer needed, so at the end of this function
buffer.fill(0);
```

2024-07-04 09:30 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  const createSharedWallet = async ({
This function doesn't seem to support HW wallets. For those you need to export own xpub by using HW key agents.
```suggestion
  const createInMemorySharedWallet = async ({
```

2024-07-04 09:30 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/types/local-storage.ts
> +  sharedWalletKey?: Wallet.Crypto.Bip32PublicKeyHex;
Why is this needed? How would this even work if you have multiple shared wallets? I suggest adding this key to `WalletMetadata` type (generic arg for the WalletRepository), so we can store it per wallet. Then once we create it, we can call `walletRepository.updateWalletMetadata`.
```suggestion
```

2024-07-04 10:10 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +const buildScript = async (expectedSigners: Array<Crypto.Bip32PublicKeyHex>, role: Wallet.KeyManagement.KeyRole) => {
We would also support "N of". I wanted to get the wallet working with "all of", and then improve it to create "N of".

2024-07-04 13:44 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +export const deriveExtendedPublicKeyHash = async (
Fixed on aaf64f5

2024-07-04 13:46 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +const buildScript = async (expectedSigners: Array<Crypto.Bip32PublicKeyHex>, role: Wallet.KeyManagement.KeyRole) => {
I updated the name to `buildSharedWalletScript` on aaf64f5 since I'll extend the function beyond "all of".

2024-07-04 13:47 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          getPassphrase: async () => Buffer.from('password', 'utf8'),
Fixed on aaf64f5

2024-07-04 13:47 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  const createSharedWallet = async ({
Fixed on aaf64f5

2024-07-04 13:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/types/local-storage.ts
> +  sharedWalletKey?: Wallet.Crypto.Bip32PublicKeyHex;
Fixed on aaf64f5

2024-07-04 15:59 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +    const multiSigParticipants = publicKeys.sort();
I passed it [here](https://github.com/input-output-hk/lace/blob/aaf64f5c7cefe93359ba01e3cbb4a8d59267959b/apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx#L55-L56) already.

2024-07-04 16:00 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +    publicKeys,
This key also contains the key of the ownSigner passed [here](https://github.com/input-output-hk/lace/blob/aaf64f5c7cefe93359ba01e3cbb4a8d59267959b/apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx#L55-L56).

2024-07-04 16:10 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +    mnemonic,
Do you mean we should create keyAgent with [this](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/key-management/test/InMemoryKeyAgent.test.ts#L259-L278) approach instead to avoid exposing the mnemonic?

Also, on `ownWallet.encryptedSecrets.rootPrivateKeyBytes`, I get this error
```
Property encryptedSecrets does not exist on type AnyWallet<WalletMetadata, AccountMetadata>
```

2024-07-09 12:51 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useAppInit.ts
> -    if (!cardanoWallet.source.account) {
@greatertomi please, anything else here?

2024-07-11 11:49 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useAppInit.ts
> -    if (!cardanoWallet.source.account) {
I don't think so.

2024-07-11 13:37 UTC, vetalcore requested changes

2024-07-11 13:37 UTC, vetalcore commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +          subtitle="Shared Wallet"
please use intl here

2024-07-11 13:37 UTC, vetalcore commented on apps/browser-extension-wallet/src/stores/types.ts
> +  password: string;
maybe it's better just to keep it locally somewhere on the component level?

2024-07-11 13:46 UTC, greatertomi commented on apps/browser-extension-wallet/src/stores/types.ts
> +  password: string;
The component is a modal, when the modal is closed the password is lost. I tried keeping it within the component and it didn't work.

2024-07-11 14:31 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +          subtitle="Shared Wallet"
Fixed on 7cb1380

2024-07-11 15:09 UTC, vetalcore commented on apps/browser-extension-wallet/src/stores/types.ts
> +  password: string;
@danielmain could you please suggest if we might get any security concerns here?

2024-07-11 16:12 UTC, greatertomi commented on apps/browser-extension-wallet/src/stores/types.ts
> +  password: string;
Fixed on d942bcd

2024-07-11 16:16 UTC, rhyslbw commented on apps/browser-extension-wallet/src/stores/types.ts
> +  password: string;
Good catch @vetalcore :mechanical_arm:

2024-07-11 18:35 UTC, vetalcore approved these changes

2024-07-12 07:45 UTC, vetalcore requested changes

2024-07-12 07:45 UTC, vetalcore commented on packages/core/src/shared-wallets/stories/SharedWalletStorybookHelper.tsx
> +import React, { VFC, useEffect, useState } from 'react';
@greatertomi this one is identical to the `packages/core/src/shared-wallets/stories/AddSharedWalletStorybookHelper.tsx`?

2024-07-12 07:45 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  const signers = [...expectedSigners].sort();
sonarlint is complaining about this one
```suggestion
  const signers = [...expectedSigners].sort((key1, key2) => key1.localeCompare(key2)));
```

2024-07-12 08:01 UTC, vetalcore commented
would you also be able to check `src/shared-wallets/add-shared-wallet/creation-flow/validateCoSigners.test.ts` since they are failing?

2024-07-12 10:59 UTC, danielmain approved these changes
Awesome Job

2024-07-12 11:01 UTC, vetalcore approved these changes

2024-07-12 11:36 UTC, merged

2024-07-14 22:04 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/main-page-flow/SharedWalletEntry/SharedWalletEntry.stories.tsx
> +import { SharedWalletEntry } from '@src/shared-wallets';
This path is incorrect and eslint raises an error here.

2024-07-14 22:04 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/main-page-flow/SharedWalletEntry/SharedWalletEntry.stories.tsx
> +    getSharedKeys: generateSharedKeysMock,
Why did we removed 3 properties? Also the added `getSharedKeys` property does not exist on the `SharedWalletEntry` component.

2024-07-15 08:47 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  purpose?: KeyManagement.KeyPurpose;
This can be removed, `purpose` is not used in `addAccount`

2024-07-15 08:49 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  createInMemorySharedWallet: (args: CreateSharedWalletParams) => Promise<Wallet.CardanoWallet>;
Martynas recommended it [here](https://github.com/input-output-hk/lace/pull/1268#discussion_r1665419122)

2024-07-15 09:21 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/main-page-flow/SharedWalletEntry/SharedWalletEntry.stories.tsx
> +    getSharedKeys: generateSharedKeysMock,
This is a conflict resolution omission. Will revert the changes to this file.

2024-07-15 12:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +  // TODO: merge with renderBip32Wallet in case wallet option is not different
Fixed this on #1291

2024-07-15 12:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  purpose?: KeyManagement.KeyPurpose;
Removed on #1291

2024-07-15 12:52 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/main-page-flow/SharedWalletEntry/SharedWalletEntry.stories.tsx
> +import { SharedWalletEntry } from '@src/shared-wallets';
Fixed on #1291