feat(extension): [lw-10527] shared tx summary
input-output-hk/lace pull request #1269
Opened 2024-07-04 11:28 UTC by vetalcore

# Checklist

- [x] JIRA - [LW-10527](https://input-output.atlassian.net/browse/LW-10527)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

[LW-10527]: https://input-output.atlassian.net/browse/LW-10527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-07-04 11:57 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6043/9793521512/index.html) for [b04aa528](https://github.com/input-output-hk/lace/pull/1269/commits/b04aa528f31f6db62e3bf13bc8c34b8cc4bd353a)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 0      | 0       | 0     | 33    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-05 13:08 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +
```suggestion
 const role = ownAddress === txInitiator ? 'summary' : 'cosigners';
const status = !cosigners.some((c) => c.address === ownAddress && c.signed) ? 'unsigned' : 'unsubmitted';

const description = t(`sharedWallets.transaction.${role}.${status}.description`);

```

2024-07-05 13:11 UTC, shawnbusuttil commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +    <div data-testid="tx-hash" className={styles.hashContainer}>
Using the components from toolkit, we can potentially eliminate external stylesheets.

2024-07-05 13:12 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  // addrInputs?: TxOutputInput[];
Are these meant to be commented out? There is an unused imports in this file.

2024-07-05 13:12 UTC, shawnbusuttil requested changes
Left some comments.

2024-07-08 07:49 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +
resolved

2024-07-08 07:55 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +    <div data-testid="tx-hash" className={styles.hashContainer}>
i don't think there is proper component to cover this one in the toolkit package

2024-07-08 07:57 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  // addrInputs?: TxOutputInput[];
resolved

2024-07-08 11:36 UTC, shawnbusuttil commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +    <div data-testid="tx-hash" className={styles.hashContainer}>
I meant using Box. Is that not possible?

2024-07-09 06:42 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +    <div data-testid="tx-hash" className={styles.hashContainer}>
TxHash is just a jsx piece that i've extracted from the huge TransactionDetails component, i'd rather keep it as it was since the refactoring is out of scope for this ticket and might cause more regression

2024-07-09 11:25 UTC, szymonmaslowski requested changes
Great job! I left some comments. We can have a call to discuss them 😉

2024-07-09 11:25 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/transaction/CosignersList.tsx
> +export const CosignersList = ({ list, title, ownAddress }: CosignerItemProps) => {
Did you check this component in a narrow view? Probably it will also be rendered in the popup view.

2024-07-09 11:25 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  ownAddress: string;
```suggestion
  ownSharedKey: Crypto.Ed25519KeyHashHex;
```

2024-07-09 11:25 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  const [isCosignersOpened, setIsCosignersOpened] = useState(true);
I think the correct form is `open`.
```suggestion
  const [isSummaryOpen, setIsSummaryOpen] = useState(true);
  const [isCosignersOpen, setIsCosignersOpen] = useState(true);
```

2024-07-09 15:13 UTC, danielmain commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  addressToNameMap: Map<string, string>;
@greatertomi can you pls confirm 🙏🏻

2024-07-09 15:32 UTC, danielmain commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +};
Only a question, why did we duplicate this file instead of adding a component that shows "cosigner-stuff"?

2024-07-09 15:34 UTC, danielmain approved these changes
If you address @szymonmaslowski suggestion I am fine with this PR.

Great job @vetalcore 💪🏻

2024-07-10 09:06 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +export const Content: React.FC = ({ children }) => (
i'd probably create a tech debt ticket to refactor this component and the one used in the tx summary in the send flow (and maybe the one related to the staking tx) since they share most of the common logic but still,
i do not consider this one as a separate building block of the tx details flow, even thought i found it the easiest just to extract it this way to be sharable between shared wallet and plain tx details
hope that makes sense @szymonmaslowski

2024-07-10 09:10 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +                ) as unknown as string
same as prev one, would suggest to keep it this way, will create a ticket to adjust this one on the toolkit level 
wdyt?

2024-07-10 09:41 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  addressToNameMap: Map<string, string>;
@szymonmaslowski addressToNameMap has nothing to do with the sharedKeys, please follow the implementation of `TxSummarySection` component in the `packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx`

2024-07-10 09:46 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +};
shared wallet tx summary looks slightly different and existing transaction details component is not that configurable :(

2024-07-10 09:48 UTC, vetalcore commented on packages/core/src/shared-wallets/stories/transaction-details.stories.tsx
> +  title: 'Main / Transaction',
resolved here da5017fa09f52aed18610ba5bf40c57b173aec76

2024-07-10 09:48 UTC, vetalcore commented on packages/core/src/shared-wallets/stories/transaction-details.stories.tsx
> +import { action } from '@storybook/addon-actions';
done here da5017fa09f52aed18610ba5bf40c57b173aec76

2024-07-10 09:48 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +/* eslint-disable no-magic-numbers */
removed most of them da5017fa09f52aed18610ba5bf40c57b173aec76

2024-07-10 09:48 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  cosigners: CosignerItemProps['list'];
done here da5017fa09f52aed18610ba5bf40c57b173aec76

2024-07-10 09:48 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  ownAddress: string;
shared wallet does not have an address? 
anyway, these would be probably changed during the integration

2024-07-10 09:48 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  const [isCosignersOpened, setIsCosignersOpened] = useState(true);
done here da5017fa09f52aed18610ba5bf40c57b173aec76

2024-07-10 10:25 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/CosignersList.tsx
> +export const CosignersList = ({ list, title, ownAddress }: CosignerItemProps) => {
looks okay for mobile

2024-07-10 10:25 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/CosignersList.tsx
> +    <div data-testid="cosigner-list" className={styles.cosignersList}>
done here e0562349e4270d88fab678504f2e94555ae63406

2024-07-10 21:23 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +                ) as unknown as string
IMO changing the type of the `message` prop should be a quick one, so making a change, creating a PR, reviewing it, and releasing a new version of the toolkit, should not take long if we coordinate ourselves well.
However, I will accept the argument that considering our time pressure it is not worth making an effort to eliminate this type-casting. @danielmain?

2024-07-10 21:30 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  addressToNameMap: Map<string, string>;
Ah sorry, my bad.

2024-07-10 21:50 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  ownAddress: string;
It is not about the shared wallet address, but the shared key of the user. This prop is used to distinguish the current user on the list of the cosigners, right? In the designs, there are addresses `addr_shared...`. I think we should display the shared keys there instead, so the hex string.
Please change the prop name 😉

2024-07-11 04:26 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +  ownAddress: string;
done here f4fbd3435da13968423bd0a468daa6d489288914

2024-07-11 06:26 UTC, danielmain commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +export const Content: React.FC = ({ children }) => (
@vetalcore, I think moving the components to separate files would be quick. Before we disable ESLint rules, let's consider if there's a significant shortcut that justifies this change 🙏🏻 (it could save hours of development time).

2024-07-11 06:32 UTC, danielmain commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +/* eslint-disable no-magic-numbers */
I see you left the complexity off, IMO this ESLint rule has no real value and is being ignored in many places. @vetalcore can you please add this in the root eslintrc `'complexity': 'off',`

2024-07-11 07:10 UTC, danielmain commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +                ) as unknown as string
if this can be done quick why not?

2024-07-11 11:28 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +export const Content: React.FC = ({ children }) => (
done here 314dea15fc9c2b5ad1b50a34ffb34dcdd930cabb

2024-07-11 11:28 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/TransactionDetails.tsx
> +                ) as unknown as string
done here 314dea15fc9c2b5ad1b50a34ffb34dcdd930cabb

2024-07-11 13:55 UTC, shawnbusuttil approved these changes

2024-07-11 15:10 UTC, danielmain approved these changes

2024-07-11 15:10 UTC, merged