Feat/UI Toolkit Control Button
input-output-hk/lace pull request #128
Opened 2023-06-14 21:33 UTC by mrcnk

# Checklist

- [x] JIRA - LW-6847
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

- Added missing variants and pieces to Control Button.
- Added more elements to Storybook.

## Screenshots

<img width="1199" alt="image" src="https://github.com/input-output-hk/lace/assets/16132011/a0e4e954-dc1c-444c-bd05-85bbcea7b92a">

2023-06-15 16:55 UTC, renanvalentin commented
- [ ] Double-check the box-shadow of the buttons

![Screenshot 2023-06-15 at 13 49 44](https://github.com/input-output-hk/lace/assets/2846918/398bbf4f-8c51-46e1-853e-c22a649daa86)

- [ ] Button label has the wrong color applied

![Screenshot 2023-06-15 at 13 53 00](https://github.com/input-output-hk/lace/assets/2846918/adbbe1b9-2a6b-415f-9119-5f162a8f0c42)

- [ ] Double check button min-width

![Screenshot 2023-06-15 at 13 53 44](https://github.com/input-output-hk/lace/assets/2846918/514b8def-c859-4596-be82-724c2c6de728)

![Screenshot 2023-06-15 at 13 54 14](https://github.com/input-output-hk/lace/assets/2846918/114dcf71-b3f0-4047-b378-51dd0a640abc)

- [ ] Icons doesn't look sharp

![Screenshot 2023-06-15 at 13 54 37](https://github.com/input-output-hk/lace/assets/2846918/6182ec48-8581-4f15-86c8-69e3347864ed)

2023-06-15 17:02 UTC, renanvalentin requested changes
Great job @mrcnk ! I have only spotted a few minor issues on the visual side compared to Figma. The rest looks good!

2023-06-15 17:02 UTC, renanvalentin commented on packages/ui/src/design-system/control-buttons/types.ts
> +export enum Scheme {
Please, rename this file to `controls-buttons.data.ts`. The `*.data.ts` defines the data representation of the UI component, application logic, and types.

2023-06-16 16:55 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/control-button.css.ts
> +    border: '2px solid',
Resolved

2023-06-16 16:58 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/types.ts
> +export enum Scheme {
Hey, the `.data.ts` file naming convention isn't clear to me and it seems like an unwritten rule. I get there are some unique file extensions like `css.ts` for styles and `component.css` for component logic, but I'm not too convinced about using `data.ts` over `types.ts` just like for example in Card component. If there should be any rule like this that would be preventing from merging the code, please first discuss it on our toolkit channel as RFC.

2023-06-16 19:28 UTC, renanvalentin commented on packages/ui/src/design-system/control-buttons/types.ts
> +export enum Scheme {
We have a ticket to document the file naming convention and possibly an eslint rule to ensure the convention (see LW-6974). 

I understand that you may disagree with the current approach. At the same time, using a different naming convention will make it even more confusing as there will be no standard. So let's stick with `*.data.ts` for now.

My original design used `*.data.ts` for the above mentioned purpose. In the meantime, you can start a new RFC thread to discuss the current file naming convention so we can review it during innovation week.

2023-06-19 06:18 UTC, szymonmaslowski requested changes
Good job!

2023-06-19 06:18 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/control-button.css.ts
> +export const borderGap = createVar();
This variable is redundant as it is not used more than once.

2023-06-19 06:18 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/control-button.css.ts
> +        outlineColor: `${vars.colors.$control_buttons_container_outlineColor}`,
```suggestion
        outlineColor: vars.colors.$control_buttons_container_outlineColor,
```

2023-06-19 06:18 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/icon-button.component.tsx
> +};
The common part of this type repeats 4 times. Please extract it it as a shared type and reuse
```suggestion
import { ControllButtonCommonProps } from './types';
type IconProps = Omit<ControllButtonCommonProps, 'label'>;
```

2023-06-19 06:18 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/outlined-button.component.tsx
> +        label: cx.label(),
There are outilne variants of container's `colorScheme`, `borderScheme` and `paddingScheme` and a label's `colorScheme` as well. Aren't they needed to be passed here?

2023-06-19 06:18 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/danger-button.component.tsx
> +            colorScheme: Scheme.Danger,
As I can see there is no case where the schemes are mixed. IMO we should have just a single scheme variant for each button type so we don't assig the same scheme name four times.

2023-06-19 11:04 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/control-buttons/control-buttons.stories.tsx
> +// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
I think we need to add this return type unless we finish a discussion whether we want to disable this.

2023-06-19 11:19 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/control-buttons/filled-button.component.tsx
> +import cs from 'classnames';
Please stick to the most popular usage `cn`

2023-06-19 14:55 UTC, mrcnk commented on packages/ui/src/design-tokens/colors.data.ts
> +  $primary_light_grey_0_56: 'rgba(239, 239, 239, 0.56)',
I could add it, but we discussed the place to use polished's `rgba` was the color-component mapping file and that's where I added it. Here we'd have to extract base colors our of the object to use it.

2023-06-19 15:11 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/types.ts
> +export enum Scheme {
Addressed

2023-06-19 15:11 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/filled-button.component.tsx
> +import cs from 'classnames';
Addressed

2023-06-19 15:12 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/control-buttons.stories.tsx
> +// eslint-disable-next-line @typescript-eslint/explicit-function-return-type
Added, seems like `JSX.Element` started to work somehow 🤔

2023-06-19 15:12 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/danger-button.component.tsx
> +            colorScheme: Scheme.Danger,
Discussed offline and skipping 😄

2023-06-19 15:13 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/icon-button.component.tsx
> +};
Resolved

2023-06-19 22:43 UTC, szymonmaslowski approved these changes
Looks good! I left a few minor comments, but maybe we could address them in some future PR.

2023-06-19 22:43 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/icon-button.component.tsx
> +export const Icon = (props: Readonly<ControlButtonProps>): JSX.Element => {
i think the `Icon` variant shouldn't have the `label` prop

2023-06-19 22:43 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/control-button.data.ts
> +};
```suggestion
export type ControlButtonProps = Omit<ButtonProps, 'className'> & {
  icon?: ReactNode;
};
```

2023-06-19 22:43 UTC, szymonmaslowski commented on packages/ui/src/design-tokens/colors.data.ts
> +import { rgba } from 'polished';
Please remove this line

2023-06-19 22:43 UTC, szymonmaslowski commented on packages/ui/src/design-system/control-buttons/icon-button.component.tsx
> +import type { ReactNode } from 'react';
Please remove this line

2023-06-20 13:39 UTC, renanvalentin commented on packages/ui/src/design-system/control-buttons/control-buttons.stories.tsx
> +  <PlusCircle className={sx({ fontSize: '$18' })} />
We know the icon container is always 24x24, and the font size is 18. Can you move this to the CSS? This way, we ensure the icons are always rendered in the correct dimension specified by the design system.

2023-06-20 13:55 UTC, renanvalentin commented on packages/ui/src/design-system/control-buttons/control-buttons.stories.tsx
> +  <PlusCircle className={sx({ fontSize: '$18' })} />
This has caused a regression on the [Bundle Input](https://www.chromatic.com/test?appId=6422dc516f0543c5fd174d4c&id=64916c5589ad0fb1fb3a9ed4)

2023-06-20 13:58 UTC, renanvalentin commented
@mrcnk make sure to rename the pull request title or edit the squash commit message to something like `feat(ui): ...`

2023-06-20 15:32 UTC, mrcnk commented on packages/ui/src/design-system/control-buttons/control-buttons.stories.tsx
> +  <PlusCircle className={sx({ fontSize: '$18' })} />
That's because I aligned the color variable to the up to date value from Figma.

2023-06-20 16:01 UTC, renanvalentin commented
There's still a regression on the Bundle Input. The Plus icon is bigger in the original version:

![Screenshot 2023-06-20 at 12 57 29](https://github.com/input-output-hk/lace/assets/2846918/9aa3771e-9403-4c9d-9c04-dfc9a87fc5b6)

![Screenshot 2023-06-20 at 12 57 37](https://github.com/input-output-hk/lace/assets/2846918/51f07e31-2193-4789-b42e-cfcdb6dcc942)

![Screenshot 2023-06-20 at 13 01 05](https://github.com/input-output-hk/lace/assets/2846918/8908e476-cf9b-41fd-9256-cb670312607a)

2023-06-21 06:42 UTC, mrcnk commented
> There's still a regression on the Bundle Input. The Plus icon is bigger in the original version:
> 
> ![Screenshot 2023-06-20 at 12 57 29](https://user-images.githubusercontent.com/2846918/247176731-9aa3771e-9403-4c9d-9c04-dfc9a87fc5b6.png)
> 
> ![Screenshot 2023-06-20 at 12 57 37](https://user-images.githubusercontent.com/2846918/247176737-51f07e31-2193-4789-b42e-cfcdb6dcc942.png)
> 
> ![Screenshot 2023-06-20 at 13 01 05](https://user-images.githubusercontent.com/2846918/247177669-8908e476-cf9b-41fd-9256-cb670312607a.png)

Resolved, aligned icon size to Figma.

2023-06-21 12:28 UTC, renanvalentin approved these changes
LGTM! great job!

2023-06-21 12:28 UTC, merged