[LW-9627] export shared wallet as a JSON file
input-output-hk/lace pull request #1280
Opened 2024-07-09 10:59 UTC by danielmain

Description

Implemented the functionality to export shared wallet data as a JSON file. This feature allows users to download the shared wallet configuration, which can be shared with other co-signers for easy wallet setup.

Changes

	•	Feature: Added JSON export functionality to the shared wallet creation flow.
	•	UI: Included functionality for “Download” button in the “Share wallet details” step.
	•	Validation: Ensured the JSON file is validated against a predefined schema before download.
	•	Code Structure: Refactored state management types for better clarity and maintainability.

2024-07-10 09:22 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6105/9871153288/index.html) for [973eb391](https://github.com/input-output-hk/lace/pull/1280/commits/973eb391cf2c17b0ec5c69e706f97aaa509a16ce)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 0      | 0       | 0     | 33    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-10 12:26 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/SharedWalletCreationStore.tsx
> +      downloadWalletData(prevState);
should it be concerning that state machine is doing side effects?

2024-07-10 12:26 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/state-and-types.ts
> +export type StateType<T extends (state: any) => any> = ReturnType<T>;
do we know the type of state here?

2024-07-10 12:27 UTC, vetalcore approved these changes

2024-07-10 15:57 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/state-and-types.ts
> +export type StateType<T extends (state: any) => any> = ReturnType<T>;
@vetalcore this code was moved existed before I would not enhance it now 🙏🏻 

Check https://github.com/input-output-hk/lace/blob/b6bcef771b1f24861d5f0a5c2cc37ed79f38b06e/packages/core/src/shared-wallets/state-utils.ts#L23

2024-07-10 16:11 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/SharedWalletCreationStore.tsx
> +      downloadWalletData(prevState);
Actually, you are right, the download button is not changing the state by any means, it is a side optional action. Can we make an exception here?

2024-07-10 16:23 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/SharedWalletCreationStore.tsx
> +      downloadWalletData(prevState);
That's a good point! When I was scratching the initial implementation of it i decided to avoid introducing more complexity and inclined the side effects. Ideally there should be some mechanism next to the machine watching the state and performing side effects. Alternatively maybe commands that machine would dispatch. What would be your suggestion on how the side effects should be handled in this implementation? Should we apply it now/later?

2024-07-10 17:09 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/state-and-types.ts
> +export type StateType<T extends (state: any) => any> = ReturnType<T>;
I think this should not be moved but rather imported from the state-utils file

2024-07-11 09:01 UTC, szymonmaslowski requested changes
GJ! I left a few comments.

2024-07-11 09:01 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/state-and-types.ts
> +export type StateType<T extends (state: any) => any> = ReturnType<T>;
This type util is now duplicated. Please import it from `state-utils.ts` file.

2024-07-11 09:13 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/SharedWalletLayout/type.ts
> +export type LayoutNavigationDownloadProps = LayoutNavigationProps & {
Why? types belong to types.ts

2024-07-12 10:58 UTC, merged