refactor: shared wallets related naming improvements
input-output-hk/lace pull request #1290
Opened 2024-07-15 10:09 UTC by szymonmaslowski

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

shared wallets related naming improvements

2024-07-15 13:05 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6222/9939698142/index.html) for [4560bcf2](https://github.com/input-output-hk/lace/pull/1290/commits/4560bcf2d735f1505ee738394f4f9443fbe56f61)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 0      | 0       | 0     | 33    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-15 14:35 UTC, greatertomi approved these changes

2024-07-17 08:54 UTC, danielmain requested changes
Tinny suggestion left

2024-07-17 08:54 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx
> +  const generateKey = async (enteredPassword: string) => {
Why returning the key and setting it using setSharedWalletKey?

2024-07-17 08:54 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx
> +              generateKey={generateKey}
what about generateSharedKey or using the technical name xpub?

2024-07-17 08:56 UTC, danielmain approved these changes

2024-07-17 11:56 UTC, merged