feat: support all quorum rules
input-output-hk/lace pull request #1291
Opened 2024-07-15 12:50 UTC by greatertomi

# Checklist

- [x] JIRA - LW-10971
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This allows support for all quorum rules

2024-07-15 13:02 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6223/9939706682/index.html) for [166cc525](https://github.com/input-output-hk/lace/pull/1291/commits/166cc52556e5e8ba72a65d359987adb882567580)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 1      | 0       | 0     | 33    | ❌     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-15 22:01 UTC, vetalcore requested changes

2024-07-15 22:01 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +        quorumRules.option === 'AllAddresses'
```suggestion
        quorumRules.option === QuorumRadioOption.AllAddresses
```

2024-07-15 22:01 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          quorumRules.option === 'RequireNOf'
ditto

2024-07-16 07:01 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
That would take time. After exporting, the SDK would need to be deployed and lace updated. I don't think it's worth it for this simple function.

2024-07-16 07:15 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +        quorumRules.option === 'AllAddresses'
Fixed on cd6be53

2024-07-16 07:16 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          quorumRules.option === 'RequireNOf'
Fixed on cd6be53

2024-07-16 09:59 UTC, vetalcore requested changes

2024-07-16 09:59 UTC, vetalcore commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
actually it's same amount of efforts as for updating the toolkit, we have a release job that you could run after merging to master, and then you could run script in lace to update all the sdk related deps

2024-07-16 12:50 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          : { kind: Wallet.Cardano.NativeScriptKind.RequireAnyOf };
sonarcloud is complaining here https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=1291&id=input-output-hk_lace&open=AZC2coRenDXdJ2Pbq-cF

2024-07-16 14:00 UTC, danielmain approved these changes

2024-07-16 14:00 UTC, danielmain commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
We have bip32 wallets and script wallets, maybe is it worth to create an Enum instead of many booleans?

Not expecting this now but maybe a TODO at least 😅

2024-07-16 14:12 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
@vetalcore What is that script? I was not aware of it.

2024-07-16 14:31 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
I am not too sure about it. WalletType is a core type in SDK used broadly. We would need some translation between those types when using SDK functions. Personally, I prefer to stick to the single type and multiple type guards. I don't have a strong opinion though.

2024-07-16 14:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
Me and Vit agreed to add a todo to this and not remove it, then create a PR to export it on the SDK so we won't be blocked.

2024-07-16 14:57 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
We already have this [walletType](https://github.com/input-output-hk/lace/blob/5796e23a64913793d4707336ce8d5823a76ea945/apps/browser-extension-wallet/src/stores/types.ts#L116), maybe I'll update this to that.

2024-07-16 22:43 UTC, greatertomi commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/UserInfo.tsx
> +const isBip32Wallet = <T, U>(wallet: AnyWallet<T, U>): wallet is AnyBip32Wallet<T, U> =>
I decided to use another approach. Check if 912c85c satisfies your concern

2024-07-16 22:43 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          : { kind: Wallet.Cardano.NativeScriptKind.RequireAnyOf };
Fixed on 912c85c

2024-07-17 07:39 UTC, vetalcore approved these changes

2024-07-17 08:13 UTC, merged