fix(extension): cosign staking transaction
input-output-hk/lace pull request #1293
Opened 2024-07-15 22:48 UTC by vetalcore

# Checklist

- [ ] JIRA - [LW-10528](https://input-output.atlassian.net/browse/LW-10528)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-15 22:57 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx
> +      setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
@greatertomi could you please suggest how do i get publicKey for shared wallet?

2024-07-15 22:57 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/is-shared-wallet.ts
> +    sharedKeys = stakingScript.scripts.filter(isRequireSignatureScriptKind)[0].keyHash;
@greatertomi how do i get Bip32PublicKeyHex from Ed25519KeyHashHex?

2024-07-15 22:57 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx
> +      setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
ditto

2024-07-15 22:57 UTC, vetalcore commented on packages/core/src/shared-wallets/transactionFileUtils.ts
> +// import { Ajv } from 'ajv';
getting 
<img width="729" alt="Screenshot 2024-07-16 at 00 49 06" src="https://github.com/user-attachments/assets/ea3b1a01-4eb3-49af-88c1-8a81a997e613">
otherwise

2024-07-15 22:57 UTC, vetalcore commented on packages/core/src/shared-wallets/transactionFileUtils.ts
> +// import { Ajv } from 'ajv';
@shawnbusuttil could you please suggest if i've missed something

2024-07-15 22:57 UTC, vetalcore commented on packages/staking/src/features/Drawer/SignConfirmation.tsx
> +      exportMultisigTransaction(signedTx, sharedKey, currentChain);
Should redirect to this [drawer](https://www.figma.com/design/RPN3V4Et7hMbXkV5ZIF75i/%5Bdeprecated%5D-Lace-Browser---Full-view-UI-Design?node-id=43402-496288&t=WFYeGcWK6va4d9Y9-1) instead, still in progress within https://input-output.atlassian.net/browse/LW-10970

2024-07-15 22:57 UTC, vetalcore commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +  const loading = isNil(protocolParameters) || isNil(rewardAccounts);
please correct me otherwise

2024-07-15 22:57 UTC, vetalcore commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +                      ownSharedKey={signPolicy?.signers[0]?.keyHash as CoSignersListItem['keyHash']}
will be fixed once

2024-07-15 22:59 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6231/9947747394/index.html) for [b2afa721](https://github.com/input-output-hk/lace/pull/1293/commits/b2afa72161613479dd5d81e6603a5615d0f59f61)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 0      | 0       | 0     | 33    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-16 06:58 UTC, vetalcore commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +                  amount={t('drawer.confirmation.validityPeriod.value')}
@danielmain is 24h validity period value something that is preconfigured?

2024-07-16 07:03 UTC, danielmain commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +                  amount={t('drawer.confirmation.validityPeriod.value')}
yes, should be a env variable or a constant

2024-07-16 07:28 UTC, greatertomi commented on apps/browser-extension-wallet/src/utils/is-shared-wallet.ts
> +    sharedKeys = stakingScript.scripts.filter(isRequireSignatureScriptKind)[0].keyHash;
I don't know. Maybe we should ask Martynas.

2024-07-16 13:41 UTC, danielmain requested changes

2024-07-16 13:42 UTC, danielmain requested changes
Awesome Job @vetalcore, incredible how fast you are

2024-07-16 23:05 UTC, greatertomi approved these changes
Amazing stuff @vetalcore

2024-07-17 08:01 UTC, szymonmaslowski commented on packages/staking/src/features/staking/StakingView.tsx
> +  }, [isSharedWallet]);
I would also revert this one. The `stepsWithBackBtn` is a configuration for the UI, but the decision if the UI should be displayed is made by the state machine, so we should handle it there.

2024-07-17 08:17 UTC, szymonmaslowski commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  deriveSharedWalletExtendedPublicKeyHash: (
Having it in the shared wallets you could import this type 😉

2024-07-17 08:25 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +
This should not be imported from the SDK as the index and role can be anything. Maybe a `derivationPath.ts` within the shared-wallets directory would be more ideal.

2024-07-17 08:26 UTC, szymonmaslowski commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +  useEffect(() => {
I suggest moving it below next to the other useEffect

2024-07-17 08:27 UTC, szymonmaslowski commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +export const stakingScriptKeyPath = {
I think this one gets repeated a few times. Maybe we could define it once and import in all the places.

2024-07-17 08:28 UTC, szymonmaslowski commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +const TX_VALIDITY_PERIOD = process.env.SHARED_WALLET_TX_VALIDITY_INTERVAL;
IMO we should not introduce many names for the same thing as it creates a confusion.

```suggestion
const SHARED_WALLET_TX_VALIDITY_INTERVAL = process.env.SHARED_WALLET_TX_VALIDITY_INTERVAL;
```

2024-07-17 08:32 UTC, szymonmaslowski commented on packages/staking/src/features/Drawer/StakePoolDetailsDrawer.tsx
> +  const titleSecond = t(`drawer.${isSharedWallet ? 'titleSharedWallet' : 'titleSecond'}`);
I don't have a good alternative name for this variable. Maybe should be the changeg to:
```
const title;
if (DrawerDefaultStep.PoolDetails === activeDrawerStep) {
  title = t('drawer.title');
} else {
  title = t(`drawer.${isSharedWallet ? 'titleSharedWallet' : 'titleSecond'}`);
}
```

2024-07-17 08:37 UTC, szymonmaslowski commented on packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolsListRow.tsx
> +      {showDAppCompatibilityModal && !isSharedWallet && (
Shouldn't we rather/also detect shared wallet in the `onSelect` callback? Otherwise as I understand nothing will happen if `multidelegationDAppCompatibility && !poolAlreadySelected` is met but it is shared wallet.

2024-07-17 08:58 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  deriveSharedWalletExtendedPublicKeyHash: (
#1291 does that. When you update this branch, you can resolve conflicts and remove this.

2024-07-17 09:15 UTC, vetalcore commented on packages/core/src/shared-wallets/transactionFileUtils.ts
> +// import { Ajv } from 'ajv';
will remove ajv dep

2024-07-17 09:24 UTC, vetalcore commented on packages/staking/src/features/Drawer/SignConfirmation.tsx
> +      exportMultisigTransaction(signedTx, sharedKey, currentChain);
leave a todo for integration

2024-07-17 12:30 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolsListRow.tsx
> +      {showDAppCompatibilityModal && !isSharedWallet && (
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on packages/staking/src/features/Drawer/StakePoolDetailsDrawer.tsx
> +  const titleSecond = t(`drawer.${isSharedWallet ? 'titleSharedWallet' : 'titleSecond'}`);
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +const TX_VALIDITY_PERIOD = process.env.SHARED_WALLET_TX_VALIDITY_INTERVAL;
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +export const stakingScriptKeyPath = {
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +  useEffect(() => {
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  deriveSharedWalletExtendedPublicKeyHash: (
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts
> +              ...(data.isSharedWallet && { activeDrawerStep: DrawerManagementStep.Confirmation }),
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts
> +    isSharedWallet: boolean | undefined;
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/is-shared-wallet.ts
> +export const isScriptWallet = (
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  deriveSharedWalletExtendedPublicKeyHash: (
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  participants: CoSigner[];
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:31 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +          participants: participants.map((p: CoSigner) => ({ sharedWalletKey: p.keys, walletName: p.name })),
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:32 UTC, vetalcore commented on packages/staking/src/features/staking/StakingView.tsx
> +  }, [isSharedWallet]);
but it wasn't made by state machine before, it was made on line 13 above

2024-07-17 12:34 UTC, vetalcore commented on packages/core/src/shared-wallets/transactionFileUtils.ts
> +// import { Ajv } from 'ajv';
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:36 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx
> +          signers: policy.signers.map((s) => ({ ...s, name: keyToNameMap.get(s.keyHash) || s.keyHash }))
done here 4f7a023ca8a159613b8b0dab0dec664d4d2a2454

2024-07-17 12:40 UTC, vetalcore commented on packages/staking/src/features/Drawer/SignConfirmation.tsx
> +      exportMultisigTransaction(signedTx, sharedKey, currentChain);
done here e6e07ecfed1db9cfd6c120dbab61daab512e638a

2024-07-17 17:09 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +        setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
This only caters for staking since you use `stakingScript` and `stakingScriptKeyPath`, I'll recommend you name this `stakingSignPolicy`. Alternatively, you can create a `getSignPolicy` function to receive a parameter that specify either to return payment or staking signPolicy

2024-07-17 19:11 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +        setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
done here 3f7f319bc2addc738d65e0a169295bbf3e56a502

2024-07-17 23:59 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +        setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
I was thinking of something along this line. This way, we don't need to pass `activeWallet`, `isSharedWallet`, `script`, `derivationPath` every time the hook is called and since they could be pulled within the hook.

```ts
type SigningPolicyType = 'payment' | 'staking';

export const useSharedWalletData = (): {
  getSignPolicy: (type: SigningPolicyType) => SignPolicy | undefined;
  sharedKey: Wallet.Crypto.Bip32PublicKeyHex | undefined;
} => {
  const [activeWallet, setActiveWallet] = useState<AnyWallet<Wallet.WalletMetadata, Wallet.AccountMetadata>>();
  const { walletRepository } = useWalletManager();
  const { cardanoWallet, isSharedWallet } = useWalletStore();
  const wallets = useObservable(walletRepository.wallets$);

  useEffect(() => {
    (async () => {
      const activeWalletId = cardanoWallet.source.wallet.walletId;
      const currentWallet = wallets.find(({ walletId }) => walletId === activeWalletId);
      setActiveWallet(currentWallet);
    })();
  }, [cardanoWallet.source.wallet.walletId, isSharedWallet, wallets]);

  const getSignPolicy = useCallback(
    async (type: SigningPolicyType): Promise<SignPolicy | undefined> => {
      if (!isScriptWallet(activeWallet)) return;

      const script = type === 'payment' ? activeWallet.paymentScript : activeWallet.stakingScript;
      const derivationPath = type === 'payment' ? paymentScriptKeyPath : stakingScriptKeyPath;

      const policy = getSharedWalletSignPolicy(script);
      const keyToNameMap = await getKeyHashToWalletNameMap({
        coSigners: activeWallet.metadata.participants,
        derivationPath
      });

      return {
        ...policy,
        signers: policy.signers.map((signer: CoSignersListItem) => ({
          ...signer,
          name: keyToNameMap.get(signer.keyHash) || signer.keyHash
        }))
      };
    },
    [activeWallet]
  );

  return { getSignPolicy, sharedKey: activeWallet.metadata.extendedAccountPublicKey };
};

```

2024-07-18 07:26 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +        setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
i'l do that in my next pr if that works fr you

2024-07-18 07:28 UTC, danielmain commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +        setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
Just add a TODO in a commit so you don't forget it?

2024-07-18 07:34 UTC, szymonmaslowski approved these changes
Really great job @vetalcore! I left plenty of comments but I think none of them are critical. I would suggest merging it after @emiride confirms it works fine, and we didn't introduce any regression. Let's discuss the comments together and apply changes later.

2024-07-18 07:34 UTC, szymonmaslowski commented on packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolsList.tsx
> +const WrappedStakePoolsListRowSkeleton = ({ index }: { index: number }) => {
How about passing isSharedWallet as an `itemContent`'s parameter instead?

2024-07-18 07:34 UTC, szymonmaslowski commented on packages/staking/src/features/Drawer/StakePoolDetail.tsx
> +            addStakingPool: ableToSelect && !selectionsEmpty && { callback: onSelectClick },
WTF is this 😨 I know you just followed it, I am the original author of this code. It must have been a late late night when I created this monster...

However I think that the correct way here would be to use that original `makeActionButtons` function and adjust conditions disabling all unnecessary buttons, so here it would be
```suggestion
            addStakingPool: !isShraredWallet && ableToSelect && !selectionsEmpty && { callback: onSelectClick },
```

2024-07-18 07:34 UTC, szymonmaslowski commented on packages/staking/src/features/Drawer/preferences/StepPreferencesContent.tsx
> +        {isSharedWallet && (
Shouldn't it be with `!` instead?
```suggestion
        {!isSharedWallet && (
```

2024-07-18 07:38 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +        setSharedKey(activeWallet.metadata.extendedAccountPublicKey);
I added this on my current branch already, You won't have to do it.

2024-07-18 09:37 UTC, merged

2024-07-19 14:00 UTC, vetalcore commented on packages/core/src/shared-wallets/docs/schema/shared-wallet-type-autogenerated.ts
> +    coSigners: {
@danielmain under what folder i need to run the script?

2024-07-19 14:11 UTC, vetalcore commented on packages/cardano/src/wallet/lib/cardano-wallet.ts
> +  coSigners?: { sharedWalletKey: string; name: string }[];
do we really want to introduce core package as dep in the cardano?

2024-07-19 14:18 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts
> +    isSharedWallet: boolean;
will postpone it then, since we have multiple pr in progress, just to avoid conflicts

2024-07-21 11:37 UTC, szymonmaslowski commented on packages/cardano/src/wallet/lib/cardano-wallet.ts
> +  coSigners?: { sharedWalletKey: string; name: string }[];
No, I realized that would be a circular dependency. This is why I suggested making the `WalletMetadata` type generic type accepting a CoSigner type so the cardano package would not import core. Both would be imported by browser and assembled there:
```
import { WalletMetadata } from 'cardano';
import { CoSigner } from 'core';
...
metadata: WalletMetadata<CoSigner>;
```

2024-07-21 11:43 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts
> +    isSharedWallet: boolean;
I mean in the machine. Right now according to the machine, it is possible to go from the `Confirmation` to the `Preferences` step. Let's adjust the `DrawerBack` the same way you adjusted the other two commands.

2024-07-22 06:35 UTC, danielmain commented on packages/core/src/shared-wallets/docs/schema/shared-wallet-type-autogenerated.ts
> +    coSigners: {
you basically need to copy the schema and also its dependencies (eg. cardano-babbage.json) to `packages/core` then run the script `npx --package json-schema-to-typescript -c 'json2ts shared-wallet-schema.json > shared-wallet-types-autogenerated.ts'`

2024-07-22 06:36 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts
> +    isSharedWallet: boolean;
Yep, it can be refactored when you guys have time. I think that @szymonmaslowski proposal is good :)

2024-07-22 08:16 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts
> +    isSharedWallet: boolean;
we do not render arrow back btn for this case

2024-07-22 08:17 UTC, vetalcore commented on packages/staking/src/features/Drawer/preferences/StepPreferencesContent.tsx
> +        {isSharedWallet && (
resolved

2024-07-22 08:57 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/ShareWalletDetails/utils.ts
> +      coSigners: coSigners.map((coSigner) => ({
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:00 UTC, vetalcore commented on packages/cardano/src/wallet/lib/cardano-wallet.ts
> +  coSigners?: { sharedWalletKey: string; name: string }[];
i'd then have to introduce this generic in few other places that are related to the create wallet utils that have wallet metadata as its deps, that feels a bit not right

2024-07-22 09:00 UTC, vetalcore commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  deriveSharedWalletExtendedPublicKeyHash: typeof Wallet.util.deriveEd25519KeyHashFromBip32PublicKey;
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:00 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +  const [sharedKey, setSharedKey] = useState<Wallet.Crypto.Bip32PublicKeyHex>();
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:00 UTC, vetalcore commented on packages/core/src/shared-wallets/index.ts
> +export * from './transaction/CosignersList';
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:00 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/CosignersList.tsx
> +  ownSharedKeyHash?: Wallet.Crypto.Ed25519KeyHashHex;
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:00 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/types.ts
> +}
i'd rather wait with this one because there are multiple pr possibly refactoring this interface

2024-07-22 09:00 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/InfoBar.tsx
> +  signed: CoSignersListItem[];
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:00 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolsList.tsx
> +const WrappedStakePoolsListRowSkeleton = ({ index }: { index: number }) => {
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:00 UTC, vetalcore commented on packages/staking/src/features/Drawer/StakePoolDetail.tsx
> +            addStakingPool: ableToSelect && !selectionsEmpty && { callback: onSelectClick },
done here https://github.com/input-output-hk/lace/pull/1311/files

2024-07-22 09:01 UTC, vetalcore commented on packages/staking/src/features/Drawer/confirmation/StakePoolConfirmationContent.tsx
> +  useEffect(() => {
there is no other useEffect in this file anymore

2024-07-22 09:04 UTC, vetalcore commented on packages/core/src/shared-wallets/docs/schema/shared-wallet-type-autogenerated.ts
> +    coSigners: {
would you be able to generate it by yourself in your next pr, please update the readme file otherwise