feat: shared wallet key generation improvements
input-output-hk/lace pull request #1302
Opened 2024-07-18 08:59 UTC by szymonmaslowski

# Checklist

- [x] JIRA - [LW-10710](https://input-output.atlassian.net/browse/LW-10710)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

 - fixed UI
 - moved password generation logic to shared wallets

## Testing

- UI is fixed
  - the spinner on the generate key button looks good
  - the generated key is broken into multiple line and the whole page is rendered correctly
- if you type incorrect password you get "Invalid password" error (on main there is some hard to understand error)

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-18 09:09 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6281/9988592384/index.html) for [30ae20da](https://github.com/input-output-hk/lace/pull/1302/commits/30ae20da8030c00026f0e57327cc5eb818d1fcb7)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 0       | 0     | 32    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-18 10:29 UTC, danielmain requested changes

2024-07-18 10:29 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts
> +  };
```suggestion
export const makeGenerateSharedWalletKey =
  ({ chainId, getMnemonic }: GenerateSharedWalletKeyDependencies): GenerateSharedWalletKeyFn =>
  async (password: string) => {
    let passphrase: Uint8Array | null = null;

    const getPassphrase = async (): Promise<Uint8Array> => {
      passphrase = Buffer.from(password, 'utf8');
      // Attempt to clear the original string
      password = '';
      return passphrase;
    };

    try {
      passphrase = await getPassphrase();
      const mnemonicWords = await getMnemonic(passphrase);

      const keyAgent = await Wallet.KeyManagement.InMemoryKeyAgent.fromBip39MnemonicWords(
        {
          accountIndex: 0,
          chainId,
          getPassphrase: async () => passphrase,
          mnemonicWords,
          purpose: Wallet.KeyManagement.KeyPurpose.MULTI_SIG,
        },
        {
          bip32Ed25519: Wallet.bip32Ed25519,
          logger: console, // Ensure this logger does not log sensitive information
        },
      );

      return keyAgent.extendedAccountPublicKey;
    } catch (error: unknown) {
      if (error instanceof Error && error.message === 'Unsupported state or unable to authenticate data') {
        throw new SharedWalletKeyGenerationAuthError();
      }
      throw error;
    } finally {
      // Clear any sensitive data from memory if possible
      if (passphrase) {
        passphrase.fill(0);
      }
    }
  };
```

2024-07-18 10:29 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts
> +  };
This is quite more secure, because we clear-up the Uint8Array

2024-07-18 10:29 UTC, danielmain requested changes
Requested minor changes

2024-07-18 12:12 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  const generateSharedWalletKey = useMemo(
@danielmain and I discussed it and we agreed that this one is not risky.

2024-07-18 12:12 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts
> +  };
Great suggestion! Thank you. I applied the change.

2024-07-18 12:19 UTC, danielmain approved these changes
Great job @szymonmaslowski

2024-07-19 10:16 UTC, vetalcore requested changes

2024-07-19 10:16 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts
> +import { Wallet } from '@lace/cardano';
what is the convention you are following for the file/folder names?

2024-07-19 16:45 UTC, greatertomi approved these changes

2024-07-19 16:45 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts
> +    password = '';
```suggestion
```

2024-07-21 12:26 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts
> +import { Wallet } from '@lace/cardano';
I used to name the following categories:
1. ComponentFiles
2. hookFiles
3. other-kinds-like-utilities-constants-types.
4. style files are named the same way as the file they belong to.

In the lace repo we comply with 1 and 4, but for other kinds I noticed it is not standardized, or am I wrong?

2024-07-21 12:28 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/generate-key-flow/generate-shared-wallet-key.ts
> +    password = '';
This is done on purpose to erase the password from the memory. I forgot to add a comment there. Will do it. Thanks for raising it.

2024-07-22 08:05 UTC, vetalcore approved these changes

2024-07-22 12:42 UTC, merged