feat: add support for joining shared wallet by uploading json file
input-output-hk/lace pull request #1304
Opened 2024-07-18 15:53 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-10529)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Uploading a valid json file lets you become part of a shared wallet.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-19 15:14 UTC, danielmain requested changes
small suggestion

2024-07-19 15:15 UTC, danielmain requested changes
Left a tinny suggestion. But overall great job @shawnbusuttil

2024-07-19 17:17 UTC, greatertomi requested changes

2024-07-19 17:17 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/SharedWalletRestorationFlow.tsx
> +        // TODO: wallet already exist should be blocked before this line executes (it must have an error registered)
I don't understand your TODO comment here. Also, can this be resolved before merge?

2024-07-19 17:17 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/sharedKeyToHash.ts
> +};
We already have this [here](https://github.com/input-output-hk/lace/blob/14e84d11de2b140089abe66ff8f8bf9fda3fd20c/packages/core/src/shared-wallets/utils/derivation-path.ts)

2024-07-19 17:17 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/sharedKeyToHash.ts
> +export const deriveSharedWalletExtendedPublicKeyHash = async (
This is already defined [here](https://github.com/input-output-hk/lace/blob/9fd75574e1fd146997ccb40e3114bef9ecd780a7/packages/cardano/src/wallet/util/derive-ed25519-key-hash-from-bip32-public-key.ts#L4-L11).

2024-07-19 17:17 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts
> +        const ownHash = await getHash(sharedKey, paymentScriptKeyPath);
We might not need to convert this to key hash if the nativeScript of the JSON follows the schema. 

Please can you convert the `nativeScript` part to `keyHash` before download, so that it could align with the schema?

<img width="1396" alt="Screenshot 2024-07-19 at 18 00 28" src="https://github.com/user-attachments/assets/0ea69d39-db39-4c45-9eb0-fc253fcba1f7">

2024-07-22 09:46 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/SharedWalletRestorationFlow.tsx
> +        // TODO: wallet already exist should be blocked before this line executes (it must have an error registered)
It just means we need to add support for wallet already exists, including an error key and a modal for it ideally.

2024-07-22 10:37 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts
> +        const ownHash = await getHash(sharedKey, paymentScriptKeyPath);
I dont get what you mean here. Isn't the schema showing it as a "pubkey"?

2024-07-22 10:41 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts
> +        const ownHash = await getHash(sharedKey, paymentScriptKeyPath);
The schema is incorrect. The person who created the NativeScript type in `cardano-babbage.json` meant to use `publicKeyHASH` instead of `pubKey`, which has caused a lot of confusion :(

2024-07-22 10:46 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6317/10039260560/index.html) for [ad871df9](https://github.com/input-output-hk/lace/pull/1304/commits/ad871df9f861fcd676e2c45b424ee1a774231ff5)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 0       | 0     | 32    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-22 18:37 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts
> +        const ownHash = await getHash(sharedKey, paymentScriptKeyPath);
But what is the difference getting it from metadata and getting it from scripts?

2024-07-22 20:08 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts
> +        const ownHash = await getHash(sharedKey, paymentScriptKeyPath);
@danielmain Can we change it to `publicKeyHash` on this PR or a separate one?

2024-07-23 12:11 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/SharedWalletRestorationFlow.tsx
> +        // TODO: wallet already exist should be blocked before this line executes (it must have an error registered)
do you want to add this to the current PR or a separate one?

2024-07-23 15:03 UTC, greatertomi approved these changes
Amazing work. Well done @shawnbusuttil

2024-07-23 15:03 UTC, greatertomi commented on packages/core/src/shared-wallets/docs/schema/shared-wallet-scriptNOfK-example.json
> +        "publicKey": "e0a8a80a28f205b69029ac8448265da2cef6e2c70d6a91fcd699ea859df45860f6788ff36f7ed44ccf564974ad2c033e640a5f25b943308935d7103612ef2c1f"
It would be a nice to have to have a different public key here

2024-07-24 08:25 UTC, danielmain approved these changes

2024-07-24 08:46 UTC, merged