feat: build shared wallet transaction
input-output-hk/lace pull request #1305
Opened 2024-07-18 17:02 UTC by greatertomi

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-22 10:12 UTC, vetalcore requested changes

2024-07-22 11:34 UTC, szymonmaslowski requested changes
GJ! Leaving some comments

2024-07-22 11:34 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/helpers.ts
> +type AssetsListItem = Unpacked<SentAssetsList>;
How about exporting the needed type from the core?

BTW for the sake of a discussion, alternatively to the `Unpacked` type you could do `SentAssetsList[number]`. But IMO exporting the type is still the best approach.

2024-07-22 11:34 UTC, szymonmaslowski commented on packages/cardano/src/wallet/lib/cardano-wallet.ts
> +  coSigners?: { sharedWalletKey: Bip32PublicKeyHex; name: string }[];
Could you please reuse the CoSigner type from core?
```
export interface WalletMetadata<CoSigner extends object> {
  ...
  coSigners?: CoSigner[];
}
```
and on the browser level compose it at the place `WalletMetadata` is used: `WalletMetadata<CoSigner>`

2024-07-22 11:34 UTC, szymonmaslowski commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  coSigners: { sharedWalletKey: Bip32PublicKeyHex; name: string }[];
Please import CoSigner type (adjusted with `Bip32PublicKeyHex`) from core

2024-07-22 11:34 UTC, szymonmaslowski commented on packages/staking/src/features/outside-handles-provider/types.ts
> +import { Bip32PublicKeyHex } from '@cardano-sdk/crypto';
Please add this package to the dependencies.

2024-07-22 11:34 UTC, szymonmaslowski commented on packages/core/src/ui/assets/icons/awaiting-signatures.svg
> +<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
Please add this icon to the toolkit if it does not exist there yet and import from there.

2024-07-22 11:34 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/types.ts
> +export type MultisigTxData = {
I think this type should be generated from the schema. @danielmain or @vetalcore could assist you with that.

2024-07-22 16:55 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +    name: metadata?.name
Considering that metadata has more [properties](https://github.com/input-output-hk/lace/blob/52872873b101d2285dcc30066bdc855dc4eeb467/packages/cardano/src/wallet/lib/cardano-wallet.ts#L27-L34), it's better to pick exactly what I need.

2024-07-22 18:02 UTC, greatertomi commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +        return TransactionActivityType.awaitingCosignatures;
Fixed on 9e85ffd

2024-07-22 18:02 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
> +        // await exportMultisigTransaction(signedTx, sharedWalletKey, currentChain);
Fixed on 9e85ffd

2024-07-22 18:02 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/SharedWalletTransactionDetailsProxy.tsx
> +    const { body } = activityDetail.activity as Wallet.Cardano.Tx;
Fixed on 9e85ffd

2024-07-22 18:03 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/SharedWalletTransactionDetailsProxy.tsx
> +    // TODO: Not exactly accurate yet
Fixed on 9e85ffd

2024-07-22 18:03 UTC, greatertomi commented on packages/core/src/shared-wallets/transaction/types.ts
> +  key: Wallet.Crypto.Bip32PublicKeyHex;
Fixed on 9e85ffd

2024-07-22 20:12 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +    async (type: SigningPolicyType): Promise<SignPolicy | undefined> => {
I don't understand what you mean here. Let's catch-up on a call.

2024-07-22 20:16 UTC, greatertomi commented on apps/browser-extension-wallet/src/assets/icons/circle-check-gradient.svg
> +<svg width="112" height="112" viewBox="0 0 112 112" fill="none" xmlns="http://www.w3.org/2000/svg">
Checked. Could not find another occurrence of this icon

2024-07-22 20:17 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +    async (type: SigningPolicyType): Promise<SignPolicy | undefined> => {
```suggestion
    async (script: Wallet.Cardano.NativeScript): Promise<SignPolicy | undefined> => {
```

2024-07-22 20:18 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +  const wallets = useObservable(walletRepository.wallets$);
Why not let's make the `useSharedWalletData` self-sufficient since `walletRepository` can be accessed from anywhere?

2024-07-22 21:00 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/helpers.ts
> +type AssetsListItem = Unpacked<SentAssetsList>;
I only moved these functions here to avoid circular imports. They are used in other components beyond shared wallet.

2024-07-22 21:21 UTC, greatertomi commented on packages/core/src/ui/assets/icons/awaiting-signatures.svg
> +<svg width="48" height="48" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
That's going to be a longer change circle. I'll create a separate PR after this change is merged to move all the icons introduced in this PR to the toolkit

2024-07-22 21:21 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/SharedWalletTransactionDetailsProxy.tsx
> +    // TODO: Not exactly accurate yet
Fixed on 9e85ffd

2024-07-22 21:21 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +  tx: Wallet.TxInFlight | Wallet.Cardano.HydratedTx | Wallet.KeyManagement.WitnessedTx;
Fixed on 9e85ffd

2024-07-22 21:21 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
> +        // await exportMultisigTransaction(signedTx, sharedWalletKey, currentChain);
We need this to export the transaction file. Resolved on 9e85ffd

2024-07-22 21:21 UTC, greatertomi commented on packages/staking/src/features/outside-handles-provider/types.ts
> +import { Bip32PublicKeyHex } from '@cardano-sdk/crypto';
I used `Wallet.Crypto. Bip32PublicKeyHex ` instead on 9e85ffd

2024-07-22 21:21 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/TransactionSuccessView.tsx
> +  if (isSharedWallet) return <SharedWalletTransactionSuccess />;
Fixed on 58eed76

2024-07-22 21:21 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +  // const transaction = 'tx' in tx ? tx.tx : tx;
Fixed on 58eed76

2024-07-22 21:31 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +            sharedWalletKey: Wallet.Crypto.Bip32PublicKeyHex(signer.sharedWalletKey)
I'll recommend we leave this as string. Since Bip32PublicKeyHex is an opaque type, it validates the data passed and throws an error when it does not match. For example an empty string like `Crypto.Bip32PublicKeyHex('')` throws an error, and empty strings are frequently used before the user enters their `sharedWalletKey`

2024-07-23 09:47 UTC, greatertomi commented on apps/browser-extension-wallet/src/assets/icons/circle-check-gradient.svg
> +<svg width="112" height="112" viewBox="0 0 112 112" fill="none" xmlns="http://www.w3.org/2000/svg">
@szymonmaslowski and I agreed that this can come as a follow up PR as soon as possible.

2024-07-23 10:07 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSharedWalletData.ts
> +    async (type: SigningPolicyType): Promise<SignPolicy | undefined> => {
I and @szymonmaslowski agreed to move this change to a separate PR.

```
useSharedWalletData -> {sharedWalletKey, coSigners, name}
useSignPolicy(signPolicyType) -> {signPolicy}
```

2024-07-23 11:17 UTC, greatertomi commented on packages/core/src/shared-wallets/types.ts
> +export type MultisigTxData = {
@szymonmaslowski. I'll add this to the changes I'll make in a follow up PR.

2024-07-23 11:54 UTC, vetalcore approved these changes

2024-07-23 13:25 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/SharedWalletTransactionDetailsProxy.tsx
> +export const SharedWalletTransactionDetailsProxy = withAddressBookContext(
Rename proxy to wrapper

2024-07-23 13:26 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/SharedWalletTransactionDetailsProxy.tsx
> +        coSigners?.map(({ sharedWalletKey: key, name }) => ({
Use whole object

2024-07-23 14:02 UTC, danielmain commented on packages/core/src/shared-wallets/transaction/SharedWalletTransactionDetails.tsx
> +    bundle: 'Bundle',
Move it to translations

2024-07-23 14:08 UTC, danielmain approved these changes

2024-07-23 21:36 UTC, szymonmaslowski approved these changes
Great Job! Please make sure you don't revert any changes and all smoke tests pass. Let's create a follow up PR with improvements 😉

2024-07-23 21:36 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/transaction/InfoBar.tsx
> +            {signed.length >= signPolicy.required
Please just make sure you don't revert other changes.

2024-07-24 06:54 UTC, greatertomi commented on packages/core/src/shared-wallets/transaction/InfoBar.tsx
> +            {signed.length >= signPolicy.required
Fixed on 0e4e4b4

2024-07-24 06:54 UTC, greatertomi commented on packages/core/src/shared-wallets/transaction/SharedWalletTransactionDetails.tsx
> +    bundle: 'Bundle',
Fixed on 0e4e4b4

2024-07-24 06:55 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/SharedWalletTransactionDetailsProxy.tsx
> +        coSigners?.map(({ sharedWalletKey: key, name }) => ({
Fixed on 0e4e4b4

2024-07-24 06:55 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/SharedWalletTransactionDetailsProxy.tsx
> +export const SharedWalletTransactionDetailsProxy = withAddressBookContext(
Fixed on 0e4e4b4

2024-07-24 11:03 UTC, merged