test(extension): add tests for LW-10853, LW-10855, LW-10857
input-output-hk/lace pull request #1309
Opened 2024-07-19 12:06 UTC by wklos-iohk

# Checklist

- [X] JIRA - LW-10999
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-19 12:18 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6300/10007781470/index.html) for [6e0f55ae](https://github.com/input-output-hk/lace/pull/1309/commits/6e0f55ae031aa988e6e82ea649f9fe2fdb850a69)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 0       | 0     | 32    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-22 07:53 UTC, ljagiela requested changes

2024-07-22 07:53 UTC, ljagiela commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +  await MultidelegationDAppIssueModal.gotItButton.waitForClickable();
cosmetic but usually we move both methods like this to the click... method inside a page object

2024-07-22 07:53 UTC, ljagiela commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +  if (mode === 'grid') {
can you move the part responsible for selecting random Index into MultiDelegationPage Object and call it here ?

2024-07-22 12:42 UTC, oldGreg5 approved these changes

2024-07-22 13:12 UTC, ljagiela approved these changes

2024-07-22 13:12 UTC, merged