fix: require min two cosigners, validate duplicated keys, fix typography
input-output-hk/lace pull request #1315
Opened 2024-07-22 19:47 UTC by vetalcore

# Checklist

- [ ] JIRA -[LW-10994](https://input-output.atlassian.net/browse/LW-10994)
- [ ] JIRA -[LW-10995](https://input-output.atlassian.net/browse/LW-10995)
- [ ] JIRA -[LW-10997](https://input-output.atlassian.net/browse/LW-10997)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-22 19:56 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6328/10047381642/index.html) for [b27c1250](https://github.com/input-output-hk/lace/pull/1315/commits/b27c12504d99b97a8159d2d48af48fd81ce2b963)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 0       | 0     | 32    | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-23 10:07 UTC, danielmain requested changes
Left one optional change and other suggestions

2024-07-23 10:07 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSignerInput.tsx
> +  if (error.sharedWalletKey === CoSignerErrorKeys.Duplicated) {
[OPTIONAL] What about a switch?

2024-07-23 10:07 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSigners.tsx
> +  const atLeastTwoValidCoSigners =
🙄 the name of the variable says `Two`, but the MIN_NUMBER_OF_COSIGNERS can potentially be 2,3,etc.

Rename it to `hasAtLeastMinValidCoSigners`

2024-07-23 10:07 UTC, danielmain commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSigners.tsx
> +      isNextEnabled={atLeastTwoValidCoSigners}
`hasAtLeastMinValidCoSigners`

2024-07-23 11:33 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSigners.tsx
> +const MIN_NUMBER_OF_COSIGNERS = 2;
done here 521b6f1ab78e3159fb7d48c7c86ec3e909a66e5a

2024-07-23 11:33 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSigners.tsx
> +  const atLeastTwoValidCoSigners =
done here 521b6f1ab78e3159fb7d48c7c86ec3e909a66e5a

2024-07-23 11:33 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSigners.tsx
> +      isNextEnabled={atLeastTwoValidCoSigners}
done here 521b6f1ab78e3159fb7d48c7c86ec3e909a66e5a

2024-07-23 12:25 UTC, shawnbusuttil approved these changes

2024-07-23 14:53 UTC, greatertomi commented on apps/browser-extension-wallet/.env.defaults
> +MIN_NUMBER_OF_COSIGNERS=2
Why do we need this?

2024-07-24 07:33 UTC, szymonmaslowski approved these changes
GJ! Just one think about having constant.

2024-07-24 07:33 UTC, szymonmaslowski commented on apps/browser-extension-wallet/.env.defaults
> +MIN_NUMBER_OF_COSIGNERS=2
I share the same question 😉 I think this should not be a subject for configuration, it is rather a nature of the feature

2024-07-24 07:35 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/AddCoSigners/AddCoSigners.tsx
> +const MIN_NUMBER_OF_COSIGNERS = 2;
@danielmain I don't think this should be placed in the env file. This is a constant determined by the nature of the feature, right? It should not be configurable I guess...

2024-07-24 08:33 UTC, vetalcore commented on apps/browser-extension-wallet/.env.defaults
> +MIN_NUMBER_OF_COSIGNERS=2
@danielmain wdyt?

2024-07-24 08:42 UTC, danielmain approved these changes
Awesome job Vit!

2024-07-24 13:28 UTC, merged