Feat/add shared wallet related buttons on activity detail drawer
input-output-hk/lace pull request #1320
Opened 2024-07-25 09:47 UTC by vetalcore

# Checklist

- [ ] rely on `AWAITING_COSIGNATURE` tx `status` instead of `type` to display shared wallet tx
- [ ] remove shared wallet specific tx wrapper nad details component
- [ ] use existing `expiresBy` logic instead of `validityInterval`
- [ ] make address box clickable in receive drawer

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-25 09:50 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetailFooter.tsx
> +  // TODO: implement
would be available in @greatertomi's pr?

2024-07-25 09:50 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetailFooter.tsx
> +    // TODO: open sign drawer from staking or send flows
these drawers are not available in activity tab

2024-07-25 09:56 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6367/10091910839/index.html) for [0a0e6dee](https://github.com/input-output-hk/lace/pull/1320/commits/0a0e6deecaa0929d8dffc79ee91d831e9881402b)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 5      | 0      | 0       | 0     | 5     | ✅     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-26 15:14 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetailFooter.tsx
> +  // TODO: implement
👍

2024-07-26 15:23 UTC, danielmain approved these changes
Left just one suggestion which by adding a TODO is sufficient

2024-07-26 15:23 UTC, danielmain commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +  const signStatus = !cosigners.some((c) => c.sharedWalletKey === ownSharedKey && c.signed)
I would not mix signStatus with unsubmitted in the same variable. But is ok for now. A TODO to enhance this would be sufficient :)

2024-07-29 08:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetailFooter.tsx
> +  // TODO: implement
resolved

2024-07-29 08:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/ActivityDetailFooter.tsx
> +    // TODO: open sign drawer from staking or send flows
not a part of this pr

2024-07-29 08:20 UTC, greatertomi requested changes
Visual inconsistency with what we currently have.

![Screenshot 2024-07-26 at 15 51 06](https://github.com/user-attachments/assets/b70619a5-91d5-4217-a397-6ac1f81ead44)

![Screenshot 2024-07-26 at 15 56 46](https://github.com/user-attachments/assets/c11f27c4-2d22-4dc6-ad41-e8b9069d7bcd)

2024-08-02 08:33 UTC, vetalcore commented
not needed anymore

2024-08-02 08:33 UTC, closed without merging