feat: add co sign button initiating file upload drawer
input-output-hk/lace pull request #1322
Opened 2024-07-25 11:46 UTC by szymonmaslowski

# Checklist

- [x] JIRA - [\<link>](https://input-output.atlassian.net/browse/LW-10777)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

![image](https://github.com/user-attachments/assets/0ea15ea5-72d6-4f71-bb01-3a17b0fcd546)
![image](https://github.com/user-attachments/assets/39d13b82-8e34-4b74-a9b5-059596d8fc3d)
![image](https://github.com/user-attachments/assets/36c67e59-fa3f-41e4-ba15-d4032486d765)

2024-07-25 11:53 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionLayout.tsx
> -    const shouldAssetPickerDisplayFooter = multipleSelectionAvailable && currentSection === Sections.ASSET_PICKER;
I moved it to a hook reused from two flows: send and co sign

2024-07-25 11:55 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/useOpenTransactionDrawer.tsx
> +/* eslint-disable react/no-multi-comp */
Render functions are seen as separate components

2024-07-25 11:57 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/useOpenTransactionDrawer.tsx
> +      Sections.IMPORT_SHARED_WALLET_TRANSACTION_JSON
If it is a `IMPORT_SHARED_WALLET_TRANSACTION_JSON` step then footer would not be rendered. Instead, the `CoSignEntry` component renders the foot buttons on its own.

2024-07-25 11:58 UTC, szymonmaslowski commented on packages/core/src/ui/components/TransactionCTAs/TransactionCTAs.tsx
> +        <Button className={buttonClassName} block onClick={onCoSignClick} color="gradient" data-testid="co-sign-button">
TODO: add icon. I would do it in separate ticket

2024-07-25 11:58 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- smokeTests -->
**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6370/10093509747/index.html) for [73297bcc](https://github.com/input-output-hk/lace/pull/1322/commits/73297bcc317db4f4020d11fc810414e6591f6995)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 25     | 7      | 0       | 0     | 32    | ❌     |
<!-- smokeTests -->

<!-- jobs -->
<!-- allurestop -->

2024-07-25 17:44 UTC, vetalcore requested changes

2024-07-25 17:44 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Transaction.tsx
> +      }),
```suggestion
        [Sections.FORM]: <TransactionForm isPopupView={isPopupView} />,
        [Sections.IMPORT_SHARED_WALLET_TRANSACTION_JSON]: <ImportSharedWalletTransaction />,
```

2024-07-25 17:44 UTC, vetalcore commented on packages/core/src/shared-wallets/transaction/CoSignEntry.tsx
> +        <Text.SubHeading>Import transaction</Text.SubHeading>
please move strings to translation package

2024-07-26 12:38 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/components/Drawer/DrawerUIContent.tsx
> +  CO_SIGN_TRANSACTION = 'co-sign-transaction',
Small: `co-sign` get rid of the hyphen here.

2024-07-26 12:39 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/components/Drawer/DrawerUIContent.tsx
> +      return <Transaction />;
Can you stack the cases here?

2024-07-26 12:41 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/transaction/CoSignEntry/CoSignEntry.tsx
> +
Can you extract the error and util function out here?

2024-07-26 12:42 UTC, shawnbusuttil requested changes
Left some suggestions.

2024-07-26 13:05 UTC, shawnbusuttil approved these changes

2024-07-26 13:06 UTC, vetalcore approved these changes

2024-07-26 14:35 UTC, merged