Lw 5329 token prices
input-output-hk/lace pull request #133
Opened 2023-06-16 07:34 UTC by oldGreg5

# Checklist

- [ ] [JIRA](https://input-output.atlassian.net/browse/LW-5329)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-16 12:17 UTC, wklos-iohk requested changes

2023-06-16 12:17 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/tokensPageAssert.ts
> +    await expect(tokenValueFiat).to.match(new RegExp('^([\\d+,.])+\\.\\d{2}\\s\\D{2,3}$'));
Please move all those regular expressions to https://github.com/input-output-hk/lace/blob/main/packages/e2e-tests/src/support/patterns.ts

2023-06-19 13:41 UTC, wklos-iohk requested changes

2023-06-19 13:41 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/tokensPageAssert.ts
> +  assertSeeNotNativeTokenData = async (tokenName: Asset, mode: 'extended' | 'popup') => {
I'd use `Non` instead of `Not`

2023-06-19 13:41 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/commonSteps.ts
> +Given(/^I delete fiat price from local storage$/, async () => {
In one step it is `fiat`, in another `FIAT`. Please keep it consistent.

2023-06-19 13:41 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/tokensPageAssert.ts
> +  assertSeeNotNativeToken = async (tokenName: Asset, mode: 'extended' | 'popup') => {
I'd use `Non` instead of `Not`

2023-06-19 13:41 UTC, wklos-iohk commented on packages/e2e-tests/src/features/TokensPageExtended.feature
> +    Given ADA FIAT price has been fetched
Why all those new scenarios start and end with `ADA FIAT price has been fetched` step?

2023-06-19 14:24 UTC, oldGreg5 commented on packages/e2e-tests/src/utils/browserStorage.ts
> +export const deleteFiatPriceFromBrowserStorage = async (): Promise<void> => {
No can do, this deletes whole 'BACKGROUND_STORAGE' but we need to delete only 'fiatPrices' which is a part of it

2023-07-20 07:30 UTC, closed without merging