refactor: use schema validator on import shared wallet
input-output-hk/lace pull request #1333
Opened 2024-07-30 17:37 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-11030)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

To avoid CSP issues, Ajv is replaced with https://zod.dev/ for schema validation.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-07-30 17:50 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6438/10167114703/index.html) for [6c7c1345](https://github.com/input-output-hk/lace/pull/1333/commits/6c7c1345854748152479462a987c8b3f852377e9)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 0       | 0     | 32    | ✅     |
<!-- processReports -->

<!-- jobs -->
<!-- allurestop -->

2024-08-01 14:42 UTC, danielmain requested changes
Hi Shawn great job finding an alternative to Ajv! I left small requests

2024-08-01 14:42 UTC, danielmain commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +import { z } from 'zod';
Could we move the content of this file outside the `docs` folder? Somewhere in utils where the component uses it?

2024-08-01 14:42 UTC, danielmain commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +              name: z.string().max(20, 'Name should not exceed 20 characters').describe('The name of the participant'),
Should we add translations here?

2024-08-01 14:42 UTC, danielmain commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +const exampleData = {
This can stay in the docs but in a markdown file, explaining how to validate.

2024-08-01 14:42 UTC, danielmain commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +              name: z.string().max(20, 'Name should not exceed 20 characters').describe('The name of the participant'),
if you move the `20` to a constant you probably don't need the eslint magic number ignore

2024-08-01 15:24 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +              name: z.string().max(20, 'Name should not exceed 20 characters').describe('The name of the participant'),
i don't think we need them here but more for the general error that gets parsed. in the future, if we show specific errors, we can have an error map with the i18n.

2024-08-01 15:25 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +              name: z.string().max(20, 'Name should not exceed 20 characters').describe('The name of the participant'),
Yes but should we do this for a schema structure?

2024-08-02 09:49 UTC, szymonmaslowski approved these changes
GJ. Leaving approval, but please split the current `shared-wallet.schema.ts` according to comments

2024-08-02 09:49 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +export type SharedWalletData = z.infer<typeof schema>;
Please move this type to `src/shared-wallets/type.ts` (import zod schema from this file)

2024-08-02 09:49 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +/* eslint-disable no-magic-numbers */
Could you please rename this file to `shared-wallet-schema.ts` (`.` to `-`) to follow the same name as the json schema file?

2024-08-02 09:49 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +/* eslint-disable no-magic-numbers */
Please add a comment at the top explaining that this file was generated from the corresponding `shared-wallet-schema.json` file and should not be modified.

2024-08-02 09:49 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +export const schemaValidator = z.preprocess((data) => {
Please move the `schemaValidator` to `src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts` or a sibling file.

2024-08-02 09:57 UTC, szymonmaslowski commented on packages/core/src/shared-wallets/add-shared-wallet/restore-flow/validateJson.ts
> +        reject({ message: (error as z.ZodError).issues[0].message });
Please pass an Error object instead of a plain object. Calling `reject` is an equivalent of throwing an error. Also sonar is complaining about this line.

2024-08-02 12:31 UTC, shawnbusuttil commented on packages/core/src/shared-wallets/docs/schema/shared-wallet.schema.ts
> +export const schemaValidator = z.preprocess((data) => {
In the general utils. A validator shouldn't be coupled to a single flow.

2024-08-05 09:32 UTC, danielmain approved these changes

2024-08-05 09:34 UTC, merged