Fix/dapp connector transaction information
input-output-hk/lace pull request #136
Opened 2023-06-16 10:06 UTC by mchappell

# Checklist

- [x] JIRA - [LW-7024](https://input-output.atlassian.net/browse/LW-7024)
- [x] JIRA - [LW-7026](https://input-output.atlassian.net/browse/LW-7026)
- [x] JIRA - [LW-7028](https://input-output.atlassian.net/browse/LW-7028)
- [ ] Screenshots added.

---

## Proposed solution

Updated styling for cip30 popup and encoded URI components for consistent display of DApp logo

## Screenshots

<img width="472" alt="Screenshot 2023-06-16 at 11 05 13" src="https://github.com/input-output-hk/lace/assets/7581002/3ac486f8-8778-4412-8e62-6683fa69abb3">

<img width="472" alt="Screenshot 2023-06-16 at 11 05 21" src="https://github.com/input-output-hk/lace/assets/7581002/14d04239-7604-489c-9d46-ee96ce6c73de">

2023-06-19 12:42 UTC, vetalcore requested changes

2023-06-19 12:42 UTC, vetalcore commented on apps/browser-extension-wallet/src/lib/scripts/background/cip30.ts
> +const getDappInfoFromLastActiveTab: () => Promise<Wallet.DappInfo> = async () => {
same as in apps/browser-extension-wallet/src/lib/scripts/background/util.ts?

2023-06-19 12:42 UTC, vetalcore commented on packages/core/src/ui/components/DappTransaction/DappTransaction.module.scss
> +  line-height: size_unit(3);
```suggestion
  @includes text-bodySmall-medium;
```

2023-06-21 10:24 UTC, mchappell commented on packages/core/src/ui/components/DappTransaction/DappTransaction.module.scss
> +  line-height: size_unit(3);
Updated in [52e4e49](https://github.com/input-output-hk/lace/pull/136/commits/52e4e490f85379c1069eecdb6939ac86a3208a9f)

2023-06-21 10:24 UTC, mchappell commented on apps/browser-extension-wallet/src/lib/scripts/background/cip30.ts
> +const getDappInfoFromLastActiveTab: () => Promise<Wallet.DappInfo> = async () => {
updated in [52e4e49](https://github.com/input-output-hk/lace/pull/136/commits/52e4e490f85379c1069eecdb6939ac86a3208a9f)

2023-06-21 10:25 UTC, vetalcore approved these changes

2023-06-22 10:21 UTC, miorsufianiohk approved these changes
LGTM. Great work @mchappell 👍

2023-07-03 10:45 UTC, merged