feat: show used addresses and next unused address in receive box
input-output-hk/lace pull request #1368
Opened 2024-08-14 11:47 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-11236)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Add used addresses and unused addresses to receive box (low fidelity). Changes have been done on full screen mode. Popup changes to be replicated once designs are finalised.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

![image](https://github.com/user-attachments/assets/a170a8b4-8cfe-4f70-aca1-43290ac94579)

2024-08-14 12:14 UTC, rhyslbw requested changes

2024-08-14 12:14 UTC, rhyslbw commented on apps/browser-extension-wallet/src/views/browser-view/components/QRInfoWalletDrawer/QRInfoWalletDrawer.tsx
> +      {useGlacierDrop && <Button.Secondary icon={<PlusOutlined />} onClick={() => void 0} label="Create new address" />}
This is not directly related to Glacier Drop

2024-08-14 12:14 UTC, rhyslbw commented on apps/browser-extension-wallet/src/views/browser-view/components/QRInfoWalletDrawer/QRInfoWalletDrawer.tsx
> +const useGlacierDrop = Boolean(process.env.USER_GLACIER_DROP);
Type on the name, but we need a new feature flag for this as it's independent from Glacier Drop. Maybe `USE_RECEIVE_ADVANCED`

2024-08-14 17:02 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6706/10391642124/index.html) for [4c8e7709](https://github.com/input-output-hk/lace/pull/1368/commits/4c8e77090c9e8d4602587383d846d084a5e4072d)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 31     | 1      | 0       | 0     | 32    | ❌     |
<!-- processReports -->

<!-- jobs -->
<!-- allurestop -->

2024-08-16 10:01 UTC, danielmain approved these changes
Left a small suggestion. But it looks awesome!

2024-08-16 10:01 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/components/QRInfoWalletDrawer/QRInfoWalletDrawer.tsx
> +        {!useAdvancedReceived ? (
I would not the word `use` because of hooks, maybe a `is/has` as a prefix?

2024-08-16 11:21 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/components/QRInfoWalletDrawer/QRInfoWalletDrawer.tsx
> +        {!useAdvancedReceived ? (
Could be but we are also "using" the feature flag. :)

2024-08-19 11:59 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/components/QRInfoWalletDrawer/QRInfoWalletDrawer.tsx
> +      {useGlacierDrop && <Button.Secondary icon={<PlusOutlined />} onClick={() => void 0} label="Create new address" />}
Need you to approve since you requested changes.

2024-08-19 12:17 UTC, rhyslbw approved these changes

2024-08-21 11:34 UTC, merged