E2e add site pick per env
input-output-hk/lace pull request #1375
Opened 2024-08-16 13:40 UTC by oldGreg5

![CleanShot 2024-08-16 at 15 39 48@2x](https://github.com/user-attachments/assets/7a0101e3-95da-4694-a2a1-4b59e7724bdb)
![CleanShot 2024-08-16 at 15 40 03@2x](https://github.com/user-attachments/assets/f2b8a67a-5f35-4d02-a6a4-ac75ad75debe)

2024-08-16 13:51 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6723/10420925635/index.html) for [634786b9](https://github.com/input-output-hk/lace/pull/1375/commits/634786b963b8e3fdb1c03710fc705d5df4f75f1d)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 30     | 2      | 0       | 0     | 32    | ❌     |
<!-- processReports -->

<!-- jobs -->
<!-- allurestop -->

2024-08-19 07:07 UTC, pczeglik-iohk commented on .github/workflows/e2e-tests-linux-split.yml
> +          - dev-mainnet.eu-west-1.lw.iog.io
I think it would be good to have all `.eu-` close to each other. I see in each cardano url options `.eu-west-1` is last. Any particular reason?

2024-08-19 07:07 UTC, pczeglik-iohk requested changes
Code looks good. I spot only one small issue, worth improving :)

2024-08-19 07:16 UTC, oldGreg5 commented on .github/workflows/e2e-tests-linux-split.yml
> +          - dev-mainnet.eu-west-1.lw.iog.io
No reason, thanks. It's changed

2024-08-19 07:52 UTC, pczeglik-iohk approved these changes
Looks good. Thank you @oldGreg5

2024-08-19 07:52 UTC, merged