[LW-9999] feat: Implement UI for manual message signing (hifi)
input-output-hk/lace pull request #1391
Opened 2024-08-27 08:55 UTC by danielmain

## Overview
This PR implements the UI for manual message signing, addressing the requirements outlined in [LW-9999]. This feature allows users to sign messages manually, which is crucial for interacting with certain DApps, including the Midnight GD Portal.

## Background
Some DApps require message signing as a method to prove ownership of keys and the assets they control. This functionality is particularly important for the Midnight dapp integration.

## Changes
- Implemented `SignMessageDrawer` component for handling message signing UI
- Added password prompt for secure signing process
- Integrated with `withSignDataConfirmation` for actual signing logic
- Used existing translation keys for consistent localization
- Ensured type safety and adherence to `ObservableWallet` interface

## Testing
- [ ] Tested manual message signing with various input scenarios
- [ ] Verified correct handling of password input
- [ ] Checked error handling and display
- [ ] Ensured compatibility with both in-memory and hardware wallets

## Screenshots

Closes [LW-9999]

2024-08-27 09:09 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/6789/10574926143/index.html) for [f69e90b1](https://github.com/input-output-hk/lace/pull/1391/commits/f69e90b11bf3fdede6c9461541cecd0fee58d948)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 4       | 0     | 36    | ✅     |
<!-- processReports -->

<!-- jobs -->
<!-- allurestop -->

2024-08-28 09:16 UTC, michalrus commented on flake.nix
> +      default = mkDevShell system;
Could you add it to `hydraJobs`, so that it's also built and cached in cache.iog.io for everyone to just download when entering the devshell?

It would be something like:

```
{
    …
    hydraJobs = {
      …
      devShells = inputs.self.devShells;
      …      
    }
    …
  }
}
```

2024-09-03 11:57 UTC, shawnbusuttil commented on packages/common/src/ui/components/Form/TextArea/TextArea.tsx
> +  rows?: number;
```suggestion
  rows? = 1;
```

2024-09-03 11:59 UTC, shawnbusuttil commented on packages/core/src/ui/components/WalletOwnAddressesDropdown/WalletOwnAddressDropdown.module.scss
> +  background-color: var(--bg-color-body, #ffffff) !important;
When you have #fff or #000 you can do `var(--color-white/black)`

2024-09-04 08:12 UTC, rhyslbw requested changes
There's a typo in the directory name `features/sing-message` 😄

2024-09-04 08:12 UTC, rhyslbw commented on apps/browser-extension-wallet/src/lib/wallet-api-ui.ts
> +const securelyEraseString = (s: string): string => {
This and the next function are utilities that, on the face of it, should be used in more places across the application. @mkazlauskas can you review this aspect of the PR and apply any learnings from the recent paper wallet audit?

2024-09-04 10:43 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/wallet-api-ui.ts
> +const securelyEraseString = (s: string): string => {
Creating a new `Buffer` object and clearing it doesn't do anything to clear `s`. Let's remove this, and follow the pattern used in `withSignTxConfirmation` where we set `password` variable to `''` in `finally`.

2024-09-04 10:53 UTC, mkazlauskas requested changes

2024-09-04 10:53 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/wallet-api-ui.ts
> +  const performAction$ = from(action());
Is there a good reason to convert this to observable and then back to promise a couple lines below? If not, let's follow the pattern used in `withSignTxConfirmation`. If yes, let's update `withSignTxConfirmation`.

2024-09-04 10:53 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/views/browser-view/features/sing-message/SignMessage.tsx
> +  const [password, setPassword] = useState<string>('');
Using this hook will help clearing secrets from memory. We spent a lot of time figuring out how to make it work and get around React cache. The hook also returns a `clearSecrets` function that should be called when we are done.

```suggestion
  const { password, setPassword } = useSecrets();
```

2024-09-04 10:53 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/views/browser-view/features/sing-message/SignMessage.tsx
> +  onSign: (address: string, message: string, password: string) => void;
We should avoid passing the password around. Instead, use the `useSecrets` hook in parent component to access it.
```suggestion
  onSign: (address: string, message: string) => void;
```

2024-09-04 10:54 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/wallet-api-ui.ts
> +const securelyEraseString = (s: string): string => {
Posted a couple change requests for handling the password. We should test it with chrome devtools to make sure it's being cleared/derefenced before merging this PR.

2024-09-04 13:31 UTC, danielmain commented on apps/browser-extension-wallet/src/lib/wallet-api-ui.ts
> +  const performAction$ = from(action());
I don't like RSjx 😅 much, it was my mistake. Fix [here](https://github.com/input-output-hk/lace/pull/1391/commits/56bf963a3051338302116a5d09a3d17d70347ab7)

2024-09-04 13:31 UTC, danielmain commented on apps/browser-extension-wallet/src/lib/wallet-api-ui.ts
> +const securelyEraseString = (s: string): string => {
Fix [here](https://github.com/input-output-hk/lace/pull/1391/commits/56bf963a3051338302116a5d09a3d17d70347ab7)

2024-09-04 13:35 UTC, danielmain commented
> There's a typo in the directory name `features/sing-message` 😄

Fixed [here](https://github.com/input-output-hk/lace/pull/1391/commits/4f56ed639163294deebfe6f6b081058a964d8dfd)

2024-09-04 13:36 UTC, danielmain commented on packages/core/src/ui/components/WalletOwnAddressesDropdown/WalletOwnAddressDropdown.module.scss
> +  background-color: var(--bg-color-body, #ffffff) !important;
I did a refactor and this file does not exist anymore. I am not using anymore hexadecimals ;)

2024-09-04 13:39 UTC, danielmain commented on packages/common/src/ui/components/Form/TextArea/TextArea.tsx
> +  rows?: number;
@shawnbusuttil  this is an interface, I can't add a value. Only in the implementation, where rows is not mentioned.

2024-09-04 13:56 UTC, danielmain commented on flake.nix
> +      default = mkDevShell system;
Added [here](https://github.com/input-output-hk/lace/pull/1391/commits/7ff8426c4a6024a6a3a8f3ce3eb6bd709af3c085) pls check @michalrus if its ok 🙏🏻

2024-09-05 06:59 UTC, mkazlauskas approved these changes
Nice work! I tested and verified that password can be GCed

2024-09-05 07:18 UTC, michalrus requested changes
One small change 🙏

2024-09-05 07:18 UTC, michalrus commented on flake.nix
> +            libudev-zero
There's an [eval failure](https://github.com/input-output-hk/lace/pull/1391/checks?check_run_id=29694964011) on `aarch64-darwin`:

```
error: Package ‘libudev-zero-1.0.3’ in […] is not available on the requested hostPlatform:

hostPlatform.config = "aarch64-apple-darwin"
```

I would suggest to also move it inside `lib.optionals stdenv.isLinux`.

2024-09-05 07:18 UTC, michalrus commented on flake.nix
> +        default = inputs.self.devShells.${system}.default;
Nice! This works, but could be simplified to just:

```nix
hydraJobs.devShells = inputs.self.devShells;
```

… while keeping the same structure inside, right? :)

2024-09-05 07:20 UTC, michalrus commented on flake.nix
> +      default = mkDevShell system;
Thanks! Commented [there](https://github.com/input-output-hk/lace/pull/1391#discussion_r1744933543).

2024-09-05 08:42 UTC, rhyslbw requested changes

2024-09-05 08:42 UTC, rhyslbw commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
> +            {process.env.USE_MIDNIGHT_PRELAUNCH_EVENT === 'true' && !isPopup && getSignMessageLink()}
```suggestion
            {process.env.USE_MESSAGE_SIGNING === 'true' && !isPopup && getSignMessageLink()}
```

2024-09-05 08:42 UTC, rhyslbw commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
> +            {process.env.USE_MIDNIGHT_PRELAUNCH_EVENT === 'true' && !isPopup && getSignMessageLink()}
This feature is not coupled with Glacier Drop, and we're looking to release it ASAP

2024-09-05 09:50 UTC, danielmain commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
> +            {process.env.USE_MIDNIGHT_PRELAUNCH_EVENT === 'true' && !isPopup && getSignMessageLink()}
@rhyslbw done here: https://github.com/input-output-hk/lace/pull/1391/commits/6a58503526d8814a04448a3f3634efb895cd6a14

2024-09-05 10:19 UTC, rhyslbw approved these changes

2024-09-05 10:43 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
> +      <Separator />
Small: Separator should probably not be part of this function.

2024-09-05 10:45 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/sign-message/SignMessageDrawer.tsx
> +    <div data-testid="sign-message" className={styles.container}>
If this is a <Flex> you can avoid the flex related styles and place them here.

2024-09-05 10:48 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/sign-message/useSignMessageState.tsx
> +      address: address.address.toString(),
For slight improvement on readability, you can desconstruct address in the map and you wouldn't need to do `address.address`.

2024-09-05 10:51 UTC, shawnbusuttil approved these changes
Left some optional suggestions. Good job.

2024-09-05 13:17 UTC, michalrus approved these changes

2024-09-05 19:52 UTC, merged