fix: disallow duplicates when updating address book
input-output-hk/lace pull request #141
Opened 2023-06-19 12:12 UTC by greatertomi

# Checklist

- [x] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Disallow duplicates when updating the address book

2023-06-19 16:11 UTC, gabriela-ponce approved these changes

2023-06-20 08:11 UTC, dmitrii-gaico approved these changes

2023-06-20 08:50 UTC, lucas-barros requested changes

2023-06-20 08:58 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/context/AddressBookProvider.tsx
> +    const currentList = list.filter((data) => data.id !== id);
`data` needs a type.

2023-06-20 09:01 UTC, VanessaPC reviewed
Looks good to me, just a small comment.

2023-06-20 09:05 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/context/AddressBookProvider.tsx
> +    const currentList = list.filter((data) => data.id !== id);
I think it gets its type from `list`.

2023-06-20 09:18 UTC, lucas-barros approved these changes

2023-06-20 09:32 UTC, shawnbusuttil approved these changes

2023-06-20 11:02 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/context/AddressBookProvider.tsx
> +    const currentList = list.filter((data) => data.id !== id);
Not for me, it's complaining about ts.

2023-06-20 12:36 UTC, merged