Feat/lw 3951
input-output-hk/lace pull request #142
Opened 2023-06-19 12:14 UTC by vetalcore

# Checklist

- [x] https://input-output.atlassian.net/browse/LW-3951
- [x] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-28 09:52 UTC, mchappell approved these changes

2023-06-29 11:58 UTC, miorsufianiohk requested changes
Hi @vetalcore ,

Just an interim test report as I am still testing this. Scenario 4 (see below), failed during testing. I believe when users click on 'View Transaction' of the "All Done!" screen, they will go to transaction screen. However, when they return back to Collateral, this screen should not be shown. At the moment it is still. [Please see video](https://drive.google.com/file/d/1955CibPmkRK1pipr2fKnlGnlWqNYRqOK/view?usp=sharing)
**4. Given the user has collateral, when going to the collateral option in settings, then will see a screen with a CTA <Reclaim collateral>**

2023-06-29 13:29 UTC, vetalcore commented
> Hi @vetalcore ,
> 
> Just an interim test report as I am still testing this. Scenario 4 (see below), failed during testing. I believe when users click on 'View Transaction' of the "All Done!" screen, they will go to transaction screen. However, when they return back to Collateral, this screen should not be shown. At the moment it is still. [Please see video](https://drive.google.com/file/d/1955CibPmkRK1pipr2fKnlGnlWqNYRqOK/view?usp=sharing) **4. Given the user has collateral, when going to the collateral option in settings, then will see a screen with a CTA **

@miorsufianiohk , fixed

2023-06-29 14:46 UTC, miorsufianiohk requested changes
Hi @vetalcore ,

I am getting a blank page and seeing DOMException error when I attempted to browse to "Collateral" from Settings. Please see [screenshot](https://drive.google.com/file/d/1mY070MEMTVH4_wuY5S1gwiFxCy5upGco/view?usp=sharing) and [video](https://drive.google.com/file/d/12cxujGzNXFwavk-v4wcsv4oCdyWZHv0J/view?usp=sharing).

2023-06-30 14:38 UTC, miorsufianiohk requested changes
Hi @vetalcore,

I found several issues in this iteration elaborated by the following:

1. After adding collateral, when I clicked ‘Close’ button at the “All done!” screen, the ‘Reclaim collateral’ screen was displayed. I believe after clicking ‘Close’ button at the “All done” screen, the screen should be dismissed and Settings screen should be displayed instead. [See video](https://drive.google.com/file/d/12f0w4cZGSk8cJ17H905QheR7kiqppMTO/view?usp=sharing)

2. After clicking on ‘Reclaim collateral’, ‘Settings’ screen was immediately shown. No "Collateral reclaimed" toast was observed. [See video](https://drive.google.com/file/d/1sQBDBYxuIo9ngOvT_FGHpmL9Y5uWrjI8/view?usp=sharing)

3. I created collateral and then reclaimed it (I noticed no "Collateral reclaimed" toast was shown). Soon after, when I created collateral again, upon connecting with Ledger, I noticed the ‘collateral reclaimed’ toast was displayed. The ‘collateral reclaimed’ toast should only be displayed when collateral gets reclaimed. [See video](https://drive.google.com/file/d/1ygc4jkaG8H9UitPezVDLQggjE51Hy2UD/view?usp=sharing)

2023-07-03 11:22 UTC, vetalcore commented
> Hi @vetalcore,
> 
> I found several issues in this iteration elaborated by the following:
> 
> 1. After adding collateral, when I clicked ‘Close’ button at the “All done!” screen, the ‘Reclaim collateral’ screen was displayed. I believe after clicking ‘Close’ button at the “All done” screen, the screen should be dismissed and Settings screen should be displayed instead. [See video](https://drive.google.com/file/d/12f0w4cZGSk8cJ17H905QheR7kiqppMTO/view?usp=sharing)
> 2. After clicking on ‘Reclaim collateral’, ‘Settings’ screen was immediately shown. No "Collateral reclaimed" toast was observed. [See video](https://drive.google.com/file/d/1sQBDBYxuIo9ngOvT_FGHpmL9Y5uWrjI8/view?usp=sharing)
> 3. I created collateral and then reclaimed it (I noticed no "Collateral reclaimed" toast was shown). Soon after, when I created collateral again, upon connecting with Ledger, I noticed the ‘collateral reclaimed’ toast was displayed. The ‘collateral reclaimed’ toast should only be displayed when collateral gets reclaimed. [See video](https://drive.google.com/file/d/1ygc4jkaG8H9UitPezVDLQggjE51Hy2UD/view?usp=sharing)

@miorsufianiohk all the following issues have been resolved

2023-07-03 14:31 UTC, mchappell approved these changes

2023-07-03 15:20 UTC, vetalcore commented on apps/browser-extension-wallet/src/hooks/useCollateral.ts
> +      const txBuilt = txBuilder.build();
it's been like that since the beginning, and no issues reported, could you please explain a bit more here?

2023-07-03 15:25 UTC, miorsufianiohk requested changes
Hi @vetalcore ,

Overall looking much better. Thank you for the fix. 👍 . However, I found a minor issue. When I 1) set collateral, 2) reclaimed collateral and 3) attempted to set collateral again, I got stuck at the "Confirm Transaction with Ledger" button. After confirming the Ledger device, the "Confirm Transaction with Ledger" button was enabled and nothing seemed to work after that. I had to refresh the page in order to proceed and retry. I repeated this test many times with the same result. [Please see video](https://drive.google.com/file/d/1FS1zh-I7BlyeUzDfDQOQQfGTH_Yy9bbr/view?usp=sharing).

2023-07-03 15:39 UTC, vetalcore commented
> Hi @vetalcore ,
> 
> Overall looking much better. Thank you for the fix. 👍 . However, I found a minor issue. When I 1) set collateral, 2) reclaimed collateral and 3) attempted to set collateral again, I got stuck at the "Confirm Transaction with Ledger" button. After confirming the Ledger device, the "Confirm Transaction with Ledger" button was enabled and nothing seemed to work after that. I had to refresh the page in order to proceed and retry. I repeated this test many times with the same result. [Please see video](https://drive.google.com/file/d/1FS1zh-I7BlyeUzDfDQOQQfGTH_Yy9bbr/view?usp=sharing).

@miorsufianiohk  fixed, please verify

2023-07-03 19:05 UTC, miorsufianiohk requested changes
Hi @vetalcore ,

Thank you for fixing the issue that I found in the previous iteration. For this iteration, when I chose to cancel the transaction on Ledger device, as expected an error screen was shown. However, both buttons "Back" and "Cancel" led to to the same "Confirm Transaction with Ledger" screen. As a user, I'd probably expect when I choose "Cancel" that I'd be redirected to the "Settings" screen instead. [Please see video](https://drive.google.com/file/d/1HbN3loZ9XFTVPvxAYpVY3wq8kVqoxdxN/view?usp=sharing)

In addition to the above, I reported the issue on the display of "New ordinary transaction" vs "New multisig transaction" when setting collateral as reported on [Slack here](https://input-output-rnd.slack.com/archives/C01S2DD5B0D/p1688404605391659). As, I am unsure if this is related to this PR or not, I am reporting for completeness. (whilst we await for somebody to reply to the Slack thread). Thank you.

2023-07-04 07:51 UTC, vetalcore commented
> Hi @vetalcore ,
> 
> Thank you for fixing the issue that I found in the previous iteration. For this iteration, when I chose to cancel the transaction on Ledger device, as expected an error screen was shown. However, both buttons "Back" and "Cancel" led to to the same "Confirm Transaction with Ledger" screen. As a user, I'd probably expect when I choose "Cancel" that I'd be redirected to the "Settings" screen instead. [Please see video](https://drive.google.com/file/d/1HbN3loZ9XFTVPvxAYpVY3wq8kVqoxdxN/view?usp=sharing)
> 
> In addition to the above, I reported the issue on the display of "New ordinary transaction" vs "New multisig transaction" when setting collateral as reported on [Slack here](https://input-output-rnd.slack.com/archives/C01S2DD5B0D/p1688404605391659). As, I am unsure if this is related to this PR or not, I am reporting for completeness. (whilst we await for somebody to reply to the Slack thread). Thank you.

@miorsufianiohk, i've just pushed a fix for the first one. As for the second one, it is definitely not related to this particular pr, nevertheless, we should be safe here, as far as user would be redirected to the fails tx screen in such case.

2023-07-04 10:13 UTC, miorsufianiohk requested changes
Hi @vetalcore ,

As discussed on Slack.  I could also get the "New multisig transaction" displayed on Ledger device when I used Lace's Popup View to set collateral (I didn't have to reject any transaction). When I continued with the multisig transaction, this was what I observed. [See screenshot ](https://drive.google.com/file/d/1P7W4xl2fNnW8NR30s_-Mve5rYcL0mTLE/view?usp=sharing)

2023-07-06 16:21 UTC, miorsufianiohk requested changes
Hi @vetalcore ,

Thanks for pushing the new updates. Overall, they look good. However, I need to double check if the Acceptance criteria that requires ADA amount to be greater than 6 ADA is still valid in order to set collateral. When testing, I discovered that when I had more than 7 ADA, I wasn't able to set collateral. Please see these: [Not enough ADA screen](https://drive.google.com/file/d/1GIVWipXHvfZE3G_tYlp5G81KSNWHHK76/view?usp=sharing) & [Total ADA is more than 7](https://drive.google.com/file/d/1__OGll1BwktYEogBlGIx4yIohvODRLUC/view?usp=sharing) & [video recording](https://drive.google.com/file/d/1INdtMZAAHboE9EzShtr0p6MddrMdpo6l/view?usp=sharing)
[Acceptance criteria are here](https://input-output.atlassian.net/browse/LW-3951?focusedCommentId=190863)

2023-07-07 11:42 UTC, miorsufianiohk approved these changes
LGTM. Great work @vetalcore 👍 

Note: We have decided on Slack that the issue with unable to set collateral when ADA balance is > 7 is not in the scope of this PR.

2023-07-07 11:44 UTC, merged