feat(extension): shared wallets feature flags are now controlled via PostHog
input-output-hk/lace pull request #1448
Opened 2024-09-26 05:54 UTC by AngelCastilloB

Currently the Shared Wallet feature is behind a build time feature flag

We’re looking to make this feature part of the new opt-in beta program, which requires it to be upgraded to a runtime feature flag, controlled remotely via PostHog

# Checklist

- [x] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-11515)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Read the flag from posthog

2024-09-26 06:05 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/7009/11046403510/index.html) for [ae98171d](https://github.com/input-output-hk/lace/pull/1448/commits/ae98171df4e5ab1ebd2314b0431bfdb8668176ed)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 4       | 0     | 36    | ✅     |
<!-- processReports -->

<!-- jobs -->
<!-- allurestop -->

2024-09-27 08:01 UTC, mchappell commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts
> +export const getDefaultFeatureFlags = (): FallbackConfiguration => ({
We could probably avoid this if we follow https://posthog.com/product-engineers/feature-flag-best-practices#5-bootstrap-your-flags-to-make-them-available-immediately in the posthog init functon

2024-09-27 08:04 UTC, AngelCastilloB commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts
> +export const getDefaultFeatureFlags = (): FallbackConfiguration => ({
This is used to initialize the record on the constructor, and also to set default values if communication with post-hog fails. I think is a good idea to initialize the record with sensible default values (even if posthog connection fails)

2024-09-27 08:10 UTC, AngelCastilloB commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts
> +export const getDefaultFeatureFlags = (): FallbackConfiguration => ({
I just want to make sure the featureFlags object is properly initialized:

```
    this.featureFlags = {
      [Wallet.Cardano.NetworkMagics.Mainnet]: getDefaultFeatureFlags(),
      [Wallet.Cardano.NetworkMagics.Preprod]: getDefaultFeatureFlags(),
      [Wallet.Cardano.NetworkMagics.Preview]: getDefaultFeatureFlags(),
      [Wallet.Cardano.NetworkMagics.Sanchonet]: getDefaultFeatureFlags()
    };
```
This object is a combination of the feature flags + the interpretation of the payload, I will look if there is an easy way to bootstrap this (including payload)

2024-09-27 12:49 UTC, mchappell approved these changes

2024-09-30 02:04 UTC, rhyslbw requested changes

2024-09-30 02:04 UTC, rhyslbw commented on apps/browser-extension-wallet/.env.example
> +POSTHOG_DEV_TOKEN=phc_gH96Lx5lEVXTTWEyytSdTFPDk3Xsxwi4BqG88mKObd1
```suggestion
POSTHOG_DEV_TOKEN='dev-token'
```

2024-09-30 03:10 UTC, AngelCastilloB commented on apps/browser-extension-wallet/.env.example
> +POSTHOG_DEV_TOKEN=phc_gH96Lx5lEVXTTWEyytSdTFPDk3Xsxwi4BqG88mKObd1
done here https://github.com/input-output-hk/lace/pull/1448/commits/47dcca4a08102436f9442ff4838c21cb7328873a

2024-09-30 04:16 UTC, rhyslbw approved these changes

2024-09-30 10:39 UTC, merged