feat: [lw-11532] add analytics for shared wallet
input-output-hk/lace pull request #1462
Opened 2024-10-07 21:36 UTC by vetalcore

# Checklist

- [ ] JIRA -[LW-11532](https://input-output.atlassian.net/browse/LW-11532)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-10-07 21:50 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/7067/11224379895/index.html) for [3eb54337](https://github.com/input-output-hk/lace/pull/1462/commits/3eb54337b041c87418a1ec985725dd6fe7cf8cc0)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 32     | 0      | 4       | 0     | 36    | ✅     |
<!-- processReports -->
<!-- jobs -->
<!-- allurestop -->

2024-10-08 13:11 UTC, greatertomi requested changes

2024-10-08 20:25 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/components/TransactionCTAsBox/TransactionCTAsBox.tsx
> +    }
done here 43a39d207d88512a6fb35873570a36b04731b2b3

2024-10-09 15:07 UTC, greatertomi requested changes

2024-10-09 15:07 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx
> +              onClose={async () => await analytics.sendEventToPostHog(PostHogAction.SharedWalletsGenerateCloseClick)}
Ditto [this](https://github.com/input-output-hk/lace/pull/1462#discussion_r1791769989). Kindly apply this to the several occurrences in this file

2024-10-09 15:07 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/SharedWalletLayout/type.ts
> +  onNext?: () => Promise<void> | void;
We are adding Promise to void because of analytics which I think is unnecessary
```suggestion
  onBack?: () => void;
  onNext?: () => void;
```

2024-10-09 15:07 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/ShareWalletDetails/ShareWalletDetails.tsx
> +  onDownloadClick?: () => Promise<void>;
Ditto this
```suggestion
  onDownloadClick?: () => void;
```

2024-10-09 15:07 UTC, greatertomi commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/SharedWalletCreationFlow.tsx
> +};
Ditto this
```suggestion
  onAddCosignersNextClick?: () => void;
  onDefineQuorumDownloadClick?: () => void;
  onDefineQuorumNextClick?: () => void;
  onImportantInfoBackClick?: () => void;
  onImportantInfoNextClick?: () => void;
  onOpenSharedWalletClick?: () => void;
  onWalletNameNextClick?: () => void;
};
```

2024-10-09 18:22 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
> +      await analytics.sendEventToPostHog(evtAction, {
done here c0fe6a164ccff6290f54af2f906d13031a2d6715

2024-10-09 18:22 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
> +    const handleClose = async () => {
done here c0fe6a164ccff6290f54af2f906d13031a2d6715

2024-10-09 18:22 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
> +          sendEventToPostHog(
done here c0fe6a164ccff6290f54af2f906d13031a2d6715

2024-10-09 18:22 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/shared-wallet/SharedWallet.tsx
> +              onClose={async () => await analytics.sendEventToPostHog(PostHogAction.SharedWalletsGenerateCloseClick)}
done here c0fe6a164ccff6290f54af2f906d13031a2d6715

2024-10-09 18:22 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/SharedWalletLayout/type.ts
> +  onNext?: () => Promise<void> | void;
done here c0fe6a164ccff6290f54af2f906d13031a2d6715

2024-10-09 18:22 UTC, vetalcore commented on packages/core/src/shared-wallets/add-shared-wallet/creation-flow/ShareWalletDetails/ShareWalletDetails.tsx
> +  onDownloadClick?: () => Promise<void>;
done here c0fe6a164ccff6290f54af2f906d13031a2d6715

2024-10-10 09:57 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/components/TransactionCTAsBox/TransactionCTAsBox.tsx
> +  };
```suggestion
  const onCoSignClick = () => {
    void analytics.sendEventToPostHog(PostHogAction.SharedWalletsCosignClick);
    openCoSignTransactionDrawer();
  };
```

2024-10-10 10:33 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/components/TransactionCTAsBox/TransactionCTAsBox.tsx
> +  };
done here 1cc494419e3cb3876e2112cdcd89d08d4bf01a3f

2024-10-10 10:33 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionDrawer/Footer.tsx
> +    const onConfirm = useCallback(async () => {
done here

2024-10-10 10:36 UTC, greatertomi approved these changes
LGTM. Well done @vetalcore 🚀

2024-10-22 09:54 UTC, merged