feat: show handles in recieve drawer
input-output-hk/lace pull request #148
Opened 2023-06-20 00:57 UTC by lucas-barros

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-22 11:43 UTC, dmitrii-gaico requested changes
@lucas-barros Hey Lucas!
Please fix two issues below : 
1.The clipboard message when copy the handle
2.The handle's order Logic. 
Please check details in Slack Thread.
cc @gabriela-ponce

2023-06-22 12:27 UTC, lucas-barros commented
@greatertomi I replaced `useAdaHandle` with the existing `useGetHandles` since the handles observable already gets the handles from assets.
https://github.com/input-output-hk/lace/pull/148/commits/883a233d92167139fed8594b631599ab433ebabc

2023-06-22 17:53 UTC, gabriela-ponce approved these changes

2023-06-22 20:31 UTC, greatertomi approved these changes

2023-06-23 07:42 UTC, dmitrii-gaico approved these changes

2023-06-23 10:39 UTC, rhyslbw approved these changes
Great work @lucas-barros. Ready for squashing

2023-06-23 11:48 UTC, merged