fix: [lw-11783] do not show add shared wallet btn for hw
input-output-hk/lace pull request #1503
Opened 2024-10-30 13:27 UTC by vetalcore

# Checklist

- [ ] JIRA - [LW-11783](https://input-output.atlassian.net/browse/LW-11783)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-10-30 13:39 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/7255/11594203143/index.html) for [4096afaa](https://github.com/input-output-hk/lace/pull/1503/commits/4096afaa75635b136518fc8f8272222722e2e76e)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 31     | 1      | 4       | 0     | 36    | ❌     |
<!-- processReports -->
<!-- jobs -->
<!-- allurestop -->

2024-10-31 08:45 UTC, mchappell requested changes

2024-10-31 08:45 UTC, mchappell commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
> +            {sharedWalletsEnabled && !isSharedWallet && !isHardwareWallet && <AddSharedWalletLink isPopup={isPopup} />}
can you extract this to a useMemo variable `showAddSharedWalletLink`

2024-10-31 08:49 UTC, vetalcore commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/DropdownMenuOverlay.tsx
> +            {sharedWalletsEnabled && !isSharedWallet && !isHardwareWallet && <AddSharedWalletLink isPopup={isPopup} />}
done here 64ad262399d833f53538064f180956fcd86932c0

2024-10-31 09:08 UTC, mchappell approved these changes

2024-10-31 09:39 UTC, merged