feat: providers are now consumed from the service worker instead of the UI script
input-output-hk/lace pull request #1507
Opened 2024-10-31 04:28 UTC by AngelCastilloB

Provider objects (or at least an instance of RateLimiter) must be shared between SW and UI.
# Checklist

- [x] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-11761)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

UI script now consumes Provider objects instead of creating their own providers

2024-10-31 04:52 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/7272/11606114687/index.html) for [aa76a7e7](https://github.com/input-output-hk/lace/pull/1507/commits/aa76a7e7d70838a272e04d08f3bf30f4d2cce5e5)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 23     | 9      | 4       | 0     | 36    | ❌     |
<!-- processReports -->
<!-- jobs -->
<!-- allurestop -->

2024-10-31 10:34 UTC, mkazlauskas requested changes

2024-10-31 10:34 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
> +            return from(getProviders(chainName));
I think this creates new provider objects rather than reusing the ones already used by the wallet. An easy fix (a little bit hacky though :sweat_smile:) would be to memoize getProviders function

2024-10-31 10:56 UTC, AngelCastilloB commented on apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
> +            return from(getProviders(chainName));
It does, but internally it uses the same RateLmiter object which was the point no?

2024-11-01 03:54 UTC, AngelCastilloB commented on apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
> +            return from(getProviders(chainName));
done here https://github.com/input-output-hk/lace/pull/1507/commits/8d9d021d58664e3bf9fa8b79be3c6c49c015e159

2024-11-01 07:35 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/background/wallet.ts
> +            return from(getProviders(chainName));
Good point, so it was already working correctly :) Thanks @AngelCastilloB

2024-11-01 07:35 UTC, mkazlauskas approved these changes
Nice work! :rocket:

2024-11-07 03:27 UTC, merged