[LW-6640] build repo with yarn v3
input-output-hk/lace pull request #159
Opened 2023-06-21 13:35 UTC by tgunnoe

# Checklist

- [x] JIRA - https://input-output.atlassian.net/browse/LW-6640
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-08-16 08:15 UTC, mchappell approved these changes

2023-08-16 09:33 UTC, rhyslbw reviewed
LGTM

2023-08-16 09:33 UTC, rhyslbw commented on .github/shared/build/action.yml
> +      run: yarn install --immutable
```suggestion
      run: yarn install --immutable --inline-builds
```

https://github.com/input-output-hk/cardano-js-sdk/blob/ab2265aa118b7f771055b5e3eab5621eea4f3476/.github/workflows/continuous-integration-unit-tests.yaml#L31

Maybe it's helpful to use this option too https://yarnpkg.com/cli/install#options

2023-08-16 09:33 UTC, rhyslbw commented on apps/browser-extension-wallet/package.json
> +    "cleanup": "yarn exec rm -rf dist node_modules",
This is nice. We can make the same change in the `cardano-js-sdk` and drop `shx` as a dependency

2023-08-16 09:48 UTC, ljagiela requested changes

2023-08-16 09:48 UTC, ljagiela commented on packages/e2e-tests/README.md
>  - Run tests (from the `packages/e2e-tests` directory)
I think we need to remove all occurrences of `./node_modules/.bin/` in this file

2023-08-16 11:46 UTC, tgunnoe commented on .github/shared/build/action.yml
> +      run: yarn install --immutable
yes, thank you.

2023-08-16 11:47 UTC, tgunnoe commented on packages/e2e-tests/README.md
>  - Run tests (from the `packages/e2e-tests` directory)
thank you!

2023-08-16 14:28 UTC, tshaynik approved these changes
LGTM.

2023-08-17 06:43 UTC, ljagiela approved these changes

2023-08-17 12:45 UTC, miorsufianiohk approved these changes

2023-08-17 16:05 UTC, merged