Fix: LW-12003
input-output-hk/lace pull request #1614
Opened 2024-12-20 13:02 UTC by mchappell

## Proposed solution

Automate snapshot checking, implement measures to prevent memoization

## Testing

Follow scenarios from ticket

2024-12-20 13:20 UTC, pczeglik-iohk commented
<!-- allure -->
# Allure Report
[`allure-report-publisher`](https://github.com/andrcuns/allure-report-publisher) generated test report!

<!-- jobs -->
<!-- processReports -->
**processReports**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/smoke/linux/chrome/7744/12431918397/index.html) for [2d070757](https://github.com/input-output-hk/lace/pull/1614/commits/2d070757ea47e44cc8829157c69ecd4b9d67faf2)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 0      | 4       | 0     | 37    | ✅     |
<!-- processReports -->
<!-- jobs -->
<!-- allurestop -->

2025-01-07 12:37 UTC, przemyslaw-wlodek approved these changes
Amazing job @mchappell! 🚀

2025-01-07 13:05 UTC, ljagiela requested changes

2025-01-07 13:05 UTC, ljagiela commented on packages/e2e-tests/src/steps/commonSteps.ts
> +        needle = String(getTestWallet(TestWalletName.MultiAccActive1).password);
maybe we could replace with just `String(process.env.WALLET_1_PASSWORD)` ?

2025-01-08 11:44 UTC, ljagiela approved these changes

2025-01-08 11:45 UTC, merged