[LW-6791] Track the opted-in & opted-out user group (using new requirements)
input-output-hk/lace pull request #173
Opened 2023-06-26 07:01 UTC by marcin-mazurek

# Checklist

- [ ] JIRA - [LW-6791](https://input-output.atlassian.net/browse/LW-6791)
- [ ] Proper tests implemented
- [ ] ~Screenshots added.~

---

## Proposed solution

Refer to the Jira ticket for the requiements and acceptance criteria.

## Testing

TBD

## Screenshots

n/a

2023-06-26 10:15 UTC, marcin-mazurek commented on apps/browser-extension-wallet/.env.example
> +# ADA Handle URLs
Not related to analytics. Just added those entries at this file got out of sync with `.env.defaults`

2023-06-26 10:18 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +    this.matomoClient.setOptedInForEnhancedTracking(status);
I know there is some repetition and I could have gone for an array of clients instead, like @vetalcore did in the original PR. However, we're likely to deprecate Matomo pretty soon, and this form makes it easier to clean up code afterwards, and it extremely unlikely we will have more than 2 tools for tracking.

2023-06-26 10:19 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +export enum EnhancedAnalyticsOptInStatus {
I'm aware we could use just a boolean instead. Unfortunately it would result in a breaking change to localStorage structure and force us to write some migration logic. So I'd rather keep it as is. Moreover, if in the future, we will want more granular level of analytics consent, this data structure will make it easier to implement.

2023-06-26 10:22 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx
> +  trackingDisabled?: boolean;
I renamed from `feature` to `tracking` as `feature` was a bit vague to me. Additionally I flipped it from `enabled` to `disabled` since it's primary use case is to disable tracking in unit/integration tests, so I think it makes the usage cleaner.

2023-06-26 10:23 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx
> +    () => tracker || new AnalyticsTracker(currentChain, trackingDisabled, optedInForEnhancedTracking),
If we happen to ever change the feature toggle in the runtime, I guess we should be OK to just re-create the whole AnalyticsTracker instance, it's not a standard use case anyway.

2023-06-26 10:24 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/config.ts
> +  [Wallet.Cardano.NetworkId.Mainnet]: 'phc_e8SaOOWpXpNE59TnpLumeUjWm4iv024AWjhQqU406jr',
Those are public write-only keys. I think it's totally fine to keep them in the source code without hiding them with eg. GitHub secrets.

2023-06-26 11:19 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/matomo/MatomoClient.ts
>    getUserId(): string {
So i guess this just needs to check local storage for any existing (permanent) ID and only return a new one if none exists?

2023-06-26 21:47 UTC, marcin-mazurek commented on apps/browser-extension-wallet/.env.example
> +USE_DATA_CHECK=false
Not related to analytics. Just added those entries at this file got out of sync with .env.defaults

2023-06-26 21:58 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx
> +  analyticsDisabled?: boolean;
I renamed from `feature` to `tracking` as `feature` was a bit vague to me. Additionally I flipped it from `enabled` to `disabled` since it's primary use case is to disable tracking in unit/integration tests, so I think it makes the usage cleaner.

2023-06-26 21:59 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx
> +    () => tracker || new AnalyticsTracker(currentChain, analyticsDisabled, optedInForEnhancedAnalytics),
If we happen to ever change the feature toggle in the runtime, I guess we should be OK to just re-create the whole AnalyticsTracker instance, it's not a standard use case anyway.

2023-06-26 22:00 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +      this.postHogClient.sendPageNavigationEvent(path)
I know there is some repetition and I could have gone for an array of clients instead, like @vetalcore did in the original PR. However, we're likely to deprecate Matomo pretty soon, and this form makes it easier to clean up code afterwards, and it extremely unlikely we will have more than 2 tools for tracking.

2023-06-26 22:02 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/matomo/MatomoClient.ts
>    getUserId(): string {
See my newest commits :)

2023-06-27 09:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/matomo/MatomoClient.ts
> +/* eslint-disable camelcase */
Just moved plus made some changes. Unfortunately GitHub lost track of this file and thinks it's a new one.

2023-06-27 09:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/matomo/config.ts
> +import { Wallet } from '@lace/cardano';
Just moved plus made some changes. Unfortunately GitHub lost track of this file and thinks it's a new one.

2023-06-27 09:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/matomo/index.ts
> +export { MatomoClient } from './MatomoClient';
Just moved plus made some changes. Unfortunately GitHub lost track of this file and thinks it's a new one.

2023-06-28 12:04 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +const userIdService = new UserIdService();
Can we separate class declaration from exposing it via `exposeApi`?

2023-06-28 12:12 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +  setSiteId(chain: Wallet.Cardano.ChainId): void {
```suggestion
  setChain(chain: Wallet.Cardano.ChainId): void {
```

2023-06-28 12:15 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +    posthog.capture('pageview', {
missing `distinct_id`

2023-06-28 12:16 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +      url: window.location.href
set `distinct_id` here?

2023-06-28 12:20 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +      this.postHogClient.sendPageNavigationEvent(path)
```suggestion
      this.matomoClient?.sendPageNavigationEvent(path),
      this.postHogClient?.sendPageNavigationEvent(path)
```

2023-06-28 12:20 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +    await this.userIdService.extendLifespan();
```suggestion
    await this.matomoClient?.sendEvent(props);
    await this.userIdService?.extendLifespan();
```

2023-06-28 12:20 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +    await this.userIdService.extendLifespan();
```suggestion
    await this.postHogClient?.sendEvent(action, properties);
    await this.userIdService.extendLifespan();
```

2023-06-28 12:20 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +    await this.matomoClient.sendEvent(props);
```suggestion
    await this.matomoClient?.sendEvent(props);
```

2023-06-28 12:21 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +    this.postHogClient.setChain(chain);
```suggestion
    this.matomoClient?.setChain(chain);
    this.postHogClient?.setChain(chain);
```

2023-07-06 19:39 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  #userId?: string;
I've noticed that here we are using `#` notation for private fields, while [here](https://github.com/input-output-hk/lace/pull/173/files#diff-449b8131af0bfe2bfd46b14c995f88a7c02893fbb0e303c707d7b5496955d62fR18) we are using `private`. is there a reason why not to follow the same declaration type?

2023-07-10 11:50 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  #userId?: string;
I'm also in favor of `private` but that's mostly stylistic reasons

2023-07-11 21:51 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  #userId?: string;
Good point, we should be consistent. Resolved in https://github.com/input-output-hk/lace/pull/173/commits/f3546c489925c327bac913c4f754bb0d78f4ef65

2023-07-11 21:52 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +const userIdService = new UserIdService();
@DominikGuzei @jplorek-atix do you think it's worth doing?

2023-07-12 09:22 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +const userIdService = new UserIdService();
@marcin-mazurek for unit testing it was not necessary but usually it's good practice not to create a singleton instance when loading a file

2023-07-17 18:56 UTC, jplorek-atix requested changes

2023-07-17 18:56 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.test.ts
> +jest.mock('../posthog/PostHogClient');
```suggestion
jest.mock('../postHog/PostHogClient');
```

2023-07-17 19:36 UTC, jplorek-atix approved these changes

2023-07-18 15:00 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/__tests__/WalletSetup.test.tsx
> +    await waitFor(() => expect(userIdServiceMock.extendLifespan).toHaveBeenCalledTimes(2)); // this is being called twice, once per tracker, is this correct?
In this case it's correct, when clicking the next button twice, we're logging two events:

![image](https://github.com/input-output-hk/lace/assets/6684554/fe1e0357-90b5-4201-ac9c-e1d922d66656)

2023-07-19 10:54 UTC, milagi approved these changes

2023-08-11 13:15 UTC, merged