Feat/Staking view portfolio bar
input-output-hk/lace pull request #176
Opened 2023-06-26 13:25 UTC by mrcnk

# Checklist

- [x]
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

- Add portfolio bar to represent current state of portfolio building.

## Screenshots

<img width="1181" alt="image" src="https://github.com/input-output-hk/lace/assets/16132011/1afe3414-a34b-4600-8bca-38cdcfd45822">
<img width="1164" alt="image" src="https://github.com/input-output-hk/lace/assets/16132011/157530af-d1d4-46c8-b955-ee29be204a25">

2023-06-26 14:57 UTC, przemyslaw-wlodek requested changes

2023-06-26 14:57 UTC, przemyslaw-wlodek commented on packages/core/src/ui/assets/icons/arrow-right.component.svg
Isn't it used by `SocialLink` component?

2023-06-26 14:57 UTC, przemyslaw-wlodek commented on packages/staking/src/features/staking/PortfolioBar.tsx
> +        <Button.Primary label="Next" icon={<img src={String(ArrowRightIcon)} alt="Go next" />} />
SVGs with `.component.svg` should be automatically converted to React components using SVGO. Please let's fix svgo config if needed (we have it in place). If that's too complex for this PR then let's create a ticket for that.

2023-06-26 14:57 UTC, przemyslaw-wlodek commented on packages/staking/src/features/staking/PortfolioBar.css.ts
> +  position: '$sticky',
Shouldn't we use `fixed` here? I don't see the benefit of using `sticky`

2023-06-27 16:52 UTC, mrcnk commented on packages/core/src/ui/assets/icons/arrow-right.component.svg
<img width="645" alt="image" src="https://github.com/input-output-hk/lace/assets/16132011/ffdb68c8-809f-41d2-aff5-c01adedb9d77">

validated and the social links are fine

2023-06-28 08:02 UTC, closed without merging