[LW-6606] Add handle capabilities to address book
input-output-hk/lace pull request #182
Opened 2023-06-27 07:50 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR attempts to tackle another issue in addition to adding ADA Handle to the address book:

Floating placeholders in the Search-type input fields to ensure consistency throughout all Form based components.

## Testing

- Add an address.
- Edit an address.
- Try to edit an address that's already registered.
- Try to edit an address into one that's incorrect.
- Regression on previously supported address type.
- Add an address in the midst of a send.
- Choose a registered address during a send.

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-27 09:01 UTC, greatertomi requested changes

2023-06-27 09:01 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.module.scss
> +    color: red;
```suggestion
    color: var(--text-color-red);
```

2023-06-27 09:01 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +      // TODO: add nicer way to handle errors, console messega removed by QA request
Is this something you can work on now in this PR?

2023-06-27 09:04 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.tsx
> +    []
are we missing a dependency?

2023-06-27 09:24 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.tsx
> +  const onClose = () => {
```
const onClose = () => {
  if (!popupView) {
    setCurrentStepConfig(stepsConfiguration[AddressDetailsSteps.DETAILS]);
  }
  onCancelClick();
};
```

2023-06-27 09:28 UTC, shawnbusuttil commented on apps/browser-extension-wallet/package.json
> +    "antd": "^4.24.10",
`Form` in antd can use `useWatch` to monitor changes to its input values.

2023-06-27 09:29 UTC, shawnbusuttil commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +      // TODO: add nicer way to handle errors, console messega removed by QA request
This is not something in scope. It wasn't introduced as part of the task.

2023-06-27 09:29 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.tsx
> +    []
Yes handleResolver will be placed in these occurrences.

2023-06-27 09:39 UTC, VanessaPC commented on packages/common/src/ui/components/Search/Search.module.scss
> +      background-color: transparent !important;
is there no workaround the `!important`.

2023-06-27 09:39 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +      // TODO: add nicer way to handle errors, console messega removed by QA request
Can you create a ticket for this and add it to the comment?

2023-06-27 09:40 UTC, VanessaPC commented on packages/core/package.json
> +    "antd": "^4.24.10",
This seems a significant upgrade.. will it not cause issues on another component?

2023-06-27 09:42 UTC, VanessaPC commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
> +      console.log('error while submitting new address', error);
'Error .. ' just caps

2023-06-27 09:59 UTC, shawnbusuttil commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +      // TODO: add nicer way to handle errors, console messega removed by QA request
Will include it in the ticket mentioned.

2023-06-27 10:03 UTC, shawnbusuttil commented on packages/core/package.json
> +    "antd": "^4.24.10",
I've done my share of exploratory checks. Hopefully there will not be anymore picked up on QA. The only change I've seen (caught by compilation) is the `InputRef` types referenced in the commit history.

2023-06-27 10:05 UTC, VanessaPC commented on packages/core/package.json
> +    "antd": "^4.24.10",
ah cool, thanks

2023-06-27 10:10 UTC, VanessaPC commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +  const nameValue = Form.useWatch('name', form);
we use `name` and `address` in various places for forms, it could be a const.

2023-06-27 10:10 UTC, VanessaPC commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +      // TODO: add nicer way to handle errors, console messega removed by QA request
do we need a ticket?

2023-06-27 10:17 UTC, shawnbusuttil commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +      // TODO: add nicer way to handle errors, console messega removed by QA request
https://github.com/input-output-hk/lace/pull/182#discussion_r1243479713

2023-06-27 10:24 UTC, shawnbusuttil commented on packages/common/src/ui/components/Search/Search.module.scss
> +      background-color: transparent !important;
https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fimg1.joyreactor.com%2Fpics%2Fpost%2Fbycicle-red-green-gif-3882579.gif&f=1&nofb=1&ipt=b57092afe0852975b3d84b05ead6541e8b97852633c5eb9603128ce4ac521e54&ipo=images

2023-06-27 10:29 UTC, greatertomi requested changes

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
>  export type FormKeys = keyof valuesPropType;
Delete `ValidationOptionsProps` and `FormKeys` since they are no longer used.

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
> +  const debouncedValidate = debounce(validate, 1000);
Maybe you should create a constant for 1000 and remove all the eslint disable `no-magic-numbers` from this file

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
> +  const handleValidator = useMemo(() => getValidatorWithResolver(validations.handle), [getValidatorWithResolver]);
Maybe replace `getValidatorWithResolver ` with `validations.handle`

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
Can we explore possible types for all the types `any` in this file? If it has to be `any`, maybe using a global eslint disable on `@typescript-eslint/no-explicit-any` will be a good idea

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
> +/* eslint-disable no-magic-numbers */
This can be removed.

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +type ResolveAddressValidatorFn = (_rule: any, value: string, handleResolver: any) => Promise<void>;
These also exist in `packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx`. Can we just share them?

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +}: EditAddressFormFooterProps) => {
Return type of `ReactElement` might help appease eslint here

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
>  };
These also exist in `packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx`. Can they be shared?

2023-06-27 10:29 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +  const handleValidator = useMemo(() => getValidatorWithResolver(validations.handle), [getValidatorWithResolver]);
This `getValidatorWithResolver` dependency should maybe be replaced with `validations.handle`

2023-06-27 10:40 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +    []
https://github.com/input-output-hk/lace/pull/182#discussion_r1243426789

2023-06-27 11:37 UTC, VanessaPC commented on packages/common/src/ui/components/Search/Search.module.scss
> +      background-color: transparent !important;
Lol. Fair enough.

2023-06-27 15:38 UTC, lucas-barros requested changes

2023-06-27 17:03 UTC, shawnbusuttil commented on package.json
> +    "debounce-promise": "^3.1.2",
Ah yeah good catch.

2023-06-27 21:31 UTC, greatertomi requested changes

2023-06-27 21:31 UTC, greatertomi commented on packages/core/src/ui/components/EditAddressForm/EditAddressForm.tsx
> +  validations: any;
```suggestion
  validations: ValidationOptionsProps<FormKeys>;
```

2023-06-27 21:34 UTC, greatertomi commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
>  export type FormKeys = keyof valuesPropType;
On second thought I think those two types can be used [here](https://github.com/input-output-hk/lace/pull/182#discussion_r1244382144). No need to delete.

2023-06-28 08:13 UTC, VanessaPC commented on packages/common/src/ui/components/Search/Search.tsx
> +      data-testid={dataTestId || 'search'}
Why do we need an 'or'? shouldn't `dataTestId` be enough?

2023-06-28 15:13 UTC, shawnbusuttil commented on packages/common/src/ui/components/Search/Search.tsx
> +      data-testid={dataTestId || 'search'}
It's an optional prop. It defaults unless you pass it something customized (which can happen if we have it tested in specific contexts).

2023-06-29 21:02 UTC, VanessaPC commented
Really good work, I see a small issue with the address book, but the rest seems to be addressed.  
Also, I restarted my wallet, and i went to my address book but it had no address saved.. is that an expected behaviour?

https://github.com/input-output-hk/lace/assets/4052063/41517e46-af84-4022-891f-01dd05b07cb9

2023-06-30 09:13 UTC, shawnbusuttil commented
> Really good work, I see a small issue with the address book, but the rest seems to be addressed. Also, after I restart my wallet, and I go to my address book but it had no address saved.. is that expected behaviour? I suspect we want to keep the saved addresses.
> 
>  Screen.Recording.2023-06-29.at.21.37.51.mov

I couldn't reproduce what was in the video. When you say reset do you mean rebuild or complete reset?

2023-06-30 11:39 UTC, greatertomi requested changes

2023-06-30 11:39 UTC, greatertomi commented on packages/core/src/ui/components/AddressFormBrowserView/AddressForm.tsx
>  export type ValidationOptionsProps<T extends string> = Record<T, (key: string) => string>;
```suggestion
```

This is not used.

2023-07-03 01:10 UTC, lucas-barros requested changes

2023-07-03 10:01 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/__tests__/AddressForm.test.tsx
> +xdescribe('Testing AddressForm component', () => {
Fixed on 3f1502a

2023-07-03 10:02 UTC, greatertomi commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +    const handleString = value.toString();
Fixed on 3f1502a

2023-07-03 11:57 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/__tests__/AddressForm.test.tsx
> +xdescribe('Testing AddressForm component', () => {
@greatertomi there are still `xdescribe` in the tests.

https://github.com/input-output-hk/lace/blob/feature/lw-6606-ada-handle-address-book/packages/core/src/ui/components/EditAddressForm/__tests__/EditAddressForm.test.tsx#L30

https://github.com/input-output-hk/lace/blob/feature/lw-6606-ada-handle-address-book/apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/__tests__/AddressForm.test.tsx#L17

https://github.com/input-output-hk/lace/blob/feature/lw-6606-ada-handle-address-book/packages/core/src/ui/components/AddressFormBrowserView/__tests__/AddressFrom.test.tsx#L8

2023-07-03 12:07 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/__tests__/AddressForm.test.tsx
> +xdescribe('Testing AddressForm component', () => {
Shawn reverted this because "We are not supposed to rename test describes unless we make them work". @shawnbusuttil when are you going to work on the tests?

Don't you think working on them in this PR would be better?

2023-07-03 12:10 UTC, greatertomi reviewed
LGTM except for `xdescribe` on important tests which indicates that those tests are skipped. We need to decide either to fix them in this PR or to create an improvement task for this

Great work @shawnbusuttil 🚀

2023-07-03 12:12 UTC, greatertomi approved these changes

2023-07-03 13:52 UTC, lucas-barros requested changes

2023-07-03 14:56 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/__tests__/AddressForm.test.tsx
> +xdescribe('Testing AddressForm component', () => {
2/3 of the tests have been resolved. One is still giving me trouble which is `EditAddressForm.test.tsx`. So looking into that during the day.

2023-07-03 14:56 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.tsx
> +                isNewAddress={popupView && !initialValues?.id}
This was likely a mistake during refactor. It has now been resolved.

2023-07-03 15:50 UTC, lucas-barros requested changes

2023-07-04 00:15 UTC, lucas-barros requested changes

2023-07-04 00:15 UTC, lucas-barros commented on packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.tsx
> +      label={translations.recipientAddress}
Any reason for replacing `inputPlaceholder` with `label`? This [assert](https://github.com/input-output-hk/lace/blob/2d6dadfa761e6c3bdf78f3d3bb50bf695ef487fb/packages/e2e-tests/src/assert/drawerSendExtendedAssert.ts#L25) is failling as it is expecting a placeholder.

2023-07-04 08:39 UTC, shawnbusuttil commented on packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.tsx
> +      label={translations.recipientAddress}
Yes. So since you can't put a floating placeholder (label) on a textarea in antd - which was the previous underlying input, we needed to switch to something that provides this functionality - which is our custom Input that does this already. Label acts as a placeholder but also floats to the top and shrinks to make room for input values when the value of said input != "".

2023-07-04 11:04 UTC, shawnbusuttil commented on packages/core/src/ui/components/DestinationAddressInput/DestinationAddressInput.tsx
> +      label={translations.recipientAddress}
@lucas-barros I think if we change it to this, it would still be sufficient.

`await webTester.waitUntilSeeElementContainingText(await t('core.destinationAddressInput.recipientAddress'));`

2023-07-04 13:20 UTC, wklos-iohk requested changes

2023-07-04 13:20 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/drawerSendExtendedAssert.ts
> +    await webTester.waitUntilSeeElementContainingText(await t('core.destinationAddressInput.recipientAddress'));
If you're using this approach the test will go through the whole DOM and look for text passed as a parameter instead of focusing on exact address input field.

2023-07-04 13:28 UTC, shawnbusuttil commented on packages/e2e-tests/src/assert/drawerSendExtendedAssert.ts
> +    await webTester.waitUntilSeeElementContainingText(await t('core.destinationAddressInput.recipientAddress'));
We have one input though with this identifying copy though. No?

2023-07-04 14:18 UTC, lucas-barros commented on packages/e2e-tests/src/assert/drawerSendExtendedAssert.ts
> +    await webTester.waitUntilSeeElementContainingText(await t('core.destinationAddressInput.recipientAddress'));
I think the point is `waitUntilSeeElementContainingText` takes much longer. I'll check for the label test id.

2023-07-04 15:05 UTC, lucas-barros commented on packages/e2e-tests/src/assert/drawerSendExtendedAssert.ts
> +    await webTester.waitUntilSeeElementContainingText(await t('core.destinationAddressInput.recipientAddress'));
Updated: https://github.com/input-output-hk/lace/pull/182/commits/d0d7797931ce6a8feff7cc4446a30f61ad5f195f

2023-07-04 17:12 UTC, gabriela-ponce approved these changes

2023-07-04 18:20 UTC, lucas-barros requested changes

2023-07-04 18:20 UTC, lucas-barros commented on packages/core/src/ui/utils/address-form.ts
> +export type ResolveAddressValidatorFn = (_rule: Rule, value: string, handleResolver: any) => Promise<void>;
Replace `any` with `HandleProvider`.

2023-07-05 07:39 UTC, VanessaPC commented
@shawnbusuttil can you please rebase master on top? I believe the black end of the tooltip is introduced with the `atnd` version change, and if so, we probably want to add a fix to the branch before we merge.

2023-07-05 08:26 UTC, VanessaPC requested changes
Review the tooltip in order to not add a regression.

2023-07-05 14:11 UTC, lucas-barros requested changes

2023-07-05 14:11 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +  const handleResolver = useHandleResolver();
I see this block repeated 3 times. It would be good to make a hook for it, like `useAddressFormValidations`.

2023-07-05 15:47 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +  const handleResolver = useHandleResolver();
We will review that in the refactor task. Let's not stretch the scope any more.

2023-07-05 19:07 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +  const handleResolver = useHandleResolver();
Ok.

2023-07-05 19:07 UTC, lucas-barros approved these changes

2023-07-06 07:44 UTC, VanessaPC approved these changes

2023-07-06 07:44 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +  const handleResolver = useHandleResolver();
The refactor task should be created.

2023-07-06 08:17 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/drawerSendExtendedAssert.ts
> +    await webTester.waitUntilSeeElementContainingText(await t('core.destinationAddressInput.recipientAddress'));
Looks fine now!

2023-07-06 09:48 UTC, dmitrii-gaico approved these changes

2023-07-06 10:01 UTC, wklos-iohk approved these changes

2023-07-06 12:52 UTC, dmitrii-gaico approved these changes

2023-07-06 12:52 UTC, gabriela-ponce approved these changes

2023-07-06 13:49 UTC, merged