refactor/LW-7148 - PortfolioBalance refactor
input-output-hk/lace pull request #186
Opened 2023-06-27 20:05 UTC by lgobbi-atix

# Checklist

- [x] JIRA - LW-7148
- [x] Proper tests implemented

---

## Proposed solution

Continuation of: https://github.com/input-output-hk/lace/pull/170

Refactor `PortfolioBalance.tsx` component to make it easier to understand and modify

- Separate into smaller components
- Rename variables and remove unnecessary ones
- Improve unit testing

## Testing

Portfolio balance in Tokens screen, balances in asset details and show/hide balance toggle should work the same way as before in both browser and popup views:

![image](https://github.com/input-output-hk/lace/assets/57540576/f14366ca-2070-464f-8926-9165fb03aef6)
![image](https://github.com/input-output-hk/lace/assets/57540576/215a5803-0395-4606-bf2e-487ce1bd35ae)

2023-07-05 07:20 UTC, vetalcore requested changes

2023-07-05 07:20 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +    font-weight: 700;
```suggestion
    @includes text-subHeading-bold;
```

2023-07-05 07:20 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +      font-weight: 700;
```suggestion
     @includes text-pageHeading;
```

2023-07-05 07:20 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +      font-weight: 700;
```suggestion
      @includes text-display;
```

2023-07-05 12:27 UTC, lgobbi-atix commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +      font-weight: 700;
Done a60294309a47e1e8decc88ac2d9ae02171e57873

2023-07-05 12:28 UTC, lgobbi-atix commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +      font-weight: 700;
Done a60294309a47e1e8decc88ac2d9ae02171e57873

2023-07-05 12:28 UTC, lgobbi-atix commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +    font-weight: 700;
Done a60294309a47e1e8decc88ac2d9ae02171e57873

2023-07-07 10:31 UTC, mchappell requested changes

2023-07-07 10:31 UTC, mchappell commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceLabel/PortfolioBalanceLabel.module.scss
> +    font-size: size_unit(2);
`@include text-bodyLarge-semi-bold`

2023-07-07 10:31 UTC, mchappell commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +      font-size: var(--pageHeading);
`@include text-pageHeading`

2023-07-07 10:31 UTC, mchappell commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +    font-size: var(--pageHeading);
`@include text-pageHeading`

2023-07-07 10:31 UTC, mchappell commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +      font-size: var(--body);
`@include text-body-bold`

2023-07-07 13:22 UTC, lgobbi-atix commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.module.scss
> +      font-size: var(--body);
Done https://github.com/input-output-hk/lace/pull/186/commits/e3904016ab2fdcf4176fff2e8dc773319ae98e6f

2023-07-18 13:13 UTC, mchappell requested changes

2023-07-18 13:13 UTC, mchappell commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.tsx
> +          className={classnames({
please extract + memoise this like you've already done with `subtitleStyles`

2023-07-18 13:13 UTC, mchappell commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalanceValue/PortfolioBalanceValue.tsx
> +              [styles.codeTextLarge]: textSize === 'large',
please extract + memoise this like you've already done with `subtitleStyles`

2023-07-18 13:55 UTC, mchappell approved these changes

2023-07-18 18:23 UTC, vetalcore approved these changes

2023-07-19 11:28 UTC, ljagiela approved these changes

2023-07-19 12:53 UTC, merged