feat(staking,common,extension): add details drawer in staking
input-output-hk/lace pull request #193
Opened 2023-06-28 13:46 UTC by przemyslaw-wlodek

# Checklist

- [x] JIRA - LW-6678
- [x] Screenshots added.

---

## Proposed solution

This PR reintroduces the pool details drawer in the staking package and necessary refactoring for common components e.g. Banner.

## Testing

1. Open Staking
2. Go to the **Browse Pools** tab
3. Click on a Pool
4. Observe the Stake Pool Details Drawer being displayed

## Screenshots
<img width="1512" alt="image" src="https://github.com/input-output-hk/lace/assets/17825044/988571e1-2a73-4f5e-a69f-2fa639d6f280">

2023-06-28 13:53 UTC, mrcnk approved these changes
Looks good 👍

2023-06-29 11:22 UTC, danielmain requested changes

2023-06-29 11:22 UTC, danielmain commented on packages/staking/src/features/outside-handles-provider/OutsideHandlesProvider.tsx
> +      backgroundServiceAPIContextSetWalletPassword,
Create a variable with all this properties and pass it in the array in line 37 with `...object` with that you will save a ton of lines of code :)

2023-06-29 11:22 UTC, danielmain commented on packages/staking/src/features/overview/Overview.tsx
> +            onStakePoolSelect={() => console.info('onStakePoolSelect')}
I think console does not belong in production code

2023-06-29 12:24 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/features/delegation/components/DelegationContainer.tsx
> -  useRedirection,
Hey :) Thank you for taking the time to review this PR.

This code is mostly like lift and shift. That was our squad agreement for now, as it requires a lot of work on our side to untangle the providers/hooks and everything that was used there in the browser extension. Most of the stuff will be addressed in future PRs (like console.logs and any other TODO/placeholders).

There are no new formatting or linting issues in this PR - we have a common configuration and it's checked in the pipeline.

I really hope that we can refactor this in the incoming sprint and PI. :)

2023-06-29 13:20 UTC, danielmain approved these changes

2023-06-29 13:24 UTC, ManusMcCole approved these changes
Looks good @mrcnk 👍

2023-06-29 13:26 UTC, merged