feat(core): adds warning icon to wallet address item
input-output-hk/lace pull request #202
Opened 2023-06-30 12:19 UTC by VanessaPC

# Checklist

- [x] JIRA - [LW-7304](https://input-output.atlassian.net/browse/LW-7304)
- [x] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Add an optional proptype to `WalletAddress` so that we can display a warning when an address has changed. 

## Testing

Running the tests. 
Also, by going to the address book and setting the prop `isWarningVisible` to true/false. 

## Screenshots

<img width="1432" alt="Screenshot 2023-06-30 at 13 11 31" src="https://github.com/input-output-hk/lace/assets/4052063/9d3967d6-e538-4162-9a94-9775c956d65e">
<img width="358" alt="Screenshot 2023-06-30 at 13 11 36" src="https://github.com/input-output-hk/lace/assets/4052063/30475aa4-c86f-4166-89ce-f7a0ef41d8c6">
<img width="1406" alt="Screenshot 2023-06-30 at 13 11 52" src="https://github.com/input-output-hk/lace/assets/4052063/dbae6a94-0c40-48f3-b3fb-ffb5810090ce">
<img width="351" alt="Screenshot 2023-06-30 at 13 11 43" src="https://github.com/input-output-hk/lace/assets/4052063/9dd202dc-1542-4978-a918-5b332ed03816">

2023-06-30 12:29 UTC, rhyslbw requested changes

2023-06-30 12:29 UTC, rhyslbw commented on packages/core/src/ui/lib/translations/en.json
> +      "addressHandleTooltip": "The link address for this handle has changed, click to update or delete."
```suggestion
      "addressHandleTooltip": "The address linked to this handle has changed, click to update or delete."
```

The designs actually say

> The linked address for this handle has changed, click to update or delete

... but the refinement above reads better IMO

2023-06-30 12:30 UTC, greatertomi requested changes
Can this black spot be changed to white?

<img width="245" alt="Screenshot 2023-06-30 at 13 40 00" src="https://github.com/input-output-hk/lace/assets/4052063/189429e5-53da-4d0f-ad4e-279bd41c2713">

2023-06-30 12:40 UTC, VanessaPC commented
> Can this black spot be changed to white?
> 
> <img alt="Screenshot 2023-06-30 at 13 26 12" width="712" src="https://user-images.githubusercontent.com/48496855/250088522-5c5806a8-f1a6-4c32-9ab0-9cb58a8d4622.png">
For context: 

I  looked into this because it bothers me too. However, this is how the tooltip is used everywhere else in the app. I worked with antd in the past.. and changing their components is very tedious and it's not 
reliable. I'd say there is probably a way and it likely deserves its own ticket. This is an example of it being used in the dropdown. 

<img width="245" alt="Screenshot 2023-06-30 at 13 40 00" src="https://github.com/input-output-hk/lace/assets/4052063/a8106916-0dad-4bfd-ae29-91a9faf9fb66">

2023-06-30 12:42 UTC, VanessaPC commented on packages/core/src/ui/lib/translations/en.json
> +      "addressHandleTooltip": "The link address for this handle has changed, click to update or delete."
Mine read differently but I had a error. I'll update to that last one. 
![Screenshot 2023-06-30 at 13 42 07](https://github.com/input-output-hk/lace/assets/4052063/1443ebcd-98ed-44a0-b261-e69305f1c16e)

2023-06-30 12:59 UTC, VanessaPC commented on packages/core/src/ui/lib/translations/en.json
> +      "addressHandleTooltip": "The link address for this handle has changed, click to update or delete."
f9ec8021799111d183a13d8d82ba958c2fac4eed should solve this

2023-06-30 13:22 UTC, greatertomi approved these changes

2023-06-30 14:48 UTC, lucas-barros approved these changes

2023-06-30 16:03 UTC, shawnbusuttil approved these changes

2023-07-03 09:38 UTC, VanessaPC commented
Updating to reflect new design changes: 
![Screenshot 2023-07-03 at 10 02 08](https://github.com/input-output-hk/lace/assets/4052063/69a25478-6828-47c1-8fc1-c0184deb09a5)
![Screenshot 2023-07-03 at 10 02 15](https://github.com/input-output-hk/lace/assets/4052063/a991e8d6-f0c0-4142-8923-ae991f5e4bbe)
![Screenshot 2023-07-03 at 10 28 29](https://github.com/input-output-hk/lace/assets/4052063/af026f3b-5424-4119-a408-9ffd03c3849b)
![Screenshot 2023-07-03 at 10 28 36](https://github.com/input-output-hk/lace/assets/4052063/76f830c5-1f0b-4edd-9bbf-054363a120af)

2023-07-04 08:41 UTC, rhyslbw approved these changes
Great work @VanessaPC 🚀

2023-07-04 13:19 UTC, merged