test(extension): e2e - add test to create folder with too long name
input-output-hk/lace pull request #230
Opened 2023-07-05 21:15 UTC by miorsufianiohk

2023-07-06 09:55 UTC, ljagiela approved these changes

2023-07-06 09:55 UTC, ljagiela commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +      : expect(await NftCreateFolderPage.folderNameInput.inputError.isExisting()).to.be.false);
please replace with:
      : await NftCreateFolderPage.folderNameInput.inputError.waitForDisplayed({ reverse: true });
      
      isExisting is checking only once in a given moment, waitForDisplayed will be checking for longer period of time (waiting)

2023-07-06 09:55 UTC, ljagiela commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +          (await t('browserView.nfts.folderDrawer.nameForm.inputError')).replace('{{length}}', maxLength.toString())
I don't think it's necessary to parametrise input lenght, but since you already implemented it let's leave it.

2023-07-06 09:55 UTC, ljagiela commented on packages/e2e-tests/src/elements/NFTs/nftCreateFolderPage.ts
> +    await clearInputFieldValue(await this.folderNameInput.input);
please remove clear, it's not necessary since input field is empty by default
If you need to clear it in your scenario please create a dedicated step for it.

(await this.folderNameInput.input) -> brackets are redundant here

2023-07-06 22:08 UTC, miorsufianiohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +      : expect(await NftCreateFolderPage.folderNameInput.inputError.isExisting()).to.be.false);
Changed

2023-07-06 22:09 UTC, miorsufianiohk commented on packages/e2e-tests/src/elements/NFTs/nftCreateFolderPage.ts
> +    await clearInputFieldValue(await this.folderNameInput.input);
Changed

2023-07-07 08:45 UTC, wklos-iohk requested changes

2023-07-07 08:45 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +          (await t('browserView.nfts.folderDrawer.nameForm.inputError')).replace('{{length}}', maxLength.toString())
I'd suggest little adjustment here for the sake of readability:
```
  async assertSeeInputMaxLengthError(shouldBeDisplayed: boolean, maxLength: number) {
    await NftCreateFolderPage.folderNameInput.inputError.waitForDisplayed({ reverse: !shouldBeDisplayed });
    if (shouldBeDisplayed) {
      const expectedErrorMessage = (await t('browserView.nfts.folderDrawer.nameForm.inputError')).replace(
        '{{length}}',
        maxLength.toString()
      );
      expect(await NftCreateFolderPage.folderNameInput.inputError.getText()).to.equal(expectedErrorMessage);
    }
  }
  ```

2023-07-07 09:37 UTC, miorsufianiohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +          (await t('browserView.nfts.folderDrawer.nameForm.inputError')).replace('{{length}}', maxLength.toString())
Thanks @wklos-iohk. I have updated the code as suggested 👍

2023-07-07 09:42 UTC, wklos-iohk approved these changes

2023-07-07 12:31 UTC, merged