feat: persists HandleResolution to addressBookContext
input-output-hk/lace pull request #235
Opened 2023-07-07 13:38 UTC by VanessaPC

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/browse/LW-7379) - 
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Adds `HandleResolution` to the `AddressBookContext` so that later on we can save and compare both values for a validation on the client side. 

## Testing

- Run the app make sure ADA Handle works without any regression.
- Address book renders 
- Profile renders and they both render the address and the handle. 

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-07-07 19:21 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +  !value.startsWith('$');
8ecce2a0cafb7e513925205c7014434508e60439 should address this

2023-07-08 13:30 UTC, lucas-barros requested changes

2023-07-08 13:30 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const hasHandleOwnerChanged = async (
I'm confused about the function name. I would expect `hasHandleOwnerChanged` to return a boolean, but it's returning handles.

2023-07-08 13:30 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +      handle: async (value: string) => await validateWalletHandle(value, undefined, handleResolver)
I would consider turning the arguments to an object.

2023-07-08 13:30 UTC, lucas-barros commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +export const isAddressAHandle = (value: Cardano.PaymentAddress | string): value is string =>
It seems these are not used anywhere.

2023-07-10 07:53 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const hasHandleOwnerChanged = async (
Well, it returns a validation and the handles when needed. 
It returns a boolean value based on whether the owner of the handle has changed, and the handles, because in the cases in which the owner has changed and we want to persist the new information we need the handle data. 
So, to me, it makes more sense to call it `hasHandleOwnerChanged` or something similar than `verifyHandles` because... verify handles isn't explicitly telling us what is proving, so when we are reading the code I'd rather know what is doing? 
Does this make sense? Also, are there other names you think could describe it better? or do you think it should be the previous one?

2023-07-10 07:57 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +export const isAddressAHandle = (value: Cardano.PaymentAddress | string): value is string =>
They aren't used here. That's right. I added this to be used in the PR of this ticket: LW-7128, where they are used, because even though they aren't applied here they still fell into context for me. But I don't mind removing them and adding them one PR later if you'd rather.

2023-07-10 08:52 UTC, greatertomi requested changes

2023-07-10 08:52 UTC, greatertomi commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +export const isAddressAHandle = (value: Cardano.PaymentAddress | string): value is string =>
Yes. I'll suggest removing them and re-adding them later when they are used. 

Also, I'll suggest you move this and `isAddressAPaymentAddress` to somewhere in the [utils](https://github.com/input-output-hk/lace/tree/cdefe01a7417a38f056fc0384c2c7507f073470a/apps/browser-extension-wallet/src/utils) folder. They fit better there than in the `lib/storage` folder.

2023-07-10 08:52 UTC, greatertomi commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +export const isAddressAPaymentAddress = (value: Cardano.PaymentAddress | string): value is Cardano.PaymentAddress =>
This is also not used. Same comment here applies

2023-07-10 09:05 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +export const isAddressAPaymentAddress = (value: Cardano.PaymentAddress | string): value is Cardano.PaymentAddress =>
8d5bb920bcda7e00ee165cd9ae5228769825b011 should address this.

2023-07-10 09:05 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +export const isAddressAHandle = (value: Cardano.PaymentAddress | string): value is string =>
8d5bb920bcda7e00ee165cd9ae5228769825b011 should address this.

2023-07-10 09:55 UTC, greatertomi approved these changes

2023-07-10 10:58 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const hasHandleOwnerChanged = async (
> It returns a boolean value based on whether the owner of the handle has changed

I don't see this part. It seems the return is not related to whether the handle owner has changed or not, just if it's able to resolve the handle or not. Maybe I'm missing something.

2023-07-10 12:28 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const hasHandleOwnerChanged = async (
I think the set up in preparation for the following PR is what's causing the confusion. I reverted. 

4f942090a669a336799e6545ce9ae2ec2851b1c0 should resolve this.

2023-07-10 12:54 UTC, lucas-barros requested changes

2023-07-10 12:54 UTC, lucas-barros commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "handleConflict": "The is a conflict with the handle. We received this {{receivedAddress}} but expected {{actualAddress}}."
```suggestion
      "handleConflict": "There is a conflict with the handle. We received this {{receivedAddress}} but expected {{actualAddress}}."
```

2023-07-10 12:57 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "handleConflict": "The is a conflict with the handle. We received this {{receivedAddress}} but expected {{actualAddress}}."
0ae0937cbd1fd21ce4decb3202e22f50242eebcb should resolve this

2023-07-10 20:08 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +  !value.startsWith('$');
This was decided to revert and add on the next PR.

2023-07-10 20:09 UTC, VanessaPC commented
In the middle of the feedback loop my `main` branch and this branch stopped working likely because of cache issues, that's what triggered me merging main into the branch.

2023-07-11 09:37 UTC, rhyslbw requested changes

2023-07-11 09:37 UTC, rhyslbw commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.tsx
> +      handle: async (value: string) => await validateWalletHandle({ value, address: undefined, handleResolver })
```suggestion
      handle: async (value: string) => await validateWalletHandle({ value, handleResolver })
```
?

2023-07-11 09:37 UTC, rhyslbw commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +      handle: async (value: string) => await validateWalletHandle({ value, address: undefined, handleResolver })
```suggestion
      handle: async (value: string) => await validateWalletHandle({ value, handleResolver })
```

2023-07-11 10:04 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/storage/models/address-book.ts
> +  address: string | Cardano.PaymentAddress;
Currently this will be out of sync when the user enters a handle that comes, on the validation step, with a new resolved address. 
So they will be out of sync. Because until the user 'updates', the previous address will not match the new address from the handle. And this check will run on opening the book. 
`address: string` is used everywhere, not just in the address book, but all through transactions, in the form. So If I change it to make it match the type above, the db will change, the forms will change, and the transactions will as well. And this is a far bigger refactor.

2023-07-11 10:08 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
>    value: string,
I can't do this in this PR because I don't have the address saved to Provider, that work is in the next PR. In the one were I show the warning. Not because I don't have the address persisted which now I do, but simply because the logic isn't set up in the addressbook because it belongs on the other one.

2023-07-11 10:12 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  address: Cardano.PaymentAddress,
https://github.com/input-output-hk/lace/pull/235#discussion_r1256286598 
This is where I pass the address and do the check. 
And at this point throw the error if they conflict. Like we saw on the demo. 
At this point if the address  is undefined, which now it is, because we don't have the logic yet on the components for this... we simply avoid error and it behaves like before.

2023-07-11 12:29 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +      handle: async (value: string) => await validateWalletHandle({ value, address: undefined, handleResolver })
85ba81cb0a41d5d43cc05dca2f7b305125fb49c9 fixes this

2023-07-11 12:29 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.tsx
> +      handle: async (value: string) => await validateWalletHandle({ value, address: undefined, handleResolver })
85ba81cb0a41d5d43cc05dca2f7b305125fb49c9 fixes this

2023-07-11 12:53 UTC, rhyslbw approved these changes

2023-07-11 15:16 UTC, lucas-barros requested changes

2023-07-11 16:06 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const getHandleResolution = async ({
We would not be changing `validateWalletHandle` or `verifyHandle`. Just remove `getHandleResolution` and replace with `verifyHandle`.

2023-07-11 16:35 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +export const getHandleResolution = async ({
> It's the same as with a piece of code that gets repeated 3 times so far, but then.. it needs to change once more once I switch to where I need the work.
But if you remove the duplication now then you would only need to change it in one place later. 

The issue I see is if in the mean time someone touches that code it would be harder to refactor or may lead to conflicts. I don't see a benefit to resolve this in another PR, but I'm not enforcing anything so feel free to do as you think is best.

2023-07-11 18:42 UTC, lucas-barros approved these changes

2023-07-12 10:30 UTC, dmitrii-gaico approved these changes

2023-07-12 10:38 UTC, merged