test(extension): quick tests fix
input-output-hk/lace pull request #239
Opened 2023-07-10 08:42 UTC by oldGreg5

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-07-10 08:44 UTC, ljagiela approved these changes

2023-07-11 11:11 UTC, wklos-iohk requested changes

2023-07-11 11:11 UTC, wklos-iohk commented on packages/e2e-tests/src/features/OnboardingCreateWallet.feature
> -    And I click "Got it" button on "DApp connector is now in Beta" modal
This modal overlaps main page, hence it may cause issues with verification.

2023-07-11 11:11 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingWalletCreationPageAssert.ts
> -    await WalletCreationPage.walletLoader.waitForDisplayed();
This assertion shouldn't be removed as it checks if spinner is displayed on the page during wallet creation.

There are actually two spinners: first one during wallet creation step, second one after clicking on 'Go to my wallet' button. First one works fine according to my observations, however second one takes longer to disappear. See https://github.com/input-output-hk/lace/blob/e56994a496cbb9c6a0cfb384fcc39392bcfc1385/packages/e2e-tests/src/steps/onboardingSteps.ts#L542 we might increase the delay here.

2023-07-11 11:11 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/addressBookExtendedSteps.ts
> +    await browser.pause(50);
Please refrain from adding `pause` method and replace it with relevant `waitFor...` method (if needed)

2023-07-11 11:50 UTC, oldGreg5 commented on packages/e2e-tests/src/features/OnboardingCreateWallet.feature
> -    And I click "Got it" button on "DApp connector is now in Beta" modal
This works fine, test was flaky because it takes longer for wallet to load now. 'I see LW homepage' step waits longer for Lace to load, so making it run first fixes that.

2023-07-13 06:36 UTC, wklos-iohk approved these changes

2023-07-13 07:22 UTC, merged