test(extension): e2e - add tests for create folder cancellation popup
input-output-hk/lace pull request #245
Opened 2023-07-10 21:46 UTC by miorsufianiohk

2023-07-11 07:26 UTC, wklos-iohk requested changes

2023-07-11 07:26 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +    await nftCreateFolderAssert.assertSeeCreateFolderPageDrawerNavigation(shouldSee === 'see', mode);
This step says that it is verifying visibility of entire "Create NFT folder" drawer, however assertion name indicates that it only verifies drawer navigation. Using  `assertSeeCreateFolderPage(...)` might be better.

2023-07-11 07:26 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +  async assertSeeCreateFolderPageDrawerNavigation(shouldSee: boolean, mode: 'extended' | 'popup') {
I'd suggest reverting this method to its previous state, as it was focused only on drawer navigation visibility, hence it shouldn't check drawer body.

2023-07-11 07:26 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +  async assertSeeYoullHaveToStartAgainModal(shouldBeDisplayed: boolean) {
It could be simplified by performing container visibility verification to the top of method body:
`await YoullHaveToStartAgainModal.container.waitForDisplayed({ reverse: !shouldBeDisplayed });` and then removing redundant code from L83 and L104

2023-07-11 21:55 UTC, miorsufianiohk commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "youllHaveToStartAgainModal": {
Changed. Thank you 👍

2023-07-11 21:56 UTC, miorsufianiohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +  async assertSeeCreateFolderPageDrawerNavigation(shouldSee: boolean, mode: 'extended' | 'popup') {
Reverted. Thank you 👍

2023-07-11 21:56 UTC, miorsufianiohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +  async assertSeeYoullHaveToStartAgainModal(shouldBeDisplayed: boolean) {
Simplified. Thank you 👍

2023-07-11 21:56 UTC, miorsufianiohk commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +    await nftCreateFolderAssert.assertSeeCreateFolderPageDrawerNavigation(shouldSee === 'see', mode);
Changed. Thank you 👍

2023-07-12 06:46 UTC, wklos-iohk requested changes

2023-07-12 06:46 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +  async assertSeeYoullHaveToStartAgainModal(shouldBeDisplayed: boolean) {
Maybe I wasn't clear enough in above comment, but I wanted that one particular line of code to be moved to the top and keep the rest of code, I didn't expect purging entire method body.

Long story short, in this method in first line of its body we need to check if the modal is/is not displayed, and then if it should be displayed we need to verify modal content.

2023-07-12 10:52 UTC, miorsufianiohk commented on packages/e2e-tests/src/assert/nftCreateFolderAssert.ts
> +  async assertSeeYoullHaveToStartAgainModal(shouldBeDisplayed: boolean) {
fixed. thank you :)

2023-07-12 10:56 UTC, wklos-iohk approved these changes

2023-07-12 11:33 UTC, merged