Feat/LW-7128 add handle update screen
input-output-hk/lace pull request #262
Opened 2023-07-13 09:43 UTC by VanessaPC

# Checklist

- [x] LW-7128
- [x] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Adds the flow for the warning of the handles that have changed ownership.
Adds a delay on retrying because when a user has several handles, and renavigates, koralabs will fail because of the limit on the number of requests to the API. 
Adds the comparison in between stake keys instead of addresses. 

## Testing
 - Try to add a handle in the popup and browser 
 - Try to add addresses in both 
 - Send a minted handle to another address 
 - Click in the warning and either delete or update the contact 
 - Check the warning disappears when the handles have been minted although if you have more than 5 handles, you might need to wait 5 seconds to see the warning. 

## Screenshots

<img width="1534" alt="Screenshot 2023-07-13 at 10 28 43" src="https://github.com/input-output-hk/lace/assets/4052063/83b8d253-7d4c-44d5-8126-012a64c769c1">
<img width="1548" alt="Screenshot 2023-07-13 at 10 28 55" src="https://github.com/input-output-hk/lace/assets/4052063/98f623da-2f1d-40a6-9eb8-4725e9d88578">
<img width="1551" alt="Screenshot 2023-07-13 at 10 29 06" src="https://github.com/input-output-hk/lace/assets/4052063/0b393252-8f1d-4250-8656-68d3e429b022">
<img width="1566" alt="Screenshot 2023-07-13 at 10 29 22" src="https://github.com/input-output-hk/lace/assets/4052063/e19607a1-80f0-432b-a09d-16f9c7691eeb">

2023-07-13 14:29 UTC, lucas-barros requested changes

2023-07-13 14:29 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +    const intervalId = setInterval(validateAddresses, fiveSecondDelay);
We had a similar discussion [here](https://github.com/input-output-hk/cardano-js-sdk/pull/786#discussion_r1244782095).

If you think this would take to long to implement here. I would suggest to create a separate task for it. Even better might be to have this on the sdk and just import it from there.

2023-07-13 14:29 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +        // eslint-disable-next-line sonarjs/no-identical-functions
I would extract onDelete to avoid duplication.

2023-07-13 14:29 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +        onConfirm={() => onHandleConfirm()}
```suggestion
        onCancel={onHandleCancel}
        onConfirm={onHandleConfirm}
```

2023-07-13 14:29 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +    const stakeKeyFromAddress = Cardano.Address.fromString(address).asBase().getStakingCredential();
We may first want to check if the address has change to check for the stake key change, to avoid calculating the stake credential everytime.

2023-07-13 15:39 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
> +  const getdescriptiontranslations = isSmall ? (
```suggestion
  const descriptionTranslations = isSmall ? (
```

2023-07-13 15:41 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +  useEffect(() => {
I would avoid specifying the amount in the name.

2023-07-13 15:44 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +  handle?: HandleResolution;
In these data models, handle is usually a subtype of address. What is this used for?

2023-07-13 15:51 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
>    isSmall?: boolean;
If `isSmall` refers to `isPopup` then lets rename it to that to keep consistency.

2023-07-13 17:20 UTC, shawnbusuttil requested changes
Is the 'handle' property being used?

2023-07-13 17:22 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +  onUpdateContact?: (event?: React.MouseEvent<HTMLButtonElement>) => unknown;
```suggestion
  onUpdateAddress?: (event?: React.MouseEvent<HTMLButtonElement>) => unknown;
```

2023-07-13 17:24 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +  beforeEllipsis?: number;
When I read this, I think it's a boolean. Is there anything else we could name them? What are they describing?

2023-07-13 19:59 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +  beforeEllipsis?: number;
The number of characters left on either side of an ellipsis. 
`beforeEllipsis` and `afterEllipsis` are properties of the component `Ellipsis` and for consistency and ability to spread the properties, I'd prefer to leave them matching the spec. This is also the most common way used across the code.

2023-07-13 20:00 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +  onUpdateContact?: (event?: React.MouseEvent<HTMLButtonElement>) => unknown;
That's deleted.

2023-07-13 20:00 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressForm/AddressForm.tsx
> +  handle?: HandleResolution;
No, this was a leftover.

2023-07-13 20:00 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  } catch (error) {
No, was mostly for debugging.

2023-07-13 20:05 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +    const intervalId = setInterval(validateAddresses, fiveSecondDelay);
Thank you, I wasn't aware of this thread. 
After looking at it, I think it should stay in the SDK as you suggest for other's to reuse, and also to make it easier to group code if discontinuing in and deleting. 
ticket: LW-7498

2023-07-13 20:17 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
> +        {action === ACTIONS.DELETE
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this

2023-07-13 20:22 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +        onCancelClick={() => {
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this 
`onUpdate` wasn't used, and `onCancel` is more specific in this case to the operation the user is taking.

2023-07-13 20:22 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +        // eslint-disable-next-line sonarjs/no-identical-functions
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this

2023-07-13 20:22 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +        onConfirm={() => onHandleConfirm()}
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this

2023-07-13 20:23 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +    const stakeKeyFromAddress = Cardano.Address.fromString(address).asBase().getStakingCredential();
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this

2023-07-13 20:23 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
> +  const getdescriptiontranslations = isSmall ? (
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this

2023-07-13 20:23 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
>    isSmall?: boolean;
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this

2023-07-13 20:23 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +  shouldUseEllipsisBeforeAndAfter?: boolean;
ccd65e797819aac7afb5e4381c26c432d72ea248 should address this

2023-07-13 20:26 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +  useEffect(() => {
@lucas-barros  I thought so too, but this task should handle it better  (LW-7486: Address book refactor to avoid two files, since they are mostly the same). 
@shawnbusuttil  3f6f0c4788137812b56f63fad5022bd59ba30aa1 should address this

2023-07-14 09:54 UTC, greatertomi requested changes

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
> +      visible={visible}
Since `visible` is deprecated. Use `open`

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +  useEffect(() => {
I would suggest extracting that to a custom hook in this ticket to reduce the work to be done in LW-7486

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +          });
Can we use async/await here?

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +}
This is the exact replica of [this](https://github.com/input-output-hk/lace/blob/5a538ccd0914ce2f7dafb1436c556f0ec017a4ce/apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressDetailDrawer.module.scss#L12-L45). Can we use imports or find ways to reuse the styles?

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +import Check from '../../../../assets/icons/check-success.component.svg';
```suggestion
import Copy from '@assets/icons/copy.component.svg';
import Check from '@assets/icons/check-success.component.svg';
```

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +    // eslint-disable-next-line unicorn/no-null
Maybe we should just switch this off in the `eslintrc.js` file. `// eslint-disable-next-line unicorn/no-null` is used for over 45 times in the repo. 😅

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +            onArrowIconClick={popupView ? onCancelClick : undefined}
```suggestion
            onCloseIconClick={!popupView && onCancelClick}
            onArrowIconClick={popupView && onCancelClick}
```

2023-07-14 09:54 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +        visible={!!selectedId}
`visible` is deprecated

2023-07-14 10:12 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +  useEffect(() => {
I'm actually addressing it here. https://input-output.atlassian.net/browse/LW-7233

2023-07-14 10:21 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +}
That's not a good idea. While that is the same now, both drawers are used for different purposes and their content is very different. If we were going to do a change to one of them in the main body of the drawer in the future, that would affect this drawer as well. The current pattern is to have a style sheet per `ts` `tsx` file, so I don't expect anyone to come and realise that they are breaking the styles of other different screens and scenarios. 
Besides, reusing global styles is good, reusing common styles is fine, but unless we were putting some .common style guide for both.. and I don't think that is consistent.

2023-07-14 10:31 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +}
Agreed.

2023-07-14 10:46 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +        visible={!!selectedId}
49241b3eeb4faade180fa9135ec2fc3c2b0fc7d8 addressed here

2023-07-14 10:46 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +            onArrowIconClick={popupView ? onCancelClick : undefined}
49241b3eeb4faade180fa9135ec2fc3c2b0fc7d8 addressed here

2023-07-14 10:46 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +import Check from '../../../../assets/icons/check-success.component.svg';
49241b3eeb4faade180fa9135ec2fc3c2b0fc7d8 addressed here

2023-07-14 10:46 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +          });
49241b3eeb4faade180fa9135ec2fc3c2b0fc7d8 addressed here

2023-07-14 10:46 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
> +      visible={visible}
49241b3eeb4faade180fa9135ec2fc3c2b0fc7d8 addressed here

2023-07-14 10:49 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +    // eslint-disable-next-line unicorn/no-null
Depending on the resolution will create a ticket. https://input-output-rnd.slack.com/archives/C01S2DD5B0D/p1689331693881559

2023-07-14 11:37 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +  useEffect(() => {
@shawnbusuttil @greatertomi @lucas-barros are we ok with doing the refactor in that PR?

2023-07-14 11:38 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +    const intervalId = setInterval(validateAddresses, fiveSecondDelay);
https://input-output-rnd.slack.com/archives/C056738NG6N/p1689319145887149 it won't be a problem much longer I don't think.

2023-07-14 12:37 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +  useEffect(() => {
991b38965b5a25feafe463f0708f422d0875cfda should address this

2023-07-14 12:48 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> +  useEffect(() => {
addressed here <- b89c98da31fa01e9b41f22c9b6cdb511d110ca53

2023-07-14 13:48 UTC, lucas-barros requested changes

2023-07-14 13:48 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
> +      visible={visible}
It seems this change was reverted on the last [commit](https://github.com/input-output-hk/lace/pull/262/commits/b89c98da31fa01e9b41f22c9b6cdb511d110ca53).

2023-07-14 13:48 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +  addressList: unknown[],
Should it be `AddressBookSchema[]`?

2023-07-14 13:48 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +  handleResolver: KoraLabsHandleProvider
```suggestion
  handleResolver: HandleProvider
```

2023-07-14 13:48 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +      addressList?.map(async (item: AddressBookSchema) => {
https://github.com/input-output-hk/lace/commit/49241b3eeb4faade180fa9135ec2fc3c2b0fc7d8#diff-ceb92477cb424ec095c0480bef592cc231f310ae6155b4d0c8c457819443c92bR101

2023-07-14 13:48 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
5000 seems like a lot, maybe 100 will already be enough?

2023-07-14 14:04 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +import Check from '../../../../assets/icons/check-success.component.svg';
You are right, I didn't update here. I reverted it because the new property `open` doesn't work.

2023-07-14 14:13 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +            <Timeline>
Try this for the white background.

```suggestion
            <Timeline className={styles.sideTimeline}>
```

Add this to the CSS file
```
.sideTimeline {
      margin: size_unit(7) 0 size_unit(7) size_unit(7.75);
      :global {
        .ant-timeline-item {
          height: 130px;
        }
        .ant-timeline-item-content {
          @include text-bodySmall-medium;
          color: var(--text-color-primary);
          margin-left: 17px;
        }
        .ant-timeline-item-head {
          width: size_unit(2.5);
          height: size_unit(2.5);
          background: var(--bg-color-container);
        }
        .ant-timeline-item-tail {
          left: 0;
          border-left: 2px solid var(--light-mode-light-grey-plus, var(--dark-mode-mid-grey));
        }
      }
    }
```

2023-07-14 14:17 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
I actually think that 100 seems too many network requests. I'd be checking it then.. like 10 times a second? I don't think that's efficient. I can try 2 seconds.. but for a component that won't have such an amount of traffic, 5 seemed not bad.

2023-07-14 14:19 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +            <Timeline>
<img width="346" alt="Screenshot 2023-07-14 at 15 18 58" src="https://github.com/input-output-hk/lace/assets/4052063/4ffbf40f-0d43-4593-af4f-df5016beac15">

2023-07-14 14:21 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +            <Timeline>
b550f34579c8d4ede3e04728de44ad2e23664cce

2023-07-14 14:21 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +  handleResolver: KoraLabsHandleProvider
b550f34579c8d4ede3e04728de44ad2e23664cce

2023-07-14 14:21 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +  addressList: unknown[],
b550f34579c8d4ede3e04728de44ad2e23664cce

2023-07-14 14:40 UTC, greatertomi requested changes

2023-07-14 14:40 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
```suggestion
    background-color: var(--light-mode-light-grey-plus, var(--dark-mode-mid-grey));
```

2023-07-14 14:40 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +         line-height: size_unit(3);
```suggestion
         @include text-bodySmall-semi-bold
```

2023-07-14 14:40 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background: var(--light-mode-light-grey-plus,--dark-mode-dark-grey-plus);
```suggestion
    background: var(--light-mode-light-grey-plus, var(--dark-mode-dark-grey-plus));
```

2023-07-14 14:40 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    line-height: size_unit(3);
```suggestion
    @include text-body-bold
```

2023-07-14 14:54 UTC, lucas-barros requested changes

2023-07-14 14:54 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +.body {
It seems this is not used.

2023-07-14 14:54 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +      addressList?.map(async (item: AddressBookSchema) => {
The async keyword was left over or it was an unintentional revert.

2023-07-14 14:54 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/validators/__tests__/address-book.test.ts
> +    test.only('getAddressToSave returns the modified address with handleResolution if the address is a valid handle', async () => {
```suggestion
    test('getAddressToSave returns the modified address with handleResolution if the address is a valid handle', async () => {
```

2023-07-14 14:54 UTC, lucas-barros commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: hasHandleOwnerChangedArgs): Promise<string | void> => {
```suggestion
}: hasHandleOwnerChangedArgs): Promise<void> => {
```

2023-07-14 15:08 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
But thinking of this example of 10 request in a second, that would mean the user has at least 10 handle contacts. In this case the last contact would only resolve 18 seconds after the first one. That is noticeable and the user will have enough time to copy the handle without being alerted the handle possible has changed owners. If we are using the delay with no feedback to the user, it should be the minimium delay possible in my opinion. I guessed 100ms but it could be even less.

2023-07-14 15:13 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
What's this for?

2023-07-17 07:06 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
Also @greatertomi  where are the black designs? all these styles are actually from another pages, where they use the same components ... is the rest of the app broken? or is this broken now?

2023-07-17 07:09 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
Yea, and for a person with a slower/poor connection, this also will be noticeable. The normal is to put interval and others, to second not to fractions of. 
This also happens in a page in which we are now complaining about an interval to reload the handleResolutioin data .. for which we have poor set up from Koralabs which could easily be improved when Koralabs isn't used. 
Also, this is happening in a page, when .. one of the things none seems to care is the fact that as soon as we go in we are making a minimum of 30 requests for the details so this is only adding on top. 
IMO... sure the UI would be marginally faster, only if ... the user has a good connections. When Preprod was activing up last week, my address book was just loading.
@rhyslbw  choose an outcome.

2023-07-17 07:10 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressActionsModal.tsx
> +      visible={visible}
Yes, and it will stay reversed simply because `open` doesn't work.

2023-07-17 08:55 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
There is this darker shade in the dot.

<img width="690" alt="Screenshot 2023-07-17 at 09 50 46" src="https://github.com/input-output-hk/lace/assets/48496855/6f259f40-65db-48b8-80d7-8b98f8c71b54">

This suggested change makes the dot more uniform to this.

<img width="261" alt="Screenshot 2023-07-17 at 09 49 16" src="https://github.com/input-output-hk/lace/assets/48496855/d53235cd-4597-4e8b-8acf-8a7075f5a184">

2023-07-17 09:01 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
Yes, it's darker in the center, and lighter in the white UI. But not uniform with the rest... which is the change you were suggesting...

2023-07-17 09:05 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
Exactly. Just to make it uniform. 🙂

2023-07-17 09:05 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
@rhyslbw  do we follow the figma file or do we change it?

2023-07-17 11:25 UTC, lucas-barros requested changes

2023-07-17 11:25 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +.body {
There is no usage of `.body`, `.name`, `.extended`, `.addressWrapper`, `.address `classes within `AddressChangeDetailDrawer`

2023-07-17 11:25 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +          }).then(() => updateAddressStatus(item.address, { isValid: true }));
Async/await is mixed with `promise.then`.

2023-07-17 11:25 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressBook/AddressBook.tsx
> +// eslint-disable-next-line sonarjs/cognitive-complexity
This is no longer needed.

2023-07-17 11:25 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressBook/AddressBook.tsx
> +          // eslint-disable-next-line sonarjs/no-identical-functions
https://github.com/input-output-hk/lace/pull/262#discussion_r1262614601

2023-07-17 11:44 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +.body {
<img width="1601" alt="Screenshot 2023-07-17 at 12 44 01" src="https://github.com/input-output-hk/lace/assets/4052063/6b62ce2b-54fa-40e9-b678-591562919c58">

2023-07-17 11:51 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +.body {
I was referencing that these classes .body, .name, .extended, .addressWrapper, .address are not used. The mixins are, so the import is valid. The issue is the unused classes.

2023-07-17 11:51 UTC, rhyslbw commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
We don't need a perfect solution at the moment since the underlying issue here is lack of batching, which is not the case with our own solution. Does the logic presented here result in a 5 second delay in between each handle resolution?

2023-07-17 11:56 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
No, we map over all the addresses and request handle ownership validation. Then 2 seconds later we re-request validation. So they are "batched" in that we request all handle validation in one go and then check again a few seconds later. This was just to avoid the "too many requests" error coming from KoraLabs.

2023-07-17 12:04 UTC, lucas-barros commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
Ok, so my comments were for the case that the interval was between each single handle resolution. If the whole address book is resolved in one go, there should be failed requests (error 429) if there are more then 6 or 7 handle contacts. That was the experience I had with resolving the wallets own handles.

2023-07-17 12:20 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
https://input-output-rnd.slack.com/archives/C059G92SYH1/p1689596306313229?thread_ts=1689241418.213169&cid=C059G92SYH1

2023-07-17 13:54 UTC, shawnbusuttil approved these changes

2023-07-17 14:24 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.module.scss
> +    background-color: var(--bg-color-body, var(--bg-color-body));
update made: https://input-output-rnd.slack.com/archives/C056738NG6N/p1689602871790599?thread_ts=1689340457.134369&cid=C056738NG6N

2023-07-18 17:29 UTC, rhyslbw requested changes

2023-07-18 17:29 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: hasHandleOwnerChangedArgs): Promise<void> => {
```suggestion
}: hasHandleOwnerChangedArgs): Promise<boolean> => {
```
Semantically I'd expect this response type based on the naming. Alternatively: `ensureHandleOwnerHasntChanged`

2023-07-18 17:29 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  if (address && address !== handles.cardanoAddress) {
```suggestion
  if (address !== handles.cardanoAddress) {
```

2023-07-18 17:29 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  const handles = response[0];
```suggestion
  const newHandleResolution = response[0];
```

2023-07-18 17:29 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  value: string;
```suggestion
  handleResolution: HandleResolution;
```
Then you can omit `address`

2023-07-18 18:05 UTC, gabriela-ponce commented
@VanessaPC here are a few issues on the latest build:
 
- Open the side drawer for a transferred handle -- Press "ESC" --> **[Some information is hidden on the drawer](https://drive.google.com/file/d/1cobJHlG1S-wq6y_iz8c6DgekqJJM-NvL/view?usp=drive_link).**

- Open the side drawer for a transferred handle -- Click "Copy" and move the cursor away --> **[The button changes from "Copied" to "Copy" quickly](https://drive.google.com/file/d/1SBS8WBT7QF9AJu_LeOC63bwLdcZrxzae/view?usp=drive_link),** maybe a delay is needed? Also, for similar actions on other features,[ a notification is displayed.
](https://drive.google.com/file/d/1sLGv19aCW5gi142_g_7hEqEp-yGej8vP/view?usp=drive_link)
- Open the side drawer for a transferred handle -- Delete the contact -- Click on "Add address" --> **[The side drawer displays the information about the deleted contact, instead of the "add address" form.](https://drive.google.com/file/d/1XxE9v5cCToGxx-RizOrsK7WrGkyO90Qq/view?usp=drive_link)**

2023-07-19 07:10 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  value: string;
I'd favour not passing all the information when we don't need it. But ok.

2023-07-19 08:57 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  const handles = response[0];
a814ce1d9877e036403c6119d5d7f6c050ff2862 should address this

2023-07-19 08:57 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +  if (address && address !== handles.cardanoAddress) {
a814ce1d9877e036403c6119d5d7f6c050ff2862 should address this

2023-07-19 08:57 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: hasHandleOwnerChangedArgs): Promise<void> => {
a814ce1d9877e036403c6119d5d7f6c050ff2862 should address this

2023-07-19 08:57 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useUpdateAddressStatus.ts
> +    const interval = 5000;
a814ce1d9877e036403c6119d5d7f6c050ff2862 should address this

2023-07-19 09:55 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: hasHandleOwnerChangedArgs): Promise<void> => {
I can see the return type was changed but the implementation remains the same, despite there being [a test](https://github.com/input-output-hk/lace/commit/a814ce1d9877e036403c6119d5d7f6c050ff2862#diff-dc73c6511012a53f13d8c3682f5b60e0674eac58c8d3c55814658224b77ae06cR290) that describes a different outcome :thinking:

2023-07-19 10:12 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: hasHandleOwnerChangedArgs): Promise<void> => {
yea, fixed here [0328590](https://github.com/input-output-hk/lace/pull/262/commits/0328590351b6757109c1b7f0707169349e290109)

2023-07-19 11:07 UTC, rhyslbw commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: hasHandleOwnerChangedArgs): Promise<void> => {
Is there a test to check it returns `true`?

2023-07-19 11:36 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: hasHandleOwnerChangedArgs): Promise<void> => {
That's fixed here: a463d6844a1e9ae2f2c485be84e1908808f249bd

2023-07-19 11:53 UTC, rhyslbw approved these changes
Great work @VanessaPC :rocket:

2023-07-19 17:24 UTC, gabriela-ponce requested changes
@VanessaPC all the fixes look good, nice job.
I found a few issues that didn't reproduce on the previous build:

- Click on any contact - Press "ESC" --> **[The form to add a contact is displayed](https://drive.google.com/file/d/1d_eTdVsVMQPaVVo0If9Dunl_4AxSx2rq/view?usp=drive_link)** (this used to close the drawer instead).

- Only on popup view, open the side drawer for a transferred handle -- **Accept** the changes or **delete** the contact (reproduces in both cases)--> **[Address book is updated, but a blank screen is displayed.](https://drive.google.com/file/d/1wIdd7RsituDEjE8Zb9nCUJsJgROXEepW/view?usp=drive_link)**

2023-07-20 08:05 UTC, VanessaPC commented
> @VanessaPC all the fixes look good, nice job. I found a few issues that didn't reproduce on the previous build:
> 
> * Click on any contact - Press "ESC" --> **[The form to add a contact is displayed](https://drive.google.com/file/d/1d_eTdVsVMQPaVVo0If9Dunl_4AxSx2rq/view?usp=drive_link)** (this used to close the drawer instead).
> * Only on popup view, open the side drawer for a transferred handle -- **Accept** the changes or **delete** the contact (reproduces in both cases)--> **[Address book is updated, but a blank screen is displayed.](https://drive.google.com/file/d/1wIdd7RsituDEjE8Zb9nCUJsJgROXEepW/view?usp=drive_link)**

Thanks for your feedback. 
The first one, I believe.. the bug should appear in main? at least the code causing the bug is in main. Both are or should be fixed.

2023-07-20 16:57 UTC, gabriela-ponce approved these changes

2023-07-20 19:05 UTC, merged