[WIP] test(extension): add test for analytics tracker
input-output-hk/lace pull request #268
Opened 2023-07-13 21:21 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-07-14 13:41 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsAnalyticsTracker.test.tsx
> +const mockGetBackgroundStorage = jest.fn();
We can simplify the mocked user service id like this:
```
/* eslint-disable import/imports-first */
const userIdServiceMock: UserIdService = {
  getId: jest.fn(),
  extendLifespan: jest.fn(),
  makeTemporary: jest.fn(),
  makePersistent: jest.fn(),
  clearId: jest.fn()
};
jest.mock('../getUserIdService', () => ({
  getUserIdService: jest.fn().mockReturnValue(userIdServiceMock)
}));
```

2023-07-17 11:27 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsAnalyticsTracker.test.tsx
> +    mockMakeTemporary.mockReset();
The issue here is that `setOptedInForEnhancedAnalytics` is call on render in [AnalyticsProvider](https://github.com/input-output-hk/lace/pull/173/files#diff-11122defbe2e4610453f2b1e69f8cc29bd1fac44937b06374634d5b57b81cecaR49), so when the assertions are run, these mocks have already been called once, and what I want to test here is, which function is called when the buttons are clicked, not prior calls

2023-07-17 13:24 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsAnalyticsTracker.test.tsx
> +const mockGetBackgroundStorage = jest.fn();
Does it make sense to move this to somewhere else? and make it available for other tests, right now we have three places using this mock. 

[AnalyticsTracker.test.ts](https://github.com/input-output-hk/lace/pull/268/files#diff-c01626bf9f58fdb84a14a38a408152a9b90dc8a5de5a0fabd772a7b69230fcf3)
[WalletSetup.test.tsx](https://github.com/input-output-hk/lace/pull/268/files#diff-3d881f0bdd5b18b6e53ee0fbc083279deb4830cd1a1dbdeaa92b9301998d02f4)
and this file

2023-07-17 14:39 UTC, marcin-mazurek requested changes
LGTM - left a few minor suggestions :)

2023-07-17 14:39 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsAnalyticsTracker.test.tsx
> +const mockGetBackgroundStorage = jest.fn();
Let's do it :)

2023-07-17 14:39 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/__tests__/WalletSetup.test.tsx
> +  test('should call makePersisten when clicking agree', async () => {
```suggestion
  test('should call makePersistent when clicking agree', async () => {
```

2023-07-17 14:39 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/__tests__/WalletSetup.test.tsx
> +const mockMakePersisten = jest.fn();
```suggestion
const mockMakePersistent = jest.fn();
```

2023-07-17 14:39 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/settings/components/__tests__/SettingsAnalyticsTracker.test.tsx
> +  test('should call makePersisten when enabling analytics', async () => {
```suggestion
  test('should call makePersistent when enabling analytics', async () => {
```

2023-07-17 17:52 UTC, marcin-mazurek approved these changes

2023-07-17 17:52 UTC, merged