test(extension): e2e - add test for create folder select nfts page co…
input-output-hk/lace pull request #281
Opened 2023-07-17 14:31 UTC by miorsufianiohk

2023-07-18 09:19 UTC, ljagiela requested changes

2023-07-18 09:19 UTC, ljagiela commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +      await $(this.DRAWER_CONTENT).$$(this.NFT_IMAGE)[i].waitForClickable();
I think it can be simplified by:
```     
await this.nfts[i].$(this.NFT_IMAGE).waitForClickable();
await this.nfts[i].$(this.NFT_IMAGE).click();
```
in such case you can remove `DRAWER_CONTENT`

2023-07-18 09:19 UTC, ljagiela commented on packages/e2e-tests/src/assert/nftSelectNftsAssert.ts
> +    await NftSelectNftsPage.clearButton.waitForDisplayed();
can you replace `waitForDisplayed` with `waitForClickable`? The latter one seems to be safer for buttons

2023-07-18 09:19 UTC, ljagiela commented on packages/e2e-tests/src/features/NFTsFoldersExtended.feature
> +    When I select 5 NFTs
Can you add a step `I do not see "Clear" button next to NFTs counter` before `"I select..."`

2023-07-18 09:19 UTC, ljagiela commented on packages/e2e-tests/src/features/NFTsFoldersExtended.feature
> +    Given I navigate to "Select NFTs" page in extended mode
Same here, if possible please add step `"I do not see counter..."` before `"I select..."`
I think we missed this validation in test case definition and it makes sense here.

2023-07-18 10:19 UTC, wklos-iohk requested changes

2023-07-18 10:19 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/nftSelectNftsAssert.ts
> +    expect(await NftSelectNftsPage.counterNumber.getText()).to.equal(counter.toString());
Please use `String(counter)` instead of `counter.toString()`

2023-07-18 10:19 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +  get nftItemSelectedCheckmark() {
This one seems to be unused

2023-07-18 10:19 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +  get counterNumber() {
How about using counter defined in L19 ?

2023-07-18 10:19 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +      await $(this.DRAWER_CONTENT).$$(this.NFT_IMAGE)[i].waitForClickable();
How about 
```
      await this.nfts[i].waitForClickable();
      await this.nfts[i].click();
```
?

2023-07-19 10:11 UTC, ljagiela approved these changes

2023-07-19 10:21 UTC, miorsufianiohk commented on packages/e2e-tests/src/assert/nftSelectNftsAssert.ts
> +    expect(await NftSelectNftsPage.counterNumber.getText()).to.equal(counter.toString());
Done 👍

2023-07-19 10:21 UTC, miorsufianiohk commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +  get nftItemSelectedCheckmark() {
Removed

2023-07-19 10:22 UTC, miorsufianiohk commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +  private COUNTER_NUMBER = '[data-testid="assets-counter"] p';
Removed

2023-07-19 10:29 UTC, miorsufianiohk commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +  get counterNumber() {
changed 👍

2023-07-19 10:29 UTC, miorsufianiohk commented on packages/e2e-tests/src/elements/NFTs/nftSelectNftsPage.ts
> +      await $(this.DRAWER_CONTENT).$$(this.NFT_IMAGE)[i].waitForClickable();
done

2023-07-19 11:28 UTC, wklos-iohk approved these changes

2023-07-19 12:03 UTC, merged