Feat/LW-7542,LW-7610,LW-7637
input-output-hk/lace pull request #302
Opened 2023-07-21 10:37 UTC by mrcnk

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

-  Add drawer closing for multi-delegation add and remove
- Fix stake pool name ellipsis for staking overview card
- Disable remove stake pool button when there's just one stake pool in multi-delegation management

2023-07-21 11:24 UTC, szymonmaslowski requested changes

2023-07-21 11:24 UTC, szymonmaslowski commented on packages/staking/src/features/i18n/translations/en.ts
> +  'drawer.preferences.pickMorePools': 'Please pick more stake pools.',
```suggestion
  'drawer.preferences.noEmptyPreferences': 'At least one stake pool is required',
```

2023-07-21 11:26 UTC, szymonmaslowski approved these changes

2023-07-24 08:07 UTC, ManusMcCole approved these changes
Looks good @mrcnk

2023-07-24 08:13 UTC, merged