feat(extension): use public key hash as id for opted in users
input-output-hk/lace pull request #304
Opened 2023-07-21 18:32 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-7574](https://input-output.atlassian.net/browse/LW-7574)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR implements the hashed wallet public key as id for opted in users, to be able to keep tracking across browsers. For opted out users, the ID keeps being randomized

## Testing

- Start any of the setup flows and complete all the steps. 
- On the analytics step, agree to be tracked. 
- Go to post hog dashboard.
- For all steps before wallet creation you will see a random ID in post hog, after the wallet is created you will see an Alias event with a new ID. 
- Click on the ID and go to the events tab, you should see the previous event for the random ID, linked to this new ID

## Screenshots

2023-07-24 11:28 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +    this.userId = undefined;
If we not remove the user ID from memory, when the user opt out, we will keep sending events with the ID that has already been linked to the permanent user ID, since we are using the userId as alias when the user opt in

Would it be better to have field for alias ID or is it ok to keep using the userId field?

2023-07-31 16:12 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +    this.userId = undefined;
When the user opts out, for the duration of that session, same ID should be still used. When the session ends and another one starts, another ID must be used.

We can have separate fields for randomUserId and walletBasedUserId, it would improve readability

2023-08-01 11:08 UTC, marcin-mazurek requested changes

2023-08-01 11:08 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +      const hash = hashExtendedAccountPublicKey(keyAgentsByChain[chainName].keyAgentData.extendedAccountPublicKey);
Should we leave a comment indicating we're calling this function twice by design?

2023-08-01 11:08 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getHashId(chainName: Wallet.ChainName): Promise<string> {
How about:
```suggestion
  async getWalletBasedUserId(chainName: Wallet.ChainName): Promise<string> {
```

2023-08-01 11:08 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  private hashId?: string;
How about:
```suggestion
  private walletBasedUserId?: string;
```

2023-08-01 11:08 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getIsPersistentId(): Promise<boolean> {
How about just:
```suggestion
  async isPersistent(): Promise<boolean> {
```

2023-08-01 11:08 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +        }
Just checking - do we need to send both of them? I thought we could use the new ID under `distinct_id` property as soon as it's aliased with `posthog.alias()`.

In general - it would be nice if we could encapsulate this whole logic inside of UserIdService to decouple PostHogClient from user ID management

2023-08-02 11:30 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +      // At this point, the wallet has been created, so, we are able to link the temporary ID with the hash ID
yes, you are right, I removed this comment, but, I left the `sendAliasEvent` call here, because we are checking if the hash id exist before sending the alias event, so, in onboarding flow, is not going to be sent, it is only going to be sent if the status change from setting section

2023-08-04 09:50 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.test.ts
> +/* eslint-disable import/imports-first */
let's move this const below the imports to get rid of this ignore rule?

2023-08-04 09:54 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.test.ts
> +    it('should not run hashExtendedAccountPublicKey, should retrieve ID from memory', async () => {
small nitpick for test description: `'should not run hashExtendedAccountPublicKey but retrieve ID from memory'`

2023-08-04 09:58 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.test.ts
> +      const walletBasedId = await userIdService.getwalletBasedUserId(1);
hm, shouldn't we throw an exception in this case? Is there any valid use case where `keyAgentsByChain` is not defined?

2023-08-04 10:05 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getRandomizedUserId(): Promise<string> {
I'm not sure if `getwalletBasedUserId` and `getRandomizedUserId` should be public API interface? To me it seems like internal implementation detail and if we offer three different methods to get an ID it can easily be used in the wrong way? To me it seems like we should only expose `getUserId` and how that's created is internal logic of the class.

2023-08-04 11:20 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.test.ts
> +      const walletBasedId = await userIdService.getwalletBasedUserId(1);
in onboarding flow until we don't reach the last step `keyAgentsByChain` is not defined since the wallet has not been created yet

2023-08-04 11:28 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getRandomizedUserId(): Promise<string> {
@DominikGuzei I agree with you, I would probably leave `getRandomizedUserId` public for now since is used in Matomo and the functionality of wallet based ID is not applicable for there.

or maybe we can add some extra check in `getUserId` to find out if it was call from Matomo. What do you think?

2023-08-04 11:30 UTC, marcin-mazurek requested changes

2023-08-04 11:30 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.test.ts
> +/* eslint-disable import/imports-first */
+1

2023-08-04 11:30 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
>    private userId?: string;
```suggestion
  private randomizedUserId?: string;
```

2023-08-04 11:30 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +      return this.walletBasedUserId;
Could we explicitly return undefined instead (also in line 42)? 
```suggestion
      return undefined;
```

2023-08-04 12:54 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getRandomizedUserId(): Promise<string> {
Yeah, in this case, for now we should leave `getRandomizedUserId()` public. We can make it private when we get rid of Matomo.

2023-08-07 14:47 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +    await this.postHogClient?.sendAliasEvent();
@marcin-mazurek I ended up making this public, as I'm using it in [WalletSetupWizard.tsx](https://github.com/input-output-hk/lace/pull/304/files#diff-cdc8ed49ef37bc5910fcc1587654a09bcc942f30e675bbafabd28028da9ce683R247) when the user clicks `go to my wallet` button

2023-08-08 10:22 UTC, DominikGuzei approved these changes
LGTM 🚢  great work 🥇

2023-08-08 14:22 UTC, marcin-mazurek approved these changes
Well done 🚀 🚢 
Just one tiny suggestion to improve the logging message :)

2023-08-08 14:22 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +    console.debug('[ANALYTICS] Linking temporary ID with permanent user ID');
```suggestion
    console.debug('[ANALYTICS] Linking randomized ID with wallet-based ID');
```

2023-08-09 12:38 UTC, milagi approved these changes

2023-08-11 09:19 UTC, marcin-mazurek commented
@jplorek-atix can you resolve merge conflicts and merge? 🙏

2023-08-11 12:14 UTC, merged