feat(staking,ui): Preferences modal, bug fixes
input-output-hk/lace pull request #305
Opened 2023-07-24 12:57 UTC by szymonmaslowski

# Checklist

- [x] JIRA
   - https://input-output.atlassian.net/browse/LW-7544
   - https://input-output.atlassian.net/browse/LW-7638
   - https://input-output.atlassian.net/browse/LW-7660
   - https://input-output.atlassian.net/browse/LW-7661
   - https://input-output.atlassian.net/browse/LW-7662
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

# Staking
Scope described by linked tasks above.

# UI Toolkit
Improved the Subnavigation component by enabling it to support controlled mode.

2023-07-24 13:24 UTC, renanvalentin approved these changes
The changes on the UI package looks good!

2023-07-24 13:36 UTC, danielmain requested changes

2023-07-24 13:36 UTC, danielmain commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +  const footerHidden =
I would create a function called, shouldFooterBeDisplayed adding comments what conditions are checked. This "if" is very hard to understand. If no time for this, just a TODO with a Jira in our backlog with some comments

2023-07-24 19:27 UTC, szymonmaslowski commented on packages/staking/src/features/modals/StakingModal.tsx
> +      footer={null}
This way we disable the footer
<img width="733" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/acdc1fe0-cc6d-42bd-b5cb-d5aaaae013ea">

2023-07-24 20:31 UTC, szymonmaslowski commented on packages/staking/src/features/staking/StakingView.tsx
> +    // TODO: implement no funds modal
Done 👍

2023-07-25 09:40 UTC, danielmain approved these changes

2023-07-25 15:26 UTC, ManusMcCole commented
Hi @szymonmaslowski. Good job on rectifying all the issues on the cards. However this flow doesnt have any Next button so the user can succesfully complete the process to delegate to multiple pools. See [video](https://drive.google.com/file/d/18hcOha9fKHoUf2A1P4zNI-wC_8Sa5tYH/view?usp=sharing)

2023-07-26 22:04 UTC, szymonmaslowski commented
> Hi Szymon. I tested newest build and the Next button is visible and clickable but results in a state of constant loading that never resolves. This happens for all delegation. See [Video](https://drive.google.com/file/d/1LkUhoUf3S5VU0O6RKeiJGhTHmeZuqUxr/view?usp=sharing)

Hey Manus. I cannot view the video because of lack of permissions. However I assume you are talking about the next button on the confirmation drawer (the one with the list of selected pool and fee) being blocked and having the spinner visible. That is a known issue and it is present also in the old staking. Please try to switch the network to overcome that issue.

2023-07-27 08:29 UTC, ManusMcCole approved these changes

2023-07-27 11:55 UTC, merged