test(extension): e2e - add nfts to existing folder
input-output-hk/lace pull request #325
Opened 2023-07-26 22:58 UTC by miorsufianiohk

2023-07-27 13:32 UTC, ljagiela requested changes

2023-07-27 13:32 UTC, ljagiela commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  /^I click "([^"]*)" button on "(Name your folder|Select NFTs)" page$/,
I think that "([^"]*)" and ignored param can be removed?

2023-07-27 13:32 UTC, ljagiela commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +When(/^I open the NFT folder with name "([^"]*)"$/, async (folderName: string) => {
We already have step: `And I left click on the NFT folder with name "Sample NFT folder"`

2023-07-27 13:32 UTC, ljagiela commented on packages/e2e-tests/src/assert/nftAddNftToFolderAssert.ts
> +  async assertSeeNftAddNftToFolderPage() {
we already have `assertSeeFolderPage` in `NftCreateFolderAssert`, can it be used?

2023-07-27 16:15 UTC, miorsufianiohk commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  /^I click "([^"]*)" button on "(Name your folder|Select NFTs)" page$/,
I have this step which I'd like to make generic `When I click "Add selected NFTs" button on "Select NFTs" page`

2023-07-28 07:33 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  /^I click "([^"]*)" button on "(Name your folder|Select NFTs)" page$/,
I'd suggest not making steps to generic. In my view button names shouldn't be wrapped with 
```
"([^"]*)"
``` 
in step definitions as it can consume any kind of text, please use the approach with defined button names 
```
"(ButtonName1|ButtonName2|ButtonName3)"
```
and adequate button handling within function scope.

2023-07-28 10:16 UTC, miorsufianiohk commented on packages/e2e-tests/src/steps/nftFoldersSteps.ts
> +  /^I click "([^"]*)" button on "(Name your folder|Select NFTs)" page$/,
Thanks guys. As advised by Lukasz, I have added a separate step def to make the code less complicated 👍

2023-07-31 10:10 UTC, wklos-iohk requested changes

2023-07-31 10:10 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/NFTs/nftsFolderPage.ts
> +  private SELECTED_FOLDER_TITLE = '[data-testid="selected-folder-title"]';
The same selector as in L5

2023-07-31 10:10 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/NFTs/nftsFolderPage.ts
> +  private SELECTED_FOLDER_NFT_COUNTER = '[data-testid="selected-folder-nft-counter"]';
The same selector as in L6

2023-07-31 11:16 UTC, wklos-iohk approved these changes

2023-07-31 11:30 UTC, ljagiela approved these changes

2023-07-31 11:59 UTC, merged