test(staking): created multidelegationdelegatedfundsextended.feature …
input-output-hk/lace pull request #327
Opened 2023-07-27 08:56 UTC by ManusMcCole

…fixed test @LW-2642 for md

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-09-06 15:31 UTC, wklos-iohk requested changes

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/stakingSteps.ts
> +When(/^I verify I am on the (Overview|Browse pools) tab$/, async (type: 'Overview' | 'Browse pools') => {
I'd suggest renaming that step to better reflect the action it executes

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/stakingSteps.ts
> +When(
It could be simplified:
```
When(/^Stake pools switching modal (is|is not) displayed$/, async (status: 'is' | 'is not') => {
  await SwitchingStakePoolModal.title.waitForDisplayed({ timeout: 5000, reverse: status === 'is not' });
});
```
but I'd suggest to move modal verification into separate assertion and it would be nice to extend it a little bit with checking other modal elements, not only the title.

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/stakingSteps.ts
> +  await multidelegationStakePoolDetailsAssert.assertMultiDelegationSeeStakePoolRows;
Missing `()`

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/stakingSteps.ts
> +// eslint-disable-next-line no-unused-vars
Do we really need to disable ESLint rules in this step?

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/staking/MultiDelegationStakingInfoComponent.ts
> +import { LocatorStrategy } from '../../actor/webTester';
I'd strongly advise to NOT use deprecated code from WebElement class or WebTester class.

Please take a look at packages/e2e-tests/src/elements/staking/stakingPage.ts for inspiration on how it can be rewritten

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/staking/MultidelegationPage.ts
> +import MultidelegationPageAssert from '../../assert/multidelegationStakingPageAssert';
This change causes issues in L201 and L205

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/staking/stakingPage.ts
> +  async clickBrowsePoolsTab() {
Seems to be unused

2023-09-06 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/staking/stakingPage.ts
> +  async clickGotItButton() {
Seems to be unused

2023-09-07 05:27 UTC, wklos-iohk requested changes

2023-09-07 05:27 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/multidelegationStakingPageAssert.ts
> +    await expect(await StakePoolDetails.ownersTitle.getText()).to.equal('Owners (1)');
Please use translation key `drawer.details.owners` to get expected text value. Relevant updates made by @oldGreg5 should be already merged to main branch.

2023-09-07 05:27 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/multidelegationStakingPageAssert.ts
> +import { StakePool } from '../data/expectedStakePoolsData';
Some of the code used in this class seems to be duplicated e.g. L23-51 and L65-93, L168-172 and L226-230 and few more. Please clean it up.

2023-09-07 05:27 UTC, wklos-iohk commented on packages/e2e-tests/src/features/MultidelegationDelegatedFundsExtended.feature
> +    Then An "staking.confirmation.title" text is displayed
I'd refrain from using `/(An|No) "([^"]*)" text is displayed/` step as it goes through the whole DOM, hence it is slow.
You can replace it with a relevant step that verifies if proper page/drawer is displayed or add a new one that uses POM.

2023-09-12 06:19 UTC, oldGreg5 commented on packages/e2e-tests/src/features/MultiDelegationExtended.feature
> +    Given Wallet is synced
Add here step 'And I disable showing Multidelegation beta banner' and remove all steps 'And I confirm multidelegation beta modal'

2023-09-12 07:09 UTC, oldGreg5 requested changes

2023-09-12 07:09 UTC, oldGreg5 commented on packages/e2e-tests/src/steps/stakingSteps.ts
>  import { Then, When } from '@cucumber/cucumber';
Please do not modify legacy staking files, move what's needed to 'multidelegationSteps' file. We need to leave legacy as is at least until we are ready to remove it. Currently we still use legacy for HW wallets.

2023-09-12 07:09 UTC, oldGreg5 commented on packages/e2e-tests/src/assert/multidelegationStakingPageAssert.ts
> +import { StakePool } from '../data/expectedStakePoolsData';
Please move this to already used file 'multidelegationPageAssert'.

2023-09-12 07:09 UTC, oldGreg5 commented on packages/e2e-tests/src/elements/staking/MultiDelegationStakingInfoComponent.ts
> +import { LocatorStrategy } from '../../actor/webTester';
Please do not create a new file, add what's needed to 'MultidelegationPage' class.

2023-09-12 07:09 UTC, oldGreg5 commented on packages/e2e-tests/src/elements/staking/stakingPage.ts
>    private EMPTY_SEARCH_RESULTS_IMAGE = '[data-testid="stake-pool-table-empty-image"]';
Please do not modify legacy staking files, move what's needed to 'MultidelegationPage' class. We need to leave legacy as is at least until we are ready to remove it. Currently we still use legacy for HW wallets.

2023-11-07 09:16 UTC, closed without merging