test(extension): first multidelegation full flow test
input-output-hk/lace pull request #332
Opened 2023-07-28 15:55 UTC by oldGreg5

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-08-07 09:45 UTC, wklos-iohk commented on packages/staking/src/features/staking/PortfolioBar.tsx
> +        <Button.Secondary label="Clear" onClick={portfolioMutators.clearDraft} data-testid="portfolioBar-btn-clear" />
1. Labels should be taken from relevant file with translations.
2. I'd suggest to not use upper-case letters in test ids.

2023-08-07 09:45 UTC, wklos-iohk commented on packages/staking/src/features/staking/PortfolioBar.tsx
> +        <Button.Primary
as above

2023-08-07 10:12 UTC, oldGreg5 commented on packages/staking/src/features/staking/PortfolioBar.tsx
> +        <Button.Secondary label="Clear" onClick={portfolioMutators.clearDraft} data-testid="portfolioBar-btn-clear" />
That's a small change so I changed to reading from i18n

2023-08-07 10:39 UTC, wklos-iohk requested changes

2023-08-07 10:39 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/staking/MultidelegationPage.ts
> +  get delegationcardPoolsValue() {
Can we adjust the name to `delegationCardPoolsValue` ?

2023-08-07 10:39 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +  /^I pick "(\d+)" pools for delegation from browse pools view: "([^"]*)"$/,
Why do we have this first parameter ignored? Is it really needed?

2023-08-07 10:39 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +  /^I click (Next|Clear) button on staking (portfolio bar|manage staking|confirmation)$/,
This step is misleading, `clear` button won't be clicked at all according to current implementation

2023-08-07 10:39 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/staking/MultidelegationPage.ts
> +    await this.overviewTab.waitForClickable();
I'd suggest to rewrite it with `switch...case` statement
```
    switch (tab) {
      case 'Overview':
        await this.overviewTab.waitForClickable();
        await this.overviewTab.click();
        break;
      case 'Browse pools':
        await this.browseTab.waitForClickable();
        await this.browseTab.click();
        break;
      default:
        ...
    }
```

2023-08-07 10:39 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/staking/MultidelegationPage.ts
> +  private async markPoolForStaking() {
This one seems to be pretty small and used only once in `markStakePoolWithName`, hence they could be merged.

2023-08-07 11:10 UTC, oldGreg5 commented on packages/e2e-tests/src/elements/staking/MultidelegationPage.ts
> +    await this.overviewTab.waitForClickable();
Yeah, normally I would prefer having less code for that simple thing(just to options) but we're gonna have there 3rd tab eventually for sure so why not, thanks.

2023-08-07 11:16 UTC, oldGreg5 commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +  /^I pick "(\d+)" pools for delegation from browse pools view: "([^"]*)"$/,
It's for the visibility on a report

2023-08-07 12:49 UTC, wklos-iohk approved these changes

2023-08-07 14:23 UTC, ljagiela approved these changes

2023-08-08 10:42 UTC, przemyslaw-wlodek approved these changes

2023-08-08 10:44 UTC, merged