feat(extension): implement post hog events for staking section
input-output-hk/lace pull request #333
Opened 2023-07-28 18:31 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-7370](https://input-output.atlassian.net/browse/LW-7370)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR implements the following analytics events on staking section:

- staking | staking | click
- staking | staking | stake pool | click
- staking | stake pool detail | stake on this pool | click
- staking | Switching pool? | fine by me | click
- staking | manage delegation | stake pool confirmation | next | click
- staking | manage delegation | password confirmation | confirm | click
- staking | manage delegation | Hurray! | view
- staking | manage delegation | hurray! | close | click
- staking | manage delegation | hurray! | x | click
- staking | manage delegation | something went wrong | back | click
- staking | manage delegation | something went wrong | cancel | click
- staking | manage delegation | something went wrong | x | click

2023-08-01 13:56 UTC, marcin-mazurek requested changes

2023-08-01 13:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +  StakingSwitchingPoolFineByMeClick = 'staking | Switching pool? | fine by me | click',
```suggestion
  StakingSwitchingPoolFineByMeClick = 'staking | switching pool? | fine by me | click',
```

2023-08-01 13:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +  StakingManageDelegationHurrayView = 'staking | manage delegation | Hurray! | view',
```suggestion
  StakingManageDelegationHurrayView = 'staking | manage delegation | hurray! | view',
```

2023-08-01 13:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +  StakingSwitchingPoolFineByMeClick = 'staking | Switching pool? | fine by me | click',
As per our convention, all events are meant to be fully lowercase :)

2023-08-01 13:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/StakePoolDetailsDrawer.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Could you explain why we don't list the `analytics` object in dependencies? Is it because in the current implementation it never changes? In the past I had to troubleshoot a few issues resulting from a fact that something wasn't listed as a dependency, it's not fun 😉

2023-08-02 10:31 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +  StakingManageDelegationHurrayXClick = 'staking | manage delegation | hurray! | x | click',
Are we sure we want an exclamation mark in this part of the event name?

2023-08-02 10:33 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/TransactionSuccess.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Why not list `analytics` as a dependency instead of adding this disable comment?

2023-08-02 10:33 UTC, DominikGuzei approved these changes
Code LGTM 🚢 i added some small suggestions

2023-08-02 10:49 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/StakePoolDetailsDrawer.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Yes, that is correct

2023-08-02 10:52 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +  StakingManageDelegationHurrayXClick = 'staking | manage delegation | hurray! | x | click',
That is how is specified in the event dictionary, so, I think this is a question for analytics team

2023-08-02 11:04 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/TransactionSuccess.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
In this case, I want this to be trigger only on first render

2023-08-04 10:39 UTC, marcin-mazurek approved these changes

2023-08-04 11:29 UTC, milagi approved these changes

2023-08-04 11:35 UTC, merged