fix: no logs added
input-output-hk/lace pull request #350
Opened 2023-08-03 10:26 UTC by VanessaPC

# Checklist

- [ ] JIRA -LW-7789
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-08-03 10:57 UTC, greatertomi approved these changes

2023-08-03 11:04 UTC, iadmytro approved these changes

2023-08-03 11:31 UTC, rhyslbw requested changes
Minor note on the commit wording. Better to explain the change as `remove debugging console logs on stake pool page`

2023-08-08 07:34 UTC, VanessaPC commented
> Minor note on the commit wording. Better to explain the change as `remove debugging console logs on stake pool page`

Good point, this is now addressed.

2023-08-08 12:09 UTC, rhyslbw approved these changes

2023-08-09 08:21 UTC, przemyslaw-wlodek approved these changes
Thanks! I don't know how it slipped through. We will consider making this an obvious ESLint error soon.

2023-08-09 08:30 UTC, merged