[LW-7570]: update handle when sending tokens
input-output-hk/lace pull request #355
Opened 2023-08-03 15:28 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-7570)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

1. Add one of your own handles to the address book and send it to another address (can skip if a previously saved handle has changed hands).
2. Go to send flow and proceed to add this handle from the address book.
3. Expected: A warning with a review option should appear post-verification. 
4. Click the call to action and you should be taken to an update/delete address flow.
5. Take an action - Update or Delete.
6. Expected: You should be taken back to the address input screen.

## Screenshots

https://github.com/input-output-hk/lace/assets/27725122/41923d92-4bec-469f-bd68-77f1cec88cbe

2023-08-07 20:51 UTC, greatertomi requested changes

2023-08-07 20:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.tsx
> +    console.log('addr2::', addressToEdit);
Remove this `console`

2023-08-07 20:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.tsx
> +      <>
This is an extra unnecessary fragment

2023-08-07 20:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/send/components/Send.tsx
> +          shouldDisplayFooter ? (
```suggestion
          shouldDisplayFooter && (
```

2023-08-07 20:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useSendEvent.ts
> +export const useSendEvent = (): SendEventFn => {
This hook was not used? Can it be deleted?

2023-08-07 20:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/AddressInput.tsx
> +    // todo: debounce this
Why not just debounce this in this PR?

2023-08-07 20:51 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionLayout.tsx
>                // eslint-disable-next-line @typescript-eslint/no-empty-function
```suggestion
```

2023-08-08 10:53 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/AddressInput.tsx
> +    // todo: debounce this
This was not me.

2023-08-08 10:57 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/hooks/useSendEvent.ts
> +export const useSendEvent = (): SendEventFn => {
Ah yes. I committed this by mistake but was going to do some refactoring which uses it.

2023-08-08 12:18 UTC, VanessaPC requested changes
My flags are turned on, but I can't see the button.  
<img width="355" alt="Screenshot 2023-08-08 at 12 47 25" src="https://github.com/input-output-hk/lace/assets/4052063/6214a20d-c225-471a-9696-05ceba51f826">

2023-08-08 12:18 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +        <AddressChangeDetail isPopupView={popupView} />
Why aren't we passing `initialValues` here to the `AddressChangeDetail` component? those contain the expected and actual address, so no calculations need to be done with `useMemo` at least when it's coming from the `AddressBook`. I think there should be a way to send the same details from the SendFlow here, because we have the same details being calculated in the previous step, now we would be doing them twice, and the UI looks slower while we are doing the calculations because it shows blank. 
If the only reason to keep this component now is to use a Drawer, we should probably delete it and move the functionality to `AddressDetailDrawer` and do the needed logic for the couple of calls on the buttons there.

2023-08-08 12:18 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useSendEvent.ts
> +export const useSendEvent = (): SendEventFn => {
If we are using a hook for analytics, we probably want to be able to send the `action, category` props, so it can be used elsewhere.

2023-08-08 12:18 UTC, VanessaPC commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: ensureHandleOwnerHasntChangedArgs): Promise<boolean> => {
Why are we returning now a boolean? this logic hasn't changed anywhere else where it's being used and it's not used anywhere new, so can we leave it as it was before?

2023-08-08 12:18 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/AddressInput.tsx
> +    setSection({ currentSection: Sections.ADDRESS_CHANGE, prevSection: Sections.FORM });
can we pass to this section the `actual` and `expected` addressed, in this way we wouldn't need further calculations one step after.

2023-08-08 12:42 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/hooks/useSendEvent.ts
> +export const useSendEvent = (): SendEventFn => {
Updated.

2023-08-08 12:49 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +        <AddressChangeDetail isPopupView={popupView} />
Because since the `AddressChangeDetail` component is now being used in two places, and as you said, the send flow works differently, I thought it should be part of the common logic.

2023-08-08 12:52 UTC, shawnbusuttil commented on nix/lace-blockchain-services/internal/lace-blockchain-services/openapi.json
> +  "tags": [{ "name": "default" }],
This came from main? Reverting anyway.

2023-08-08 13:17 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/utils/validators/address-book.ts
> +}: ensureHandleOwnerHasntChangedArgs): Promise<boolean> => {
Reverting. This was also part of conflict resolution I think.

2023-08-08 13:47 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressDetailDrawer/AddressChangeDetailDrawer.tsx
> +        <AddressChangeDetail isPopupView={popupView} />
That's fine. But then `AddressChangeDetailDrawer` is now a redundancy of drawers... because it's only used to present this part that contains the actual UI and logic for the job. So either we can clean it up here or open a ticket for more cleanup.

2023-08-08 13:48 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/Form/AddressInput.tsx
> +    setSection({ currentSection: Sections.ADDRESS_CHANGE, prevSection: Sections.FORM });
I thought we had passed a prop like `name` somewhere else.

2023-08-11 10:27 UTC, greatertomi requested changes

2023-08-11 10:27 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.module.scss
> +}
This style is not used too

2023-08-11 10:27 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.module.scss
> +}
Couldn't find where this is used too

2023-08-11 10:27 UTC, greatertomi commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.module.scss
> +}
This too. Couldn't find where it was used.

2023-08-11 11:28 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.module.scss
> +}
It is used. I specifically put it there to override the one coming from the Timeline module. Because it was rendering with a big space to the left.

2023-08-14 08:42 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.module.scss
> +}
@shawnbusuttil  good catch! do we want to log this as a bug? this space might be affecting the other place where it's used. cd

2023-08-14 09:14 UTC, VanessaPC requested changes

2023-08-14 09:14 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> -          expectedAddress={validatedAddressStatus[addressToEdit.address]?.error?.expectedAddress ?? ''}
This expected And actual address where here so that we wouldn't be doing calculations in the drawers. They are smaller components that just render and pass values to.. they don't need to be doing calculations. 
The large calculations should be done in the parent components where can't extract them from. 
So this was correct at this level. 
If we do this here, we need to get the same address from the Send flow, but on the send flow we are calculating already the handle verification so at that point we also already have an actual and expected address to send to the drawer.

2023-08-14 09:14 UTC, VanessaPC commented on apps/browser-extension-wallet/src/hooks/useValidateAddressStatus.tsx
> +  const expectedAddress = useMemo(
I don't understand the use of `useMemo`, this should only be used when we need to allocate memory aside for a large calculation, extracting data from the store isn't one. Let's lighten this.

2023-08-14 09:14 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransaction.tsx
> +          expectedAddress={expectedAddress}
if we have this here, why do we have to then calculate it in the drawer? can we find a way to send it through? else in this case I would leave it.

2023-08-14 10:56 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressChangeDetail.module.scss
> +}
The only other place is the onboarding flow right?

2023-08-14 10:59 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> -          expectedAddress={validatedAddressStatus[addressToEdit.address]?.error?.expectedAddress ?? ''}
After my change, the component now shows the addresses immediately. Are you saying that we should pass them two levels down from the parent?

2023-08-14 11:00 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/hooks/useValidateAddressStatus.tsx
> +  const expectedAddress = useMemo(
Will remove this.

2023-08-14 11:00 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransaction.tsx
> +          expectedAddress={expectedAddress}
There is no drawer in this case. There are only component mapping to each section.

2023-08-14 11:37 UTC, VanessaPC commented on apps/browser-extension-wallet/src/features/address-book/components/AddressBook.tsx
> -          expectedAddress={validatedAddressStatus[addressToEdit.address]?.error?.expectedAddress ?? ''}
I am saying that one of the levels is now not needed, because that drawer does no calculations at all and its props are almost the same as the other drawer because the Timeline part of it has been abstracted. So, I think we should calculate it here, and pass it down to the drawer. The drawer has no reason to do a calculation.

2023-08-15 07:51 UTC, greatertomi approved these changes

2023-08-15 12:14 UTC, VanessaPC commented
I am testing your branch, but can't send an NFT, all the flags are enabled, and the app is rebuilt and restarted, but this is what I get, though my balance is 3000 ish tADA. 
![Screenshot 2023-08-15 at 13 13 41](https://github.com/input-output-hk/lace/assets/4052063/4a6a69fa-2e69-4dd7-a277-dfea0257750e)

2023-08-15 14:06 UTC, VanessaPC approved these changes
Great work!

2023-08-21 07:34 UTC, dmitrii-gaico requested changes
@shawnbusuttil Hey!
Could you please take a look why it is showing the same Address for Previous/New while Send flow. If reviewing the Handle from the Address Book then it works fine.
Address Book:
![image](https://github.com/input-output-hk/lace/assets/83477982/c1f720a7-00d4-48e3-81df-4499d84976b5)
While Send Flow:
![image](https://github.com/input-output-hk/lace/assets/83477982/f1cef8ea-51b0-4dc9-a42d-c4eaf8f3813e)

2023-08-22 11:20 UTC, dmitrii-gaico approved these changes

2023-08-23 13:03 UTC, mchappell approved these changes

2023-08-23 13:03 UTC, merged