fix: typo fixed in string
input-output-hk/lace pull request #356
Opened 2023-08-03 15:31 UTC by VanessaPC

# Checklist

- [x] JIRA - LW-7791
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1378/5796265267/index.html) for [1db67aca](https://github.com/input-output-hk/lace/pull/356/commits/1db67aca127a94558d7538450473fee37175f94c)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 35     | 1      | 0       | 0     | 36    | ❌     |

2023-08-03 15:58 UTC, rhyslbw requested changes

2023-08-03 15:58 UTC, rhyslbw commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "previewsAddress.description": "Previous linked address",
```suggestion
      "previousAddress.description": "Previous linked address",
```

2023-08-03 20:25 UTC, VanessaPC commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "previewsAddress.description": "Previous linked address",
fixed here => e7ae9339a9466240c5121507f57cce285217dae6

2023-08-07 07:41 UTC, dmitrii-gaico approved these changes

2023-08-08 12:08 UTC, rhyslbw approved these changes

2023-08-08 12:08 UTC, merged