refactor: move timeline component to common package and reuse
input-output-hk/lace pull request #357
Opened 2023-08-03 17:40 UTC by greatertomi

# Checklist

- [x] JIRA - LW-7756
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Move the Timeline component into the common package  and reuse

2023-08-08 10:51 UTC, shawnbusuttil requested changes

2023-08-08 10:51 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressBook/AddressBook.tsx
> +        shouldUseEllipsisBeforeAfter: true,
```suggestion
        shouldUseEllipsis: true,
```

2023-08-08 14:46 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/adress-book/components/AddressBook/AddressBook.tsx
> +        shouldUseEllipsisBeforeAfter: true,
Fixed on b920f4a

2023-08-09 08:14 UTC, VanessaPC approved these changes
Nice cleanup @greatertomi , thanks

2023-08-09 08:56 UTC, shawnbusuttil approved these changes

2023-08-09 11:54 UTC, rhyslbw approved these changes

2023-08-09 20:01 UTC, merged