feat(extension): add custom person properties
input-output-hk/lace pull request #375
Opened 2023-08-08 18:51 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-7651](https://input-output.atlassian.net/browse/LW-7651)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR implements custom person properties

The following properties are linked once to the user id and will be visible in the `Set Once` list of properties

- initial_hardware_wallet_model
- initial_firmware_version
- initial_cardano_app_version

The `user_tracking_type` property is sent in every user event and will be visible in the `Set` list of properties

## Testing

To test the `user_tracking_type` properties is needed to send an event, this property will appears in the list `Set` and can have two values 

- enhanced: opted in user
- basic: opted out user

The Hardware Wallet properties `initial_hardware_wallet_model`, `initial_firmware_version` and `initial_cardano_app_version` will be set only once and will be sent in `onboarding | hardware wallet | all done | go to my wallet | click` event, under the `Set Once` property list

2023-08-09 11:11 UTC, DominikGuzei commented
@jplorek-atix im getting this error on `yarn dev`
![CleanShot 2023-08-09 at 13 11 00](https://github.com/input-output-hk/lace/assets/172414/d0d7d1f1-3d7b-4674-b317-21e583850ad4)

2023-08-09 11:26 UTC, jplorek-atix commented
> @jplorek-atix im getting this error on `yarn dev`
> ![CleanShot 2023-08-09 at 13 11 00](https://user-images.githubusercontent.com/172414/259387697-d0d7d1f1-3d7b-4674-b317-21e583850ad4.png)

@DominikGuzei That was a missing mock, this should be working now

2023-08-09 11:54 UTC, DominikGuzei commented
@jplorek-atix atm I cannot get beyond hurray screen (hw restore flow) because when clicking on "Go to my wallet" button it asks me to connect to Ledger but nothing happens when i select the device.

![CleanShot 2023-08-09 at 13 42 07](https://github.com/input-output-hk/lace/assets/172414/6aa7e876-8a33-4bf3-8adf-6c8123abda36)

2023-08-10 13:25 UTC, jplorek-atix commented
> @jplorek-atix atm I cannot get beyond hurray screen (hw restore flow) because when clicking on "Go to my wallet" button it asks me to connect to Ledger but nothing happens when i select the device.
> 
> ![CleanShot 2023-08-09 at 13 42 07](https://user-images.githubusercontent.com/172414/259397145-6aa7e876-8a33-4bf3-8adf-6c8123abda36.png)

This might be happening because we are calling [LedgerKeyAgent.checkDeviceConnection](https://github.com/input-output-hk/cardano-js-sdk/blob/master/packages/hardware-ledger/src/LedgerKeyAgent.ts#L207-L222) without a deviceConnection, so, when it doesn't receive this parameter, it establishes a new connection


We can change the `getLedgerSpecifications` helper to receive the `deviceConnection` that we have already established

```
export const getLedgerSpecifications = async (
  deviceConnection: LedgerKeyAgent['deviceConnection']
): Promise<HardwareWalletPersonaProperties> => {
  const cardanoApp = await deviceConnection.getVersion();
  const firmware = await LedgerKeyAgent.getAppVersion(Wallet.KeyManagement.CommunicationType.Web, deviceConnection);
};
```
Then [here](https://github.com/input-output-hk/lace/pull/375/files#diff-cbd3442baeb476bca519056d5a085ee1f1dca91fa8c9490b51c1a99928927d10R208), we can use the `deviceConnection` state as a parameter

2023-08-16 07:56 UTC, marcin-mazurek requested changes

2023-08-16 07:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +    const HWSpecifications =
Can we go one step further and extract the whole function giving us person properties to a helper function? It feels like there is quite a lot of complexity in this component. Perhaps we could also cover it with some unit test?

2023-08-16 07:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +    await sendAnalytics(
Can we make sure we create a wallet even if analytics call crashes?

2023-08-16 07:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/helpers.ts
> +type HardwareWalletPersonaProperties = {
Small suggestion - PostHog calls those Person Properties, let's use the same vocabulary everywhere :) 
```suggestion
type HardwareWalletPersonProperties = {
```

2023-08-16 07:56 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async isPersistentUser(): Promise<boolean> {
Or maybe, we should return `UserTrackingType` from here?

2023-08-16 08:11 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/helpers.ts
> +  const firmware = await LedgerKeyAgent.getAppVersion(Wallet.KeyManagement.CommunicationType.Web, deviceConnection);
This is Cardano App version as well, not FW

2023-08-16 17:19 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +export enum UserTrackingType {
Yes. I considered use this, but, at the end, since they have different values, I will have to have something with the values that I need

2023-08-18 10:31 UTC, DominikGuzei commented
@marcin-mazurek @jplorek-atix I updated the branch to latest `main` and this is ready for final code review

2023-08-18 14:14 UTC, milagi requested changes
The following properties are only displayed in opted in users and are expected to be displayed in opted in and opted out users

- Initial Hardware Wallet Model
- Initial Firmware version (only Trezor Model T will have data on Initial Firmware version)
- Initial Cardano App version (note that Trezor Model T device doesn’t use any Cardano Apps. Only Ledger devices use Cardano Apps)

2023-08-21 20:05 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getUserTrackingType(): Promise<UserTrackingType> {
@jplorek-atix sorry for a bit of back and forth on this PR, but it just occurred to me we would be calling this function a lot. Could we maybe reduce the storage read operations, and store the value as an instance property, just like we do with `randomizedUserId` and `walletBasedUserId`? I believe we can initialize it with `restoreUserId` where we ask for `usePersistentUserId` anyway, and update if `makePersistent` and `makeTemporary` is called

2023-08-22 10:50 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getUserTrackingType(): Promise<UserTrackingType> {
Alternative option would be to set `user_tracking_type` person property only when user gives consent / changes their devision. Since it's a person property we don't really have to send it with every call to PostHog, only once is enough.

2023-08-23 20:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  async getUserTrackingType(): Promise<UserTrackingType> {
```suggestion
  getUserTrackingType(): UserTrackingType {
```

2023-08-23 20:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +export type PostHogSetMetadata = {
I think `set` is how PostHog technically names it (pretty badly as it doesn't tell me much :) ) - shall we give it a bit more meaningful name indicating the real purpose? :) 
```suggestion
export type PostHogPersonProperties = {
```

2023-08-23 20:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +  protected async getSetProperties(): Promise<PostHogSetMetadata | undefined> {
How about:
```suggestion
  protected async getPersonProperties(): Promise<PostHogSetMetadata | undefined> {
```

2023-08-23 20:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +    const currentUserTrackingType = await this.userIdService.getUserTrackingType();
We should be able to make this function synchronous as getUserTrackingType doesn't need to return a promise now

2023-08-23 20:49 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +        postHogOnboardingActions.hw?.DONE_GO_TO_WALLET,
@jplorek-atix can you take a look at this comment? 🙏

2023-08-24 19:52 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +        postHogOnboardingActions.hw?.DONE_GO_TO_WALLET,
Sorry, I thought I had done this. Now it's actually done

2023-08-24 19:54 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +    const currentUserTrackingType = await this.userIdService.getUserTrackingType();
Same as https://github.com/input-output-hk/lace/pull/440#discussion_r1304557699,  it's not possible as all background services call are asynchronous

2023-08-25 11:08 UTC, milagi approved these changes

2023-08-25 15:05 UTC, marcin-mazurek approved these changes

2023-08-25 15:05 UTC, merged