fix(extension): cip30 dApp connector is now injected as a regular js …
input-output-hk/lace pull request #383
Opened 2023-08-10 12:47 UTC by AngelCastilloB

CIP30 => enable() returns a proxy object and makes incompatible the wallet incompatible with some Dapps.

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/browse/LW-7919) 

---

## Proposed solution

Wrap the proxy object with a regular js object.

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1433/5821740010/index.html) for [6782fcc0](https://github.com/input-output-hk/lace/pull/383/commits/6782fcc0a000b6ad9f241cf1394c9ff843087b47)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 34     | 2      | 0       | 0     | 36    | ❌     |

2023-08-10 12:57 UTC, mkazlauskas requested changes

2023-08-10 12:57 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/background/inject.ts
> +  // Wrap the proxi API object with a regular javascript object to avoid interop issues with some dApps.
```suggestion
  // Wrap the proxy API object with a regular javascript object to avoid interop issues with some dApps.
```

2023-08-10 12:57 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/background/inject.ts
> +    getRewardAddresses: () => proxyApi.getRewardAddresses(),
Might as well get rid of the double proxy
```suggestion
    getRewardAddresses: () => proxyApi.getRewardAddresses(),
    experimental: {
      getCollateral: (params?: { amount?: Cbor }) => proxyApi.getCollateral(params)
    }
```

2023-08-10 13:02 UTC, mirceahasegan approved these changes
Great work, @AngelCastilloB ! 🚀

2023-08-10 13:15 UTC, mkazlauskas approved these changes
Nice work!

2023-08-10 13:45 UTC, rhyslbw approved these changes

2023-08-15 13:21 UTC, mchappell approved these changes

2023-08-15 13:27 UTC, danielmain approved these changes

2023-08-15 14:55 UTC, ManusMcCole approved these changes

2023-08-15 17:55 UTC, merged