test(extension): hd wallet first 2 tests
input-output-hk/lace pull request #386
Opened 2023-08-11 08:02 UTC by oldGreg5

# Checklist

- [ ] JIRA [LW-7543](https://input-output.atlassian.net/browse/LW-7543)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

First 2 HD wallet tests. Checking discovery of multiple used addresses and correctness of transaction history when different wallet addresses were used.

2023-08-17 11:54 UTC, ljagiela approved these changes

2023-08-18 07:28 UTC, wklos-iohk requested changes

2023-08-18 07:28 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/nftsExtendedSteps.ts
> +Given(/^I'm sending an NFT with name: "([^"]*)" with HD wallet$/, async (nftName: string) => {
Let's use article `the` here

2023-08-18 07:28 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/nftsCommonSteps.ts
> +Given(
It seems that we have 2 almost identical steps - this one and the one starting in L75.
Please consider merging them together.
I'd also suggest a little renaming:
`/^I use a (wallet_type_1|wallet_type_2) wallet with "([^"]*)" NFT in (popup|extended) mode$/`
Don't forget to adjust the wallet type names and parameter names and order in step definition.

2023-08-18 07:28 UTC, wklos-iohk commented on packages/e2e-tests/src/features/HdWalletExtended.feature
> +    And I see NFT with name: "DEV 3432" on the NFTs page
Please replace `And` with `Then`

2023-08-18 07:28 UTC, wklos-iohk commented on packages/e2e-tests/src/features/HdWalletExtended.feature
> +    And I can see transaction <txNumber> has type "<txType>" and value "<txValue>"
As above

2023-08-18 07:28 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/tokensPageAssert.ts
> +  async expectedAdaBalance(balanceInAda: number) {
Let's keep previous naming convention where all assertion names start with `assert...`

2023-08-18 07:28 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/tokensPageAssert.ts
> +    const balance: number = await TokensPage.tokenBalance(tokenIndex)
I'd suggest to not chain promises with `then(...)` and use 
```
const balance = Number((await TokensPage.tokenBalance(tokenIndex).getText()).replace(',', ''));
```
instead

2023-08-18 11:02 UTC, wklos-iohk approved these changes

2023-08-21 12:33 UTC, merged