LW-7770 Prevent from adding more than 5 pools in Browse Pools
input-output-hk/lace pull request #396
Opened 2023-08-14 07:40 UTC by mrcnk

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/browse/LW-7770)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

- Adds limit set to 5 as max pools to add to draft in hover stake pool buttons.

## Screenshots

<img width="727" alt="image" src="https://github.com/input-output-hk/lace/assets/16132011/f6563d9e-6d81-402b-9b9e-876dabc0d8ca">

2023-08-17 11:39 UTC, szymonmaslowski requested changes

2023-08-17 11:39 UTC, szymonmaslowski commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolItemBrowser/StakePoolItemBrowser.tsx
> +const MAX_ITEMS_IN_DRAFT = 5;
This value is already defined in the `delegationPortfolio` store. Please import it instead

2023-08-24 13:11 UTC, przemyslaw-wlodek requested changes

2023-08-24 13:11 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolio.ts
> +    },
Please make it a selector, not a query. 🙏🏻

2023-08-24 14:57 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolio.ts
> +    },
As discussed offline. There is another query that should become a selector. Let's tackle that in another PR 👍🏻

2023-08-24 14:57 UTC, przemyslaw-wlodek approved these changes

2023-08-25 10:47 UTC, ManusMcCole commented
Hi @mrcnk. Looks good almost ready to approve. One last thing though could we make the tooltip closer to the Figma design. There is a lot of usused space in the tooltip towards the right hand side.Not sure if there was a conversation about how it hovers over the button.
<img width="319" alt="Screenshot 2023-08-25 at 11 46 07" src="https://github.com/input-output-hk/lace/assets/56027085/3f8d4f59-6e94-4b3a-9809-8ee168f33c3e">
Figma = 
<img width="254" alt="Screenshot 2023-08-25 at 11 42 40" src="https://github.com/input-output-hk/lace/assets/56027085/cc7b46fb-787c-4870-b616-76913725e185">

2023-08-28 13:06 UTC, ManusMcCole approved these changes

2023-08-28 14:15 UTC, merged