feat(staking): LW-7864 add migrating stake pools banner
input-output-hk/lace pull request #402
Opened 2023-08-15 20:54 UTC by refi93

# Checklist

- [x] JIRA - \[LW-7864](https://input-output.atlassian.net/browse/LW-7864)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Motivation

Having already some delegation or starting a new one  user won’t  see immediately on the overview page untill the transaction gets submited which may confuse them.

## Proposed solution

While the delegation transaction is pending, we'd show to the user a banner letting them know the staking portfolio is about to change. There are two scenarios to consider:

1. User is already delegating, so the message is about migrating stake pools
2. User is not delegating, so this is their first delegation. In that case we show the same banner informing them that their staking portfolio will appear soon

## Testing

1. Test banner for scenario 1 by delegating from a wallet with no previous delegations, check that while the transaction is pending, in the "Staking" tab the screenshotted banner would appear.
2. Test banner for scenario 2 by picking some set of pools to delegate to, delegate to them and check that while the transaction is pending, the screenshotted banner would appear.

## Note

There is an edge-case if user delegates to the same portfolio they are currently delegating to, in which case the transaction is identified as a "self" transaction and therefore no banner is shown due to us listnening just for pending `delegation*` transaction types. So, arguably, this edge-case is handled by this PR reasonably (no real change to the portfolio, so no reason to show a banner about a pending "change"). Showing some other message to the user warning them about the redundancy of this action (delegating to the same portfolio) is part of this task in the backlog: https://input-output.atlassian.net/browse/LW-7641

## Screenshots
First pending delegation:
![Screenshot 2023-08-15 at 22 50 19](https://github.com/input-output-hk/lace/assets/4980147/63739944-d4c1-455c-afc6-e788b145fd05)

Pending delegation for existing portfolio:
![Screenshot 2023-08-15 at 22 49 42](https://github.com/input-output-hk/lace/assets/4980147/501376f4-596f-424d-b93b-5c57f1cfefd9)

2023-08-15 20:59 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +  }, [fetchWalletActivities]);
this code is already repeated three times in places related to the Activity and is apparently needed to trigger fetching of the activity data/be reactive to its changes. I considered refactoring/deduplicating it but it would touch areas we, as the purple squad don't own (AFAIK) so I concluded the most sensible for now is to repeat the code 1:1 and should anybody refactor this in the future, they would at least have an easier job by finding the impacted places by a simple string match in the codebase.

Places where this logic is already repeated: https://github.com/search?q=repo%3Ainput-output-hk%2Flace%20setWalletActivitiesObservable&type=code

2023-08-15 21:00 UTC, refi93 commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  hasPendingDelegationTransaction?: boolean;
made this optional to not force the popup to load activity (from which this flag is inferred) which would probably look arbitrary there given it's not used and would just result in redundant network requests

2023-08-15 21:03 UTC, refi93 commented on apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
> +export const DelegationTransactionTypes: Set<TransactionType> = new Set([
added explicit typing for better type-safety, i.e. to ensure TS would warn us if any of the types in the set isn't a valid `TransactionType`

2023-08-15 21:14 UTC, refi93 commented on packages/staking/src/features/overview/Overview.tsx
> +            customIcon={<InfoCircleOutlined className={styles.infoIcon} />}
this need to style explicitly the info icon to be purple seems a bit cumbersome to me, but I didn't find any reusable "purple info" icon, did I perhaps miss something?

2023-08-16 10:57 UTC, refi93 commented on packages/staking/src/features/overview/Overview.tsx
> +        <Text.SubHeading>Start staking</Text.SubHeading>
hide this if banner is shown

2023-08-16 11:13 UTC, refi93 commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  hasPendingDelegationTransaction?: boolean;
@przemyslaw-wlodek let's double-check if we want the banner in the popup view or not

2023-08-16 20:12 UTC, refi93 commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  hasPendingDelegationTransaction?: boolean;
checked offline with Przemek and popup is out of scope indeed

2023-08-16 21:26 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetDetailsDrawer/AssetDetailsDrawer.tsx
> -        fiatPrice &&
@przemyslaw-wlodek @szymonmaslowski the deduplication of the wallet activities fetching logic seemed straightforward perhaps except this place where I had to decide between keeping the `fiatPrice` passed from outside as a parameter to this function vs retrieving it within the `useWalletActivities()` hook.

I finally went with the former as it seems more convenient for the caller and also considering that apparently the original code wasn't really consistent, because the `fiatCurrentcy` was obtained from the store vs the `fiatPrice` passed from outside, and the refactored `useWalletActivities` hook makes the source of these two (related) properties consistent

2023-08-16 21:29 UTC, refi93 commented on apps/browser-extension-wallet/src/hooks/useWalletActivities.ts
> +export const useWalletActivities = ({
@przemyslaw-wlodek @szymonmaslowski I ended up deduplicating the wallet activity fetching logic into this hook. In the end it seemed quite straightforward but maybe it turns out to go against some practices/patterns in the codebase I'm not yet aware of. If this refactor turns out to "open a can of worms" don't hesitate to point it out and I can drop this commit

2023-08-16 21:40 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetDetailsDrawer/AssetDetailsDrawer.tsx
> -        fiatPrice &&
what I'm unsure about is that this new `useWalletActivities()` hook basically introduces an additional way of accessing the activities and related data, so a bit of ambiguity, but I'd nevertheless consider it an improvement to the existing approach of repeating the fetching boilerplate pretty much anywhere the activity data was needed so far.

2023-08-17 11:31 UTC, szymonmaslowski requested changes
Great Job 💪

2023-08-17 11:31 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +    getWalletActivitiesObservable: state.getWalletActivitiesObservable
This line is redundant

2023-08-17 11:31 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +  );
Let's move this logic to staking. The more we encapsulate inside, the better. Ideally Staking should be a "plug and play" component.

I would suggest creating a helper function in the overview directory called `hasPendingDelegationTransaction` and accepting `walletActivities`, so it could be reused by the `Overview` and `OverviewPopup` components.

2023-08-17 11:31 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +        hasPendingDelegationTransaction,
Moving the `hasPendingDelegationTransaction` logic to the staking we will need to pass the `walletActivities` instead. We need to do that for the `MultiDelegationStakingPopup` component as well.

2023-08-17 11:31 UTC, szymonmaslowski commented on packages/staking/src/features/overview/Overview.css.ts
> +  color: `${theme.colors.$bannerInfoIconColor} !important`,
Are we able to set the color other way than using important? Maybe increasing the specificity?

2023-08-17 12:04 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +  );
I agree, but initially I discussed this with you and we decided to put it here. 😄 Now I see no harm in moving it (we will need to duplicate the `DelegationTransactionTypes` though). This comment is just to make it clear for @refi93 and @xdzurman.

2023-08-17 21:03 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +        hasPendingDelegationTransaction,
The task still states that the popup view should have the banner, too, but @przemyslaw-wlodek confirmed with me offline that the popup view is left out of scope after discussing it with Fernando. The reason is that the user needs to be in the expanded view anyway to perform the pool migration. @przemyslaw-wlodek do you have a link to Fernando's comment or was it just a private conversation? Nevertheless, once I have the link to the comment, I'll update the task to prevent further confusion, sorry for that.

2023-08-17 21:22 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +  );
> I would suggest creating a helper function in the overview directory

I'd consider generalizing the `mapPortfolioToDisplayData.ts` file to `helpers.ts` and include there also the `hasPendingDelegationTransaction` helper, in order to not "spam" the overview folder with a new file for each helper, does that sound good to you?

2023-08-18 08:42 UTC, refi93 commented on packages/staking/src/features/overview/Overview.css.ts
> +  color: `${theme.colors.$bannerInfoIconColor} !important`,
actually, I just tried it without `!important` and it worked fine :D But I'm surprised because I remember trying the same before without success and as I've seen uses of "!important" in similar contexts, e.g. here: https://github.com/input-output-hk/lace/blob/d4801af6b7740f1d649f17324248b52d28ecc9a2/apps/browser-extension-wallet/src/features/dapp/components/Connect.module.scss#L145 I just went with putting there `!imporant` and it seemed to solve the problem. But apparently it works now, so I must have overlooked something subtle, so nevermind

2023-08-18 08:50 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +  );
done in https://github.com/input-output-hk/lace/pull/402/commits/f0b69bd90b45f748612093ff10d73afcb86a5db2

2023-08-18 08:50 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +        hasPendingDelegationTransaction,
addressed in https://github.com/input-output-hk/lace/pull/402/commits/f0b69bd90b45f748612093ff10d73afcb86a5db2

2023-08-18 08:53 UTC, refi93 commented on packages/staking/src/features/overview/Overview.css.ts
> +  color: `${theme.colors.$bannerInfoIconColor} !important`,
done in https://github.com/input-output-hk/lace/commit/84f48d98d4ccca00c5d496794575fd120b72fa60

2023-08-18 08:53 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +    getWalletActivitiesObservable: state.getWalletActivitiesObservable
done in https://github.com/input-output-hk/lace/commit/84f48d98d4ccca00c5d496794575fd120b72fa60

2023-08-18 08:56 UTC, refi93 commented on apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx
> +        walletStoreWalletActivities: walletActivities,
I checked the network requests in the popup and empirically, the popup was loading the wallet activities on load even before this change, so this doesn't result in any additional requests (which would be sad, because we currently don't use the activity for the popup as we don't show any banner there)

2023-08-18 09:13 UTC, przemyslaw-wlodek approved these changes
💪🏻 great work! Thank you @refi93 :)

2023-08-21 18:28 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +  );
@refi93 TBH I would keep both in separate files as IMO it is a good practise (similar to having a single react compoennt per file). I am ok with having helpers file for now. We definitely should establish some guidelines and write them down 😉

2023-08-21 18:30 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +        hasPendingDelegationTransaction,
If it was about my preference I would definitely include the banner in the popup view even if we cannot stake there. That is just an info for the user so he is not surprised with what he sees there.

2023-08-21 18:43 UTC, szymonmaslowski approved these changes
Well done!

2023-08-21 18:43 UTC, szymonmaslowski commented on packages/staking/src/features/outside-handles-provider/types.ts
> +  walletStoreWalletActivities: AssetActivityListProps[];
Our intention with those names was to include the data source in them, so e.g. `useWalletStore` hook exposes the `InMemoryWallet` object so the property name here is called `walletStoreInMemoryWallet`. Following this that property here should be called just wallet activities 😉 It's shit, I know 😄 It is there only temporary to help us understand all the data sources of the Staking once we have some more time.

That is not something for which we should block merging of the PR, I am just saying for an informative purpose 😉

2023-08-21 20:21 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +  );
ok, I'll leave the "helpers" file for now, IMHO I wouldn't look at helper functions as "react components", components usually are "composite" structures (combining hooks, styles, ...) and hence usually have some boilerplate around which may look a bit confusing if mixed. But such pure functions are usually pretty simple and separating them into files may make the codebase just look more cluttered to the "naked eye", also if some pattern emerges in the helpers it is a bit harder to notice as they are scattered around, hence making it harder to group them nicely which would otherwise aid readability, but if we agree on the pattern of one function per file, that's fine by me, too, of course, but I'd rather align on that on a team level as you mentioned

2023-08-22 11:43 UTC, ManusMcCole approved these changes

2023-08-23 12:01 UTC, refi93 commented
sorry I had to force-push this branch to revert a broken merge commit that was the result of merging this branch into a local version of `main` that contained additional commits I've been expreimenting with. The commit 2684f50 I force pushed was already approved in this PR

2023-08-23 12:11 UTC, danielmain approved these changes

2023-08-23 14:50 UTC, merged