fix(staking): LW-7865 adjust padding of stake pool browser items, background color of Unselect button
input-output-hk/lace pull request #403
Opened 2023-08-16 08:56 UTC by xdzurman

# Checklist

- [ ] JIRA - [link](https://input-output.atlassian.net/jira/software/c/projects/LW/boards/1209?modal=detail&selectedIssue=LW-7865)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Problem

1. Pool rows had wrong height and wrong button paddings
2. There was too much space (24px) between rows instead of 8px from Figma
3. Unselect button did not have a different background from its parent

## Proposed solution

Adjusted css classes to reflect Figma designs.

## Testing

Compare app against Figma designs.

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/22454337/31add79e-c361-4412-b590-495b19e63bfb)

2023-08-17 15:28 UTC, xdzurman commented
New changes:
Unselect button is primary (https://www.figma.com/file/RPN3V4Et7hMbXkV5ZIF75i/Lace-Browser---Full-view-UI-Design?node-id=9%3A22682&mode=dev)
![image](https://github.com/input-output-hk/lace/assets/22454337/fb8b4997-1e4f-48a1-93c7-f6e0bc491889)

Button height is 40px (https://www.figma.com/file/RPN3V4Et7hMbXkV5ZIF75i/Lace-Browser---Full-view-UI-Design?node-id=9%3A22682&mode=dev)
![image](https://github.com/input-output-hk/lace/assets/22454337/480c9ef3-95a5-48fc-b8a5-a366cd7940d0)

2023-08-21 18:58 UTC, szymonmaslowski requested changes

2023-08-21 18:58 UTC, szymonmaslowski commented on packages/ui/src/design-system/buttons/call-to-action-button.css.ts
> +    height: '$40',
This change is affecting all of the buttons right? I guess we should rather keep the current buttons unchanged and introduce a possibility to have a size of 40px ([Figma](https://www.figma.com/file/qGPfPiE6J7Oa7R1I1me6Vi/Lace-Browser---UI-Toolkit?node-id=59%3A869&mode=dev)). I am not sure how to approach this though. The most correct way IMO would be to add additional size for all of the variants and just control it with some component property. WDYT @przemyslaw-wlodek @mrcnk?

BTW: here is some VR testing results for this PR where we can see the affected places 😉 https://www.chromatic.com/build?appId=6422dc516f0543c5fd174d4c&number=251

2023-08-21 19:35 UTC, xdzurman commented on packages/ui/src/design-system/buttons/call-to-action-button.css.ts
> +    height: '$40',
Yes, all buttons are affected, since 48px relates to an outdated size from designs, which is now 40px in Figma if I'm not mistaken

2023-08-24 14:59 UTC, przemyslaw-wlodek approved these changes

2023-08-25 09:05 UTC, oldGreg5 approved these changes

2023-08-28 10:36 UTC, xdzurman commented
PR waiting for UI toolkit approval: https://input-output-rnd.slack.com/archives/C057ZSEU7NF/p1692969563991809

2023-08-30 14:45 UTC, przemyslaw-wlodek approved these changes

2023-08-31 07:55 UTC, szymonmaslowski approved these changes

2023-08-31 08:53 UTC, merged