Feat/LW-7101 multi delegation empty states
input-output-hk/lace pull request #405
Opened 2023-08-17 07:27 UTC by mrcnk

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/browse/LW-7101)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

- Add m. deleg. empty states for extended mode
- Add m. deleg. empty states for popup mode

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1718/5977534072/index.html) for [85dd1b0b](https://github.com/input-output-hk/lace/pull/405/commits/85dd1b0b0c229c8939f49a3492f261cb24df0573)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 33     | 2      | 0       | 0     | 35    | ❌     |

2023-08-21 19:21 UTC, xdzurman commented on packages/staking/src/features/staking/FundWalletBanner.tsx
> +  // eslint-disable-next-line react/no-multi-comp
What is the reason for this ts-ignored element declaration? Sure, compared to the browser code this looks cleaner to me than a function, but other elements are still functions so it's not consistent, and somewhere down the line this can lead to performance issues

2023-08-23 12:51 UTC, szymonmaslowski requested changes

2023-08-24 13:37 UTC, mrcnk commented on apps/browser-extension-wallet/src/features/delegation/components/MultiDelegationStakingPopup.tsx
> +  const hasNoFunds = (coinBalance < Number(minAda) && !isStakeRegistered) || (coinBalance === 0 && isStakeRegistered);
Done here, moved part of the calculations inside Staking.

2023-08-25 09:41 UTC, szymonmaslowski approved these changes

2023-08-25 14:08 UTC, oldGreg5 approved these changes

2023-08-25 17:11 UTC, merged