chore(all): LW-8019 fix critical/high yarn audit vulnerabilities
input-output-hk/lace pull request #408
Opened 2023-08-17 10:52 UTC by refi93

# Checklist

- [x] JIRA - \ [LW-8019](https://input-output.atlassian.net/browse/LW-8019)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---
## Motivation
`yarn audit` is currently reporting 324 vulnerabilities:

```
324 vulnerabilities found - Packages audited: 4632
Severity: 206 Moderate | 106 High | 12 Critical
```

## Proposed solution

Run [yarn-audit-fix](https://www.npmjs.com/package/yarn-audit-fix) which is an automated tool looking for non-vulnerable versions of packages that comply with the dependency constraints. Fix the rest of reported (high/critical) vulnerabilities ad-hoc.

The commits are split in the following way:

1. just the automatic fixes by `yarn-audit-fix`
2. removal of vulnerable dependencies that seemed unused as they weren't referenced anywhere in the project nor as peer dependencies
3. re-installing/bumping node-sass (without modifying package.json constraints on major/minor version), and webpack  from version 5.75 to 5.76
4. reintroduced `yarn audit` into CI, basically reverting https://github.com/input-output-hk/lace/pull/241/files (except sonarqube)

## Testing

1. run `yarn audit` and there should be no high/critical vulnerabilities reported
2. run full test suite in CI

2023-08-17 11:16 UTC, przemyslaw-wlodek requested changes

2023-08-17 12:51 UTC, danielmain commented on .github/scripts/audit.sh
> +yarn audit --groups dependencies --level high; [[ $? -ge 8 ]] && exit 1 || exit 0;
@refi93 thank you for the idea, but I am not a good friend to add yet another dependency 😔. The project seems not to support yarn3? https://github.com/djfdyuruiry/improved-yarn-audit/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

I'm afraid if the audit does not stop the CI it will be ignored. That is why I added a task to address all reports from git-dependabot in the release process.

2023-08-17 12:57 UTC, refi93 commented on .github/scripts/audit.sh
> +yarn audit --groups dependencies --level high; [[ $? -ge 8 ]] && exit 1 || exit 0;
I see, thanks for the insight @danielmain , will remove the `yarn audit` from CI then 👍

2023-08-17 16:44 UTC, tgunnoe commented
This will have to be rebased and updated for yarn3

2023-08-17 20:04 UTC, refi93 commented
@tgunnoe will do 👍 btw, I noticed that the `yarn npm audit --all --recursive` seems to yield a lot less vulnerabilities than `yarn audit` did (324 vs ~20), seems to be related to this PR apparently fixing the issue https://github.com/yarnpkg/berry/pull/5501 but not released yet. Based on this comment: https://github.com/yarnpkg/berry/pull/5501#issuecomment-1620149651 I'm not actually sure if the fix would ever be released in yarn v3

For the time being I will fix the vulnerabilities respective to the v3 report then

2023-08-17 20:36 UTC, refi93 commented on .github/scripts/audit.sh
> +yarn audit --groups dependencies --level high; [[ $? -ge 8 ]] && exit 1 || exit 0;
btw yarn v3 has native support for ignoring security advisories:

> If particular advisories are needed to be ignored, the --ignore flag can be used with Advisory ID's to ignore any number of advisories in the audit report. This can also be set in the configuration file with the [npmAuditIgnoreAdvisories](https://yarnpkg.com/configuration/yarnrc#npmAuditIgnoreAdvisories) option.

https://yarnpkg.com/cli/npm/audit/

however as far as I tried it seems that yarn v3 audit is underreporting vulnerabilities as I pointed out below :( https://github.com/input-output-hk/lace/pull/408#issuecomment-1682902840

2023-08-18 22:25 UTC, refi93 commented
@przemyslaw-wlodek I force-pushed the fixes to yarn.lock because I basically did the update from scratch so the code requires re-reviewing anyway as it doesn't share anything in common apart from the general steps (autofix issues with `yarn-audit-fix` and try reinstalling packages that have vulnerable recursive deps while retaining their version constraints in package.json).

I also bumped webpack which although wasn't reported by the v3 `yarn npm audit --all --recursive` scripts, it has apparently a know vulnerability: https://www.wordfence.com/threat-intel/vulnerabilities/detail/webpack-js-package-5750-sandbox-bypass#:~:text=The%20JS%20package%20webpack%20is,are%20not%20vulnerable%20to%20exploitation

Currently only one critical dependency should be reported by `yarn npm audit --all --recursive` , namely `mockery` via `@wdio/cucumber-framework` which [doesn't seem fixable atm](https://github.com/webdriverio/webdriverio/issues/10818), until the package migrates away from it (mockery seems abandoned) and is used just in the e2e tests anyway.

2023-08-21 07:22 UTC, przemyslaw-wlodek approved these changes

2023-08-23 07:27 UTC, oldGreg5 approved these changes

2023-08-23 10:08 UTC, danielmain approved these changes
Great job @refi93

2023-08-23 14:51 UTC, merged