feat(extension): add ada handle name to receive QR drawer
input-output-hk/lace pull request #41
Opened 2023-06-01 12:18 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR aims to add the handle name (if found) to the receive drawer.

## Testing

Simply click the receive button in the wallet. Note: You must have a minted ADA Handle NFT in your wallet.

## Screenshots

TBD

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ✅ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/376/5256337899/index.html) for [e915e9a5](https://github.com/input-output-hk/lace/pull/41/commits/e915e9a5f98fce82c22d2f956de5362b1c6cb689)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 19     | 0      | 0       | 0     | 19    | ✅     |

2023-06-06 11:13 UTC, rhyslbw requested changes
There's also a lint warning to address still.
<img width="597" alt="Screenshot 2023-06-06 at 12 12 48" src="https://github.com/input-output-hk/lace/assets/303881/673169ef-cbd1-450c-9487-1547439603ee">

2023-06-06 11:13 UTC, rhyslbw commented on apps/browser-extension-wallet/manifest.json
> +    "extension_pages": "default-src 'self' $LOCALHOST_DEFAULT_SRC; frame-src https://connect.trezor.io/; script-src 'self' 'wasm-unsafe-eval' $LOCALHOST_SCRIPT_SRC; font-src 'self' https://use.typeki
`$ADA_HANDLE_URLS`

2023-06-08 12:05 UTC, dmitrii-gaico approved these changes

2023-06-08 17:34 UTC, gabriela-ponce approved these changes

2023-06-13 09:52 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useGetHandles.ts
> +export const useGetHandles = () => {
Maybe we should add a return type and remove the disable eslint lint comment
```suggestion
export const useGetHandles = (): HandleInfo[] | undefined => {
```

2023-06-13 09:52 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useGetHandles.ts
We can also add this hook to the hooks index file `apps/browser-extension-wallet/src/hooks/index.ts`

2023-06-13 10:25 UTC, greatertomi requested changes

2023-06-13 10:25 UTC, greatertomi commented on apps/browser-extension-wallet/src/hooks/useGetHandles.ts
> +export const useGetHandles = () => {
Maybe we should add a return type and remove the disable eslint lint comment

```suggestion
export const useGetHandles = (): HandleInfo[] | undefined => {
```

2023-06-13 17:17 UTC, rhyslbw approved these changes

2023-06-13 17:18 UTC, greatertomi approved these changes

2023-06-13 17:19 UTC, merged