fix(staking): LW-8018 turn off unstaking banner for multi-delegation
input-output-hk/lace pull request #412
Opened 2023-08-17 17:16 UTC by xdzurman

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/jira/software/c/projects/LW/boards/1209?modal=detail&selectedIssue=LW-8018&assignee=5cfdfc4bc97d8b0c633413a7&assignee=UNASSIGNED_USER_ID)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Check environment variable to judge whether to render the warning banner or not.

## Testing

Click on a pool you are delegating to, and verify that you cannot see this banner:
![image](https://github.com/input-output-hk/lace/assets/22454337/2563ea3c-13ac-4b98-aa01-092be8dbf3f5)

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/1670/5960547225/index.html) for [7352ecf1](https://github.com/input-output-hk/lace/pull/412/commits/7352ecf1980ecdb94b50487b1608194d4a8a9d1c)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 34     | 1      | 0       | 0     | 35    | ❌     |

2023-08-21 19:02 UTC, szymonmaslowski requested changes

2023-08-21 19:02 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetail.tsx
> +          {delegatingToThisPool && !isMultiDelegationEnabled && (
The adequate component on the browser-extension-wallet side is loaded only when the `USE_MULTI_DELEGATION_STAKING` flag is turned off and this one only if that flag is turned on. Because of that we can safely just remove the Banner code from here without any additional logic and not touch the adequate component on the browser side 😉

2023-08-23 12:57 UTC, szymonmaslowski requested changes

2023-08-23 12:57 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/StakePoolDetail.tsx
> +          {isDelegatingToThisPool && !isMultiDelegationEnabled && (
Browser side components don't support multidelegation so actually we don;t need any change in here 😉

2023-08-24 07:03 UTC, refi93 commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolDetails/StakePoolDetail.tsx
> +  const isMultiDelegationEnabled = process.env.USE_MULTI_DELEGATION_STAKING === 'true';
as @szymonmaslowski wrote: https://github.com/input-output-hk/lace/pull/412/files#r1302634104 this shouldn't be needed and then also any syncing with my PR shouldn't be needed either, resolving

2023-08-24 10:50 UTC, szymonmaslowski approved these changes

2023-08-24 10:53 UTC, refi93 commented
LGTM, I'd just consider adding to the PR description a more detailed description of how to verify the fix (how to trigger the affected modal) to make it clear for QA what they need to test without being familiar with the code

2023-08-24 10:53 UTC, refi93 approved these changes

2023-08-24 15:04 UTC, merged