feat(extension): add posthog_project_id property to events
input-output-hk/lace pull request #432
Opened 2023-08-22 18:32 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-8081](https://input-output.atlassian.net/browse/LW-8081)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR implements `posthog_project_id` for all Post Hog event. This property contains the ID of each project

## Testing

Send an event to Post Hog, `posthog_project_id` should be visible in the event property list.
To verify if the project ID is correct, go to the `Project settings` section and look for `Project ID`, this should be the same as the ID in the event.

2023-08-23 09:58 UTC, DominikGuzei approved these changes
LGTM 👍

2023-08-23 22:03 UTC, marcin-mazurek requested changes
Well done 🎉 Just one tiny nitpick.

2023-08-23 22:03 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/postHog/PostHogClient.ts
> +  protected getProjectID(): number {
Small suggestion for improving consistency:
```suggestion
  protected getProjectId(): number {
```

2023-08-24 13:12 UTC, milagi approved these changes

2023-08-25 14:36 UTC, marcin-mazurek approved these changes

2023-08-28 11:40 UTC, merged