feat(staking): LW-7674 split 1 delegation&deregistration tx into two activities
input-output-hk/lace pull request #433
Opened 2023-08-23 07:48 UTC by xdzurman

# Checklist

- [ ] [JIRA](https://input-output.atlassian.net/jira/software/c/projects/LW/boards/1209?modal=detail&selectedIssue=LW-7674&assignee=5cfdfc4bc97d8b0c633413a7&assignee=UNASSIGNED_USER_ID)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Split the transaction, which both delegates and de-registers keys, into two actions. 
- Delegation action shows tx fee, and no returned deposits
- De-registration action shows only returned deposits (not fees), so that fees are not duplicated and deposits are nice round number

This applies to pending txs as well. 
One edge case is when user re-delegates from 2 pools (A, B) into one pool (A) - this is not a delegation action chain-wise, only a de-registration. In such a case, we cannot split it into 2 actions, since the delegation action isn't anywhere on-chain. Therefore, this action will be shown as just "De-registration" and its value is deposit deducted by tx fee (e.g. 1.77 ADA = 2 ADA - 0.23 ADA) 

Since there is no plus or minus of values in the activity tab, I introduced a `Returned deposit` label in `Transaction Detail` to make it clear for the user. Tech-wise, this avoids a lot of mental gymnastics we'd have to deal with if both paid and returned deposits were handled by just one prop (now we have both `deposit` and `returnedDeposit` props)

## Testing

- Stake from two pools (A, B) into one pool that is different from them (C)
- Stake from two pools (A, B) into one pool that is one from them (A)

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/22454337/f58dff77-ba7e-433c-b41a-f0ba7c973db4)
![image](https://github.com/input-output-hk/lace/assets/22454337/afb1a4c4-6aef-4fee-b354-f2fc1e87c639)

Detail of delegation activity:
![image](https://github.com/input-output-hk/lace/assets/22454337/d2fc40a3-d907-4db2-b924-01a7e1cbeb1b)
Detail of de-registration activity:
![image](https://github.com/input-output-hk/lace/assets/22454337/cc508c89-534b-418c-8191-c5fc45283745)

2023-08-23 08:08 UTC, xdzurman commented on packages/core/src/ui/components/Activity/AssetActivityItem.tsx
> +const translationTypes = {
typo

2023-08-23 08:09 UTC, xdzurman commented on packages/core/src/ui/components/Transactions/Transaction.tsx
> -      {deposit && (
Just moved this above "Inputs" and "Outputs" in tx detail according to figma designs.

2023-08-23 08:10 UTC, xdzurman commented on packages/core/src/ui/components/Transactions/Transaction.tsx
> +        {returnedDeposit && (
Currently these are "two separate rows", so perhaps some logic for exclusion could be added, but there should never be a situation where both `deposit` and `returnedDeposit` are in one transaction

2023-08-23 12:24 UTC, przemyslaw-wlodek approved these changes
Great work! We've left some improvement proposals.

2023-08-23 12:24 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
>  const getDelegationAmount = (activity: AssetActivityItemProps) => {
Could you please fix the type here to include only delegation types? (`DelagatioinTransactionTypes` - with typo in codebase)

2023-08-23 12:24 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
> +  );
Can we be more explicit in this case? It requires a deep understanding of the flow to know that both `deposit` and `returnedDeposit` cannot be present at the same time.

After applying the above comment we can do the following:

```suggestion
  if (activity.type === 'delegationRegistration') {
    return fee.plus(activity.deposit);
  }
  
  if (activity.type === 'delegationDeregistration') {
    return new BigNumber(activity.returnedDeposit).minus(fee);
  }
  
  return fee;
```

2023-08-23 12:25 UTC, przemyslaw-wlodek requested changes
Sorry, I wanted to request changes in the previous review 😅

2023-08-23 12:31 UTC, xdzurman commented on apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
> +          transformedTx.status || Wallet.TransactionStatus.SUCCESS,
Before there was hardcoded `Wallet.TransactionStatus.SUCCESS` so I wasn't sure whether this can fail somehow, I can remove it however and try to trust it

2023-08-23 14:10 UTC, xdzurman commented on packages/core/src/ui/components/Transactions/Transaction.tsx
> +        {returnedDeposit && (
removed altogether, it wasn't necessary

2023-08-23 14:37 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
> +  );
I hope that when you narrow the types you will mitigate unhandled edge cases + the QA phase will reveal if something is there. Technically it'd be more correct to do it this way, as we described but given the time pressure and that your logic also "does the job" 😄 it's for you to decide.

2023-08-24 14:30 UTC, xdzurman commented
I split the delegation & Registration tx into two actions in this PR, since the changes are almost identical. Note that I also changed the order so that Registration/Deregistration appears "older in time", and so that the Delegation comes on top as the "main" action of the two.
![image](https://github.com/input-output-hk/lace/assets/22454337/9b0ca6c0-c114-4099-8163-0ac549dc477d)

2023-08-25 13:06 UTC, przemyslaw-wlodek approved these changes

2023-08-28 10:32 UTC, szymonmaslowski approved these changes
I left few minor suggesctions 😉

2023-08-28 10:32 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/stores/slices/wallet-activities-slice.ts
> +    const finalizeTransaction = (transformedTx: Omit<AssetActivityItemProps, 'onClick'>) => ({
```suggestion
    const extendWithClickHandler = (transformedTx: Omit<AssetActivityItemProps, 'onClick'>) => ({
```

or at least `finalizeTransactionEntryData`

`finalizeTransaction` sounds to me like it would be submiting the transaction 😉

2023-08-28 10:32 UTC, szymonmaslowski commented on packages/core/src/ui/components/Transactions/Transaction.tsx
> +        )}
I would reduce code duplication here
```suggestion
        const renderDepositValueSection = ({ value, label }) => (
          <div className={styles.details}>
            <div className={styles.title}>{label}</div>
            <div className={styles.detail}>
              <div className={styles.amount}>
                <span className={styles.ada}>{`${value} ${coinSymbol}`}</span>
                <span className={styles.fiat}>{amountTransformer(value)}</span>
              </div>
            </div>
          </div>
        )
        ...
        {deposit && renderDepositValueSection({ value: deposit, label: t('package.core.transactionDetailBrowser.deposit') })}
        {depositReclaim && renderDepositValueSection({ value: depositReclaim, label: t('package.core.transactionDetailBrowser.depositReclaim') })}
```

2023-08-30 10:39 UTC, merged