feat(staking): LW-7817 current pools managenet
input-output-hk/lace pull request #438
Opened 2023-08-23 13:29 UTC by szymonmaslowski

# Checklist

- [x] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-08-24 11:52 UTC, przemyslaw-wlodek requested changes

2023-08-24 11:52 UTC, przemyslaw-wlodek commented on packages/staking/src/features/browse-pools/PortfolioBar.tsx
> +    selectedPoolsCount: store.selections.length,
Nitpick:

Can we still have a selector for that? I see it's being accessed more than once.

2023-08-24 11:52 UTC, przemyslaw-wlodek commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolItemBrowser/StakePoolItemBrowser.tsx
> +  const selectionsNotEmpty = selectionsCount > 0;
Nitpick:

const selectionsNotEmpty = useDelegationPortfolioStore((state) => state.selections.length > 0);

2023-08-24 11:52 UTC, przemyslaw-wlodek commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolItemBrowser/StakePoolItemBrowser.tsx
> +  const poolAlreadySelected = useDelegationPortfolioStore((state) => state.queries.isPoolAlreadySelected(hexId));
I left another comment about naming methods `byId` etc. in this case we use `hexId` so I see it's even more relevant to include this and potentially unify usage of id/hexId.

2023-08-24 11:52 UTC, przemyslaw-wlodek commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolItemBrowser/StakePoolItemBrowser.tsx
> +  unselect,
Nitpick/question: Would `onToggle` / `onToggleSelection` do the job?

2023-08-24 11:52 UTC, przemyslaw-wlodek commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolsTable.tsx
> +  const { selectPool, unselectPool } = useDelegationPortfolioStore((state) => state.mutators);
Nitpick/question: Can we please follow accessing the mutators and other top-level properties without deep destructuring?

With this approach you need to go to the destructuring place to understand it's coming from the store, not inline `useState` or sth else. I like the approach from `packages/staking/src/features/drawer/StakePoolPreferences.tsx`

2023-08-24 11:52 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/types.ts
> +}
What do you think about the following?

```suggestion
export enum PortfolioProcess {
  Idle = 'Idle',
  ManagingNewPortfolio = 'ManagingNewPortfolio',
  ManagingCurrentPortfolio = 'ManagingCurrentPortfolio',
}
```

2023-08-24 12:09 UTC, szymonmaslowski commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolItemBrowser/StakePoolItemBrowser.tsx
> +  unselect,
```suggestion
  onSelect,
  onUnselect,
```

2023-08-25 09:57 UTC, mrcnk commented on packages/staking/src/features/store/delegationPortfolio.ts
> +      isPoolAlreadySelected: (id) => {
Hex ID is fine, it's more accurate in a sense that pool has: public key, id and hex id.

2023-08-25 13:32 UTC, przemyslaw-wlodek approved these changes

2023-08-28 08:59 UTC, oldGreg5 approved these changes

2023-08-28 10:29 UTC, merged