Fix/lw 7895 fetch token price fails makes lace crash
input-output-hk/lace pull request #447
Opened 2023-08-24 17:48 UTC by DominikGuzei

# Checklist

- [x] https://input-output.atlassian.net/browse/LW-7895
- [x] Screenshots added.

---

## Proposed solution

This PR fixes a bug that crashed the extension when the coin prices could not be fetched from coingecko for 3 minutes. It also changes the endpoint URL to our custom coingecko proxy.

## Testing

1. Open the extension
2. block requests to our custom coingecko proxy
3. After 3 minutes you should see a banner like this appear and the extension should not crash: 
![CleanShot 2023-08-24 at 19 46 14](https://github.com/input-output-hk/lace/assets/172414/8364e7c8-36c7-4810-b28c-9aebafe520cd)

2023-08-24 19:59 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/scripts/background/services/utilityServices.ts
> +    `https://coingecko.live-mainnet.eks.lw.iog.io/api/v3/simple/price?ids=cardano&vs_currencies=${vsCurrencies}&include_24hr_change=true`
Is this the endpoint proxy URL?

2023-08-24 19:59 UTC, jplorek-atix approved these changes

2023-08-25 15:15 UTC, marcin-mazurek requested changes

2023-08-25 15:15 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/utilityServices.ts
> -      await setBackgroundStorage({
We should also remove `getADAPriceFromBackgroundStorage` function and its usage, as well as `fiatPrices` property from `BackgroundStorage` interface

2023-08-25 15:15 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalance.tsx
> +            customIcon={<QuestionMarkIcon />}
That's the fix itself, right?

2023-08-25 15:20 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/views/browser-view/components/PortfolioBalance/PortfolioBalance.tsx
> +            customIcon={<QuestionMarkIcon />}
@marcin-mazurek yes and importing it via `.component.svg` so that it uses RSVG

2023-08-25 15:31 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/utilityServices.ts
> -      await setBackgroundStorage({
@marcin-mazurek done 👍

2023-08-28 12:42 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/utilityServices.ts
> -const { ADA_PRICE_CHECK_INTERVAL, SAVED_PRICE_DURATION } = config();
@DominikGuzei can you also check if this one can be removed too?

2023-08-29 14:01 UTC, marcin-mazurek approved these changes

2023-08-29 15:12 UTC, jplorek-atix approved these changes

2023-08-30 18:49 UTC, milagi approved these changes

2023-08-31 11:44 UTC, merged