fix(staking): LW-8144 align multistaking announcement beta pill to the left
input-output-hk/lace pull request #454
Opened 2023-08-25 15:12 UTC by refi93

# Checklist

- [x] JIRA - LW-8144
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Move beta pill in the staking announcement in the popup view to the left, add bottom margin, as shown in the figma designs in the Jira ticket

## Testing

Load a clean wallet and go to the staking section in the popup view, the announcement shown should appear as in figma/the "after" screenshot below

## Screenshots

before:
![Screenshot 2023-08-25 at 17 12 14](https://github.com/input-output-hk/lace/assets/4980147/b3edc47b-90d8-4419-a3d0-cee2f9d9313a)

after:
![Screenshot 2023-08-25 at 17 08 03](https://github.com/input-output-hk/lace/assets/4980147/518647d1-610d-4d2c-801c-f579b4d06f73)

2023-08-28 08:20 UTC, przemyslaw-wlodek requested changes
Great work but please apply your changes only for the popup view :)

2023-08-28 14:54 UTC, mrcnk approved these changes

2023-08-30 09:18 UTC, ManusMcCole approved these changes

2023-08-31 08:21 UTC, przemyslaw-wlodek approved these changes

2023-08-31 08:21 UTC, merged