feat(staking): match multistaking overview empty state with designs
input-output-hk/lace pull request #457
Opened 2023-08-29 00:45 UTC by refi93

# Checklist

- [x] JIRA - LW-8149
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Restructure the elements and add styles to make the empty state screen match the Figma designs (see JIRA task for link)

## Testing

1. set up a wallet with no staking and non-empty funds
2. go to "Staking" section in the expanded view
3. check that the "Get started" section matches the figma designs in both light and dark mode

## Screenshots

Before:

<img width="903" alt="Screenshot 2023-08-29 at 02 43 11" src="https://github.com/input-output-hk/lace/assets/4980147/8b79716d-f53e-439d-96d5-07bd227f13bc">

After:

light mode:

<img width="912" alt="Screenshot 2023-08-29 at 02 44 00" src="https://github.com/input-output-hk/lace/assets/4980147/79476a3b-6aec-4044-b3d1-782cbfb9e34e">

dark mode:

<img width="780" alt="Screenshot 2023-08-29 at 02 44 16" src="https://github.com/input-output-hk/lace/assets/4980147/f67c9516-4483-43b5-a59c-96f176e79645">

2023-08-29 00:48 UTC, refi93 commented on packages/staking/src/features/theme/colors.ts
> +  $getStartedStepNumberColor: laceGradient,
I noticed this "laceGradient" value (`linear-gradient(94.22deg, #FF92E1 -18.3%, #FDC300 118.89%)`) doesn't match 1:1 the value in the figma design (`var(--gradient-lace, linear-gradient(135deg, #FF92E1 0%, #FDC300 100%));`) but in the end I concluded it's probably better to stick the "lace gradient" we already have in the code for the sake of consistency

2023-08-29 00:52 UTC, refi93 commented on packages/staking/src/features/theme/colors.ts
> +  $getStartedStepBorderColor: darkColorScheme.$primary_mid_black,
this color doesn't match the dark theme color from figma either (`fill: var(--dark-mode-dark-grey, #2E2E2E);`) , because if I tried to use the figma color it turned out to match the background, making the circle invisible, so I used a lighter color from the palette (`primary_mid_black` -> `#252525`)

2023-08-30 04:54 UTC, mrcnk requested changes
Looks good, I'd just make sure `<Link>` components actually navigate user through screens to correct place.

2023-08-30 08:06 UTC, mrcnk approved these changes

2023-08-30 08:18 UTC, refi93 commented on packages/staking/src/features/overview/GetStartedSteps.tsx
> +                  Link: <a target="_blank" href={`${process.env.FAQ_URL}?question=what-are-staking-and-delegation`} />,
@mrcnk worth noting that the `<Link>` "component" seen in the translations is just an interpolation placeholder and what to replace it with is specified here. I actually haven't seen this used in the codebase (nor examples of adding links within translations in other ways), but found it to be pretty handy for this case

https://react.i18next.com/latest/trans-component#alternative-usage-which-lists-the-components-v11.6.0

2023-08-30 12:43 UTC, ManusMcCole approved these changes

2023-08-31 08:06 UTC, merged