feat(extension): clear input on address delete in send flow
input-output-hk/lace pull request #458
Opened 2023-08-29 09:46 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Passing a flag to communicate to the root component that the action the user has taken is a delete action and handling it by clearing the input field.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-08-30 11:14 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionLayout.tsx
> +    const clearInput = () => {
Nice! How did this file get so many extra changes? Did we change the linter?

2023-08-30 11:14 UTC, VanessaPC approved these changes

2023-08-30 13:05 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionLayout.tsx
> +    const clearInput = () => {
I want an answer to this myself because my lint doesn't even work. Will investigate and amend if I have to.

2023-08-31 14:01 UTC, greatertomi requested changes

2023-09-04 15:04 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionLayout.tsx
> +                      action === 'DELETE' && clearInput();
Done. Awaiting rereview. :)

2023-09-04 16:25 UTC, rhyslbw commented on apps/browser-extension-wallet/src/views/browser-view/features/send-transaction/components/SendTransactionLayout.tsx
> +                      action === 'DELETE' && clearInput();
@greatertomi

2023-09-04 16:32 UTC, greatertomi approved these changes

2023-09-04 17:45 UTC, gabriela-ponce approved these changes

2023-09-04 20:36 UTC, merged