feat(staking): show tooltip for column names in browse pools section [LW-6851]
input-output-hk/lace pull request #466
Opened 2023-08-31 07:46 UTC by xdzurman

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/browse/LW-6851?atlOrigin=eyJpIjoiNWMzNWNiNTFlMzRiNDFkMWI3YzE3NDg3ODU5YjdmNzQiLCJwIjoiaiJ9)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

According to figma - add info icon with an on-hover tooltip.

## Testing

Go to staking/browse-pools section, compare the column tooltips with Figma.

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/22454337/b619e2c6-a94b-4cea-accb-794336e994e2)
![image](https://github.com/input-output-hk/lace/assets/22454337/10bd7b26-9fc2-4d34-8c36-c00d9a11ac6b)
![image](https://github.com/input-output-hk/lace/assets/22454337/0e4bc99a-19c1-4aae-a23b-3456289c6130)

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2001/6155807699/index.html) for [3fe942fc](https://github.com/input-output-hk/lace/pull/466/commits/3fe942fc5719c18bacefca2abdd6e7c2054e9027)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 30     | 2      | 0       | 0     | 32    | ❌     |

2023-08-31 07:47 UTC, xdzurman commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/info-icon.component.svg
I really don't like adding this to the codebase for the 4th time, but there is currently no way to import it from anywhere.

2023-08-31 07:50 UTC, xdzurman commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/StakePoolTableBrowser.tsx
> +      tooltipText: t('browsePools.stakePoolTableBrowser.tableHeader.ros.tooltip'),
I don't like that translation labels live in a different file, as if this component was generic and could be used with different columns, but it can't - column names are baked in this file (`SortKey`). Ideally I'd like to see column names and column popups to be defined in the same place, but I did not want to refactor it here

2023-09-06 13:56 UTC, przemyslaw-wlodek approved these changes

2023-09-08 15:04 UTC, refi93 commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/info-icon.component.svg
actually, I think you should be able to use the `InfoCircleOutlined` icon from the `and-design` package here: https://github.com/input-output-hk/lace/pull/402/files#diff-1ec8137b4ba95e07867090dee0807af792a281ed4d1d03558257698321cdfda1R1

2023-09-08 15:13 UTC, refi93 commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/StakePoolTableBrowser.tsx
> +      tooltipText: t('browsePools.stakePoolTableBrowser.tableHeader.ros.tooltip'),
I'm checking the other place (legacy staking overview) where the translation keys are declared and there doesn't seem to be a corresponding key in the translations map, so I'm wondering if it works at all currently 🤔

https://github.com/search?q=repo%3Ainput-output-hk%2Flace%20cardano.stakePoolTableBrowser.tableHeader.cost&type=code

can be checked by importing a hw wallet/disabling multistaking in env - my guess is that just the translation key would be shown, in which case I guess it's worth fixing/refactoring it right within this PR, should be a quick fix/win after all

2023-09-08 15:26 UTC, refi93 requested changes
overall LGTM, left few minor comments to address

2023-09-11 06:46 UTC, xdzurman commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/info-icon.component.svg
I technically could, but it looks different. I preferred to satisfy the figma design

Current state:
![image](https://github.com/input-output-hk/lace/assets/22454337/01c17be2-ccd0-4e40-b3ff-2b93c2f1a6f5)

Designs:
![image](https://github.com/input-output-hk/lace/assets/22454337/32b24cb9-7d37-44a7-9f4a-d9f784404044)

Antd icon:
![image](https://github.com/input-output-hk/lace/assets/22454337/47a1e73c-a69a-49c5-9139-7071bdabb65f)

2023-09-11 07:21 UTC, xdzurman commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/StakePoolTableBrowser.tsx
> +      tooltipText: t('browsePools.stakePoolTableBrowser.tableHeader.ros.tooltip'),
Are you sure? I found this 
https://github.com/input-output-hk/lace/blob/e0f11db34af145bf90dc763b054ef52a835721b5/apps/browser-extension-wallet/src/lib/translations/en.json#L1014

2023-09-11 21:12 UTC, refi93 commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/info-icon.component.svg
I see, didn't notice this subtle difference :( nevermind then

2023-09-11 21:17 UTC, refi93 commented on packages/staking/src/features/browse-pools/stake-pools-table/StakePoolTableBrowser/StakePoolTableBrowser.tsx
> +      tooltipText: t('browsePools.stakePoolTableBrowser.tableHeader.ros.tooltip'),
you are right, sorry I assumed all translations are in a plain object (as is the case with `browsePools.stakePoolTableBrowser.tableHeader.*` translations), but apparently they can also be in a nested one 🤦

2023-09-11 21:17 UTC, refi93 approved these changes

2023-09-12 14:58 UTC, merged