chore: update ada handle copies
input-output-hk/lace pull request #479
Opened 2023-09-01 13:50 UTC by greatertomi

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-09-01 14:27 UTC, VanessaPC approved these changes
Nice!

2023-09-01 21:07 UTC, shawnbusuttil approved these changes

2023-09-04 17:20 UTC, gabriela-ponce approved these changes

2023-09-04 20:42 UTC, rhyslbw commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "banner.browserDescription": "This handle may no longer belongs to your contact {{name}}. Please, review to proceed.",
This is a grammar error. Can you point me to where this change was requested?

2023-09-04 20:56 UTC, rhyslbw requested changes

2023-09-04 20:56 UTC, rhyslbw commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "banner.browserDescription": "This handle may no longer belongs to your contact {{name}}. Please, review to proceed.",
```suggestion
      "banner.browserDescription": "This handle may no longer belong to your contact {{name}}. Please, review to proceed.",
```

This is a grammar error. @daniloprates can you approve this?

2023-09-04 20:57 UTC, daniloprates requested changes

2023-09-04 20:57 UTC, daniloprates commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "banner.browserDescription": "This handle may no longer belongs to your contact {{name}}. Please, review to proceed.",
This is wrong. It was fixed on Ditto and will soon be reflected in Figma. Let's please revert back to `belong` please 🙏

2023-09-04 21:51 UTC, rhyslbw approved these changes

2023-09-04 21:51 UTC, merged