Refactor lace to use tx builder
input-output-hk/lace pull request #48
Opened 2023-06-01 17:45 UTC by lucas-barros

# Checklist

- [ ] JIRA - LW-6508
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-02 05:44 UTC, mkazlauskas requested changes

2023-06-02 05:44 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useBuildDelegation.ts
> +        if (error instanceof InputSelectionError) {
`instanceof` won't work for errors until we do LW-6749
```suggestion
        if (typeof error === 'object' && Object.values(InputSelectionFailure).includes((error as any).failure)) {
```

2023-06-06 10:52 UTC, rhyslbw approved these changes
This all looks good to me, so happy to see this go through to regression testing

2023-06-07 19:50 UTC, mkazlauskas approved these changes
Nice work! :rocket:

2023-06-07 21:27 UTC, mchappell approved these changes

2023-06-07 22:07 UTC, merged