Feat/lw 8049 a b test pass name screen
input-output-hk/lace pull request #496
Opened 2023-09-05 18:54 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-8049](https://input-output.atlassian.net/browse/LW-8049)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR adds a component combining both password and name step on onboarding flow, this keeps the previous functionality of each component but combined into one.
Adds two new post hog events for the next click action of this component

- onboarding | new wallet | wallet name & password | next | click
- onboarding | restore wallet | wallet name & password | next | click

This component is designed to be used in the AB test, but, while we are waiting for the final implementation of Post Hog remote feature flag,  will be hidden behind an environment variable flag

## Testing

To enable this feature the environment variable `USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT` has to be set to true

## Screenshots

<img width="1425" alt="Screenshot 2023-09-05 at 15 51 40" src="https://github.com/input-output-hk/lace/assets/65184652/ce0dfaf0-04dc-457d-9e25-9b5e8eddaaff">

<img width="1425" alt="Screenshot 2023-09-05 at 15 52 09" src="https://github.com/input-output-hk/lace/assets/65184652/165b393d-e4c7-423f-a2df-1bd2973c9782">

<img width="1425" alt="Screenshot 2023-09-05 at 15 52 14" src="https://github.com/input-output-hk/lace/assets/65184652/61caae98-c199-4f99-b356-a2359f46cea7">

2023-09-06 10:54 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "secondLevelPasswordStrengthFeedback": "Weak password. Add some numbers and characters to make it stronger.“ to “Getting there! Add some symbols and numbers to make it stronger."
it seems like there are two messages in this one? Is this intentional (are we splitting them into an array or something? or just a typo)

2023-09-06 10:59 UTC, DominikGuzei commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.tsx
> +        {score >= minimumPassLevelRequired && (
Are we sure that there should not be any fade-in animation? If so, we would need to handle it over a CSS class

2023-09-06 15:49 UTC, allanleone commented
@DominikGuzei  I think adding a basic fade-in effect when an element becomes visible is a good idea. I've tried different animations for this with the prototype, but a simple fade-in still seems better than other options or just suddenly appearing.

examples:
https://github.com/input-output-hk/lace/assets/8201486/579125e4-27f4-48fe-8660-e8704256d5f9
https://github.com/input-output-hk/lace/assets/8201486/3c70738c-d437-4ba9-bbca-953c13d6550f
https://github.com/input-output-hk/lace/assets/8201486/dce35701-0547-4daf-9d8a-9dd7e7735031
https://github.com/input-output-hk/lace/assets/8201486/c6c2519c-18dc-48a8-b8f8-21520cc73cdb

2023-09-07 09:22 UTC, tommayeliog approved these changes

2023-09-07 18:34 UTC, marcin-mazurek requested changes

2023-09-07 18:34 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +const isCombinedPasswordNameStepEnabled = process.env.USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT === 'true';
I'm just wondering if we should already make the code structured in similar way to how we will the experiment mechanism (hook/async fn?), so later it's just a matter of changing one line of code :)

2023-09-07 18:34 UTC, marcin-mazurek commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.module.scss
> +@import '../../../styles/theme.scss';
Is this mostly copied from original implementation? If so, is it worth leaving a note that the duplication is on purpose since this is just an temporary experiment?
(Just thinking out loud now) Perhaps it's worth importing styles from the original implementation? Even though both approaches are hacky, at least we would have less duplication.

2023-09-07 18:34 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "confirmPasswordInputLabel": "Confirms password",
Probably a typo:
```suggestion
      "confirmPasswordInputLabel": "Confirm password",
```

2023-09-07 18:34 UTC, marcin-mazurek commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/utils.ts
> +export const getComplexityBarStateList = (
I can see some duplication between this file and `packages/core/src/ui/components/WalletSetup/WalletSetupRegisterStep.tsx` - not sure if that is intentional, perhaps we can use those utils also in the implementation you copied it from? (assuming it uses the same logic)

2023-09-07 18:34 UTC, marcin-mazurek commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.tsx
> +import React, { useMemo, useState } from 'react';
Just a question on the folder structure - I see you created a subfolder whereas other components use flat structure:

![image](https://github.com/input-output-hk/lace/assets/6684554/f3ca6557-d905-4062-ba1a-5305a7e19774)

I like subfolders much more, but I'm not sure where the name is coming from? I'd assume the folder name would be same as the main React component name - in this case `WalletSetupNamePasswordStep`

2023-09-08 18:54 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +const isCombinedPasswordNameStepEnabled = process.env.USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT === 'true';
I wouldn't do it now, since we don't have the final implementation for experiments, if we change something there, this will change as well

2023-09-08 18:55 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/utils.ts
> +export const getComplexityBarStateList = (
Yes, this is intentional, I guess in this case, we can use these in the original components, but, to be honest, I would rather not use them, since the current implementation is working properly, and I don't want to mess the thing up

2023-09-08 19:03 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.tsx
> +import React, { useMemo, useState } from 'react';
Actually, I've mixed up the names here, the name input component is call `WalletSetupRegisterStep`, so, I believe it comes from there.
change done in [99bdcde](https://github.com/input-output-hk/lace/pull/496/commits/99bdcde0ba8f4aab09d154566cb4e2f7b7bc5c7a)

2023-09-08 19:03 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/types.ts
> +export type validationErrorKeys = 'nameMaxLength';
change done in [97877af](https://github.com/input-output-hk/lace/pull/496/commits/97877afc5290e4ea86071917fd1949362511c6ed)

2023-09-08 19:04 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "confirmPasswordInputLabel": "Confirms password",
change done in [97877af](https://github.com/input-output-hk/lace/pull/496/commits/97877afc5290e4ea86071917fd1949362511c6ed)

2023-09-08 19:04 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.tsx
> +        {score >= minimumPassLevelRequired && (
animation added in [97877af](https://github.com/input-output-hk/lace/pull/496/commits/97877afc5290e4ea86071917fd1949362511c6ed)

2023-09-08 19:07 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.module.scss
> +@import '../../../styles/theme.scss';
I Left a comment for this. There are a few differences between these files, so, wouldn't mix them
done in [97877af](https://github.com/input-output-hk/lace/pull/496/commits/97877afc5290e4ea86071917fd1949362511c6ed)

2023-09-11 12:05 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "secondLevelPasswordStrengthFeedback": "Weak password. Add some numbers and characters to make it stronger.“ to “Getting there! Add some symbols and numbers to make it stronger."
@jplorek-atix are we splitting sentences ( to have an array ) or it is ok to have a long message with multiple sentences?

2023-09-11 12:07 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.tsx
> +        {score >= minimumPassLevelRequired && (
I will mark it as resolved 👍

2023-09-11 12:11 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +const isCombinedPasswordNameStepEnabled = process.env.USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT === 'true';
@jplorek-atix is this changed? If yes, please let me know in which commit 🙏

2023-09-11 12:14 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/types.ts
> +export type validationErrorKeys = 'nameMaxLength';
👍

2023-09-11 12:14 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "confirmPasswordInputLabel": "Confirms password",
👍

2023-09-11 12:17 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/utils.ts
> +export const getComplexityBarStateList = (
@jplorek-atix I agree, but please leave a comment so we are aware of potential unifying

2023-09-11 12:21 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +                setupType === 'create'
can we isolate this and other setup types as constants? e.g. `SETUP_TYPE_CREATE = 'create'`

2023-09-11 12:22 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +                  : skipTo(WalletSetupSteps.Mnemonic);
Can you isolate complex logic to helper function? It would be much easier to read it

2023-09-11 12:23 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +              }}
Same as prev comment. Question / Suggestion about constant and isolated logic

2023-09-11 12:28 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        password.length > 0
I'm not sure why is this not aligned?

2023-09-11 12:30 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        <div>
is this element necessary?

2023-09-11 12:32 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +              : undefined
is it necessary to say it is undefined? Can it be just `passwordLevelFeedback && [t('package.core.walletNameAndPasswordSetupStep.secondLevelPasswordStrengthFeedback')]` ?

2023-09-11 12:34 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +          data-testid="wallet-setup-password-step-password"
is this test id correct since the component clearly says it is a verification step?

2023-09-11 12:35 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/utils.ts
> +export const passwordLevelFeedback = 2;
maybe it would be better to have UPPER CASE here ?

2023-09-11 12:36 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/utils.ts
> +export const WALLET_NAME_INPUT_MAX_LENGTH = 30;
Can you move this to line 6 so you have all the main constants in one place?

2023-09-11 13:08 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +const isCombinedPasswordNameStepEnabled = process.env.USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT === 'true';
@tomislavhoracek Not yet, I would wait until [LW-8239](https://input-output.atlassian.net/browse/LW-8239) is fully implemented. 
For [LW-8239](https://input-output.atlassian.net/browse/LW-8239) implementation, the main idea is to follow what is implemented in https://github.com/input-output-hk/lace/pull/418, but, any change on that implementation will affect this too, So, I don't know how much time it would save us at the end

2023-09-11 13:14 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "secondLevelPasswordStrengthFeedback": "Weak password. Add some numbers and characters to make it stronger.“ to “Getting there! Add some symbols and numbers to make it stronger."
@tomislavhoracek No, the first sentence was an error, we shouldn't have had that one there, I removed it and left `Getting there! Add some symbols and numbers to make it stronger.` sentence only.

https://github.com/input-output-hk/lace/pull/496/commits/7fa2f1c1bb1ad05b3b9f4da272df04371c27b417#diff-201377fbc9d747e2af074fde5c6f613b534819613e0fedf6301af216285beb26R69

2023-09-11 13:58 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        <div>
We are doing a `flex-direction: column;` with a gap of 24px between elements, inside this element we have an `input` and `p` tag for the error message, with a gap of 4px, so, if I remove this, the gap of 24px will affect the` p` tag as well

2023-09-11 14:28 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +const isCombinedPasswordNameStepEnabled = process.env.USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT === 'true';
@jplorek-atix ok, could you add it to the TODO list of [LW-8239](https://input-output.atlassian.net/browse/LW-8239) so we have that addressed there?

2023-09-11 14:38 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        <div>
to be honest, structuring code like this is a little bit weird to me :/ 
Can you at least add a className that says, ok, this is a destructuring.... or say that it is a special wrapper and add a class?
p.s. `walletSetupNamePasswordStep` is also something that I don't understand by reading the wrapper name. Can it be more descriptive? e.g. if that is a password setup only, use e.g. `walletSetupAddPasswordStep` "Add" instead of "Name"

2023-09-11 14:41 UTC, tomislavhoracek requested changes
please take a look at the comments I left 🙏

2023-09-11 14:41 UTC, tomislavhoracek commented
@jplorek-atix please merge the latest `main` branch

2023-09-11 14:56 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/utils.ts
> +export const getComplexityBarStateList = (
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 14:57 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletRegisterStep/WalletSetupNamePasswordStep.module.scss
> +// most of these were copied from WalletSetupRegisterStep.module.scss and WalletSetupPasswordStep.module.scss, there are a few minor  difference between each other
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 14:57 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +                setupType === 'create'
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 14:58 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +                  : skipTo(WalletSetupSteps.Mnemonic);
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 14:58 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +              }}
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 14:58 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +  const isNextBtnEnabled = () => {
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 15:02 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        password.length > 0
It was the prettier auto format, not sure why it was formatting like this. I have added constants for `score >= minimumPassLevelRequired` and `password.length > 0`, so, this is more readable now
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 15:02 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +  const handleNextBtnClick = () => {
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 17:11 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        <div>
@tomislavhoracek I've restructured this component. [2258e10](https://github.com/input-output-hk/lace/pull/496/commits/2258e109bca81256a6fe66aeb0eadb10e4ab6561)

2023-09-11 17:12 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +  const handleNextBtnClick = () => {
done in [2258e10](https://github.com/input-output-hk/lace/pull/496/commits/2258e109bca81256a6fe66aeb0eadb10e4ab6561)

2023-09-11 17:12 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/utils.ts
> +export const WALLET_NAME_INPUT_MAX_LENGTH = 30;
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 17:12 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/utils.ts
> +export const passwordLevelFeedback = 2;
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 17:13 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +          data-testid="wallet-setup-password-step-password"
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-11 17:13 UTC, jplorek-atix commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +              : undefined
done in [d53717e](https://github.com/input-output-hk/lace/pull/496/commits/d53717e5d855d2a96bd7e38c86871d2039c8511c)

2023-09-12 08:21 UTC, tomislavhoracek commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "secondLevelPasswordStrengthFeedback": "Weak password. Add some numbers and characters to make it stronger.“ to “Getting there! Add some symbols and numbers to make it stronger."
@jplorek-atix but those are 2 sentences
1. Getting there! 
2.  Add some symbols and numbers to make it stronger.

2023-09-12 08:26 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        password.length > 0
👌

2023-09-12 08:27 UTC, tomislavhoracek commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +        <div>
Thanks @jplorek-atix  🎉

2023-09-12 08:31 UTC, tomislavhoracek approved these changes
@jplorek-atix Amazing stuff 💯

2023-09-12 17:06 UTC, milagi requested changes
Small comment: When you access to the 'Let's set up your new wallet' step, the prompt is set in the 2nd (password) field instead of the first field (name)

2023-09-12 17:59 UTC, jplorek-atix commented
> Small comment: When you access to the 'Let's set up your new wallet' step, the prompt is set in the 2nd (password) field instead of the first field (name)

@milagi added in [e85262c](https://github.com/input-output-hk/lace/pull/496/commits/e85262c75f791478fee280d4a97c1ba805623cb1)

2023-09-12 18:17 UTC, milagi approved these changes

2023-09-27 08:43 UTC, marcin-mazurek approved these changes

2023-09-27 10:47 UTC, merged