fix(extension): return apierror refused on window.close for cip30 requests
input-output-hk/lace pull request #524
Opened 2023-09-12 12:16 UTC by mchappell

# Checklist

- [x] JIRA - [LW-8421](https://input-output.atlassian.net/browse/LW-8421)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Add explicit eventlistener prior to `window.close` which will reject the Dapp request

## Testing

In a console window, execute the following:
`const api = await window.cardano.lace.enable();`
`const signedData = await api.signData('60d2696793b60a6e1c619dd16ff02be81e3d9ec435cfb880ac5e32b93a', 'a2354422');`

Close the second popup request to sign data via the cross icon, not via the cancel button inside the popup

Assert that an error has been explicitly thrown 

[LW-8421]: https://input-output.atlassian.net/browse/LW-8421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@dq4ajm5i5q7bz.cloudfront.net/linux/chrome/2014/6162005219/index.html) for [fc1275c6](https://github.com/input-output-hk/lace/pull/524/commits/fc1275c64a457c74f71af079d6c01643d97b98ed)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 31     | 1      | 0       | 0     | 32    | ❌     |

2023-09-12 12:53 UTC, lgobbi-atix requested changes

2023-09-12 12:53 UTC, lgobbi-atix commented on apps/browser-extension-wallet/src/features/dapp/components/ConfirmData.tsx
> +  window.addEventListener('beforeunload', cancelTransaction);
Shouldn't we also add this to `SignTransaction` and `SignData` in case the user closes the popup when entering the password?

2023-09-12 13:44 UTC, lgobbi-atix approved these changes

2023-09-29 11:32 UTC, ljagiela approved these changes

2023-10-09 14:54 UTC, merged

2023-10-19 11:10 UTC, mchappell commented
Fixes https://github.com/input-output-hk/lace/issues/60