Implement collapsible left-hand side panel
input-output-hk/lace pull request #53
Opened 2023-06-02 11:31 UTC by jplorek-atix

# Checklist

- [x] JIRA [LW-6561](https://input-output.atlassian.net/browse/LW-6561)
- [x] Screenshots added.
- [ ] Proper tests implemented

---

## Proposed solution

This PR introduces the responsiveness for the side menu on viewports smaller than 1024px

Moves all components of the left side column from the layout to a new component VerticalNavigationBar
Refactors the NetworkPill component by adding a property that allows the component to display the status on hover 

## Screenshots

<img width="807" alt="Screenshot 2023-05-18 at 14 51 19" src="https://github.com/input-output-hk/wallet-world/assets/65184652/8b2ec74d-60e8-4641-8fd0-c054509f38b4">

<img width="807" alt="Screenshot 2023-05-18 at 14 54 44" src="https://github.com/input-output-hk/wallet-world/assets/65184652/103b0571-3404-4e8a-acb3-ef1a6e33ab24">

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/394/5266107414/index.html) for [20149393](https://github.com/input-output-hk/lace/pull/53/commits/20149393c75ef3d61adc8c8d0efa1f428796dc47)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 12     | 7      | 0       | 0     | 19    | ❌     |

[LW-6561]: https://input-output.atlassian.net/browse/LW-6561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-14 10:45 UTC, DominikGuzei approved these changes
Code LGTM 🚢

2023-06-15 17:03 UTC, milagi requested changes
When width is 668px horizontal scrollbar isn't displayed. It's only displayed when it's 577px and lower for Tokens, NFTs and Activity, and when it's 810px and lower in Staking section
![image](https://github.com/input-output-hk/lace/assets/75744070/724aec39-14ec-4a9a-bbf9-90755fdf5027)

2023-06-16 13:52 UTC, milagi approved these changes

2023-06-20 08:40 UTC, marcin-mazurek approved these changes

2023-06-20 08:42 UTC, bslabiak approved these changes

2023-06-20 14:02 UTC, bslabiak commented
I am able to reproduce the issue with staking after recent changes:
![image](https://github.com/input-output-hk/lace/assets/112852128/85cb190c-92b3-4e62-be24-9d84bf310570)

2023-06-21 12:16 UTC, bslabiak approved these changes

2023-06-21 16:58 UTC, merged