feat(staking): LW-7966 drift warning (WIP)
input-output-hk/lace pull request #533
Opened 2023-09-14 14:27 UTC by refi93

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-09-21 11:49 UTC, refi93 commented on packages/staking/src/features/store/types.ts
> +        basedOnCurrentPortfolio: false;
I considered having an optional `currentPortfolioRef: {percentage: Wallet.Percent}` property instead, but I found that to be more fragile as it's pretty easy to miss the removal/addition of such property when "detaching/ejecting" the portfolio draft from the current portfolio when user first edits it, whereas the boolean flag IMHO somewhat forces the writer of the code to "stop" and think what to set it to and configure the `DraftPortfolio` appropriately

2023-09-21 21:43 UTC, refi93 commented on packages/staking/tsconfig.json
> +      "@assets/*": ["assets/*"]
this is crucial to finally be able to use assets "hidden" within the UI package which weren't accessible so far. This means we are able to use them without having to duplicate them which I leveraged e.g. for info-icon.component.svg in our banner

2023-09-21 21:45 UTC, refi93 commented on packages/ui/src/design-system/control-buttons/control-button.css.ts
> +    cursor: 'pointer',
not really related to the task itself, fixes the "Manage" button that until now didn't have the right cursor type on hover (default cursor remained)

2023-09-21 22:02 UTC, refi93 commented on packages/staking/src/features/overview/StakingNotificationBanner.tsx
> +          customIcon={<BellIcon className={styles.bannerInfoIcon} />}
note that in Figma the icon is aligned to the top in the popup view, but in the codebase are already other popup-view banners aligning the icon to the center so I decided to remain consistent with that -  for context see my comment raised in the figma design for the popup view

2023-09-22 07:58 UTC, refi93 commented on packages/staking/src/features/overview/OverviewPopup.tsx
> +            onPortfolioDriftedNotificationClick={expandStakingView}
as per the original task description this should have led to the management drawer but this would be a more complex change because it would require propagating a new kind of message between the popup view and expanded view and parsing it on the other end, made this redirection to the management drawer from popup view into a follow up task (LW-8543)

2023-09-22 08:00 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +const ejectDraftFromCurrentPortfolio = (
this is the function responsible from removing reference to the original "current portfolio" (i.e. the on-chain percentages), which as per the current logic is supposed to be triggered (manually) anytime we mutate the initial state of the draft portfolio, based off the current portfolio (it's idempontent, so no issue running this function also on already "ejected" drafts)

2023-09-25 07:39 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/atomicStateMutators.ts
> +const ejectDraftFromCurrentPortfolio = (
this is the function responsible from removing reference to the original "current portfolio" (i.e. the on-chain percentages), which as per the current logic is supposed to be triggered anytime we mutate the initial state of the draft portfolio, based off the current portfolio (it's idempontent, so no issue running this function also on already "ejected" drafts)

2023-09-25 07:41 UTC, refi93 commented on packages/staking/src/features/overview/helpers/getPortfolioTotalPercentageDrift.ts
> +    })
formula from the task description for reference:

```
Sum (n from 1 to Number_of_userPools) of Pool_N original % - Pool_N actual %)
```

of course, the differences need to all be made positive (i.e. use `Math.abs()`), otherwise they would even out

2023-09-25 07:59 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/types.ts
> +    | {
I considered having an optional currentPortfolioRef: {percentage: Wallet.Percent} property instead, but IMHO that would be more fragile as it IMHO makes it easier to miss the removal/addition of such property when "transforming" or "ejecting" (upon first editation) the portfolio draft from the current portfolio, whereas the basedOnCurrentPortfolio boolean flag IMHO somewhat forces the writer of the code to "stop" and think what to set it to and configure the DraftPortfolio appropriately

2023-09-25 09:48 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/types.ts
> +  percentage: Wallet.Percent;
it's a fair point that it seems odd that here we express the target as a `targetWeight` and the current portfolio on-chain state as `percentages` - for now I deliberately chose not to try to unify these because for representing the target portfolio on-chain, the percentages don't allow for an unambiguous/lossless representation of them and I'd rather leave such unification (if at all needed) for later - I guess the path would become clear as soon as SDK is updated to persist/return the target portfolio and sliders are implemented in the management UI.

What I mean by "lossless" -> if e.g. we represent the target weight in the state as percentage and do some arithmetics (adding, multiplying, ...), we may end up having a target percentage `0.33......01` (because JS floats) and it may not be correctly translated to a weight in the (re)balancing tx/portfolio - the drift would be very slight, but I'd rather steer clear from any numerical instability if avoidable as it introduces its own class of edge-cases that are very easy to forget

On the other hand, we may choose to represent "percentages" as integers from 0 to 100, but that would lead to issues as soon as somebody chose to increase the precision shown in the UI (need to scale up all values), moreover it would not be consistent with other instances of percentages in the code where these are already encoded as decimal numbers from 0 to 1

So all in all, to avoid this "rabbit hole" I rather avoided having a single unit to represent target vs current distribution of the portfolio, and postpone that decision only after we implement more features/sdk implementation of portfolio persistence is available which should be soon anyway. The conversions are simple to handle, thinking about/dealing with the loss of precision is IMHO harder in general

2023-09-25 10:11 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/types.ts
>    displayData: Wallet.util.StakePool & {
@szymonmaslowski made the follow up refactoring issue to de-ducplicate the structure of `Current/DraftPortfolioStakePool` structures, as discussed offline: https://input-output.atlassian.net/browse/LW-8580

2023-09-25 12:30 UTC, refi93 commented on packages/staking/src/features/drawer/PoolDetailsCard.tsx
> +              stakePercentage: formatPercentages(percentage, { decimalPlaces: 0, rounding: 'down' }),
let's round up - should solve at least one class of edge-cases (e.g. `10.6 | 89.4`)

2023-09-26 11:45 UTC, szymonmaslowski approved these changes
Great improvements!

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/overview/OverviewPopup.tsx
> +            onPortfolioDriftedNotificationClick={expandStakingView}
Was the redirection from popup to manage drawer an intention of the original task? I can see in the ACs that it is saying about redirecting to the browse pools, however that is incorrect I guess. IMO it should be Overview page instead, as this is about the current portfolio, so your implementation actually achieves the goal, so in this case the follow up task is probably not needed. Thought, please double check that with Fernando 😉

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/overview/helpers/getCurrentStakingNotification.ts
> +import { CurrentPortfolioStakePool } from 'features/store';
Please move this file along with the `StakingNotificationBanner` component to the dedicated `overview/StakingNotificationBanner` dir 🙏 

@edit: Actually please move all of the banner related functions to that dedicated dir 🙏

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/overview/helpers/getCurrentStakingNotification.ts
> +import { CurrentPortfolioStakePool } from 'features/store';
Sorry, but IMO we shouldn't have aliases. I would preffer to have a relative paths ;)

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/overview/helpers/getCurrentStakingNotification.ts
> +import type { AssetActivityListProps } from '@lace/core';
This should got to the top of the imports list according to our eslint config. I wonder why it was not fixed automatically... 🤔

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/overview/types.ts
> +export type StakingNotificationType = 'pendingFirstDelegation' | 'pendingPoolMigration' | 'portfolioDrifted';
This one also should be moved to the banner dir IMO

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/types.ts
> +  id: Wallet.Cardano.Cip17Pool['id'];
Please consider also adding a `stakePool` property here. Maybe it will enable us to simplify implementation. For the first glance it seems better if current and draft types were more symetric

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +import type { ExecuteCommand, Handler } from './stateMachine/types';
```suggestion
import type { ExecuteCommand, Handler } from './stateMachine';
```

However, I am curious was there somethis wrong with importing those types without the `type` import?

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/src/features/store/__snapshots__/delegationPortfolio.test.ts.snap
> +    "percentage": 0.33,
It looks like this file is no longer used. Could you please remove it?

2023-09-26 11:45 UTC, szymonmaslowski commented on packages/staking/tsconfig.json
> +      "@assets/*": ["assets/*"]
I think it would be more correct to expose those icons instead of implicitly accessing them with ts magic (if I correctly understand the way it works). Sorry, but I am not a fan of aliases and would prefer to avoid them. Let's have a offline discussion about this change.

2023-09-26 11:46 UTC, szymonmaslowski requested changes
Sorry, a missclick. I wanted to request changes instead of approving right away 😆

2023-09-26 12:14 UTC, refi93 commented on packages/staking/src/features/overview/helpers/getCurrentStakingNotification.ts
> +import type { AssetActivityListProps } from '@lace/core';
actually, as soon as I tried to put the type imports at the top, eslint warned me about an incorrect import order, I guess `features/store` is considered to be "external" by the eslint rule. Nevertheless, in this specific case a simple "fix" is to make the CurrentPortfolioStakePool import a type import

2023-09-26 12:20 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +import type { ExecuteCommand, Handler } from './stateMachine/types';
in this specific case there probably isn't much of a benefit, in general it helps the compiler as it is obvious such imports can be dropped, also runtime cyclic dependencies can be avoided this way, especially if some file with type definitions, but used solely for types happens to have a non-type import for whatever reason.

But I agree in this specific case it makes not that much sense, it was rather my "reflex" to isolate type imports, will merge it into a single one

https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md

2023-09-26 13:27 UTC, refi93 commented on packages/staking/src/features/overview/helpers/getCurrentStakingNotification.ts
> +import { CurrentPortfolioStakePool } from 'features/store';
I see, VSCode intellisense actually suggested me that alias 🤔 do you perhaps know of some eslint rule/setting to disable these aliases, if we don't want to use them at all?

2023-09-26 13:47 UTC, refi93 commented on packages/common/src/ui/components/Banner/Banner.tsx
> +        {!!onBannerClick && !onButtonClick && (
IMHO the banner and button click are two mutually exclusive behaviors and a banner having both would not be good UX, for which we moreover don't have designs. So actually I'd rather go with a discriminating union to prevent accidentally combining both callbacks which doesn't have well defined behavior/UX as of now

2023-09-26 14:17 UTC, refi93 commented
> Was the redirection from popup to manage drawer an intention of the original task? I can see in the ACs that it is saying about redirecting to the browse pools, however that is incorrect I guess. IMO it should be Overview page instead, as this is about the current portfolio, so your implementation actually achieves the goal, so in this case the follow up task is probably not needed. Thought, please double check that with Fernando 😉

The task originally stated that both for the expanded and popup view the "drift warning" banner should lead to the management drawer. After I raised the need for implementing additional messaging for the popup view with Fernando, we agreed to update the ACs to take the user to the expanded view and I'd say "Browse pools" was introduced there by mistake, should have been Overview actually - I'm clarifying this with him right now

Still, I made a low-priority follow-up task to take the user straight to the management drawer as I believe that to be superior UX, just not worth the additional effort right now

2023-09-26 14:30 UTC, refi93 commented on packages/staking/tsconfig.json
> +      "@assets/*": ["assets/*"]
sure, let's discuss it - I dropped the alias, though I'm curious - what issues do you see with aliases? At first sight, I'd say it makes imports neater and somewhat prevents incorrect imports, especially if two files with the same name happen to be present in the project, but TBH, I haven't used them yet, so I'm probably just not aware of the caveats :)

2023-09-26 14:39 UTC, refi93 commented
@szymonmaslowski ACs updated already to state that Popup view banner should take the user to "Overview" 👍 thanks for the catch

2023-09-27 09:37 UTC, szymonmaslowski approved these changes

2023-09-27 11:39 UTC, oldGreg5 approved these changes

2023-09-27 12:17 UTC, merged