test(extension): e2e - add tests for ada handles on wallet address page
input-output-hk/lace pull request #536
Opened 2023-09-15 10:50 UTC by ljagiela

2023-09-15 10:59 UTC, bslabiak approved these changes

2023-09-15 11:52 UTC, wklos-iohk requested changes

2023-09-15 11:52 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/walletAddressPageAssert.ts
> +    await expect(names[0]).equals(Asset.ADA_HANDLE_1.name);
redundant `await` keyword

2023-09-15 11:52 UTC, wklos-iohk commented on packages/e2e-tests/src/data/Asset.ts
> +  public static readonly ADA_HANDLE_2 = new Asset('$t_h_1', '$t_h_1');
Most of those entries seem to be unused

2023-09-15 11:52 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/walletAddressPage.ts
> +    await addressCard.moveTo();
`moveTo` does the scrolling as well if needed, see https://webdriver.io/docs/api/element/moveTo/

2023-09-15 11:52 UTC, wklos-iohk commented on packages/e2e-tests/src/features/e2e/SendTransactionSimpleExtendedE2E.feature
> +    And I click "Copy" button on "Wallet Address" page for default wallet address
step not found

2023-09-15 11:52 UTC, wklos-iohk commented on packages/e2e-tests/src/features/e2e/SendTransactionSimplePopupE2E.feature
> +    And I click "Copy" button on "Wallet Address" page for default wallet address
step not found

2023-09-15 11:52 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/waletAddressPageSteps.ts
> +  await walletAddressPage.addressCard.moveTo();
moveTo does the scrolling as well if needed, see https://webdriver.io/docs/api/element/moveTo/

2023-09-15 13:52 UTC, ljagiela commented on packages/e2e-tests/src/data/Asset.ts
> +  public static readonly ADA_HANDLE_2 = new Asset('$t_h_1', '$t_h_1');
I'd leave it as is for future tests and for others to know that those assets are available.

2023-09-15 13:52 UTC, ljagiela commented on packages/e2e-tests/src/elements/walletAddressPage.ts
> +    await addressCard.moveTo();
It does not :) At least in practise. When I tried without scroll to WDIO was trying to moveTo to invisible element (below scroll). Tests were failing.

2023-09-15 13:53 UTC, ljagiela commented on packages/e2e-tests/src/features/e2e/SendTransactionSimpleExtendedE2E.feature
> +    And I click "Copy" button on "Wallet Address" page for default wallet address
fixed, nice catch

2023-09-15 13:53 UTC, ljagiela commented on packages/e2e-tests/src/features/e2e/SendTransactionSimplePopupE2E.feature
> +    And I click "Copy" button on "Wallet Address" page for default wallet address
fixed, nice catch

2023-09-15 13:53 UTC, ljagiela commented on packages/e2e-tests/src/steps/waletAddressPageSteps.ts
> +  await walletAddressPage.addressCard.moveTo();
see my comment above

2023-09-18 08:39 UTC, wklos-iohk approved these changes

2023-09-18 10:32 UTC, merged