Feat/lw 8355 post hog experiments implementation
input-output-hk/lace pull request #537
Opened 2023-09-15 13:17 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR implements Post Hog experiments provider
Refactors Post Hog client

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-09-19 14:45 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +  const [experimentsConfigStatus, setExperimentsConfigStatus] = useState(ExperimentsConfigStatus.IDLE);
is `useState` automatically typed to `ExperimentsConfigStatus` like this?

2023-09-19 14:49 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.test.ts
> +    await waitFor(() => expect(client).toBeDefined());
Why is this required? The constructor of `PostHogClient` cannot be async, right?

2023-09-19 15:11 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +                posthog.featureFlags.override(backgroundStorage?.experimentsConfiguration || fallbackConfiguration);
Let's use the `??` operator instead of `||` here

2023-09-19 15:14 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    return this.userIdService.userTrackingDetails$.subscribe(async () => {
This is a bit confusing due to the naming "tracking details" (although it's just the tracking type) – that's another reason to rename the observable to something like `userTrackingType$`

2023-09-19 15:17 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    if (!variant || typeof variant === 'boolean') {
can you elaborate on the boolean case? What about the difference between `true` and `false`? This would always return the default variant now, right?

2023-09-19 15:20 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClientInstance.ts
> +    if (this.prototype.postHogClientInstance || !POSTHOG_ENABLED) return this.prototype.postHogClientInstance;
Why use `prototype` here, it's a standard static class property, right?

2023-09-19 15:23 UTC, DominikGuzei approved these changes
Great work 🎉 I left a few comments and suggestions

2023-09-20 17:26 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  public userTrackingDetails$ = new Subject<{ trackingType: UserTrackingType }>();
done in [d2be57c](https://github.com/input-output-hk/lace/pull/537/commits/d2be57c201dd916ce5d399d1be82f610cbf59707)

2023-09-20 17:28 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +  const [experimentsConfigStatus, setExperimentsConfigStatus] = useState(ExperimentsConfigStatus.IDLE);
yes, I've checked this again and it is automatically typed

2023-09-20 17:29 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.test.ts
> +    await waitFor(() => expect(client).toBeDefined());
I have this in the constructor https://github.com/input-output-hk/lace/pull/537/files#diff-dd5bbd0987ed12222b056f1abb147fddc8aa189ba85af71fa31b39e9602ea9f5R48 
so, for this assertion `expect(posthog.init).toHaveBeenCalledWith` I need to wait until that promise resolve and `posthog.init` is called

2023-09-20 17:31 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +                posthog.featureFlags.override(backgroundStorage?.experimentsConfiguration || fallbackConfiguration);
In this case I want to check for falsy values, not just null or undefined

2023-09-20 17:31 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    return this.userIdService.userTrackingDetails$.subscribe(async () => {
done in [d2be57c](https://github.com/input-output-hk/lace/pull/537/commits/d2be57c201dd916ce5d399d1be82f610cbf59707)

2023-09-20 18:18 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClientInstance.ts
> +  static createInstance(
yes, you are right
done in [84b5ec7](https://github.com/input-output-hk/lace/pull/537/commits/84b5ec7ff69f12f361dd4f4ec209917f7d9c161a)

2023-09-20 18:19 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClientInstance.ts
> +    if (this.prototype.postHogClientInstance || !POSTHOG_ENABLED) return this.prototype.postHogClientInstance;
I didn't make it a static property, so, I wasn't able to access it, I've changed this to static in [84b5ec7](https://github.com/input-output-hk/lace/pull/537/commits/84b5ec7ff69f12f361dd4f4ec209917f7d9c161a)

2023-09-21 12:02 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.test.ts
> +      const mockedPostHogClient = (PostHogClient as any).mock.instances[0];
why `any` here?

2023-09-21 15:51 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.test.ts
> +      const mockedPostHogClient = (PostHogClient as any).mock.instances[0];
When I added the static properties to `PostHogClient`, typescript started to complain about this

2023-09-29 12:40 UTC, marcin-mazurek requested changes
Well done :rocket: I a pretty big PR, so I left a bunch of comments, but they are generally minor.

2023-09-29 12:40 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +  }, []);
Worth specifying `postHogClient` as a dependency, just in case?

2023-09-29 12:40 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
Worth specifying `postHogClient` as a dependency, just in case?

2023-09-29 12:40 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    private backgroundServiceUtils: {
Can we reuse any existing interface here? Potentially with `Partial<T>` if required?

2023-09-29 12:40 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    this.hasPostHogInitialized$ = new Subject();
Similar comment as earlier, just checking if we shouldn't use BehaviorSubject instead?

2023-09-29 12:40 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/context.tsx
> +// do we move it to PostHogClientInstance?
We need to make a call I presume. And I think leaving as is and injecting it as a dependency is making it a bit cleaner and easier to test, and personally would just drop the comment :)

2023-09-29 14:25 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts
> +  [ExperimentName.COMBINED_PASSWORD_NAME_COMPONENT]: 'control'
Done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:27 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/config.ts
> +    variants: ['control', 'name-password-component'],
I agree, I wasn't sure about about the variant name
Done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:32 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +      this.userTrackingType = trackingType;
The change was made in the [userIdService.ts](https://github.com/input-output-hk/lace/pull/537#diff-3d58b25dee1636c71588ad49e95356cc6bd9c53bc8ed7137515d375b471040ea) file not in this one

2023-09-29 14:33 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx
> +        postHogClient,
We can add it to the dependency array, `postHogClient` should not change
Done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:35 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +  const experimentVariantByKey = useCallback(
I used `getExperimentVariant`
Done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:35 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +  const overrideExperimentVariant = (flags: Record<string, string | boolean>) => {
Done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:35 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +  static createInstance(
Done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:36 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    // create post hog instance once. If post hog is disabled we just return an empty client
Removed in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:43 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/context.tsx
> +    // we have two options here, we keep the memoization with PostHogClientInstance or
I would leave `currentChain` as a dependency since we need it to initialize the client with the correct token.
After initializing the client, `AnalyticsTracker` is the one calling `PostHogClient.setChain` to update the chain

2023-09-29 14:46 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/types.ts
> +export enum ExperimentsConfigStatus {
We can change this, but, what would be the correct naming convention?
There is a mix in every place of the app, some enums are using PascalCase, other are using UpperCase + SnakeCase, also I found one in lowercase
This might be something to raise as a tech debt, and also have some guidelines for this

2023-09-29 14:46 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +  }, []);
done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:46 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/context.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:47 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    private backgroundServiceUtils: {
done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:47 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    this.hasPostHogInitialized$ = new Subject();
done in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 14:47 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/context.tsx
> +// do we move it to PostHogClientInstance?
Removed in [74238a6](https://github.com/input-output-hk/lace/pull/537/commits/74238a6b802dad977e1d4d2cda8fdeeefa933849)

2023-09-29 17:14 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    return this.userIdService.userTrackingType$.subscribe(async (trackingType) => {
Done in [3f15746](https://github.com/input-output-hk/lace/pull/537/commits/3f15746acd22827aab514e4d9dbd28c16d0e8d06)

2023-09-29 17:58 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/context.tsx
> +    // we have two options here, we keep the memoization with PostHogClientInstance or
But we have `currentChain` as a dependency of `useMemo`, so I think `PostHogClient.getInstance()` will be called anyway when network changes. Is it safe to do it?

2023-09-29 17:58 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    private backgroundServiceUtils: {
Sorry, I actually wanted to say `Pick<T>` where you specify keys of given object that are required. But it's fine we can change it next time.

2023-09-29 17:58 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/PostHogClientProvider/client/PostHogClient.ts
> +    return this.userIdService.userTrackingType$.subscribe(async (trackingType) => {
Excellent :)

2023-09-29 17:59 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/ExperimentsProvider/types.ts
> +export enum ExperimentsConfigStatus {
OK, let's skip that for now

2023-09-29 18:40 UTC, marcin-mazurek approved these changes

2023-10-06 14:53 UTC, bslabiak approved these changes

2023-10-09 12:17 UTC, merged