Staking portfolio store state machine POC
input-output-hk/lace pull request #539
Opened 2023-09-18 09:27 UTC by szymonmaslowski

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-09-18 10:26 UTC, danielmain reviewed
Just left some non-blocking comments

2023-09-18 10:26 UTC, danielmain commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  selectPool: ({ pool, state }: { pool: DraftPortfolioStakePool; state: State }) => {
I would not return anything because the function is returning `void`

So I would push only if `!selectionsFull && !alreadySelected`

2023-09-18 10:26 UTC, danielmain commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +    state.mode = targetMode;
Could we keep the helpers pure? And let the `executeCommand` modify the state?

2023-09-18 16:26 UTC, szymonmaslowski commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  selectPool: ({ pool, state }: { pool: DraftPortfolioStakePool; state: State }) => {
I guess current implementation is the same. Just a bare return statement is like exiting a function with returning nothing, isn't it?

I considered doing like you suggested in case of potential readability improvement but actually IMO having a condition `if (selectionsFull || alreadySelected)` is easier to reason about than `if (!selectionsFull && !alreadySelected)` so in the end current implementation is simpler IMO. I am eager to change it though if you thing otherwise 😉

2023-09-18 16:56 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +enum DrawerManagementSection {
I'd consider naming this "step" instead to make the sequentiality of these obvious to the reader at first sight

2023-09-18 17:06 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +}
I'd consider coupling the commands with the expected data and making it a union of objects, otherwise it gets pretty tricky for the reader to understand what are the commands parametrized by which I believe is important to get the bigger picture

```suggestion
type DrawerPreferencesCommand = {
  name: 'UpdateWeight',
  params: { weight: number }
} | ...
```

I believe this should also make it pretty straightforward to come up with the "command" callback signature below

```
// WIP: trying to match command to its corresponding data/payload

```

2023-09-18 17:28 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +enum Mode {
I'd consider renaming `Mode -> Section` to `Flow -> Step` which would imho be more descriptive to the reader at first sight, if I understood correctly what we are trying to capture here -> "Multistep forms, with the special case of single-step "forms" with no actions"

2023-09-18 17:31 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +type Command = OverviewCommand | BrowsePoolsCommand | PoolDetailsCommand | DrawerPreferencesCommand;
I'd consider making this an interface and be explicit in the commands that these are implementing this interface, which would then have the benefit of ensuring consistency of the structure and should in theoery allow even for extracting the individual Commands into separate files and generalize the handler in a way that adding a new Command wouldn't force the generic logic to be updated

```suggestion
interface Command = { name: string, params: unknown };
```

2023-09-18 22:01 UTC, szymonmaslowski commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +enum Mode {
Totally agree 👍

2023-09-19 07:27 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +type Command = OverviewCommand | BrowsePoolsCommand | PoolDetailsCommand | DrawerPreferencesCommand;
note, actually an ordinary `type` should do, an interface may mislead the reader into thinking that classes are involved which isn't the case

2023-09-19 07:43 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  draftPortfolio: DraftPortfolioStakePool[];
Could you clarify what's the difference between the "draft portfolio" and "selection"? From this file alone/code I briefly looked up it wasn't obvious to me and I'm wondering whether these couldn't somehow be merged or at least their relation be made clearer by some more descriptive name

2023-09-19 07:51 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +type DataOfCommand<C extends Command> = C extends OverviewCommand.ShowDetails
I'd consider making a similar `SectionOfMode` (`StepOfFlow`) type and leverage it in the state to ensure consistency between the Flow and Step in the state which I'd find valuable not only from readability perspective but also as one more safeguard against bugs

2023-09-19 09:11 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  draftPortfolio: DraftPortfolioStakePool[];
I see pretty much the same question was answered on Slack, pasting your answer here @szymonmaslowski 

> draftPortfolio is there because we have two different flows (current pools management and new portfolio creation) used by the same UI. When we initiate one of those flows we copy either currentPortfolio or selections to the draftPortfolio and the UI (drawer) reads from single sorce. This also allows us to have a copy of the original state (currentPortfolio or selections) so we can modify the copy preserving the original state untouched. Consider the scenario: we have some selections but instead of submitting them we go to overview and click manage button so we enter the management of the current portfolio but thanks to copying the currentPortfolio to draft we preserve selections untouched, so user can cancel managemet of current portfolio and continue with selections instead.

2023-09-19 09:21 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  draftPortfolio: DraftPortfolioStakePool[];
what would perhaps help me get this nuance at first sight would be if `selections` was called `browsePoolsSelections`

2023-09-19 09:59 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +}
Shouldn't this be a simple type? & Nit: please name enum key/value with same casing `detail = 'detail'` for consistency and to allow easy "mirror-like" access to the value (which usually helps in type-guards) etc.

2023-09-19 10:32 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  viewedStakePool?: Wallet.Cardano.StakePool;
I feel weird about having implicit payloads for some of the Actions/Commands. Here it's purely `payload` of a `BrowsePoolsCommand.ShowDetails` but on the other hand e.g. `selections` and `draftPoftfolio` are the payloads of other commands. Maybe it's okay but I wanted to say if out loud so we can brainstorm it.

I think staying with this approach but introducing change that @refi93 and I proposed [here](https://github.com/input-output-hk/lace/pull/539/files#r1329889177) we can have something like `viewedStakePool?: BrowsePoolsCommand.ShowDetails.payload`

2023-09-19 10:37 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +    }) => Promise<void>;
Can this be also a command with payload?

Then we can have instead of `mutators` -> `actions` and everything is cleaner.

If we still want to separate "flows" from this setter then let's rename `command` as @refi93 proposed.

2023-09-19 10:41 UTC, szymonmaslowski commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  draftPortfolio: DraftPortfolioStakePool[];
How about `selectedPortfolio` to have consistency with other two properties?

2023-09-19 10:46 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +    handlerBody(params);
A lot of these types will be removed/simplified if we introduce other proposed changes. So I'm not digging into it right now.

2023-09-19 10:51 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +        params.command as OverviewCommand,
Can we please utilise some of the proposed libraries e.g. for the pattern matching or state machines? I know it's a lot of great work but in general I feel bad that we are reinventing the wheel and it's not fully type-safe etc.

I feel that our own abstraction may not be future-proof.

2023-09-21 21:33 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  | CommandCommonPreferencesStepUpdateWeight;
did I understand correctly that this `CommandCommonPreferencesStepUpdateWeight` command is a preparation for the introduction of sliders and currently it isn't really used, or does it already have a purpose?

2023-09-21 21:58 UTC, refi93 commented
"build staking center" job is failing in CI with some TS errors, needs to be fixed before merging

![Screenshot 2023-09-21 at 23 57 58](https://github.com/input-output-hk/lace/assets/4980147/6380ed53-991e-407f-a836-ec2e1f49b43f)

2023-09-22 08:17 UTC, refi93 commented on packages/staking/src/features/store/types.ts
I'd consider keeping a separate file for types, at least the ones not directly related to useDelegationPortfolioStore, such as `AdaSymbol`, `DraftPortfolioStakePool` / `CurrentPortdolioStakePool` - decouples the hook from more general types and another benefit of a separate file for types is prevention of potential runtime/compilation issues with cyclic imports because `type` imports are excluded from the built js

2023-09-22 09:37 UTC, szymonmaslowski commented on packages/staking/src/features/store/types.ts
Yep, we need to have a discussion anyway about structuring this code. I would even have a few files just for types like having commands separately for example.

2023-09-22 09:38 UTC, mrcnk requested changes
Great job, just please make sure all the commented out code sections are there to be left or cleaned up

2023-09-22 09:38 UTC, mrcnk commented on packages/common/src/ui/lib/__tests__/format-number.test.ts
> +    expect(getNumberWithUnit('10235000000000000')).toEqual({ number: '10.24', unit: 'Q' });
I think this is precisely what Intl.NumberFormat is supposed to do 🤔 do we know why we created whole custom formatter (not i18n ready) for that matter? (what a rhyme lol)

2023-09-22 09:38 UTC, mrcnk commented on packages/staking/src/features/browse-pools/BrowsePools.tsx
> +  // const {
Is it left intentionally or should it be removed?

2023-09-22 09:38 UTC, mrcnk commented on packages/staking/src/features/browse-pools/PortfolioBar.tsx
> +          onClick={() => portfolioMutators.executeCommand({ type: 'ClearSelections' })}
❤️

2023-09-22 09:39 UTC, szymonmaslowski commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  | CommandCommonPreferencesStepUpdateWeight;
I removed it actually. It was not used currently. Let's introduce it back once we have a sliders ;)

2023-09-22 09:41 UTC, szymonmaslowski commented on packages/staking/src/features/browse-pools/BrowsePools.tsx
> +  // const {
We realized that whole of this commented code is related to the hardware wallets. We decided to comment it out but maybe we should just remove it for now and re-introduce once we are ready for hardware wallets. We ignored the HW implementation in the PR as anyway we are not able to check if it would work correctly.

2023-09-22 10:22 UTC, refi93 commented on packages/common/src/ui/lib/__tests__/format-number.test.ts
> +    expect(getNumberWithUnit('10235000000000000')).toEqual({ number: '10.24', unit: 'Q' });
Intl.NumberFormat afaik works with native JS numbers which however lose precision beyond ~2^53 which is less than some token amounts may be, so I guess that's the main reason for such custom utility function

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

2023-09-22 12:53 UTC, refi93 commented on packages/staking/src/features/store/useDelegationPortfolioStore.ts
> +  cardanoCoinSymbol: 'ADA',
IMHO the cardano coins symbol shouldn't be part of the drawer state nor the "display data" of stakepools, I see that rather as a global context that should rather be retrieved only when actualy rendering ADA values in components. Not worth it changing this now, but if you agree, I'd suggest making it a follow-up refactoring task

2023-09-22 13:37 UTC, refi93 approved these changes

2023-09-22 17:14 UTC, przemyslaw-wlodek approved these changes
🚀 💜 🚀

2023-09-23 09:10 UTC, mrcnk approved these changes

2023-09-23 09:10 UTC, merged