test(maintenance): maintenance 18 sep 2
input-output-hk/lace pull request #546
Opened 2023-09-18 15:35 UTC by bslabiak

Improvement for Dapps test stability

2023-09-19 07:51 UTC, wklos-iohk requested changes

2023-09-19 07:51 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/dAppConnectorSteps.ts
> +  await browser.pause(500);
Could you please consider replacing that pause with waiting mechanism for a button inside `clickButtonInDAppAuthorizationModal` method?

2023-09-19 07:51 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/dAppConnectorSteps.ts
> +  await browser.waitUntil(
In my view this should be split into 2 parts: switch-case with clicking on a proper button and then `waitUntil` for handles.

2023-09-19 07:51 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/dAppConnectorSteps.ts
> +          break;
I'd suggest to replace `break` keyword  under `default` section with throwing and error/exception to indicate that unexpected value has been passed.

2023-09-19 08:16 UTC, bslabiak commented on packages/e2e-tests/src/steps/dAppConnectorSteps.ts
> +  await browser.pause(500);
I will move pasue inside, there is waiting mechanizm which unforutanlety not always stable.

2023-09-19 08:18 UTC, bslabiak commented on packages/e2e-tests/src/steps/dAppConnectorSteps.ts
> +  await browser.waitUntil(
Could you please elaborate more? I merged it because there is an issue. Inside Dapp when user click "Run" button does not always trigger Dapp Modal (that was causing this instability in this test, always failing as smoke/it is also reproducable as manual execution). I am using wait until as "retry" for clicking and checking the handles

2023-09-19 12:02 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/dAppConnectorSteps.ts
> +  await browser.waitUntil(
In such case I'd extract switch-case part into another method and invoke it here.

2023-09-19 16:05 UTC, ljagiela approved these changes

2023-09-20 10:13 UTC, wklos-iohk approved these changes

2023-09-20 10:13 UTC, merged