test(extension): lw-8420 trezor emulator automation
input-output-hk/lace pull request #551
Opened 2023-09-20 08:09 UTC by bslabiak

# Checklist

- [ ] JIRA - \<[link](https://input-output.atlassian.net/browse/LW-8420)>

2023-09-20 10:03 UTC, DominikGuzei approved these changes
Code LGTM 👍

2023-10-30 15:27 UTC, wklos-iohk requested changes

2023-10-30 15:27 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/trezorConnectPage.ts
> +  private EXPORT_BUTTON = "[id='container'] .confirm";
I'd suggest replacing single quotes with double quotes and vice versa in this line to keep consistency. Expected: `'[id="container"] .confirm'`

2023-10-30 15:27 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/trezorConnectPage.ts
> +  }
Please add empty line between each element definition

2023-10-30 15:27 UTC, wklos-iohk commented on packages/e2e-tests/src/features/trezor/Trezor.feature
> +    And I click trezor wallet icon
I'd suggest to replace `trezor` with `Trezor`

2023-10-30 15:27 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/commonSteps.ts
> +  await browser.pause(4000);
This would affect multiple other scenarios which are using this particular step. Please check if this can be handled more gracefully.

2023-10-30 15:27 UTC, wklos-iohk commented on packages/e2e-tests/src/utils/trezorEmulatorApiClient.ts
> +import fetch from 'node-fetch';
NodeJS 18 has internal `fetch` method already, hence we don't need external one.

`fetch(url, {method: "POST"})` should work fine.

2023-10-30 15:27 UTC, wklos-iohk commented on packages/e2e-tests/src/utils/trezorEmulatorApiClient.ts
> +    response.status === 200
it might be replaced with `response.ok` which returns `true` if status is in range 200-299

2023-10-30 15:27 UTC, wklos-iohk commented on packages/e2e-tests/wdio.conf.chrome.ts
> -          '--disable-web-security',
what is the reason behind this property being removed?

2023-10-31 15:16 UTC, ljagiela requested changes

2023-10-31 15:16 UTC, ljagiela commented on packages/e2e-tests/src/steps/onboardingSteps.ts
> +      await commonOnboardingElements.nextButton.waitForClickable();
Please create a dedicated method for click in commonOnboardingElements which contains both of those actions (wait + click) and use it here.

2023-10-31 15:16 UTC, ljagiela commented on packages/e2e-tests/src/steps/trezorConnetSteps.ts
> +  await TrezorConnectPage.analyticsToggleButton.waitForClickable();
as per my previous comment (dedicated click methoda in TrezorConnectPage).

2023-11-08 08:40 UTC, bslabiak commented on packages/e2e-tests/wdio.conf.chrome.ts
> -          '--disable-web-security',
With this flag connecting trezor is not possible. I have run full regression without this flag and it seems not affect rest of our test.
Question is why do we have this flag added in first place?

2023-11-09 15:29 UTC, wklos-iohk commented on packages/e2e-tests/wdio.conf.chrome.ts
> -          '--disable-web-security',
As I know it enabled us with Lace development as there were some issues with CORS (this parameter disables CORS). Anyway, if everything works fine without this property then I don't mind removing it.

2023-11-09 15:30 UTC, wklos-iohk commented on packages/e2e-tests/wdio.conf.chrome.ts
> -          '--disable-web-security',
@ljagiela what's your opinion?

2023-11-13 11:19 UTC, ljagiela commented on packages/e2e-tests/wdio.conf.chrome.ts
> -          '--disable-web-security',
If Bart tested it and it works fine then I think it's ok to remove it.

2023-11-13 11:23 UTC, ljagiela approved these changes

2023-11-13 11:51 UTC, wklos-iohk approved these changes

2023-11-13 15:12 UTC, merged