Implement add new address form in side drawer
input-output-hk/lace pull request #57
Opened 2023-06-02 14:12 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-6579](https://input-output.atlassian.net/browse/LW-6579)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR removes the add new address form from right column and adds a side drawer to handle this.
Refactors the AddressDetailDrawer.tsx component to allow saving new addresses.

## Screenshots

<img width="1413" alt="Screenshot 2023-05-29 at 15 48 03" src="https://github.com/input-output-hk/wallet-world/assets/65184652/39bb8480-aba6-44cc-b5d5-727345810ebe">

<img width="1413" alt="Screenshot 2023-05-29 at 15 48 21" src="https://github.com/input-output-hk/wallet-world/assets/65184652/17fb1129-227e-4260-8d8d-eb515a1fc53c">

<img width="1413" alt="Screenshot 2023-05-29 at 15 47 48" src="https://github.com/input-output-hk/wallet-world/assets/65184652/08598047-6f6d-4698-97b2-680823a3923f">

---
# Allure report
`allure-report-publisher` generated test report!

**smokeTests**: ❌ [test report](https://lace-qa:8PP5wBaDV6UoXj@d1terqjryk7mu9.cloudfront.net/linux/chrome/490/5313965613/index.html) for [55a92633](https://github.com/input-output-hk/lace/pull/57/commits/55a9263331bf4c32c832a4d9347b39588849fa53)
|       | passed | failed | skipped | flaky | total | result |
|-------|--------|--------|---------|-------|-------|--------|
| Total | 13     | 6      | 0       | 0     | 19    | ❌     |

[LW-6579]: https://input-output.atlassian.net/browse/LW-6579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-05 10:38 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/hooks/useEnterKeyPress.ts
> +  if (addressDeleteBtn.offsetHeight && !addressDeleteBtn.hasAttribute('disabled')) {
Following up on this discussion: https://github.com/input-output-hk/wallet-world/pull/2729#discussion_r1214226529

Could we then extract it to a const to improve readability:
```
const isDeleteBtnVisible = !!addressDeleteBtn.offsetHeight
```

2023-06-13 09:41 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/hooks/useEnterKeyPress.ts
> +  if (addressDeleteBtn.offsetHeight && !addressDeleteBtn.hasAttribute('disabled')) {
To be honest i think the whole `useEnterKeyPress` hook should be refactored as this is just a messy function bound to the button DOM elements of various screens by IDs using query selectors 🙈  but ofc i can make this small adjustment 😆

2023-06-13 09:54 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/hooks/useEnterKeyPress.ts
> +  if (addressDeleteBtn.offsetHeight && !addressDeleteBtn.hasAttribute('disabled')) {
@marcin-mazurek this is improved in my last commit ✅

2023-06-13 09:55 UTC, DominikGuzei commented
@marcin-mazurek @jplorek-atix i updated and tested this PR with the latest `main` branch changes 👍

2023-06-13 09:56 UTC, DominikGuzei approved these changes
Updated to latest `main` version and tested locally 👍

2023-06-13 11:23 UTC, milagi requested changes
- ‘Save your faorite addresses to find them easily’ not displayed in mockup
- ‘Done’ button instead of ‘Save address’
![image](https://github.com/input-output-hk/lace/assets/75744070/f8d94e95-03eb-48cf-b3f0-da6d956a5067)

Expected:
![image](https://github.com/input-output-hk/lace/assets/75744070/0fb0e89a-56b6-49d0-bc60-635b407426f8)

2023-06-14 08:39 UTC, milagi commented
Allan comments (https://input-output.atlassian.net/browse/LW-6579?focusedCommentId=184899)
-Remove description at the top
-'Save address' button instead of 'Done' is OK

Basically the only change that has to be made is removing the top description

2023-06-14 10:24 UTC, milagi commented
Another thing to fix: Keyboard shortcuts don't work properly when editing:
-Add address in extended mode
-Refresh page
-Click on saved address
-Press 'Enter' key

**Actual Result:**
Nothing happens

**Expected Result:**
Edit screen is displayed

2023-06-19 13:08 UTC, bslabiak approved these changes

2023-06-19 16:57 UTC, merged