feat(staking): LW-8179 Make CTAs in staking management drawer dynamic
input-output-hk/lace pull request #575
Opened 2023-09-27 10:40 UTC by refi93

# Checklist

- [x] JIRA - LW-8179
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Extended staking management drawer state machine footer logic to dynamically change the footer depending on the portfolio state.

Moreover, this PR refactors the `footerVisible` variable to include the logic within the Footers mapping which simplifies reasoning about the visibility of the footer as it moves the logic closer to the actually impacted Flow/Step/Element

## Testing

1. Rebalance the portfolio and check that upon clicking on "Manage" no footer is visible. Check that upon removing a pool "Confirm staking" button appears
2. Drift the portfolio e.g. by sending a large portion of funds to yourself (provided dekegating at least 2 pools) and check that upon clicking "Manage" the button text is "Rebalance staking"
3. Select manually some pools in "Browse pools" section, click "Next" and check that the management drawer that appears has below a button with the text "Confirm staking"
4. Check that the buttons mentioned above work as intended
5. Check that button texts match Figma designs from the task description

## Screenshots

before, all management drawer initial screens looked the same:

![Screenshot 2023-09-27 at 12 39 01](https://github.com/input-output-hk/lace/assets/4980147/4b2713af-34b0-45d4-8682-42323a4c10de)

after:
![Screenshot 2023-09-27 at 12 31 33](https://github.com/input-output-hk/lace/assets/4980147/fa9e8c16-8a8a-4904-aab0-434aa08e1a4f)

![Screenshot 2023-09-27 at 12 31 53](https://github.com/input-output-hk/lace/assets/4980147/4ec08e98-49e2-4236-806b-b91cc1a4e7fb)

![Screenshot 2023-09-27 at 12 32 38](https://github.com/input-output-hk/lace/assets/4980147/bdab1767-768a-46ce-b781-b2502da65b94)

2023-09-27 10:50 UTC, refi93 commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> -  const footer = footerVisible && activeDrawerStep ? footersMap[activeDrawerStep] : undefined;
if I understood correctly, this condition basically made the footer visible for all steps except "Pool Details", so I just moved that condition to the "PoolDetailsStep" and inverted it to return a `null` i.e. empty/invisible footer if the condition is met, which IMHO simplifies the reasoning about Footer visibility as at first sight the reader may have originally thought that visibility is conditional across all steps, making reasoning about it a lot more complex

2023-09-27 13:36 UTC, szymonmaslowski approved these changes
Nicely done. Left some improvement suggescions.

2023-09-27 13:36 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +  const selectionActionsAllowed = !selectionsFull || openPoolIsSelected;
How about moving those variables to the `useDelegationPortfolioStore` selector instead of exposing the `currentPortfolio`?

2023-09-27 13:36 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +      })(),
<3. Now it is much easier to reason about.

2023-09-27 13:36 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +        return <StakePoolPreferencesFooter buttonTitle={t('drawer.preferences.confirmButton')} />;
```suggestion
        return <StakePoolPreferencesFooter buttonTitle={!portfolioModified && portfolioDrifted ? t('drawer.preferences.rebalanceButton') : t('drawer.preferences.confirmButton')} />;
```

2023-09-27 13:36 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +        return <StakePoolDetailFooter popupView={popupView} />;
I think it is even easier to understand if we invert the condition. And also it is worth to add a case with the CurrentPoolDetails to make it explicit
```suggestion
        if (activeFlow === Flow.CurrentPoolDetails || (activeFlow === Flow.PoolDetails && !delegationPending && selectionActionsAllowed) {
          return <StakePoolDetailFooter popupView={popupView} />;
        }
        return null;
```

2023-09-27 15:32 UTC, refi93 commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +  const selectionActionsAllowed = !selectionsFull || openPoolIsSelected;
`selectionActionsAllowed` consists of a bit more complex expressions under the hood, but the newly introduced ones indeed seem worth moving to the selector 👍

2023-09-28 09:15 UTC, xdzurman requested changes

2023-09-28 09:15 UTC, xdzurman commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +          activeFlow === Flow.CurrentPoolDetails ||
This is Overview > PoolDetails:
![image](https://github.com/input-output-hk/lace/assets/22454337/49c60343-6852-4375-8f11-6327910217a9)

There should be no actions here as far as I know and previously there was

```ts
  const drawerNotOnDetails = activeDrawerStep !== DrawerDefaultStep.PoolDetails;
  const footerVisible =
    drawerNotOnDetails || (activeFlow === Flow.PoolDetails && !delegationPending && selectionActionsAllowed);
```
note the `!==`. Now here's `===`

2023-09-28 11:40 UTC, xdzurman approved these changes

2023-09-29 07:49 UTC, oldGreg5 approved these changes

2023-09-29 09:38 UTC, merged