feat(extension): add events for settings
input-output-hk/lace pull request #576
Opened 2023-09-27 12:39 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-8381](https://input-output.atlassian.net/browse/LW-8381)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR implements Post Hog events for settings currency, theme, show recovery phrase, analytics and faqs

Event list
settings | currency | click
settings | currency | select currency | click
settings | currency | x | click
settings | theme | light mode | click
settings | theme | dark mode | click
settings | show recovery phrase | click
settings | show recovery phrase | enter your password | show recovery phrase | click
settings | show recovery phrase | Your recovery phrase (keep it secret!) | hide passphrase | click
settings | show recovery phrase | Your recovery phrase (keep it secret!) | x | click
settings | analytics | agree | click
settings | analytics | skip | click
settings | faqs | click

For `settings | currency | select currency | click` event the currency property is added, this property has the selected currency

2023-09-27 18:06 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
>        if (this.trackingTypeChangedFromSettings) {
hm … im not very happy with this kind of app views logic leaking into the implementation of the relatively abstract and clean `AnalyticsTracker` 🤔 i think the events regarding settings clicks should belong in the respective components

2023-09-27 18:09 UTC, DominikGuzei requested changes
I'm not sure when this was introduced but I just realized in this PR that we are coupling the `AnalyticsTracker` logic to the settings: https://github.com/input-output-hk/lace/blob/8f012c4b1232538bfb3838cd193ae923ec6c3ebf/apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts#L96

I would love to untangle those two again and keep the `AnalyticsTracker` completely unaware of any views/components in the app.

2023-09-27 19:51 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
>        if (this.trackingTypeChangedFromSettings) {
I know this is not the best implementation, the main issue here is that we need to wait until the `userTrackingType` change to be able to send these events in the correct moment. And right now we are not updating this directly from the component.
We are updating the local storage first https://github.com/input-output-hk/lace/blob/main/apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsSecurity.tsx#L43
then in the analytics context we are listening for that change https://github.com/input-output-hk/lace/blob/main/apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx#L42
and then calling `setOptedInForEnhancedAnalytics` to update the `userTrackingType` https://github.com/input-output-hk/lace/blob/main/apps/browser-extension-wallet/src/providers/AnalyticsProvider/context.tsx#L61C22-L61C52
So, these events are calling before the update of `userTrackingType` happen
For `settings | analytics | skip | click` this is ok, but `settings | analytics | agree | click` should be sent after the `userTrackingType` changes

2023-09-27 19:56 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
>        if (this.trackingTypeChangedFromSettings) {
I think it would be better to not make the update of the `userTrackingType` dependent of the local storage update, this way we can call `setOptedInForEnhancedAnalytics` in the component before we sent these events

2023-09-28 13:36 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
>        if (this.trackingTypeChangedFromSettings) {
@DominikGuzei refactor done in [754f7b3](https://github.com/input-output-hk/lace/pull/576/commits/754f7b3d8a11d970c0de19aa38789dc38dedab4b)

2023-09-28 16:14 UTC, DominikGuzei approved these changes
Great work 🎉  code LGTM now 🚢

2023-09-29 12:46 UTC, milagi requested changes
event settings | faqs | click in popup mode is not sent

2023-10-03 14:53 UTC, milagi approved these changes

2023-10-03 15:42 UTC, merged