Adjustments to layout content for different screen sizes
input-output-hk/lace pull request #59
Opened 2023-06-02 15:13 UTC by jplorek-atix

# Checklist

- [ ] JIRA - \<[LW-6560](https://input-output.atlassian.net/browse/LW-6560)>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This PR makes small adjustments to Layout content to adapt to different screen sizes

2023-06-13 11:31 UTC, DominikGuzei commented on packages/core/src/ui/components/WalletAddresses/WalletAddressItem.tsx
> +  shouldUseEllipsisBeferoAfter?: boolean;
typo in `shouldUseEllipsisBeferoAfter` … should probably be `shouldUseEllipsisBeforeAndAfter`?

2023-06-16 13:55 UTC, milagi requested changes
When in the staking section, and the resolution is between 669px and 690px, the menu covers some of the content in the main section:
![image](https://github.com/input-output-hk/lace/assets/75744070/f8275ed9-9779-40e8-be2c-e842da929a51)

2023-06-19 13:34 UTC, bslabiak approved these changes

2023-06-19 14:32 UTC, DominikGuzei approved these changes

2023-06-20 10:41 UTC, merged