refactor(staking): [LW-8510] refactor percentage slider
input-output-hk/lace pull request #593
Opened 2023-10-02 10:29 UTC by refi93

# Checklist

- [x] JIRA - LW-8510
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

amend hotfix from #590 that fixed the infinite loop of the percentage slider, however it was at the cost of detaching the components from the `onPercentageChange` callback changes which makes it fragile, especially, if immutable structures would be involved. This PR fixes that flaw by keeping the ref to the current callback which is updated anytime the callback is modified from above

On top of that, this PR gives more specific names to percentage-related props in the same component, suffing them all consistently with the `percentage` suffix, improving overall readability of the code

## Testing

Open management drawer and try changing the slider values, check that after closing and reopening it still works

2023-10-02 10:33 UTC, refi93 commented on packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx
> +    onPercentageChangeRef.current = onPercentageChange;
the main fix in this PR, took inspiration from the slider implementation in the lib

[state management hook used in the slider](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/slider/src/Slider.tsx#L102)
[the implementation of it](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/use-controllable-state/src/useControllableState.tsx#L12)
[the ref to the callback](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/use-callback-ref/src/useCallbackRef.tsx#L7)

2023-10-02 11:31 UTC, refi93 commented on packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx
> -  }, [localValue]);
actually, even the previous solution should work properly in the sense that if the value of the slider changed, the latest `onPercentageChange` passed from above would be used, but it's not very clean/intuitive that the `onPercentageChange` callback is left from the hook dependencies

2023-10-02 14:36 UTC, szymonmaslowski requested changes

2023-10-02 14:38 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx
> +    onPercentageChangeRef.current = onPercentageChange;
I just realized we don't need `useEffect` at all. We removed a debounce so now we can just assign the `onPercentageChange` directly to the  Slider's `onValueChange`.

2023-10-03 07:38 UTC, refi93 commented on packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx
> +    onPercentageChangeRef.current = onPercentageChange;
> I just realized we don't need useEffect at all. We removed a debounce so now we can just assign the onPercentageChange directly to the Slider's onValueChange.

indeed 🤦  good catch 👍

2023-10-03 08:15 UTC, refi93 commented on packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx
> +    onPercentageChangeRef.current = onPercentageChange;
done in https://github.com/input-output-hk/lace/pull/593/commits/6a208d05973b38626059d3c2921b42999ea606ca

2023-10-03 11:03 UTC, szymonmaslowski approved these changes

2023-10-03 11:21 UTC, przemyslaw-wlodek approved these changes

2023-10-09 14:15 UTC, oldGreg5 approved these changes

2023-10-09 16:13 UTC, merged