fix(staking): preserve pool onchain/saved percentages upon SM transitions
input-output-hk/lace pull request #601
Opened 2023-10-03 13:47 UTC by xdzurman

# Checklist

- [ ] [JIRA - \<link>](https://input-output.atlassian.net/browse/LW-8685?atlOrigin=eyJpIjoiMzIyNTY1NjM0YjljNDYwZTkyZTQ3NGFmZDYzOTMyYmMiLCJwIjoiaiJ9)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Remove notion of `basedOnCurrentPortfolio`. To preserve the current portfolio's percentages (onchain, saved), these percentages need to live on `DraftPortfolioPool` somehow as well. Therefore, I made these percentages required on `CurrentPortfolioPool` type, and optional on `DraftPortfolioPool`. When adding a new pool (from browsePools, or stake-all-on-this-pool), there's a check if this pool resides in the currentPortfolio and if so, saved and onchain percentages are copied from there to the new pool. This allows the user to see these percentages in all places (adding pool to current portfolio / creating new portfolio that might have some current pool) if they're defined.

## Testing

Make sure that saved/onchain percentages of current pools are never lost throughout the app, even when creating a new portfolio and the draft pools happen to also be in the current portfolio.

## Video
1. current portfolio > add pool > see that saved and onchain percentages are not lost
2. new portfolio > see that every "current portfolio pool" added to new portfolio retains saved/onchain percentages
3. stake-all-on-this-pool on current portfolio pool retains   saved/onchain percentages

https://github.com/input-output-hk/lace/assets/22454337/a034e31e-c791-450f-88f6-9e7a2cf49b02

2023-10-03 15:08 UTC, refi93 commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +      ) || false,
my understanding is that this flag is supposed indicate that the portfolio draft has changed respective to the current portfolio (at least that was my understanding at the time of introducing this flag and that's how it's used e.g. for the sake of the dynamic button text). I think the current logic may not always work that way, namely in these two cases:

1. User removes a pool from the current portfolio -> all remaining pools would have the same percentages, making this check evaluate incorrectly to `false`
2. When working with selected pools not included in the current portfolio, these don't have any `sliderIntegerPercentage` making this condition evaluate to `false` as well, despite the portfolio being obviously different from the `current portfolio`

If I'm correct, I'd suggest for the sake of clarity and simplicity reversing the flag (renaming it to `portfolioDraftMatchesCurrentPortfolio`) and adding a few conditions which should ensure that the flag is checking 1:1 match with the current portfolio:

```suggestion
    portfolioDraftMatchesCurrentPortfolio:
      store.draftPortfolio.length === store.currentPortfolio?.length
      && (store.draftPortfolio || []).every(
        ({ sliderIntegerPercentage, savedIntegerPercentage }) =>
          !!savedIntegerPercentage && sliderIntegerPercentage !== savedIntegerPercentage
      ),
```

2023-10-03 15:21 UTC, refi93 requested changes
see my comment regarding detection of portfolio modification, which I believe to not match the desired UX (e.g. confirm button (even if disabled) not visible if pool removed when managing current portfolio)

2023-10-04 09:16 UTC, refi93 approved these changes

2023-10-04 09:49 UTC, szymonmaslowski requested changes
Great Improvement! Left a few comments

2023-10-04 09:49 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +        ) {
Can we move this whole condition to the selector?

2023-10-04 09:49 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +      ),
IMO it would be better to have a boolean `footerHiddenInPreferencesStep` and check if it is a management flow. Right now you always compare the draft against the current, but that check is invalid in the new portfolio flow. So by checking all directly here we eliminate this problem

2023-10-04 09:49 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +              currentPortfolioDrifted
I guess this also could be moved to the selector

2023-10-04 09:49 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/preferences/StepPreferencesContent.tsx
> +      onChainPercentage: draftPool?.onChainPercentage,
❤️

2023-10-04 09:49 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/initializeDraftPortfolioPool.ts
> +import { mapStakePoolToPortfolioPool } from './mapStakePoolToPortfolioPool';
How about moving the `mapStakePoolToPortfolioPool` into this file as a local helper?

2023-10-04 09:49 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/atomicStateMutators.ts
> +    const newPool = initializeDraftPortfolioPool({ initialPercentage: 0, stakePool, state });
This means values will be populated even if we make selections just going to browse pools manually... Is this a requirement? I lost track already...

2023-10-04 10:50 UTC, refi93 commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +      ),
IMHO I'd rather leave in the state/selectors UI-agnostic facts and the logic deciding whether something should be shown or not should be as close to the relevant place as possible, especially in components like this where multiple flows are mixed, so having UI logic at the top-level could make it pretty tricky for the reader to figure out which flow is it bound to, making the code harder to follow than it needs to be

So IMHO the `portfolioDraftMatchesCurrentPortfolio` variable (or some equivalent fact-based flag) should actually be left here (the fact whether the draft matches current portfolio makes sense regardless of the flow) and I'd keep the check whether a footer should be shown or not rather right within the footers map to not clutter the top-level scope of this "master" component

2023-10-04 11:09 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +      ),
Right, I agree with you :wink: I initially thought comparing the draft vs current not considering the kind of flow is problematic, however because the variable name explicitly explains that fact it rather won't be missused. :+1:

2023-10-04 11:09 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/atomicStateMutators.ts
> +    const newPool = initializeDraftPortfolioPool({ initialPercentage: 0, stakePool, state });
Confirmed with Fernando, that is ok :+1:

2023-10-04 14:44 UTC, merged