Feature/lw 8343 posthog start session event
input-output-hk/lace pull request #606
Opened 2023-10-04 13:11 UTC by tommayeliog

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-10-05 19:53 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +    if (this.userTrackingType === UserTrackingType.Basic) {
is there a reason why not to use `userTrackingType$.value` instead of `this.userTrackingType`?

2023-10-05 19:53 UTC, jplorek-atix commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> -    await this.userIdService?.extendLifespan();
Isn't `this.checkNewSessionStarted()` necessary here?

2023-10-09 10:50 UTC, tommayeliog commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +    if (this.userTrackingType === UserTrackingType.Basic) {
removed

2023-10-09 10:50 UTC, tommayeliog commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> -    await this.userIdService?.extendLifespan();
yes, we are checking for a new session before sending the event to posthog

2023-10-09 11:56 UTC, jplorek-atix approved these changes

2023-10-10 10:34 UTC, DominikGuzei commented
@tommayeliog there are merge conflicts in this PR and please edit the PR description to remove any template text + add at least one sentence of description 🙏

2023-10-20 12:39 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.test.ts
> +      // eslint-disable-next-line no-magic-numbers
i guess this comment can be removed as i can't see any magic numbers

2023-10-20 12:40 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/types.ts
> +  LifeExtended = 'LIFE_EXTENDED'
Let's change this event name to `SessionExtended` and `SESSION_EXTENDED`?

2023-10-20 12:45 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  private lastStartSessionEventSent = false;
I'm not sure if this really belongs to the `userIdService` because it doesn't handle sending events - so this is leaking-in concerns from the PostHogClient

2023-10-20 12:48 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +    this.lastStartSessionEventSent = true;
A getter function that changes state is red flag … this is the consequence of the `userIdService` now being coupled to something outside itself (in this case the `PostHogClient`) sending events. The `userIdService` itself shouldn't know anything about events being sent - it just manages user ids and sessions.

2023-10-20 12:50 UTC, DominikGuzei requested changes
I have added a few comments - most importantly I think that the `userIdService` should not be coupled to the concept of "sending events". It should only talk about user ID and session

2023-10-23 10:52 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.test.ts
> +      await userIdService.getRandomizedUserId();
@tommayeliog Here's my suggestion to make the test implementation cleaner.
How about if we extract this bit of logic from `UserIdService` into a public method called `init`, and call it directly in the test, as well as from `getRandomizedUserId` function?

```
    if (!this.userIdRestored) {
      console.debug('[ANALYTICS] Restoring user ID...');
      await this.restoreUserId();
    }

    if (!this.randomizedUserId) {
      console.debug('[ANALYTICS] User ID not found - generating new one');
      this.randomizedUserId = randomBytes(USER_ID_BYTE_SIZE).toString('hex');
    }
```

I think it will help us clear express the intent in the test, but still it doesn't have to be called explicitly, so we don't have to deal with the async initialization issues we stumbled upon while pair programming.

2023-10-23 10:52 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +    // TODO: make this method private when Motamo is not longer in use
How about moving it above the function declaration and adding the ticket number (I've asked @vhulchenko-iohk to raise one)?

2023-10-23 10:52 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  private lastStartSessionEventSent = false;
@DominikGuzei the problem here comes from the fact that UserIdService works in the background, whereas PostHogClient is initialized on the front-end (one instance for each view). Initially we wanted to expose a "new session" event as a stream, but that resulted in duplicated events. We would need to move entire tracking to a background service, which is quite a lot of work (well beyond scope of this task), we probably don't have a full understanding of what could go wrong here.

So this is more of a tactical approach, but I think we could at least use more generic name here to avoid coupling UserIdService with tracking on name level.

I think tactical is fine for now, as going forward, I would love to review the whole UserIdService when:
1. We remove Matomo (needs to happen this year).
2. We come to a final agreement on whether we're ever going to drop opted out tracking, in which case, we can remove a lot of code, which adds unnecessary complexity and doesn't bring any benefit.

2023-10-23 12:54 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +  private lastStartSessionEventSent = false;
Thanks for the details @marcin-mazurek - ok, yeah then let's keep the current solution and maybe improve the naming to avoid talking about "events" in the user id service 👍

2023-10-24 09:24 UTC, marcin-mazurek requested changes

2023-10-24 09:24 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/lib/scripts/background/services/userIdService.ts
> +    return shouldSendNewSessionEvent;
@tommayeliog could we review the variable names in this function? I thought we wanted to completely get rid of coupling with session in this class.

2023-10-24 09:24 UTC, marcin-mazurek commented on apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/AnalyticsTracker.ts
> +      await this.postHogClient?.sendSessionStartEvent();
```suggestion
      await this.postHogClient.sendSessionStartEvent();
```
(you're asserting above that PostHog client is defined)

2023-10-25 11:04 UTC, marcin-mazurek approved these changes
LGTM, but please make sure to fill in the PR template (even short, single sentence works, if the changes are not massive).

2023-10-25 11:39 UTC, DominikGuzei approved these changes

2023-10-27 13:02 UTC, bslabiak approved these changes

2023-11-15 10:16 UTC, merged