feat(staking): [LW-8683] make normalization work with decimals, handle onchain percentages
input-output-hk/lace pull request #611
Opened 2023-10-05 15:42 UTC by xdzurman

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Make normalization work with decimals (to apply to onchain percentages). Still throw if sum is not 100, but check whether the sum is 100 before calling the function. To ensure a lossless sum of float percentages, a new function is implemented (sumPercentagesLossless). 

Now, instead of always calling normalization for onchain percentages, check if sum is 100 beforehand. If it isn't, still round the onchain percentages at 2 decimal places. No special gray pie slice is added, this is handled implicitly by DelegationCard.

## Testing

Check the app no longer crashes with the non-100% staked wallet. Check that onchain percentages are shown with 2 decimal places at most.

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/22454337/f610111e-8fd8-4f77-9f74-522d1e0ffe50)
![image](https://github.com/input-output-hk/lace/assets/22454337/5ebee1f4-5e10-490e-803f-f0ada32494a6)

![image](https://github.com/input-output-hk/lace/assets/22454337/4e8580ba-6670-4658-9e36-f3ee8e02a6ef)

2023-10-05 15:51 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/sumPercentagesLossless.ts
> +  return Number(sum.toFixed(10));
not sure how/if that can happen but `0.999999...` may get evaluated by this function to `0.9999999999` as `toFixed()` does no rounding, which I gues wouldn't be intended. Wouldn't it be safer to do a "precision round" like proposed in this SO answer? https://stackoverflow.com/a/49729715

2023-10-05 15:53 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/sumPercentagesLossless.ts
> +export const sumPercentagesLossless = <K extends string, T extends { [key in K]: number }>({
"lossless" is IMHO a bit too strong of a claim, I'd consider calling it rather "sanitized" in the sense that this function shouldn't output any "wild" values

2023-10-05 15:56 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +const adjustOnchainPercentages = <K extends string, T extends { [key in K]: number }>({
in line with my other [suggestion](https://github.com/input-output-hk/lace/pull/611/files#r1347649019)  I'd use the term "sanitize" 

```suggestion
const sanitizeOnchainPercentages = <K extends string, T extends { [key in K]: number }>({
```

2023-10-05 16:03 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +  sumPercentagesLossless({ items, key }) === PERCENTAGE_SCALE_MAX
I'd leave here a comment clarifying that percentages may not add up to 100% especially if some of the stake keys bound to account is deregistered and has funds at the same time - this is IMHO something that a casual reader of this code has very low chance of figuring out on their own

2023-10-05 16:11 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/normalizePercentages.ts
> +//                            =>          [{val: 33.34}, {val: 33.33}, {val: 33.33} ]
I'd make this a proper docstring for better development experience, so that it's shown by editor intellisense when hovering over the function invocation in the code
```suggestion
/**
 * Rounds values of properties of an input array of objects, while keeping the sum of the numbers equal to 100 (PERCENTAGE_SCALE_MAX)
 * Requires input array to sum to 100 +- epsilon
 * Works at arbitrary decimal precision
 * Examples:
 * ```
 *           normalizePercentages({items: [{val: 33.33},{val: 33.33},{val: 33.33}], key: 'val', decimals: 0})
 *                             =>          [{val: 34},   {val: 33},   {val: 33}   ]
 * ```
 * ```
 *           normalizePercentages({items: [{val: 33.333},{val: 33.333},{val: 33.333}], key: 'val', decimals: 2})
 *                            =>          [{val: 33.34}, {val: 33.33}, {val: 33.33} ]
 * ```
 */
```

2023-10-05 19:16 UTC, refi93 requested changes
overall LGTM, left a few renaming suggestions

2023-10-06 09:14 UTC, xdzurman commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/sumPercentagesLossless.ts
> +  return Number(sum.toFixed(10));
toFixed does round the numbers at the specified decimal point. In the funciton, I changed this to bignumber implementation since their `toFixed` is less buggy and I added a JS-math edge case unit test

2023-10-06 10:21 UTC, szymonmaslowski requested changes
Good job!

2023-10-06 10:21 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/sumPercentagesLossless.ts
> +  return Number(sum.toFixed(decimals));
I think cutting the tail of the sum is redundant. We don't use `decimals` argument anywhere. I would resign from this and just return the real sum without any rounding. If rounding would be needed somewhere then it could be handled in there explicitly

2023-10-06 10:21 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/normalizePercentages.ts
>      throw new Error(`Percentages must sum to ${PERCENTAGE_SCALE_MAX}`);
If we stick to throwing then we need to catch it its usage places. Otherwise, it might happen we still haven't catch some edge case and the UI will be broken (e.g. staking won't show)

2023-10-06 10:21 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/__tests__/normalizePercentages.test.ts
> +  test('Should correctly normalize numbers to 0 decimal places', () => {
A nitpick, but the word `should` is redundant 😉 
```suggestion
  test('correctly normalizes numbers to 0 decimal places', () => {
```

2023-10-06 10:45 UTC, xdzurman commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/sumPercentagesLossless.ts
> +  return Number(sum.toFixed(decimals));
![image](https://github.com/input-output-hk/lace/assets/22454337/7adb3e5e-294e-4de2-bae2-f4ca0272d915)
This is what it's needed for. I added "decimals" for modifiability, before I had just a magic number of 10 inline. I can remove that parameter, but cutting decimals somewhere is necessary.

2023-10-06 11:47 UTC, xdzurman commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/normalizePercentages.ts
>      throw new Error(`Percentages must sum to ${PERCENTAGE_SCALE_MAX}`);
When operating on onchain percentages (sanitizeOnchainPercentages fn), before calling `normalizePercentages` there's an explicit check of `sumPercentagesSanitized` (previously sumPercentagesLossless), so this will never throw. 

The other calling place is
```
    const percentageValue = PERCENTAGE_SCALE_MAX / selections.length; // may be float
      state.draftPortfolio = selections.map((pool) => ({
        ...pool,
        sliderIntegerPercentage: percentageValue,
      }));
      state.draftPortfolio = normalizePercentages({ items: state.draftPortfolio, key: 'sliderIntegerPercentage' });
```
which deterministically assigns 100/N value N items, I can wrap that but I see it as an overkill. What do you think?

2023-10-06 11:49 UTC, xdzurman commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +import { PERCENTAGE_SCALE_MAX } from '../store';
I imported it from ../store/constants, does that fix the issue? I'm afraid we would forget such TODO comments before merging.

2023-10-09 09:43 UTC, szymonmaslowski commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +import { PERCENTAGE_SCALE_MAX } from '../store';
It is fine if it works 😄 Could you check if story for this component works fine? (`yarn dev`)

2023-10-09 10:56 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/sumPercentagesLossless.ts
> +  return Number(sum.toFixed(decimals));
It cannot happen because you operate on a `BigNumber` object which solves the problem

2023-10-09 11:02 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +import { sumPercentagesSanitized } from './stateMachine/sumPercentagesSanitized';
```suggestion
import { sumPercentagesSanitized } from './stateMachine';
```

2023-10-09 13:45 UTC, szymonmaslowski approved these changes

2023-10-10 07:05 UTC, refi93 commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +// re-declared due to ladle crash if importing from ../store
I'd consider making a ticket for this issue, and referencing it in the comment, so that we get to it hopefully sooner than later as keeping in mind such arbitrary constraint IMHO degrades development experience significantly

2023-10-10 07:08 UTC, refi93 approved these changes

2023-10-10 12:10 UTC, merged