feat(ui): add tooltip to piechart
input-output-hk/lace pull request #616
Opened 2023-10-06 12:40 UTC by greatertomi

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-10-09 10:34 UTC, przemyslaw-wlodek requested changes

2023-10-09 10:34 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
Can we please leave this component unmodified? It was designed to consume default tooltips and your implementation makes it very limited to accept only simple name/value data for tooltips.

Recharts [passes down all the necessary props](https://github.com/recharts/recharts/blob/master/src/component/Tooltip.tsx#L303) for the `Tooltip` component. You just need to pass our custom Tooltip "adapter" in props and it should render in the correct position (recharts handles that). This adapter will just consume the props from `PieChart.data` and pass it to our Tooltip component from `ui-toolkit`. So we don't need pie-chart-tooltip as each pie-chart tooltip might be different.

I am happy to explain in detail / assist you e.g. pair-programming.

2023-10-10 08:00 UTC, greatertomi commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
Fixed on 32a4712

2023-10-10 15:08 UTC, szymonmaslowski requested changes
Well done. I left a few comments.

2023-10-10 15:34 UTC, refi93 commented
Seems like the tooltip may get overlapped by the piechart, see screenshot:

![Screenshot 2023-10-10 at 17 33 45](https://github.com/input-output-hk/lace/assets/4980147/754d3f5b-05fd-4fc0-9e82-821300363d57)

2023-10-10 15:35 UTC, refi93 requested changes
see comments

2023-10-10 15:49 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +  saturation?: string | number | undefined;
For consistency sake considering [here](https://github.com/input-output-hk/lace/blob/90b6b2dd81b0835616b4ac6689c7b1413f0d951b/packages/cardano/src/wallet/util/stake-pool-transformer.ts#L19-L21), I think we should leave the union type as it is. I'll remove the `undefined`

2023-10-10 16:12 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +    const saturation = payload[0]?.payload.saturation;
The payload Recharts piechart passes to the tooltip is an array, that is why I am using an array here.

2023-10-10 16:28 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +  saturation?: string | number | undefined;
Fixed on d45203e

2023-10-10 16:30 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationCard.css.ts
> +export const tooltip = style([
Fixed on a0c53db

2023-10-10 16:31 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationCard.css.ts
> +    background: '$tooltip_container_bgColor',
Fixed on a0c53db

2023-10-10 16:32 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +  name: string;
Fixed on d4483fb

2023-10-10 16:33 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +import { DistributionItem } from './DelegationCard';
Fixed on f1fc236

2023-10-10 16:54 UTC, greatertomi commented
> 0f47826



> Seems like the tooltip may get overlapped by the piechart, see screenshot:
> 
> ![Screenshot 2023-10-10 at 17 33 45](https://user-images.githubusercontent.com/4980147/273972608-754d3f5b-05fd-4fc0-9e82-821300363d57.png)

Thanks for this. I fixed this on 0f47826, kindly review again.

2023-10-11 09:18 UTC, refi93 commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +            tooltip={DelegationTooltip as any}
Rather than casting to `any` which basically breaks off the DelegationTooltip interface from the real interface expacted by the Recharts component, I'd consider declaring an easier to follow interface within the `PieChart` component. As far as I tried an interface like this should do and actually plays well with Recharts without requiring any re-casting, while being a lot simpler to follow:

```typescript
interface TooltipContentRendererProps<T> {
  active?: boolean;
  payload?: { name?: string; payload?: T }[];
}
interface TooltipProps<T> {
  content:
    | ReactElement
    | ((props: TooltipContentRendererProps<T>) => ReactNode);
}
``` 

```suggestion
            tooltip={DelegationTooltip}
```

2023-10-11 09:24 UTC, refi93 commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
if https://github.com/input-output-hk/lace/pull/616/files#r1354544516 is implemented, this should no longer be needed

2023-10-11 09:27 UTC, refi93 commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +    const saturation = payload[0]?.payload.saturation;
```suggestion
    const { apy, saturation } = payload[0]?.payload || {};
```

2023-10-11 11:58 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +    const saturation = payload[0]?.payload.saturation;
Fixed on c70445d

2023-10-11 11:58 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +/* eslint-disable @typescript-eslint/no-explicit-any */
Fixed on c70445d

2023-10-11 11:58 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +            tooltip={DelegationTooltip as any}
Fixed on c70445d

2023-10-11 12:55 UTC, refi93 commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +  tooltip?: TooltipProps<PieChartDataProps & T>['content'];
I just tried and the intersection with `PieChartDataProps` should be redundant

```suggestion
  tooltip?: TooltipProps<T>['content'];
```

2023-10-11 22:42 UTC, szymonmaslowski commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +  saturation?: string | number | undefined;
Regarding `stakePoolTransformer`'s type definition, I think it is a better design to have just one specific type for a property and eventually convert it once at the data entry point (API call or such), so we don't have to deal with different types in multiple places. So I would definitely suggest here to pick either `string` or `number`.

Besides that, we want to decouple from the `stakePoolTransformer` at some point. It does things that are more of a UI component's concern like formatting the data, enriching it with some text, etc. It also duplicates (or is duplicated by) some other utility, if I am not mistaken it was a zustand selector for the selected pool.

2023-10-11 23:00 UTC, szymonmaslowski commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +  saturation?: string | number | undefined;
I just checked the code and it looks like we should go with a `string` as a type for both of those properties. The type that we pass to the DelegationCard is already narrowed. The data is not coming from the `stakePoolTransformer` but [another util](https://github.com/input-output-hk/lace/blob/aaf6838a9b422a30a22810798f6dd2d791796053/packages/staking/src/features/store/delegationPortfolioStore/mapStakePoolToDisplayData.ts#L18). That until actually exists to reduce duplication and improve the typing.

2023-10-11 23:36 UTC, szymonmaslowski reviewed
Please consider few additional suggestions

2023-10-11 23:36 UTC, szymonmaslowski commented on packages/staking/src/features/delegation-card/DelegationTooltip.css.ts
> +  background: theme.colors.$tooltipContainerBgColor,
```suggestion
  background: theme.colors.$tooltipBgColor,
```

2023-10-11 23:36 UTC, szymonmaslowski commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +type TooltipContentProps<T> =
I would suggest making the API of the Tooltip component more pleasant for the devs. Please take a look at this suggestion:
```
import { isValidElement } from 'react';
...
type TooltipComponent<T> = ((props: {
  active: boolean;
  name?: string;
  payload: T;
}) => React.ReactNode)

type Tooltip<T> = React.ReactElement | TooltipComponent<T>;

type PieChartBaseProps<T extends object> = {
  ...
  tooltip?: Tooltip<T>;
}
...
const makeTooltipContent = <T>(TooltipComponent: TooltipComponent<T>) => ({ active, payload }: {
  active?: boolean;
  payload?: { name?: string; payload?: T }[];
}) => (
  <TooltipComponent
    active={!!active}
    name={payload?.[0].name}
    payload={payload?.[0].payload}
  />
);
...
const tooltipContent = useMemo(() =>
  isValidElement(tooltip)
    ? tooltip
    : makeTooltipContent(tooltip),
  [tooltip],
);
...
<Tooltip
  ...
  content={tooltipContent}
/>
```

cc: @przemyslaw-wlodek

2023-10-12 09:04 UTC, przemyslaw-wlodek requested changes

2023-10-12 09:04 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +type TooltipContentProps<T> =
Looks nice! I think it could be even simplified but I'd like to play with it locally.

e.g. we don't need a `Tooltip` type (we can omit `React.ReactElement`)
```
type PieChartBaseProps<T extends object> = { ... tooltip?: TooltipComponent<T>; }
```

2023-10-12 09:49 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +                <Box>{apy ? `${apy}%` : '-'}</Box>
Yes, but I don't think ros is currently available.

2023-10-12 10:14 UTC, przemyslaw-wlodek commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +                <Box>{apy ? `${apy}%` : '-'}</Box>
Yep, Confirmed APY and ROS in our example mean the same. Apologies for the confusion

2023-10-12 15:25 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationCard.tsx
> +  saturation?: string | number | undefined;
Fixed on 512aeac

2023-10-12 15:26 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationTooltip.css.ts
> +  background: theme.colors.$tooltipContainerBgColor,
Fixed on https://github.com/input-output-hk/lace/commit/512aeace244746783a5e43ad13eeb674c4a54e5a

2023-10-12 15:26 UTC, greatertomi commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +type TooltipContentProps<T> =
Fixed on e41f849

2023-10-12 16:45 UTC, greatertomi commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
Added on 2c5abfb

2023-10-13 07:12 UTC, refi93 commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +  tooltip?: ReactNode;
this doesn't seem type safe nor in line with @szymonmaslowski 's [suggestions](https://github.com/input-output-hk/lace/pull/616#discussion_r1355884124) in that sense as it allows basically any react component if I understood correctly, can you clarify what was the reason to broaden this type as much?

2023-10-13 07:21 UTC, refi93 commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +  tooltip?: ReactNode;
seems like the original comment with the same question somehow doesn't appear here, linking it: https://github.com/input-output-hk/lace/commit/e41f849e95c08377ba9996607c84db4d63f465a5#r129887710

2023-10-13 07:36 UTC, greatertomi commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +  tooltip?: ReactNode;
Responded here: https://github.com/input-output-hk/lace/commit/e41f849e95c08377ba9996607c84db4d63f465a5#r129887938

2023-10-13 09:42 UTC, greatertomi commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +type TooltipContentProps<T> =
I added a comment about this change here: https://github.com/input-output-hk/lace/commit/e41f849e95c08377ba9996607c84db4d63f465a5#r129887938

2023-10-25 13:04 UTC, oldGreg5 approved these changes

2023-10-25 15:32 UTC, szymonmaslowski requested changes
Just a few last comments 😉

2023-10-25 15:32 UTC, szymonmaslowski commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +// eslint-disable-next-line react/no-multi-comp
Is this comment relevant? I can't see another component. Please double check that 🙏

2023-10-26 04:34 UTC, greatertomi commented on packages/staking/src/features/delegation-card/DelegationTooltip.tsx
> +  const { t } = useTranslation();
Fixed on 9c33d93

2023-10-26 04:34 UTC, greatertomi commented on packages/ui/src/design-system/pie-chart/pie-chart.component.tsx
> +// eslint-disable-next-line react/no-multi-comp
Fixed on 9c33d93

2023-10-26 11:25 UTC, szymonmaslowski approved these changes

2023-10-26 11:30 UTC, przemyslaw-wlodek approved these changes
💪🏻 🍻

2023-10-26 11:31 UTC, merged