Lw 8595 stakepool drawer
input-output-hk/lace pull request #626
Opened 2023-10-10 09:20 UTC by oldGreg5

# Checklist

- [ ] [LW-8595](https://input-output.atlassian.net/browse/LW-8595)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Extended View - Staking - Stakepool drawer tests

2023-10-10 15:31 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/multidelegation/StakePoolDetailsAssert.ts
> +  async assertStakePoolDetailsModalIsNotOpened() {
I'd rather replace `modal` with `drawer` in `assertStakePoolDetailsModalIsNotOpened` as it could be a little bit misleading.

2023-10-10 15:38 UTC, wklos-iohk requested changes

2023-10-10 15:38 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +Then(/^I see drawer with "([^"]*)" stake pool details and a buttons for staking$/, async (stakePoolName: string) => {
Seems to be similar to L75-81

2023-10-11 07:08 UTC, wklos-iohk approved these changes

2023-10-11 07:31 UTC, ljagiela approved these changes

2023-10-11 08:47 UTC, merged