feat(staking): [LW-7508] add un-delegation functionality
input-output-hk/lace pull request #634
Opened 2023-10-11 09:21 UTC by xdzurman

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Always allow removing pools from preferences drawer. If the last pool was removed, render the sad smiley content. I chose the easier alternative to get this out quick - i.e., you can remove pools not just in overview Management drawer, but also in Browse pools to not complicate the code. Also adjusted the result screen (see screenshots).

## Testing

Manage current portfolio > Remove all pools > continue, sign the transaction

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/22454337/3d85c806-67c3-466c-8796-5dc0bd155103)
![image](https://github.com/input-output-hk/lace/assets/22454337/d36d83e3-e871-4922-9a9b-5b88eeeb4aa7)
![image](https://github.com/input-output-hk/lace/assets/22454337/8f6dfb66-c8a8-4527-aa34-bb047f17401b)
![image](https://github.com/input-output-hk/lace/assets/22454337/156ba7e8-53a6-4031-be16-f74a931edd12)

2023-10-11 10:13 UTC, refi93 commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +  if (!store.draftPortfolio || store.draftPortfolio.length === 0) return { valid: true };
nitpick - I'd consider re-writing it a bit more concisely:

```suggestion
  if (!store.draftPortfolio?.length) return { valid: true };
```

2023-10-11 10:22 UTC, refi93 commented on packages/staking/src/features/drawer/preferences/empty.svg
I'd consider giving this a more descriptive name, perhaps `sad-smiley.svg`. Moreover, took me a while to realize that `<Empty />` actually refers to a pricture and not some placeholder "empty" component, `<SadSmiley />` would be obvious at first sight

2023-10-11 10:29 UTC, refi93 commented on packages/staking/src/features/drawer/preferences/NoPoolsSelected.tsx
> +    </div>
nitpick - I'd consider using the ui component `Box` which leverages the `@lace/ui` framework and I'd consider dropping the button style as it seems overall the preferred way in the codebase to use the `mt` prop. Moreover, I'd consider moving the "weight" property of the `Text.Body.Normal` within the styles to keep the styles for the respective component in a single place

```suggestion
    <Box className={styles.container}>
      <Empty className={styles.icon} />
      <Text.Body.Normal className={styles.text}>
        {t('drawer.preferences.noSelectedPools')}
      </Text.Body.Normal>
      <Box mt="$40">
        <Button.CallToAction label={t('drawer.preferences.browsePools')} onClick={onBrowsePoolsButtonClick} />
      </Box>
    </Box>
```

2023-10-11 10:52 UTC, refi93 approved these changes
only minor suggestions, other than that LGTM

2023-10-12 14:35 UTC, szymonmaslowski approved these changes
Just a few minor nitpicks. Approving already 😉

2023-10-12 14:35 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolDetails.tsx
> +  if (!store.draftPortfolio || store.draftPortfolio.length === 0) return { valid: true };
I think our lint rules will allow for
```suggestion
  if (store.draftPortfolio?.length !== 0) return { valid: true };
```

2023-10-12 14:35 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/preferences/NoPoolsSelected.css.ts
> +export const button = style({
it is really a nitpick, but I don't have other things to comment so... 😆 this class might be removed if you add margin-bottom to the text class 😉

2023-10-24 10:36 UTC, przemyslaw-wlodek requested changes

2023-10-24 10:36 UTC, przemyslaw-wlodek commented on packages/staking/src/features/Drawer/preferences/sad-smiley.svg
Let's discuss placing assets in the common dir in staking, like @refi93 [suggested](https://github.com/input-output-hk/lace/pull/659/files#r1369308748).

2023-10-24 11:11 UTC, przemyslaw-wlodek approved these changes
Sorry, I wanted to approve 😄 These are just a couple of minor improvements that can be done.

2023-11-06 07:44 UTC, xdzurman commented
Blocked by a bug in js sdk - https://input-output.atlassian.net/browse/LW-8993

2023-11-16 16:14 UTC, ljagiela requested changes
My issues described in Jira.

2024-02-29 13:39 UTC, merged