feat(staking): [LW-8574] ellipsize long pool names in confirmation
input-output-hk/lace pull request #637
Opened 2023-10-11 13:35 UTC by xdzurman

# Checklist

- [ ] JIRA - LW-8574
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Ellipsize pool names if longer than 15 chars. Theoretically more could fit, but if the name is in Caps, the characters are wider, so playing it safe here.

Last item also had a different font size, so I removed that.

## Testing

Select long pool names into portfolio. In confirmation, make sure they're ellipsized if they're too long (with tooltip), and they don't overlap as shown in JIRA.

## Screenshots

![image](https://github.com/input-output-hk/lace/assets/22454337/e28ef6ad-d9ed-4f6b-ab37-9c5ea048f017)

2023-10-12 14:43 UTC, szymonmaslowski approved these changes
Too few changes in here 😛 Perfect PR for making some ocasional improvements 😜

2023-10-12 14:43 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +const EllipsizedPoolName = ({ stakePool }: { stakePool: DraftPortfolioStakePool }) => {
That's a really small PR so it is a perfect case for making some improvements 😄 How about creating a `confirmation` directory and put there all components and utilities from this file as separate files? 😉 Please take a look at the preferences directory as an example. Of course, this is just a suggestion 😉

2023-10-12 14:43 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +            text={<EllipsizedPoolName {...{ stakePool }} />}
```suggestion
            text={<EllipsizedPoolName stakePool="stakePool" />}
```
Alternatively, allow for passing just a pool name.

2023-10-13 12:10 UTC, szymonmaslowski requested changes

2023-10-13 12:10 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/confirmation/StakePoolConfirmationContent.tsx
> +/* eslint-disable react/no-multi-comp */
Could you please use `git mv` to rename `StakePoolConfirmation` to `StakePoolConfirmationContent`? This way we will preserve part of history for the `StakePoolConfirmationContent`

2023-10-13 12:10 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/confirmation/StakePoolConfirmation.module.scss
> +// TODO: refactor to .css.ts, split to multiple files
Please split or rename this file to make it belonging to specific components 🙏

2023-10-13 12:10 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/confirmation/body/StakePoolConfirmationBody.tsx
> +/* eslint-disable react/no-multi-comp */
Please rename the directory `body` to `StakePoolConfirmationBody`. We had a rule to name the directory the same as the component if that component is the main thing of this directory. I think we had it written in the staking readme but I can't find it now. Probably it disappeared after migration from the old repo :(

2023-10-13 12:10 UTC, szymonmaslowski commented on packages/staking/src/features/drawer/confirmation/body/StakePoolConfirmationBody.tsx
> +/* eslint-disable react/no-multi-comp */
Please split this file to multiple components instead of disabling this rule 🙏

2023-10-13 13:43 UTC, xdzurman commented on packages/staking/src/features/drawer/confirmation/body/StakePoolConfirmationBody.tsx
> +/* eslint-disable react/no-multi-comp */
ehh there are shared styles between the components and they are getting quite complex, I'd rather not split  these small helper components away
![image](https://github.com/input-output-hk/lace/assets/22454337/ab347d35-69e2-4804-9044-0aefd099ca52)
![image](https://github.com/input-output-hk/lace/assets/22454337/909600b4-f317-40af-bf9b-962a5ec4c838)

2023-10-30 09:14 UTC, szymonmaslowski approved these changes

2023-10-30 14:39 UTC, oldGreg5 approved these changes

2023-10-31 10:43 UTC, merged