feat(staking): [LW-8628] read portfolio persistence data
input-output-hk/lace pull request #640
Opened 2023-10-11 22:16 UTC by szymonmaslowski

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-10-23 14:30 UTC, szymonmaslowski commented on package.json
> +    "base-command-for-build-scripts": "wsrun --prefix -trame ${APP_NAME:+-p \"@lace/$APP_NAME\"} ${EXCLUDE_APP:+-x \"@lace/$APP_NAME\"} ${EXCLUDE_BROWSER:+-x \"@lace/browser-extension-wallet\"}",
Additional `e` parameter makes the command failing if an error happens to any of the executed scripts
The `yarn browser build` will fail fast if e.g. `common` package fails to build

2023-10-23 14:30 UTC, szymonmaslowski commented on packages/staking/src/features/Drawer/preferences/PoolDetailsCard/PoolDetailsCardData.tsx
> +          {savedPercentage || '-'} {!!savedPercentage && <Text.Body.Small weight="$medium">%</Text.Body.Small>}
Casting to boolean to avoid displaying unnecessary `0`

2023-10-23 14:32 UTC, szymonmaslowski commented on packages/staking/src/features/overview/helpers/isPortfolioDrifted.ts
> +  if (onChainPercentageSum !== PERCENTAGE_SCALE_MAX) return true;
A case when there are more funds in the wallet and overview shows them as unallocated.

2023-10-23 14:33 UTC, szymonmaslowski commented on packages/staking/src/features/overview/helpers/isPortfolioDrifted.ts
> +  if (savedPercentageMissing) return false;
In case there is `onChainPercentages` sum up to 100% BUT there is no `savedPercentage` (portfolio built before persistence) then there is no point in comparing the on-chain to saved. We cannot detect if there was a drift - ignoring this case

2023-10-23 14:34 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts
> +      sliderIntegerPercentage: cp.savedIntegerPercentage || cp.onChainPercentage,
Falling back slider values to on-chain values if there is no saved values

2023-10-23 14:35 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/sanitizePercentages.ts
> +// If percentages add up to 100, normalize them. Otherwise, round them to N decimal places.
Moved from https://github.com/input-output-hk/lace/pull/640/files#diff-8c2da5fb662c55f1e206a0dc2c425e019a4aaa051ad51af64e5dace701b9615cL30

2023-10-23 14:36 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts
> +  sanitizePercentages({
Sanitizing in case `sliderIntegerPercentage` received `onChainPercentage` values

2023-10-24 08:27 UTC, refi93 commented on packages/staking/src/features/overview/helpers/isPortfolioDrifted.ts
> +  if (onChainPercentageSum !== PERCENTAGE_SCALE_MAX) return true;
I'd find it more resilient to modify the `getPortfolioTotalPercentageDrift()` function to deal with partially delegated portfolios which then removes the need for this check which may result in false positives, if just a small fraction of funds is undelegated (imagine the extreme case sending 1 ADA to an undelegated address to a wallet with 1M ADA, which would trigger this condition which is IMHO not desired)

I'd propose something like this:

```
const getPortfolioTotalPercentageDrift = (portfolio: CurrentPortfolioStakePool[]): number => {
  const onChainPercentageSum = sumPercentagesSanitized({
    items: portfolio,
    key: 'onChainPercentage',
  });
  // note that "on chain" percentages of the portfolio may not add up if part of the funds
  // reside on an undelegated stake key and the code below deals with that edge-case
  const totalDelegatedValue = Wallet.BigIntMath.sum(portfolio.map(({ value }) => value));
  const totalValue = new BigNumber(totalDelegatedValue.toString()).times(PERCENTAGE_SCALE_MAX / onChainPercentageSum);
  return sum(
    portfolio.map(({ value, savedIntegerPercentage }) => {
      const currentPercentage = new BigNumber(value.toString()).div(totalValue).times(PERCENTAGE_SCALE_MAX).toNumber();
      return Math.abs(savedIntegerPercentage - currentPercentage);
    })
  );
};
```

With the proposed version of `getPortfolioTotalPercentageDrift()` the `if (onChainPercentageSum !== PERCENTAGE_SCALE_MAX) return true;` check will become redundant

2023-10-24 08:31 UTC, refi93 commented on packages/staking/src/features/overview/helpers/isPortfolioDrifted.ts
>  // TODO: move this file to store. It gets imported also outside the overview feature so the store seems better place.
as part of this PR I'd consider already moving this helper to store as suggested, should be a small change

2023-10-24 08:33 UTC, refi93 commented on packages/staking/src/features/overview/helpers/isPortfolioDrifted.ts
> +  if (savedPercentageMissing) return false;
I'd leave a comment in the code clarifying this. In the future, when portfolios would be persisted by default for a long time already, it may no longer be obvious why this check is here

2023-10-24 08:37 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +              savedIntegerPercentage: mapOfPoolIdBySavedPercentages[stakePool.hexId] || 0,
I think it would be better for readability if we explicitly captured with `null` that the given saved percentage is just missing:

```suggestion
              savedIntegerPercentage: mapOfPoolIdBySavedPercentages[stakePool.hexId] ?? null,
```

e.g. `isPortfolioDrifted()` helper and the check for missing percentage would become more readable as checking for `zero` (which one may argue is a valid value) is IMHO unnecessarily "hacky"

2023-10-24 10:23 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +        }
I'd consider simplifying/extracting this logic into a helper `mapPoolsToSavedPercentages`:

```typescript
const getPoolsSavedPercentages = (pools: Wallet.Cardano.Cip17Pool[]) => {
  const weightsSum = Number(Wallet.BigIntMath.sum(pools.map(({ weight }) => BigInt(weight))));
  // eslint-disable-next-line unicorn/no-array-reduce
  return pools.reduce<Record<Wallet.Cardano.PoolIdHex, number>>((acc, { id, weight }) => {
    acc[id] = (weight / weightsSum) * PERCENTAGE_SCALE_MAX;
    return acc;
  }, {});
};
```

2023-10-24 10:30 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +        }
or I guess it would be even more convenient if the helper already sanitized the percentages:

```typescript
const mapPoolsToSavedIntegerPercentages = (pools: Wallet.Cardano.Cip17Pool[]) => {
  const weightsSum = Number(Wallet.BigIntMath.sum(pools.map(({ weight }) => BigInt(weight))));
  const rawPoolPercentages = pools.map(({ id, weight }) => ({
    id,
    percentage: (weight / weightsSum) * PERCENTAGE_SCALE_MAX,
  }));
  const sanitizedPoolPercentages = sanitizePercentages({
    decimals: 2,
    items: rawPoolPercentages,
    key: 'percentage',
  });

  // eslint-disable-next-line unicorn/no-array-reduce
  return sanitizedPoolPercentages.reduce<Record<Wallet.Cardano.PoolIdHex, number>>((acc, { id, percentage }) => {
    acc[id] = percentage;
    return acc;
  }, {});
};
```

2023-10-24 12:10 UTC, szymonmaslowski commented on packages/staking/src/features/overview/helpers/isPortfolioDrifted.ts
>  // TODO: move this file to store. It gets imported also outside the overview feature so the store seems better place.
IMO it should not be placed in the store if it does not use it. I can see usage in the overview and the drawer, so it doesn't belong to any of the `features`' directories, so it should get its own directory 😉 I will think about it.

2023-10-24 12:15 UTC, szymonmaslowski commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +              savedIntegerPercentage: mapOfPoolIdBySavedPercentages[stakePool.hexId] || 0,
I considered `null` at first, but I realized it requires more changes in places, where we read the value. In those places, we would need to fall back it to 0 anyway. Not in all the places, though. I am tentative about this, but I support your argument about readability.

2023-10-24 20:10 UTC, refi93 commented on packages/staking/src/features/store/delegationPortfolioStore/useDelegationPortfolioStore.ts
> +        const mapOfPoolIdBySavedPercentages = makeMapOfSavedPercentages(delegationPortfolio?.pools);
naming nitpick: `mapOfPoolIdBySavedPercentages` makes it sound as if the percentages were the keys which obviously isn't the case, I'd consider naming it `mapOfPoolIdToSavedPercentages` instead

2023-10-24 20:16 UTC, refi93 commented on packages/staking/src/features/portfolio-drift/isPortfolioDrifted.ts
> +  currentPortfolio.some(({ savedIntegerPercentage }) => !savedIntegerPercentage);
I guess this should actually be the inverse: 

```suggestion
  currentPortfolio.every(({ savedIntegerPercentage }) => savedIntegerPercentage);
```

also, I'd consider calling the function `hisPortfolioWithSavedPercentages` which IMHO aligns better with its purpose/logic

2023-10-24 20:19 UTC, refi93 requested changes
looks good 👍 just last few nitpicks

2023-10-25 06:16 UTC, szymonmaslowski commented on packages/staking/src/features/portfolio-drift/isPortfolioDrifted.ts
> +  currentPortfolio.some(({ savedIntegerPercentage }) => !savedIntegerPercentage);
Nice catch! Thanks for spotting this! I might have missed this case while testing 😅

2023-10-25 07:57 UTC, refi93 approved these changes

2023-10-26 06:24 UTC, merged