feat: add confirmation modal to pool management drawer
input-output-hk/lace pull request #652
Opened 2023-10-17 23:08 UTC by greatertomi

# Checklist

- [x] JIRA - LW-7931
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="706" alt="Screenshot 2023-10-18 at 00 05 18" src="https://github.com/input-output-hk/lace/assets/48496855/fd2d237b-c13e-4a2b-a770-592a1c269812">

<img width="704" alt="Screenshot 2023-10-18 at 00 06 51" src="https://github.com/input-output-hk/lace/assets/48496855/561212d0-c80e-4ee5-bd47-475b167c2638">

2023-10-24 10:50 UTC, przemyslaw-wlodek requested changes

2023-10-24 10:50 UTC, przemyslaw-wlodek commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +  });
The current name suggests it's `boolean` but it's an object with configuration.

1. What do you think about a nullable state like this? (I will follow up with another comment and show you how it simplifies things)

```suggestion
  const [openPoolManagementModal, setOpenPoolManagementModal] = useState<PoolsManagementModalType>(null);
```

2. Should we rename `PoolsManagementModal` to e.g. `PoolsManagementConfirmationModal`?

2023-10-24 10:50 UTC, przemyslaw-wlodek commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +      return setConfirmationModalVisible((prevState) => ({ ...prevState, reduction: true }));
Based on previous comment then we can do:

`setOpenPoolManagementModal(PoolsManagementModalType.REDUCTION)`

2023-10-24 10:50 UTC, przemyslaw-wlodek commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +    if (JSON.stringify(currentPortfolioRatios) !== JSON.stringify(draftPortfolioRatios))
You can try to utilize lodash here :)

If you want to have exactly the same order and values:
```
if (!isEqual(currentPortfolioRatios, draftPortfolioRatios))
```

If you want to have exactly the same values but order doesn't matter:
```
if (!difference(currentPortfolioRatios, draftPortfolioRatios).length)
```

2023-10-24 10:50 UTC, przemyslaw-wlodek commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +        visible={confirmationModalVisible.reduction || confirmationModalVisible.adjustment}
Also based on the previous comment we can do:

```suggestion
        type={openPoolManagementModal}
        visible={!!openPoolManagementModal}
```

2023-10-24 10:50 UTC, przemyslaw-wlodek commented on packages/staking/src/features/modals/PoolsManagementModal.tsx
> +  const translation = {
I'm sorry but I am not sure if we follow this kind of pattern anywhere. Can we just pass the translations in place? This object is recreated with each render. Of course it might not impact the performance but I don't see the reason to keep it.

2023-10-24 21:08 UTC, greatertomi commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +  });
`poolsManagementConfirmationModal` is more descriptive to me.

2023-10-24 21:40 UTC, greatertomi commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +  });
Fixed on c61b8ac

2023-10-24 21:40 UTC, greatertomi commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +      return setConfirmationModalVisible((prevState) => ({ ...prevState, reduction: true }));
Fixed on c61b8ac

2023-10-24 21:41 UTC, greatertomi commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +        visible={confirmationModalVisible.reduction || confirmationModalVisible.adjustment}
Fixed on c61b8ac

2023-10-24 21:41 UTC, greatertomi commented on packages/staking/src/features/modals/PoolsManagementModal.tsx
> +  const translation = {
Fixed on 29189b0

2023-10-24 21:42 UTC, greatertomi commented on packages/staking/src/features/drawer/StakePoolConfirmation.tsx
> +    if (JSON.stringify(currentPortfolioRatios) !== JSON.stringify(draftPortfolioRatios))
Fixed on 8c60402

2023-10-25 06:22 UTC, szymonmaslowski commented
Please rename the PR to `feat(staking): [LW-your card number] add confirmation modal to pool management drawer`

2023-10-25 13:19 UTC, mrcnk approved these changes

2023-10-26 07:19 UTC, przemyslaw-wlodek approved these changes

2023-10-26 07:19 UTC, przemyslaw-wlodek commented
Thank you @greatertomi! 😄 Great job! 💪🏻

2023-10-26 10:05 UTC, oldGreg5 approved these changes

2023-10-26 11:22 UTC, merged