feat(extension): voting procedures
input-output-hk/lace pull request #655
Opened 2023-10-20 16:43 UTC by renanvalentin

2023-10-23 12:15 UTC, lucas-barros requested changes

2023-10-23 12:15 UTC, lucas-barros commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
>  export const getTitleKey = (txType: TxType): string => {
Add the title logic here.

2023-10-23 12:15 UTC, lucas-barros commented on packages/core/src/ui/components/VotingProcedures/VotingProcedures.tsx
> +              <Fragment key={votingProcedure.anchor.hash}>
Anchor can be `null` here.

2023-10-24 16:22 UTC, mchappell approved these changes

2023-10-24 16:28 UTC, merged

2023-10-24 16:32 UTC, renanvalentin commented
The correct ticket for is [c91552c](https://github.com/input-output-hk/lace/commit/c91552c09abcb77d0a96fbaffd71294796bc7dd2) [LW-8489]