feat: add warning banner for retiring, retired and saturated stake pools
input-output-hk/lace pull request #659
Opened 2023-10-23 20:01 UTC by greatertomi

# Checklist

- [x] JIRA - LW-7837
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Add a warning banner when any pool in the user portfolio is saturated, retiring or retired.

## Screenshots

<img width="951" alt="Screenshot 2023-10-23 at 20 29 43" src="https://github.com/input-output-hk/lace/assets/48496855/e2eec690-9410-44f0-837d-666033ce6e7b">

2023-10-23 21:25 UTC, refi93 commented on packages/staking/src/features/overview/StakingNotificationBanner/StakingNotificationBanner.tsx
> +          onBannerClick={onPortfolioDriftedNotificationClick}
the `onPortfolioDriftedNotificationClick` name no longer makes sense as it's being used also for the case of saturated/retired pools which is not related to portfolio drift. To tackle this, I'd consider generalizing the name of the prop to `clickableBannerAction`

2023-10-23 21:27 UTC, refi93 commented on packages/staking/src/features/overview/StakingNotificationBanner/StakingNotificationBanner.tsx
> +          onBannerClick={onPortfolioDriftedNotificationClick}
alternatively, we can just encapsulate this logic into `StakingNotificationBanner` and bind it to `isPopupView` flag (i.e. open management drawer if expanded view, otherwise open expanded view) - I think that would indeed be cleaner

2023-10-23 21:32 UTC, refi93 commented on packages/staking/src/features/overview/StakingNotificationBanner/getCurrentStakingNotification.ts
> +  if (hasSaturatedOrRetiredPools(currentPortfolio)) {
I don't see in the task the priority of the "saturated or retired" notification vs the "drift" one and I can see arguments in favor of either ordering. I'd suggest clarifying the precence of notification in such a case with Fernando, if you already didn't

2023-10-23 21:48 UTC, refi93 commented on packages/staking/src/features/overview/helpers/hasSaturatedOrRetiredPools.ts
> +export const SATURATION_UPPER_BOUND = 100;
I'd consider extracting this constant which is already used in the staking package to a `constants.ts` file within the `helpers` folder

2023-10-23 22:02 UTC, refi93 commented on packages/staking/src/assets/icons/triangle-exclamation.component.svg
to prevent further duplication/inconsistencies of assets I'd consider moving this (together with other icons in this folder, for the sake of consistency) to `packages/ui/assets/icons` folder from where we could import them as we already do e.g. for `chevron-up` icon: https://github.com/input-output-hk/lace/blob/0ce732940b0aea274e9036c491863c21e409b607/packages/staking/src/features/drawer/preferences/PoolDetailsCard/PoolDetailsCard.tsx#L3C1-L3C1

2023-10-23 22:04 UTC, refi93 requested changes
see comments

2023-10-24 11:58 UTC, greatertomi commented on packages/staking/src/features/overview/StakingNotificationBanner/getCurrentStakingNotification.ts
> +  if (hasSaturatedOrRetiredPools(currentPortfolio)) {
I asked Fernando and he said we should show both banners. 8a1ba0d does that.

2023-10-24 12:00 UTC, greatertomi commented on packages/staking/src/features/overview/helpers/hasSaturatedOrRetiredPools.ts
> +export const SATURATION_UPPER_BOUND = 100;
Fixed on 82593bd

2023-10-25 13:27 UTC, mrcnk approved these changes

2023-10-25 14:43 UTC, refi93 commented on packages/staking/src/features/overview/Overview.tsx
> +          <Banner
I'd consider keeping this Banner within the `StakingNotificationBanner` component to keep the notification logic in a single place, otherwise it may become hard to follow what notifications are shown when which may result in undesired combinations of the notifications being shown

I'd suggest refactoring `getCurrentStakingNotification()` to return an array of notifications (most of the time it would be empty or single item, with the exception of saturated/retired pool and drift at the same time) and then this Banner component should be movable into `StakingNotificationBanner` component (which I'd also refactor to take an array of notifications and rename it to `StakingNotificationBanners`

What do you think?

2023-10-25 14:44 UTC, refi93 requested changes
see comment

2023-10-26 07:02 UTC, greatertomi commented on packages/staking/src/features/overview/Overview.tsx
> +          <Banner
I agree. Created an array of notifications here: 97d92bb

2023-10-26 07:25 UTC, refi93 commented on packages/staking/src/features/overview/StakingNotificationBanner/StakingNotificationBanner.tsx
> +          onBannerClick={onPortfolioDriftedNotificationClick}
agreed offline to go with the first suggestion, but naming the flag `onClickableBannerClick` which is simpler while it should make clear enough to the reader that not all banners are clickable

2023-10-26 07:25 UTC, refi93 commented on packages/staking/src/features/overview/StakingNotificationBanner/StakingNotificationBanners.tsx
> +type StakingNotificationBannerProps = {
```suggestion
type StakingNotificationBannersProps = {
```

2023-10-26 07:31 UTC, refi93 approved these changes

2023-10-26 11:02 UTC, oldGreg5 approved these changes

2023-10-26 12:07 UTC, merged