Feat/proposal procedure
input-output-hk/lace pull request #670
Opened 2023-10-26 12:55 UTC by renanvalentin

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-11-30 12:43 UTC, vetalcore requested changes

2023-11-30 12:43 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +    actionId: {
might be null, do we need to hide this section on the ui then?

2023-11-30 12:43 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +      ...(explorerBaseUrl && governanceActionId?.id && { txHashUrl: `${explorerBaseUrl}/${governanceActionId?.id}` })
please validate

2023-11-30 12:43 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/ParameterChangeActionContainer.tsx
> +        minFeeB: minFeeConstant.toString(),
please validate

2023-11-30 12:43 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/ParameterChangeActionContainer.tsx
> +        tau: treasuryExpansion,
please validate

2023-12-05 12:56 UTC, vetalcore requested changes

2023-12-05 12:56 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +      // TODO: voter type is not defined on ProposalProcedures level
@mchappell please suggest

2023-12-05 12:56 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +    // TODO: there is no actionId in Wallet.Cardano.InfoAction;
@mchappell please suggest

2023-12-05 12:56 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/InfoActionContainer.tsx
> +      // TODO: where do i get it from?
@mchappell please suggest

2023-12-05 12:56 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/HardForkInitiationAction/HardForkInitiationAction.tsx
> +        <Metadata label={translations.protocolVersion.major} text={protocolVersion.major} />
what should be the common approach of restyling all the components exported from the ui package
@mchappell @renanvalentin please suggest

2023-12-05 13:46 UTC, vetalcore requested changes

2023-12-12 19:49 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +      // TODO: voter type is not defined on ProposalProcedures level
resolved

2023-12-12 19:49 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/ParameterChangeActionContainer.tsx
> +            (acc, cur) => ({ ...acc, [cur[0]]: cur[1] }),
waiting for an updated from @jackrousian

2023-12-13 14:40 UTC, mchappell requested changes

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/components/ProcedureTypes.ts
> +  anchor?: {
Anchors in a procedure should always be defined

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/components/Procedure.tsx
> +      {data.anchor && (
this should always exist

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/UpdateCommitteeAction/UpdateCommitteeActionAction.tsx
> +        {membersToBeRemoved?.length > 0 && (
this will always be required from the types, but could be an empty set

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/UpdateCommitteeAction/UpdateCommitteeActionAction.tsx
> +        {membersToBeAdded?.length > 0 && (
this will always be required, but could be an empty set

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/TreasuryWithdrawalsAction/TreasuryWithdrawalsAction.tsx
> +        {actionId && (
this will always exist for a governance action

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/ParameterChangeAction/TechnicalGroup.tsx
> +        {costModels.map(({ title, fields }, idx) => (
please add a todo to review cost model syntax/display

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/ParameterChangeAction/ParameterChangeAction.tsx
> +        {anchor && (
should always exist

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/NoConfidenceAction/NoConfidenceAction.tsx
> +      {actionId && (
should always exist for a governance action

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/NewConstitutionAction/NewConstitutionAction.tsx
> +      {actionId && (
should always exist for a governance action

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/InfoAction/InfoAction.tsx
> +      {actionId && (
should always exist for a governance action

2023-12-13 14:40 UTC, mchappell commented on packages/core/src/ui/components/ProposalProcedures/HardForkInitiationAction/HardForkInitiationAction.tsx
> +      {actionId && (
should always exist for a governance action

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/UpdateCommitteeActionContainer.tsx
> +        hash: hash.toString()
please add todo comment to use bech32 in future revision

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/UpdateCommitteeActionContainer.tsx
> +    membersToBeRemoved: [...membersToBeRemoved].map(({ hash }) => ({ hash: hash.toString() }))
please add todo comment to use bech32 in future revision

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/UpdateCommitteeActionContainer.tsx
> +      ...(anchor && {
will always be required

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/TreasuryWithdrawalsActionContainer.tsx
> +      lovelace: Wallet.util.lovelacesToAdaString(withdrawal.coin.toString())
can you check if this is formatted with the coinSymbol at point of display

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/NoConfidenceActionContainer.tsx
> +    ...(governanceActionId && {
always required

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/NoConfidenceActionContainer.tsx
> +      ...(anchor && {
also always required

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/InfoActionContainer.tsx
> +      ...(anchor && {
always required

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +    ...(governanceActionId && {
always required

2023-12-13 14:40 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +      ...(anchor && {
always required

2023-12-13 15:18 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/TreasuryWithdrawalsAction/TreasuryWithdrawalsAction.tsx
> +        {actionId && (
is is typed as `governanceActionId: GovernanceActionId | null;`

2023-12-13 15:19 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/components/ProcedureTypes.ts
> +  anchor?: {
fixed

2023-12-13 15:19 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/components/Procedure.tsx
> +      {data.anchor && (
fixed

2023-12-13 15:19 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/UpdateCommitteeAction/UpdateCommitteeActionAction.tsx
> +        {membersToBeRemoved?.length > 0 && (
fixed

2023-12-13 15:23 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/ParameterChangeAction/TechnicalGroup.tsx
> +        {costModels.map(({ title, fields }, idx) => (
done

2023-12-13 15:29 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/NoConfidenceAction/NoConfidenceAction.tsx
> +      {actionId && (
fixed

2023-12-13 16:01 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/NewConstitutionAction/NewConstitutionAction.tsx
> +      {actionId && (
fixed

2023-12-13 16:01 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/InfoAction/InfoAction.tsx
> +      {actionId && (
fixed

2023-12-13 16:01 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/HardForkInitiationAction/HardForkInitiationAction.tsx
> +      {actionId && (
fixed

2023-12-13 16:01 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/UpdateCommitteeActionContainer.tsx
> +        hash: hash.toString()
done

2023-12-13 16:01 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/UpdateCommitteeActionContainer.tsx
> +    membersToBeRemoved: [...membersToBeRemoved].map(({ hash }) => ({ hash: hash.toString() }))
done

2023-12-13 16:02 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/TreasuryWithdrawalsActionContainer.tsx
> +      lovelace: Wallet.util.lovelacesToAdaString(withdrawal.coin.toString())
added

2023-12-13 16:02 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/NoConfidenceActionContainer.tsx
> +    ...(governanceActionId && {
is either `GovernanceActionId`  or  `null`;

2023-12-13 16:03 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/NoConfidenceActionContainer.tsx
> +      ...(anchor && {
fixed

2023-12-13 16:03 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/InfoActionContainer.tsx
> +      ...(anchor && {
fixed

2023-12-13 16:03 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +    ...(governanceActionId && {
is either `GovernanceActionId`  or  `null`;

2023-12-13 16:03 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/HardForkInitiationActionContainer.tsx
> +      ...(anchor && {
fixed

2023-12-13 16:08 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/ParameterChangeActionContainer.tsx
> +            (acc, cur) => ({ ...acc, [cur[0]]: cur[1] }),
deferring this to another task

2023-12-14 11:00 UTC, merged