feat(staking): add portfolio persistence one-time message
input-output-hk/lace pull request #671
Opened 2023-10-26 15:26 UTC by greatertomi

# Checklist

- [x] JIRA - LW-8837
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Add a one-time announcement modal that shows on the staking view when the user has an active multi-delegation portfolio.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="746" alt="Screenshot 2023-10-26 at 16 11 48" src="https://github.com/input-output-hk/lace/assets/48496855/942529a7-df08-40f0-98bc-fab28a38e201">

2023-10-27 12:30 UTC, refi93 commented on packages/staking/src/features/staking/StakingView.tsx
> +        <PortfolioPersistenceModal visible={multidelegationFirstVisit} onConfirm={triggerMultidelegationFirstVisit} />
`multidelegationFirstVisit` will in practice already be `false` for users that are multidelegating because they obviously visited this section in the past. Therefore this one-time message wouldn't be visible to them.

If I understood that correctly, I think we need to introduce a new flag into local storage besides `multidelegationFirstVisit` (e.g. `multidelegationMigrationWarningSeen`) where we would capture if the user has already seen this banner or not

2023-10-27 12:31 UTC, refi93 requested changes
see comment

2023-10-27 13:39 UTC, refi93 commented on packages/staking/src/features/staking/StakingView.tsx
> +        <PortfolioPersistenceModal visible={multidelegationFirstVisit} onConfirm={triggerMultidelegationFirstVisit} />
clarified offline - the important case where the `multidelegationFirstVisit` flag alone would fail is that users that have seen the original "multidelegationFirstVisit" modal in earlier releases won't see the new modal at all because the `multidelegationFirstVisit` flag is already false for them. We can't just reset the `multidelegationFirstVisit` flag to `false` either because it would obviously result in the original "first visit" modal to appear for users without an active portfolio.

So the only viable solution I see is introducing a new separate flag for this modal and update the logic to handle it appropriately together with the pre-existing `multidelegationFirstVisit` ensuring the correct modal is shown (or not) to the user

2023-10-30 14:15 UTC, greatertomi commented on packages/staking/src/features/staking/StakingView.tsx
> +        <PortfolioPersistenceModal visible={multidelegationFirstVisit} onConfirm={triggerMultidelegationFirstVisit} />
Fixed on f794d58

2023-10-31 10:37 UTC, przemyslaw-wlodek approved these changes
There's a bit of duplication here but that's fine for now. Let's ship it :) Thanks for addressing @refi93 comments

2023-10-31 13:37 UTC, emiride approved these changes
Works as expected

2023-10-31 14:14 UTC, merged