test(extension): [LW-8666] add e2e tests for staking empty states & start staking
input-output-hk/lace pull request #681
Opened 2023-10-27 13:18 UTC by ljagiela

2023-10-27 13:47 UTC, oldGreg5 requested changes

2023-10-27 13:47 UTC, oldGreg5 commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +  await localStorageInitializer.disableShowingMultidelegationBetaBanner();
Don't we want to use step for this for consistency? 
'And I disable showing Multidelegation beta banner'
We wanted to refactor this step later and make it part of wallet setup or some other appropriate place to disable it for all, unless we explicitly want it to be shown.

2023-10-27 14:02 UTC, oldGreg5 approved these changes

2023-10-30 08:18 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +Then(/^I click Get Started step '(1|2)' link$/, async (linkNumber: '1' | '2') => {
I'd suggest to wrap `Get Started`  with double quotes to distinguish that label and remove single quotes that are wrapping step number as here are only 2 predefined options.

2023-10-30 09:18 UTC, ljagiela commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +  await localStorageInitializer.disableShowingMultidelegationBetaBanner();
There is no way now to workaround this. I think we will handle it in separate PR.

2023-10-30 11:13 UTC, merged