[WIP] feat(staking): load multi-delegation for HW wallets
input-output-hk/lace pull request #686
Opened 2023-10-30 15:08 UTC by xdzurman

2023-10-31 16:21 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts
> +// TODO: should not have DrawerBack, it's not used
👍🏻 please resolve when PR isn't WIP

2023-11-02 08:25 UTC, xdzurman commented on packages/staking/src/features/Drawer/StakePoolDetailsDrawer.tsx
> +      return popupView ? closeDrawer() : onGoBack();
It does not work without it. This is a fix

2023-11-02 08:31 UTC, przemyslaw-wlodek commented on packages/staking/src/features/Drawer/StakePoolDetailsDrawer.tsx
> +      return popupView ? closeDrawer() : onGoBack();
Sorry, you're right -> I was reviewing this in a rush. Then the name of the function is misleading as it doesn't create a callback, it is a callback 😅

2023-11-02 09:17 UTC, xdzurman commented on packages/staking/src/features/Drawer/StakePoolDetailsDrawer.tsx
> +      return popupView ? closeDrawer() : onGoBack();
I'll rename it

2023-11-02 11:18 UTC, przemyslaw-wlodek approved these changes
Can't wait for the reactions on the new releases. 😄

2023-11-08 09:34 UTC, refi93 commented
I guess for Trezor multidelegation hasn't been officiallt released yet, probably neither for Ledger (latest available version I found in Ledger Live is 5.0.1) and if that's the case I think we should add separate feature flags for enabling multidelegation for trezor and ledger wallets to ensure the feature doesn't become live before hw wallets actually support this, or am I missing something?

https://trezor.io/learn/a/firmware-changelog

https://github.com/vacuumlabs/ledger-app-cardano-shelley/commits/develop -> multidelegation available in Ledget Cardano app 6.1.2 (not released yet, apparently)

2023-11-08 09:35 UTC, refi93 requested changes
I believe a feature flag to gate the feature in production is probably needed, see comment

2023-11-09 15:27 UTC, refi93 approved these changes

2023-11-15 11:57 UTC, oldGreg5 approved these changes

2023-11-28 19:20 UTC, merged