Feat/lw 6437 past epochs rewards chart
input-output-hk/lace pull request #718
Opened 2023-11-09 09:51 UTC by mrcnk

# Checklist

- [x] JIRA
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

- Add stacked bar chart for rewards from past 5/15 epochs.

## Screenshots

![CleanShot 2023-11-09 at 10 50 33@2x](https://github.com/input-output-hk/lace/assets/16132011/a5d4cdc6-657b-4fc1-89db-a4166e521727)

2023-11-09 11:32 UTC, xdzurman reviewed
Few minor suggestions

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/EpochsSwitch.tsx
> +export type EpochsSwitchProps = {
```suggestion
type EpochsSwitchProps = {
```

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/EpochsSwitch.tsx
> +    <Text.Body.Normal>Epochs:</Text.Body.Normal>
```suggestion
    <Text.Body.Normal>{t('...')}:</Text.Body.Normal>
```

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/EpochsSwitch.tsx
> +        return <Component key={i} label={`Last ${option}`} onClick={() => setEpochsCount(option)} />;
This should go into translations as well I think

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/RewardsChart.module copy.scss
This file looks like a forgotten deletion

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/RewardsChart.module.scss
This `chartContainer` does not seem to be used

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/RewardsChartTooltip.tsx
> +          <Text.Body.Small weight="$semibold">Epoch {label}</Text.Body.Small>
```suggestion
          <Text.Body.Small weight="$semibold">{t('...')}</Text.Body.Small>
```

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/RewardsChartTooltip.tsx
> +                      <Text.Body.Small>Rewards: {payload[i]?.value} ADA</Text.Body.Small>
```suggestion
                      <Text.Body.Small>{t('...')}</Text.Body.Small>
```

2023-11-09 11:32 UTC, xdzurman commented on packages/staking/src/features/activity/useRewardsByEpoch.ts
> +  }, [epochsCount, rewardsHistory]);
```suggestion
  }, [epochsCount, rewardsHistory, walletStoreBlockchainProvider.stakePoolProvider]);
```

2023-11-09 14:24 UTC, refi93 commented on packages/staking/src/features/activity/Activity.tsx
> +      <PastEpochsRewards />
I think this component should be nested within the "false" branch of the condition below, so that it's not mounted if there's no staking activity where this graph wouldn't make sense, if I understood correctly

2023-11-09 14:27 UTC, refi93 commented on packages/staking/src/features/activity/EpochsSwitch.module.scss
I'd consider moving all "epoch rewards charts" stuff within its own subfolder to separate it conceptually from the rewards history, making the file structure easier to follow

2023-11-09 14:33 UTC, refi93 commented on packages/staking/src/features/activity/const.ts
> +export const GRAYSCALE_PALETTE = [
the amount of pools delegated to in the past is potentially unbounded, so I'd consider making this a function which would generate the shades of gray instead of having them hardcoded. I think the total amount of poolsis known at the moment of using it, so it could be a fairly straightforward helper which would spread the shades returned evenly across the range.

Alternatively, I'd consider adding there a fall back which in case of an unmatched color would just randomly (using the index as the seed) pick a shade of grey if the index happens to be outside the range of the pallete

2023-11-09 14:41 UTC, refi93 commented on packages/staking/src/features/activity/usePoolInPortfolioPresence.tsx
> +export const usePoolInPortfolioPresence = () => {
I'd consider making this a selector and moving it to the selectors declared in `features/store/delegationPortfolioStore/selectors.ts` which seem to be of similar nature

2023-11-09 14:52 UTC, refi93 commented on packages/staking/src/features/activity/useRewardsByEpoch.ts
> +  }, [epochsCount, rewardsHistory]);
If you added just `walletStoreBlockchainProvider` wouldn't it work? If it wouldn't work, I'd leave an eslint ignore comment to silence this warning and a comment explanining this issue to give the context to whoever would be reading this code in the future

2023-11-09 14:56 UTC, refi93 commented on packages/staking/src/features/activity/useRewardsByEpoch.ts
though not strictly a "store", I'd consider moving this file to the `store` folder as it serves to access external data which I'd consider a "store" in the broader sense (a repository of data that other components can read from)

2023-11-09 15:13 UTC, refi93 commented on packages/staking/src/features/activity/RewardsChartTooltip.tsx
> +                    <PoolIndicator color={poolInPortfolio ? PIE_CHART_DEFAULT_COLOR_SET[i] : GRAYSCALE_PALETTE[i]} />
I believe this may not ensure consistent coloring of the pools across epochs, and even if it does, it doesn't look very evident from the code. I'd suggest making the mapping of pools to colors upfront to remove this doubt

2023-11-09 15:16 UTC, refi93 requested changes
see comments

2023-11-10 17:48 UTC, refi93 commented on packages/staking/src/features/activity/useRewardsByEpoch.ts
> +  }, [epochsCount, rewardsHistory]);
done as I suggested, seems to work without issues 👍

2023-11-10 17:49 UTC, refi93 commented on packages/staking/src/features/activity/const.ts
> +export const GRAYSCALE_PALETTE = [
addressed here: https://github.com/input-output-hk/lace/pull/718/files#diff-685d6d538e6cbc3ab0925ac44d90afccae975c4b246b8c49329fbfcc25ae1147R23

2023-11-10 17:50 UTC, refi93 commented on packages/staking/src/features/activity/useRewardsByEpoch.ts
I ended up moving this into a "hooks" subfolder within the component as in the current form I'd consider it an ad-hoc hook meant really just for the chart

2023-11-10 17:50 UTC, refi93 commented on packages/staking/src/features/activity/RewardsChartTooltip.tsx
> +                    <PoolIndicator color={poolInPortfolio ? PIE_CHART_DEFAULT_COLOR_SET[i] : GRAYSCALE_PALETTE[i]} />
fixed with https://github.com/input-output-hk/lace/pull/718/files#diff-685d6d538e6cbc3ab0925ac44d90afccae975c4b246b8c49329fbfcc25ae1147R23

2023-11-10 17:51 UTC, refi93 commented on packages/staking/src/features/activity/usePoolInPortfolioPresence.tsx
> +export const usePoolInPortfolioPresence = () => {
I dropped this hook in favor of https://github.com/input-output-hk/lace/pull/718/files#diff-685d6d538e6cbc3ab0925ac44d90afccae975c4b246b8c49329fbfcc25ae1147R23

2023-11-10 17:51 UTC, refi93 approved these changes

2023-11-17 11:50 UTC, greatertomi approved these changes

2023-11-17 14:15 UTC, oldGreg5 approved these changes

2023-11-28 18:25 UTC, merged