WIP Feat/sanchonet
input-output-hk/lace pull request #727
Opened 2023-11-14 14:58 UTC by mchappell

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-11-22 21:02 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/VotingProceduresContainer.tsx
> +      return 'Abstain';
Comment from #655:
- missing translations

2023-11-22 21:02 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/VotingProceduresContainer.tsx
> +      return 'DRep';
Comment from #655:
- missing translations (even though it's probably static string in other langs, it should be in the translation file)

2023-11-23 11:06 UTC, mchappell commented on apps/browser-extension-wallet/.env.defaults
> +AVAILABLE_CHAINS=Preprod,Preview,Mainnet,Sanchonet
@vetalcore please remove this from defaults, we'll need a special configuration just for sanchonet for now to account for a bunch of missing capabilities on the network, e.g adahandle support

2023-11-23 11:06 UTC, mchappell commented on apps/browser-extension-wallet/.env.defaults
> +ADA_HANDLE_URL_SANCHONET=https://preprod.api.handle.me
Please remove and use empty string

2023-11-23 11:07 UTC, mchappell commented on apps/browser-extension-wallet/src/features/ada-handle/config.ts
> +export const HANDLE_SERVER_URLS: Record<Cardano.NetworkMagics, string> = {
```suggestion
export const HANDLE_SERVER_URLS: Record<Exclude<Cardano.NetworkMagics, Cardano.NetworkMagics.Sanchonet>, string> = {
```

2023-11-27 21:06 UTC, vetalcore requested changes

2023-11-27 21:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/TransactionDetailsProxy.tsx
> +      return `${CEXPLORER_BASE_URL[environmentName]}/${CEXPLORER_URL_PATHS.Tx}`;
```suggestion
      return environmentName === 'Sanchonet' ? '' : ${CEXPLORER_BASE_URL[environmentName]}/${CEXPLORER_URL_PATHS.Tx}` ;
```

2023-11-27 21:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/components/TransactionDetailsProxy.tsx
> +      return `${CEXPLORER_BASE_URL[environmentName]}/${CEXPLORER_URL_PATHS.Tx}`;
do we have 'Sanchonet' string somewhere in the typings?

2023-11-27 21:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetDetailsDrawer/AssetDetails.tsx
> +    return CEXPLORER_BASE_URL[environmentName];
```suggestion
    return (environmentName === 'Sanchonet') ? '' :  CEXPLORER_BASE_URL[environmentName];
```

2024-01-22 14:41 UTC, vetalcore requested changes

2024-01-22 14:41 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/DappError.tsx
> +    if (onCloseClick) onCloseClick();
onCloseClick?.();

2024-01-22 14:41 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/DappError.tsx
> +    if (onMount) onMount();
onMount?.();

2024-01-22 14:41 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/VotingProceduresContainer.tsx
> +export const getVoterType = (voterType: Wallet.Cardano.VoterType): VoterType => {
has been refactored here https://github.com/input-output-hk/lace/pull/819

2024-01-22 14:45 UTC, mchappell commented on apps/browser-extension-wallet/src/lib/scripts/migrations/__tests__/versions/v0_6_0.test.ts
> -/* eslint-disable sonarjs/no-identical-functions */
yeh I think dropping the whole file makes sense, we shouldn't keep historical migrations in the codebase, they should be short-lived.

2024-01-31 10:19 UTC, vetalcore requested changes

2024-01-31 10:19 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +      // TODO: can we map to Cip30TxType instead?
not valid anymore

2024-01-31 10:19 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +const txIncludesConwayCertificates = (certificates?: Wallet.Cardano.Certificate[]) =>
could be a part of an inspector

2024-01-31 10:19 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +const isTxWithRewardsWithdrawal = (
could this on be also provided by sdk?

2024-01-31 10:19 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +type TransactionGovernanceProposal = {
already removed in the upcoming pr

2024-01-31 10:19 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetDetailsDrawer/AssetDetails.tsx
> +  // TODO remove if sanchonet gets an explorer
remove this one

2024-01-31 10:19 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetDetailsDrawer/AssetDetails.tsx
> +                    // TODO remove if sanchonet gets an explorer
ditto

2024-01-31 10:19 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetDetailsDrawer/AssetDetails.tsx
> +                    // TODO remove if sanchonet gets an explorer
ditto

2024-01-31 10:19 UTC, vetalcore commented on packages/cardano/src/wallet/types.ts
> +export enum Cip30TxType {
consider picking proper types from the tx types on the extension level

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/Activity/AssetActivityItem.tsx
> +  const translationTypes: Record<ActivityType, string> = {
ditto

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.module.scss
> +@import '../../styles/theme.scss';
already refactored

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx
> +  const isGovernanceTx =
alreadu refactored

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/TransactionDetails.tsx
> +  const translatedCertificates = certificates?.map((certificate) =>
would be refactored in scope of https://input-output.atlassian.net/browse/LW-9034

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/TxDetailsList.tsx
> +  const Icon = BracketDown ? <BracketDown className={styles.bracket} style={{ ...animation }} /> : <DownOutlined />;
move to the scss file

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/types.ts
> +export type TxDetailsCertificateTitles =
maybe we could get rid of this and just render whatever we pass

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/InsufficientFundsWarning/InsufficientFundsWarning.tsx
> +export const InsufficientFundsWarning = ({ translations }: DappTransactionProps): React.ReactElement => (
please check this one

2024-01-31 10:19 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/ParameterChangeAction/EconomicGroup.tsx
> +              label: 'Memory',
this one should not be hardcoded

2024-01-31 11:13 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
> +export const certificateInspectorFactory =
At the point of dApp popup opening theres nothing we can do except loop through the certificate bodies or use `getCertificatesByType` from the SDK.

2024-02-26 09:41 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransaction.tsx
> -        errorMessage={getSignTxDataError}
@mchappell  do we still need to show the error?
do we need to remove all the usages in the child components then?

2024-02-26 10:03 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/DappError.tsx
> +  useEffect(() => {
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:03 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/DappError.tsx
> +    window.close();
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:04 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmDRepRegistrationContainer.tsx
> +  const depositPaidWithCardanoSymbol = `${Wallet.util.lovelacesToAdaString(certificate.deposit.toString())} ${
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:04 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmDRepRegistrationContainer.tsx
> +  return (
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:05 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmDRepRetirementContainer.tsx
> +  const depositPaidWithCardanoSymbol = `${Wallet.util.lovelacesToAdaString(certificate.deposit.toString())} ${
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:05 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmDRepRetirementContainer.tsx
> +export const disallowSignTx = (): void => {
is not valid anymore

2024-02-26 10:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmDRepRetirementContainer.tsx
> +        onMount={() => {
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmStakeRegistrationDelegationContainer.tsx
> +  const depositPaidWithCardanoSymbol = `${Wallet.util.lovelacesToAdaString(certificate.deposit.toString())} ${
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmStakeVoteRegistrationDelegationContainer.tsx
> +  const depositPaidWithCardanoSymbol = `${Wallet.util.lovelacesToAdaString(certificate.deposit.toString())} ${
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmTransactionContent.tsx
> +  if (txType === Wallet.Cip30TxType.DRepRegistration) {
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ConfirmVoteRegistrationDelegationContainer.tsx
> +  const depositPaidWithCardanoSymbol = `${Wallet.util.lovelacesToAdaString(certificate.deposit.toString())} ${
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:06 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ProposalProceduresContainer.tsx
> +  const props = useMemo(() => ({ dappInfo, errorMessage }), [dappInfo, errorMessage]);
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:08 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/ProposalProceduresContainer.tsx
> +              {...{ ...props, deposit, rewardAccount, anchor, governanceAction }}
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:09 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/UpdateCommitteeActionContainer.tsx
> +      // TODO: use bech32 in future revision
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:09 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
> +    ? `core.${txType}.title`
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:09 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
> +  exposeApi<Pick<UserPromptService, 'allowSignTx'>>(
not applicable anymore

2024-02-26 10:09 UTC, vetalcore commented on apps/browser-extension-wallet/src/routes/DappConnectorView.tsx
> +    tabs.create({ url: 'app.html#/setup' });
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:10 UTC, vetalcore commented on packages/core/src/ui/components/ProposalProcedures/ParameterChangeAction/EconomicGroup.tsx
> +              label: 'Memory',
fixed in https://github.com/input-output-hk/lace/pull/868

2024-02-26 10:11 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/utils.ts
> +export const getTitleKey = (txType: Wallet.Cip30TxType): string =>
fixed in https://github.com/input-output-hk/lace/pull/868

2024-03-01 16:08 UTC, vetalcore commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/ParameterChangeActionContainer.tsx
> +      txDetails: {
ticket's been created

2024-03-01 16:18 UTC, mchappell commented on apps/browser-extension-wallet/src/features/dapp/components/confirm-transaction/proposal-procedures/ParameterChangeActionContainer.tsx
> +        // TODO: review cost model syntax/display
let's defer for now

2024-03-05 08:06 UTC, vetalcore approved these changes

2024-03-05 20:50 UTC, vetalcore approved these changes

2024-03-06 10:33 UTC, wklos-iohk approved these changes

2024-03-06 10:42 UTC, ljagiela approved these changes

2024-03-06 10:42 UTC, merged