feat: add cancel dialog
input-output-hk/lace pull request #781
Opened 2023-12-11 19:30 UTC by lucas-barros

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-12-12 09:25 UTC, VanessaPC requested changes

2023-12-12 09:25 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.tsx
> +      <Dialog.Root open={isDialogOpen} setOpen={setIsDialogOpen} zIndex={1000}>
Is it possible to move the Dialog into its own component so the Multiwallet.tsx file mostly only cares about the actions about it?

2023-12-12 09:25 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +export const useCancelDialog = (
`useCancelDialog` seems very specific, it's a corner or a small dialogue, that can be used for a cancel action, but also any other action. We can just pass any strings into it. 
Making it this way would also make more sense to move it into the `hooks` folder so it can be reused somewhere else in the project, otherwise, we would have to create a hooks folder inside multi-wallet, which could be less necessary. WDYT?

2023-12-12 13:59 UTC, renanvalentin commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +    shouldOpenDialogRef.current = true;
What if we create a Prompt component for handling this situation in a more declarative manner? For instance, when the user inputs a value but then clears it out, we should set `shouldOpenDialogRef.current` as false. Additionally, with regards to a hardware wallet, shouldn't we display the dialog box after the user connects the wallet but then closes it?

```tsx
<PromptProvider>
      <Prompt title={t('multiWallet.cancelDialog.title')} subtitle={{t('multiWallet.cancelDialog.description')}} />
      <WalletSetupFlowProvider flow={WalletSetupFlow.ADD_WALLET}>
      <Modal centered closable={false} footer={null} open={!isDialogOpen} width="100%" className={styles.modal}>
        <div className={styles.closeButton}>
          <NavigationButton icon="cross" onClick={closeWithDialog} />
        </div>
        <div ref={setRef}>
          <Switch>
            <Route path={newWallet.create.root} component={SetupCreateWallet} />
            <Route path={newWallet.hardware.root} component={SetupHardwareWallet} />
            <Route path={newWallet.restore.root} component={SetupRestoreWallet} />
            <Route exact path={`${path}/`} component={withReset(Home)} />
          </Switch>
        </div>
    </WalletSetupFlowProvider>

</PromptProvider>
```

Each flow could supply an observable `state$` to the providers property, which would allow you to display the `prompt`. e.g:

```tsx
export const SetupRestoreWallet = (): JSX.Element => {
   const [prompt, setPrompt]=  usePrompt()
   const state$ = useMemo(() => new Observable(), []);

 useEffect(() => {
    const subscription = state$.subscribe((state) => {
      if (state is Dirty) {
        setPrompt(true)
      }
    });

    return () => {
      subscription.unsubscribe();
    };
  }, [state$]);


 return (
  <RestoreWallet
    providers={{
      createWallet
    }}
  />
)
};
```

2023-12-12 14:20 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +export const useCancelDialog = (
Are you suggestion a name change? Or to make it the logic more generic?

2023-12-12 16:13 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +export const useCancelDialog = (
I suggest considering both. As well as moving the hook into a folder for hooks.

2023-12-13 12:51 UTC, renanvalentin commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +    shouldOpenDialogRef.current = true;
You could trigger from the context: https://github.com/input-output-hk/lace/blob/feat/lw-9157-cancel-adding-new-wallet/apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/context.tsx#L38

The core logic is centralized inside the context.ts file, so it should be easier to emit a new state change whenever something changes.

2023-12-13 13:57 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +    shouldOpenDialogRef.current = true;
If I'm not mistaken, those state changes only get triggered once the user goes from one step to the other, not on input event. I think we'll need a combination of both approaches.

2023-12-14 02:22 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +    shouldOpenDialogRef.current = true;
@renanvalentin I'm still going to make some improvements, but I updated the PR to incorporate some of your suggestions. Let me know what you think.

2023-12-14 02:24 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/useCancelDialog.tsx
> +export const useCancelDialog = (
I incoporated some of your and Renan's suggestion and moved the Dialog to a provider along with the hook logic.

2023-12-14 14:11 UTC, renanvalentin commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/Setup.tsx
> +  const { withConfirmationDialog } = useWalletSetupConfirmationDialog();
EDIT: It may be possible to remove the `WalletSetupConfirmationDialogProvider` component altogether. 

```tsx
interface Props {
  onProgressChange: () => 'dirty' | 'none' 
}

export const SetupCreateWallet = ({onProgressChange}: {onChang}): JSX.Element => {
   const state$ = useMemo(() => new Observable(), []);

    useEffect(() => {
    const subscription = state$.subscribe((state) => {
      if (state is Dirty) {
        onProgressChange('dirty')
      }
    });

    return () => {
      subscription.unsubscribe();
    };
  }, [state$]);

  return (
  <CreateWallet
    providers={{
      createWallet,
      generateMnemonicWords: Wallet.KeyManagement.util.generateMnemonicWords,
     state$
    }}
  />
  );
};


export const MultiWallet = (): JSX.Element => {
  /*...*/
const onProgressChange = (status) => setState({progress: status })

const leave = () => {
     setBackgroundPage();
              history.push(page);
}

  return (
<>
    /*.... */
       <div className={styles.closeButton}>
          <NavigationButton
            icon="cross"
            onClick={() => {
            if state.progress is 'none'
              leave()
            else
                 setState((s) => ({
                ...s,
                showLeavingDialog: true
              }))
            }}
          />
        </div>
          <Route path={newWallet.create.root} component={SetupCreateWallet} onProgressChange={}/>
   /* ... */
   {state. showLeavingDialog && <Dialog onConfirm={() => {
              leave()
} } />
<>
  );
};
```

2023-12-15 13:57 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/Setup.tsx
> +  const { withConfirmationDialog } = useWalletSetupConfirmationDialog();
I think we still need the provider to cover the OnBack dialog scenario. Without it we would have to keep a local state for the dialog for each step and it would not be possible to hide the flow modal. We would display the dialog on top of the modal.

2023-12-15 16:59 UTC, renanvalentin commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/Setup.tsx
> +  const { withConfirmationDialog } = useWalletSetupConfirmationDialog();
> I think we still need the provider to cover the OnBack dialog scenario. Without it we would have to keep a local state for the dialog for each step and it would not be possible to hide the flow modal. We would display the dialog on top of the modal.

See this comment: https://github.com/input-output-hk/lace/pull/781#discussion_r1426754511

We only need to apply this logic to the initial screen.

2023-12-16 00:30 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/steps/Setup.tsx
> +  const { withConfirmationDialog } = useWalletSetupConfirmationDialog();
@renanvalentin updated.

2023-12-18 17:35 UTC, renanvalentin commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/CreateWallet.test.tsx
> +  test.only('should emit correct value for shouldShowDialog', (done) => {
remove `test.only`

2023-12-18 17:35 UTC, renanvalentin commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/CreateWallet.test.tsx
> +    const secondSub = providers.confirmationDialog.shouldShowDialog$.subscribe((value) => {
how about using `firstValueFrom` to keep a flat control flow?

2023-12-19 12:06 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/CreateWallet.test.tsx
> +  test.only('should emit correct value for shouldShowDialog', (done) => {
Thanks, updated.

2023-12-19 12:06 UTC, lucas-barros commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/create-wallet/CreateWallet.test.tsx
> +    const secondSub = providers.confirmationDialog.shouldShowDialog$.subscribe((value) => {
Thanks, updated.

2023-12-20 16:09 UTC, renanvalentin approved these changes
great job @lucas-barros

2023-12-21 13:15 UTC, pczeglik-iohk approved these changes
Looks good. Thank you @lucas-barros

2024-01-05 12:37 UTC, VanessaPC approved these changes
Great work!

2024-01-05 12:42 UTC, merged