feat(ui): add toggle button group component [LW-9269]
input-output-hk/lace pull request #788
Opened 2023-12-18 13:28 UTC by przemyslaw-wlodek

# Checklist

- [ ] [JIRA](https://input-output.atlassian.net/browse/LW-9269)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

## Testing

## Screenshots

2023-12-19 16:08 UTC, mchappell requested changes

2023-12-19 16:08 UTC, mchappell commented on packages/ui/src/assets/icons/key.component.svg
Please put this in a separate nested folder to denote that it's not actually used in the app

2023-12-19 16:08 UTC, mchappell commented on packages/ui/src/assets/icons/home.component.svg
Please put this in a separate nested folder to denote that it's not actually used in the app

2023-12-19 16:08 UTC, mchappell commented on packages/ui/src/assets/icons/globe-alt.component.svg
Please put this in a separate nested folder to denote that it's not actually used in the app

2023-12-19 16:08 UTC, mchappell commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-item.component.tsx
> +  'children' | 'disabled' | 'id' | 'value'
can we add a `dataTestId` attribute here to make e2e targeting easier

2023-12-19 16:08 UTC, mchappell commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-root.component.tsx
> +  'loop' | 'rovingFocus'
can we add a `dataTestId` attribute here to make e2e targeting easier

2023-12-20 10:10 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-item.component.tsx
> +  'children' | 'disabled' | 'id' | 'value'
All data attributes can be placed without explicit mention in props :) I also include the example in storybook e.g. `data-testid="tab1-label-only"`

2023-12-20 10:10 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-root.component.tsx
> +  'loop' | 'rovingFocus'
same as above, thanks :)

2023-12-20 13:48 UTC, mchappell approved these changes

2023-12-20 13:49 UTC, mchappell commented
Nice work @przemyslaw-wlodek 💪

2023-12-27 07:11 UTC, merged