feat: add developer preview build tooling
input-output-hk/lace pull request #792
Opened 2023-12-19 10:47 UTC by mchappell

# Checklist

- [x] JIRA - [LW-9810](https://input-output.atlassian.net/browse/LW-9180)
- [x] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Add a dedicated GitHub action to build the developer preview build of Lace

## Testing

- Existing functionality should not be broken
- Run the GitHub action against a specific branch, and assert that the `.env.devpreview` parameters have been used

2023-12-22 11:35 UTC, przemyslaw-wlodek commented on .github/shared/build/action.yml
> +    default: 'false'
I have a couple of concerns.
1. This variable description looks like it intends to be used as a flag to decide whether to build a dev preview or not but in the `build-dev-preview.yml` I see it's always running the build (there are no `if` statements for workflow).
2. I feel like we should have different `inputs` defined and used in the environment variables during the build instead of replacing the defaults file for `dotenv-defaults`.
3. Can we please remove decrypt/lint/test steps from the workflow and leave just build/upload? We are doing it in Build and Test workflow. Maybe we could just make dev preview build dependant on the success of that job?

Apologies but I'm not an expert with github actions (and best practices) so my concerns may be unfounded.

2023-12-22 12:27 UTC, mchappell commented on .github/shared/build/action.yml
> +    default: 'false'
1. this means it'll only set the env variable to build the developer preview version if this is set, in this case that is only enabled in the `build-dev-preview.yml` so this is what i'd expect
2. This would only work for CI, and it's useful to have these changes explicitly set, rather than declaring overrides in local `.env` files
3. Unfortunately not, we'd still want to lint even the dev preview version and test it. and the decrypt step is required and isn't covered in the `action.yml` file. and is a requirement of the linting, I'd be happy to cover this workflow refactoring in a secondary change to streamline all the workflows

2023-12-22 13:19 UTC, przemyslaw-wlodek commented on .github/shared/build/action.yml
> +    default: 'false'
1. Ok. I just noticed that the description is different than for Analytics. It could be i.e. `Enable developer preview build`
2. 👍🏻 
3. It's still running before the dev preview build (I mean we always run regular `CI / Build & Test` before)

2023-12-22 13:20 UTC, przemyslaw-wlodek approved these changes
Just one comment. LGTM 🚀

2023-12-22 18:51 UTC, bernokl approved these changes

2024-01-03 13:52 UTC, pczeglik-iohk commented on .github/shared/build/action.yml
> +  BUILD_DEV_PREVIEW:
If this is not breaking anything I would keep those inputs sorted alphabetically :)

2024-01-03 13:53 UTC, pczeglik-iohk commented on .github/workflows/build-dev-preview.yml
> +          DEFAULT_CHAIN: 'Preprod'
Is `Preprod` correct here? Should it be `Preview` maybe?

2024-01-03 13:57 UTC, pczeglik-iohk commented on apps/browser-extension-wallet/webpack-utils.js
> +    defaults: process.env.BUILD_DEV_PREVIEW === 'true' ? './.env.devpreview' : './.env.defaults'
Can we rename this `.env.devpreview` file to `.env.dev.preview`? It improves slightly readability imo

2024-01-03 13:58 UTC, pczeglik-iohk commented on apps/browser-extension-wallet/webpack-utils.js
> +  yy.getTime();
do we need `yy`?

2024-01-03 14:01 UTC, pczeglik-iohk commented on apps/browser-extension-wallet/webpack.common.dev.js
> +            defaults: process.env.BUILD_DEV_PREVIEW === 'true' ? '.env.devpreview' : true,
If you decide to rename this file, please update it in places like this one

2024-01-03 14:03 UTC, pczeglik-iohk reviewed
Have a look at my comments please @mchappell

2024-01-03 15:18 UTC, danielmain requested changes
small changes, great job!

2024-01-03 15:18 UTC, danielmain commented on apps/browser-extension-wallet/webpack-utils.js
>    const manifest = JSON.parse(content.toString());
try catch for JSON.parse?

2024-01-03 15:18 UTC, danielmain commented on apps/browser-extension-wallet/webpack-utils.js
> +  manifest.name = manifest.name.replace('$WALLET_MANIFEST_NAME', process.env.WALLET_MANIFEST_NAME);
chaining operator for `manifest?.name?.replace`

2024-01-03 15:18 UTC, danielmain commented on apps/browser-extension-wallet/webpack-utils.js
> +    manifest.version = `${manifest.version}.${date.getTime()}`;
I would write it like this: 
```
manifest.version = `${manifest.version}.${Date.now()}`;
```

no need for like 13

2024-01-04 08:43 UTC, mchappell commented on .github/workflows/build-dev-preview.yml
> +          DEFAULT_CHAIN: 'Preprod'
Preprod is correct here, the unit tests run in an identical way to current `ci.yml` step

2024-01-04 08:44 UTC, mchappell commented on apps/browser-extension-wallet/webpack-utils.js
> +    defaults: process.env.BUILD_DEV_PREVIEW === 'true' ? './.env.devpreview' : './.env.defaults'
how about `.env.developerpreview` as I want to distinguish that these aren't defaults for the `preview` network?

2024-01-04 08:46 UTC, mchappell commented on apps/browser-extension-wallet/.env.devpreview
> +GITHUB_URL=https://github.com/input-output-hk
it's identical to the current defaults, we can raise another ticket to change this if required

2024-01-04 08:56 UTC, pczeglik-iohk commented on apps/browser-extension-wallet/webpack-utils.js
> +    defaults: process.env.BUILD_DEV_PREVIEW === 'true' ? './.env.devpreview' : './.env.defaults'
It makes sense. Thank you

2024-01-04 09:12 UTC, mchappell commented on apps/browser-extension-wallet/.env.devpreview
> +DISCORD_URL=https://discord.gg/inputoutput
updated with latest merge from `main` in 12327ac94840cf583d176fb122d0b7b1bc447f2e

2024-01-04 09:12 UTC, mchappell commented on apps/browser-extension-wallet/webpack-utils.js
>    const manifest = JSON.parse(content.toString());
done in 12327ac94840cf583d176fb122d0b7b1bc447f2e

2024-01-04 09:12 UTC, mchappell commented on apps/browser-extension-wallet/webpack-utils.js
> +  manifest.name = manifest.name.replace('$WALLET_MANIFEST_NAME', process.env.WALLET_MANIFEST_NAME);
as this is a required manifest field, I don't think this is necessary, do you?

2024-01-04 09:12 UTC, mchappell commented on apps/browser-extension-wallet/webpack-utils.js
> +    manifest.version = `${manifest.version}.${date.getTime()}`;
done in 12327ac94840cf583d176fb122d0b7b1bc447f2e

2024-01-04 09:13 UTC, mchappell commented on apps/browser-extension-wallet/webpack.common.dev.js
> +            defaults: process.env.BUILD_DEV_PREVIEW === 'true' ? '.env.devpreview' : true,
updated in 12327ac94840cf583d176fb122d0b7b1bc447f2e

2024-01-04 09:14 UTC, mchappell commented on apps/browser-extension-wallet/webpack-utils.js
> +  yy.getTime();
no, thanks for spotting this, removed in 12327ac94840cf583d176fb122d0b7b1bc447f2e

2024-01-04 09:15 UTC, danielmain commented on apps/browser-extension-wallet/webpack-utils.js
> +  manifest.name = manifest.name.replace('$WALLET_MANIFEST_NAME', process.env.WALLET_MANIFEST_NAME);
you have a try catch, not so necessary ;)

2024-01-04 09:16 UTC, danielmain commented on apps/browser-extension-wallet/webpack-utils.js
> +    manifest.version = `${manifest.version}.${date.getTime()}`;
but you are still defining one line before :D 
```
const date = new Date();
```

2024-01-04 09:17 UTC, danielmain commented on apps/browser-extension-wallet/webpack-utils.js
> +    manifest.version = `${manifest.version}.${date.getTime()}`;
![CleanShot 2024-01-04 at 10 17 08@2x](https://github.com/input-output-hk/lace/assets/4303099/793922d3-2bb0-47fd-b402-9e9e63783f81)

2024-01-04 09:18 UTC, pczeglik-iohk approved these changes
Looks good. Thank you @mchappell

2024-01-04 10:15 UTC, mchappell commented on apps/browser-extension-wallet/webpack-utils.js
> +    manifest.version = `${manifest.version}.${date.getTime()}`;
🤦 fixed in 144a7b0783c03aa0dde5a05e231936d45e3e6b4f

2024-01-04 13:47 UTC, danielmain approved these changes

2024-01-05 09:41 UTC, merged