chore(staking): migrate from ladle to storybook [LW-9454]
input-output-hk/lace pull request #800
Opened 2023-12-21 21:03 UTC by przemyslaw-wlodek

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/browse/LW-9454)

---

## Proposed solution
This PR enables storybook development in Staking. Previously we used Ladle but due to the testing approach (using Chromatic) we are bringing Storybook back in place as a standard tool.

## Testing
- QA: Not required.
- DEV: Please run the storybook locally.

2023-12-22 13:33 UTC, przemyslaw-wlodek commented on packages/staking/.storybook/StakingStorybookProvider.tsx
> +// @ts-ignore
Not sure how to solve it elegantly. `baseUrl` is set to `src` dir and this file is just a mock provider for storybook (outside of `src` dir). I think we could probably add `include` to `tsconfig.json` but this may require explicit mention on src files again. I see no harm in that for now.

2023-12-22 13:35 UTC, przemyslaw-wlodek commented on packages/staking/.storybook/main.js
> +      // new TsconfigPathsPlugin({ baseUrl: path.resolve(__dirname, '../src') }),
There were ongoing discussions if we even wanted to have the aliases/baseUrl (how much value vs tooling problems it gives). If we want then we need to fix this, otherwise I can create a separate task to migrate from paths `features/x` to `../../x` for example and remove `baseUrl` config.

2024-01-02 08:59 UTC, vetalcore commented
running `yarn story:build` fails for me with:
```
ERR! Module build failed (from ./node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
ERR! Error: No module factory available for dependency type: CssDependency
```

2024-01-02 09:02 UTC, vetalcore requested changes

2024-01-02 09:02 UTC, vetalcore commented on packages/staking/package.json
> +    "story:build": "build-storybook",
would i make sence to have same steps as in the browser-extension app?
```suggestion
        "storybook": "ENV=development start-storybook -p 6006",
    "prestorybook:build": "yarn build",
    "storybook:build": "ENV=development build-storybook --log-level error",
```

2024-01-02 09:03 UTC, vetalcore requested changes

2024-01-02 09:03 UTC, vetalcore commented on packages/staking/.storybook/StakingStorybookProvider.tsx
> +const outsideHandlesMocks: OutsideHandlesContextValue = {
```suggestion
const outsideHandlesMocks = {
```

2024-01-02 09:03 UTC, vetalcore commented on packages/staking/.storybook/StakingStorybookProvider.tsx
> +};
```suggestion
} as unknown as OutsideHandlesContextValue;
```

2024-01-02 09:03 UTC, vetalcore commented on packages/staking/.storybook/StakingStorybookProvider.tsx
> +// @ts-ignore
somehow it works fine if i remove `// @ts-ignore` comments here

2024-01-02 15:20 UTC, tommayeliog approved these changes

2024-01-03 13:11 UTC, przemyslaw-wlodek commented on packages/staking/package.json
> +    "story:build": "build-storybook",
I've updated scripts now we have it `build` and `build:storybook`. I hope it makes more sense now. `pre*` step in this case would be a killer. I cannot imagine building all packages each time I run storybook. Everyone has to do it manually if needed 🙏🏻

2024-01-03 13:12 UTC, przemyslaw-wlodek commented on packages/staking/.storybook/StakingStorybookProvider.tsx
> +const outsideHandlesMocks: OutsideHandlesContextValue = {
Outside handles should be removed in the future when we migrate these functions/hooks/etc to `staking`. Let's leave it as it is. Now we explicitly see which functionalities aren't mocked as opposed to the type-casting you proposed.

2024-01-03 14:08 UTC, vetalcore approved these changes

2024-01-03 15:52 UTC, mchappell approved these changes

2024-01-04 08:42 UTC, przemyslaw-wlodek commented on packages/staking/.storybook/main.js
> +      // new TsconfigPathsPlugin({ baseUrl: path.resolve(__dirname, '../src') }),
Fixed 🎉

2024-01-04 09:40 UTC, wklos-iohk approved these changes

2024-01-04 13:02 UTC, merged