feat(staking): add feature flag for new grid view
input-output-hk/lace pull request #805
Opened 2023-12-27 16:26 UTC by przemyslaw-wlodek

# Checklist

- [x] [JIRA](https://input-output.atlassian.net/browse/LW-9266)

---

## Proposed solution
Add a new feature flag for staking that will enable switching between Grid and List view when browsing pools.

## Testing
To be covered in the other PR (Grid View).

2024-01-02 08:22 UTC, vetalcore requested changes

2024-01-02 08:22 UTC, vetalcore commented on apps/browser-extension-wallet/.env.example
> +USE_MULTI_DELEGATION_STAKING_GRID_VIEW=false
```suggestion
USE_MULTI_DELEGATION_GRID_VIEW=false
```
wdyt?

2024-01-02 08:45 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/.env.example
> +USE_MULTI_DELEGATION_STAKING_GRID_VIEW=false
I'd say yes but I want to be consistent with all variables we have. 😄 I think it'd be worth renaming after we drop the old single-staking impl.
```
USE_MULTI_DELEGATION_STAKING_LEDGER=false
USE_MULTI_DELEGATION_STAKING_TREZOR=false
...
USE_MULTI_DELEGATION_STAKING_ACTIVITY=true
```

2024-01-02 11:10 UTC, vetalcore commented on apps/browser-extension-wallet/.env.example
> +USE_MULTI_DELEGATION_STAKING_GRID_VIEW=false
could you please leave a todo then?

2024-01-03 14:07 UTC, vetalcore approved these changes

2024-01-03 15:37 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/.env.example
> +USE_MULTI_DELEGATION_STAKING_GRID_VIEW=false
Done :)

2024-01-04 13:36 UTC, mchappell approved these changes

2024-01-04 13:36 UTC, merged