Feature/lw 9267 stake pool card
input-output-hk/lace pull request #809
Opened 2024-01-03 12:46 UTC by tommayeliog

# Checklist

- [x] JIRA - \[https://input-output.atlassian.net/browse/LW-9267](https://input-output.atlassian.net/browse/LW-9267)<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---
Created uses full width of available space StakePoolCard, and fixed height.
Ticker with limited width. Icon and metricValue on the right.
Progress bar with "hardcodded" colors (TBD where to define the colors).
Storybook added

TODO: 
check different metricType formatting

2024-01-08 13:25 UTC, przemyslaw-wlodek requested changes
Good job @tommayeliog. I found some possible improvements. We can catch up to solve them quickly. :)

2024-01-08 13:25 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.css.ts
> +export const tickerName = style({
1. It can be a ticker or pool name, so let's call it a `title` (as we discussed).
2. We have an `<Ellipsis />` component which may work here. We need to add an ellipsis after a certain number of letters.

2024-01-08 13:25 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.stories.tsx
> +const metricTypeOptions: Array<MetricType> = [
Nit. We always use `MetricType[]` notation. 🙏🏻

2024-01-08 13:25 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.stories.tsx
> +    </div>
As discussed:

Please try to represent the Figma design 1:1 where possible. Follow examples from the `@lace/ui`. :)

2024-01-08 13:25 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.tsx
> +  console.debug('[STAKE]:', { metricType, metricValue, onClick, saturation, ticker });
Please remove before merging.

2024-01-08 13:25 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.tsx
> +      </div>
```suggestion
      <Flex justifyContent="space-between">
        <Text.Body.Large className={styles.tickerName}>{ticker}</Text.Body.Large>
        <PoolMetric metricType={metricType} metricValue={metricValue} />
      </Flex>
```

2024-01-08 13:25 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.css.ts
> +});
You can remove it if you will apply `<Flex />` (see the other comment)

2024-01-11 22:49 UTC, przemyslaw-wlodek approved these changes
LGTM. Good job @tommayeliog! 😄 Just a few minor comments + conflicts to be resolved. Ping me if you need any help.

2024-01-11 22:49 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/PoolMetric/PoolMetric.tsx
> +import ChartPieIcon from '/src/assets/icons/chart-pie.svg';
`assets/icons/...` P.S. We need to introduce linter for that.

2024-01-11 22:49 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.stories.tsx
> +import { Section } from '@lace/ui/src/design-system/decorators';
Can we re-export `Section` in the same way as `Variants`?

2024-01-11 22:49 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.stories.tsx
> +          headers={['Ticker', 'Satiration', 'ROS', 'Cost', 'Margin', 'Produced-blocks', 'Pledge', 'Live stake']}
```suggestion
          headers={['Ticker', 'Saturation', 'ROS', 'Cost', 'Margin', 'Produced-blocks', 'Pledge', 'Live stake']}
```

2024-01-11 22:49 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.stories.tsx
> +    <div style={{ width: 220 }}>
Probably all occurrences could be replaced with `<Box w="220">...` (untested)

2024-01-11 22:49 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.tsx
> +  <Card.Outlined className={cn(styles.card, selected && styles.cardSelected)} {...(onClick ? { onClick } : {})}>
Spread is redundant, you can assign it with `undefined` and it will have the same effect.

```suggestion
  <Card.Outlined className={cn(styles.card, selected && styles.cardSelected)} onClick={onClick}>
```

2024-01-12 12:19 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.stories.tsx
> +    <div style={{ width: 220 }}>
the closest width is "$214"

2024-01-12 12:59 UTC, przemyslaw-wlodek approved these changes
Thanks! All good now

2024-01-18 10:44 UTC, wklos-iohk approved these changes

2024-01-18 10:54 UTC, merged