feat(extension): lw-8600
input-output-hk/lace pull request #819
Opened 2024-01-06 19:03 UTC by vetalcore

# Checklist

- [ ] JIRA - [LW-8600](https://input-output.atlassian.net/browse/LW-8600)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Apply proper mapping on the tx inspection lvl, add handlers for the activities sections ui.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="887" alt="Screenshot 2024-01-06 at 21 00 22" src="https://github.com/input-output-hk/lace/assets/7934077/ba7bdf99-7a56-4c5d-ba54-cfc4796bab90">

2024-01-16 09:04 UTC, mchappell requested changes

2024-01-16 09:04 UTC, mchappell commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx
> +          Object.values(ConwayEraCertificatesTypes).includes(type as unknown as ConwayEraCertificatesTypes) ||
for readability please extract this to a boolean value before the jsx return

2024-01-16 10:30 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +      // TODO: should we create proper inspector instead?
done https://input-output.atlassian.net/browse/LW-9569 
could you please help me to create proper ticket for the implementation itself?

2024-01-16 10:30 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +    case Wallet.Cardano.VoterType.dRepKeyHash:
done

2024-01-16 10:30 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx
> +  // TODO: set fill color for every icon using currentColor, replace icon not to contain surrounding circle
ticket has been created

2024-01-16 10:30 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx
> +          Object.values(ConwayEraCertificatesTypes).includes(type as unknown as ConwayEraCertificatesTypes) ||
done

2024-01-16 10:33 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/mocks/governance.ts
> +// const STAKE_KEY_HASH = Wallet.Cardano.RewardAccount.toHash(REWARD_ACCOUNT);
done

2024-01-16 10:33 UTC, vetalcore commented on apps/browser-extension-wallet/src/stores/slices/activity-detail-slice.ts
> +      votingProcedures: votingProceduresTransformer(tx.body.votingProcedures),
done

2024-01-17 11:01 UTC, mchappell approved these changes

2024-01-24 13:39 UTC, merged