[LW 9404] Shared wallet info
input-output-hk/lace pull request #825
Opened 2024-01-08 17:47 UTC by lucas-barros

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-01-08 18:14 UTC, renanvalentin commented on packages/ui/src/design-system/check-box/check-box.component.tsx
> +export const Root = ({
Should we rename it to Checkbox? It would make sense to use root if it was composed of many building blocks.

2024-01-08 18:24 UTC, lucas-barros commented on packages/ui/src/design-system/check-box/check-box.component.tsx
> +export const Root = ({
Sure. Updated!

2024-01-09 08:35 UTC, pczeglik-iohk commented on packages/ui/src/design-system/check-box/check-box.component.tsx
What about changing the directory and file name to `checkbox`, without `-`?

2024-01-09 08:44 UTC, pczeglik-iohk commented on packages/ui/src/design-system/check-box/check-box.stories.css.ts
> +export const focus = style({
This is how we present focus state in storybook?

What if somebody updates focus css rules in `packages/ui/src/design-system/check-box/check-box.css.ts`?

2024-01-09 12:07 UTC, pczeglik-iohk reviewed
Code looks good. There are few questions from my site @lucas-barros

2024-01-09 12:38 UTC, lucas-barros commented on packages/ui/src/design-system/check-box/check-box.stories.css.ts
> +export const focus = style({
Updated to use box shadow var.

2024-01-09 12:39 UTC, lucas-barros commented on packages/ui/src/design-system/check-box/check-box.component.tsx
Makes sense. Updated!

2024-01-09 14:45 UTC, DominikGuzei commented
@lucas-barros maybe let's move the important info component into the `core` package? In the other PRs we only put more general purpose components (like the Checkbox) into the `@lace/ui` package.

2024-01-09 14:48 UTC, lucas-barros commented
> @lucas-barros maybe let's move the important info component into the `core` package? In the other PRs we only put more general purpose components (like the Checkbox) into the `@lace/ui` package.

@DominikGuzei it already is in the core package and checkbox is in the ui package.

2024-01-09 18:50 UTC, renanvalentin approved these changes
great work @lucas-barros !

2024-01-09 21:55 UTC, vetalcore requested changes

2024-01-09 21:55 UTC, vetalcore commented on packages/ui/src/design-system/checkbox/checkbox.css.ts
> +export const unchecked = style([
could we merge this one with the checkbox class? don't think there would me any more states besides these two

2024-01-09 21:55 UTC, vetalcore commented on packages/ui/src/design-tokens/theme/dark-theme.css.ts
> +
@renanvalentin is there a way we could override these values, have you thought about having these vars somehow local to the component, or at least scope it under some parent object? dunno it it's possible though, this file is getting way too big

2024-01-10 09:33 UTC, pczeglik-iohk approved these changes
Code looks good. Thank you @lucas-barros

2024-01-10 12:17 UTC, lucas-barros commented on packages/ui/src/design-system/checkbox/checkbox.css.ts
> +export const unchecked = style([
If I merge this with checkbox class there are some issues with css specificity when applying the checked style. It would need to increase the specificity to override the base style.
Having two seperate class applied at separete times seems like the simplest solution to me. Feel free to give it a try and suggest a solution if you want.

2024-01-11 10:46 UTC, bslabiak approved these changes

2024-01-11 13:11 UTC, merged