feat(extension): lw-9532 extend stake pool details drawer with more metadata
input-output-hk/lace pull request #832
Opened 2024-01-11 12:32 UTC by vetalcore

# Checklist

- [x] JIRA -[ LW-9532](https://input-output.atlassian.net/browse/LW-9532)
- [x] Proper tests implemented
- [x] Screenshots added.

# TODO:
- [ ] pledge is coming as lovelaces value (design show percentages)
- [ ] how to calculate costs per epoch

---

## Proposed solution

add blocks, costs/p epoch, pledge, margin into the stake pool details drawer

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

<img width="1150" alt="Screenshot 2024-01-11 at 14 25 35" src="https://github.com/input-output-hk/lace/assets/7934077/2969abae-1664-4726-a7f1-a220346efd2a">

2024-01-11 12:39 UTC, mchappell requested changes

2024-01-11 12:39 UTC, mchappell commented on packages/cardano/src/ui/components/StakePoolMetricsBrowser/StakePoolMetricsBrowser.tsx
> +        <div className={styles.statBody} data-testid="active-stake-value">
```suggestion
        <div className={styles.statBody} data-testid={`${testId}-value`}>
```

2024-01-11 12:39 UTC, mchappell commented on packages/staking/src/features/store/delegationPortfolioStore/mapStakePoolToDisplayData.ts
> +    costsPerEpoch: 'costsPerEpoch',
reminder to change for a transformable value

2024-01-11 12:39 UTC, mchappell commented on apps/browser-extension-wallet/src/features/delegation/stores/createDelegationStore.ts
> +      costsPerEpoch: 'costsPerEpoch',
reminder to change for a transformable value

2024-01-11 12:49 UTC, mchappell commented on apps/browser-extension-wallet/src/features/delegation/stores/createDelegationStore.ts
> +      pledge: Wallet.util.lovelacesToAdaString(pledge.toString())
👍

2024-01-11 16:02 UTC, mchappell approved these changes
Nice job @vetalcore!

2024-01-16 09:23 UTC, wklos-iohk approved these changes

2024-01-16 12:01 UTC, merged