feat: add lock and key angent data  migration
input-output-hk/lace pull request #833
Opened 2024-01-11 18:55 UTC by lucas-barros

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-01-16 09:15 UTC, mkazlauskas approved these changes
Looks good! Just a question below

2024-01-16 09:15 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +        // Save temporary storage. Revert if something fails
I don't quite understand the purpose of temp storage, it doesn't seem to be used anywhere?

2024-01-16 12:21 UTC, lucas-barros commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +        // Save temporary storage. Revert if something fails
You're right. Updated, thanks!

2024-01-17 12:44 UTC, lucas-barros commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +        metadata: {
@mkazlauskas @DominikGuzei is this aligned with https://github.com/input-output-hk/cardano-js-sdk/pull/1050?

2024-01-17 12:45 UTC, lucas-barros commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +            metadata: { name: 'Account #0', lockValue },
@mkazlauskas now that the wallet will have metadata, does it make sense to add `lockValue` to the wallet level?

2024-01-17 13:02 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +        metadata: {
Looks good to me

2024-01-17 17:34 UTC, DominikGuzei commented
@lucas-barros should I remove the browser extension or just reload it with the new code?

2024-01-17 17:38 UTC, DominikGuzei commented
@lucas-barros I'm getting this on running `yarn dev` with this PR:
![image](https://github.com/input-output-hk/lace/assets/172414/416b4486-98a1-4979-ba82-7640b90a5262)

what could be wrong?

2024-01-17 17:40 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +): Promise<AddWalletProps<Wallet.Metadata>> => {
@lucas-barros I think you need to also adjust the types here and provide `Promise<AddWalletProps<Wallet.Metadata, Account.Metadata>>`

2024-01-17 17:50 UTC, lucas-barros commented
> @lucas-barros for testing: should I remove the browser extension or just reload it with the new code?

You can use your current installation. I added the steps for testing in the description.

2024-01-18 08:47 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +): Promise<AddWalletProps<Wallet.Metadata>> => {
Updated SDK in base branch, unit tests should be passing now too

2024-01-18 13:06 UTC, mkazlauskas requested changes

2024-01-18 13:06 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +        removeItemFromLocalStorage(KEY_AGENT_DATA_STORAGE);
This should also be obsolete
```suggestion
        removeItemFromLocalStorage(KEY_AGENT_DATA_STORAGE);
        removeItemFromLocalStorage('wallet');
```

2024-01-18 16:42 UTC, lucas-barros commented on apps/browser-extension-wallet/src/lib/scripts/migrations/versions/v1_8_2.ts
> +): Promise<AddWalletProps<Wallet.Metadata>> => {
@DominikGuzei @marcin-mazurek updated with base branch. Also added removing wallet from the repo in case of a rollback.

2024-01-19 11:43 UTC, DominikGuzei commented
@lucas-barros the migration seems to be working for me now 👍 for me the wallet is getting locked after the migration (even if i never locked the wallet before), is this intentional? Btw. it's not locked anymore after closing the popup and re-opening it, so it doesn't seem to be enforced either.

![image](https://github.com/input-output-hk/lace/assets/172414/f5ce9b97-d060-4bf0-a00b-3b22221be1d9)

2024-01-19 12:26 UTC, lucas-barros commented
> @lucas-barros the migration seems to be working for me now 👍 for me the wallet is getting locked after the migration (even if i never locked the wallet before), is this intentional? Btw. it's not locked anymore after closing the popup and re-opening it, so it doesn't seem to be enforced either.
> 
> ![image](https://private-user-images.githubusercontent.com/172414/298054620-f5ce9b97-d060-4bf0-a00b-3b22221be1d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2NjcyOTksIm5iZiI6MTcwNTY2Njk5OSwicGF0aCI6Ii8xNzI0MTQvMjk4MDU0NjIwLWY1Y2U5Yjk3LWQwNjAtNGJmMC1hMDBiLTNiMjIyMjFiZTFkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExOVQxMjIzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02OTFlZjQ2MjVlY2MyZjliOTNkNzRhZGI1NGQ3ODg1YjVhNmY0ZThmYTZmYmQ1NTU2NjA4ZThhYTQ1YTljZmE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wF8A3Z4o4km301HBzhVodi1y5hocuJ6G3SltnDHpCcw)

@DominikGuzei did you update the manifest file version to a higher then your current version? If not, likely the migration didnt run, the new build was loaded once (which will "lock" the wallet), then the older version would be reload due to the version being higher. What does your local storage look like after the migration?

2025-03-13 07:20 UTC, closed without merging