test(extension): lw-9097 add e2e tests for multidelegation card buttons
input-output-hk/lace pull request #847
Opened 2024-01-22 11:41 UTC by ljagiela

2024-01-22 13:14 UTC, wklos-iohk requested changes

2024-01-22 13:14 UTC, wklos-iohk commented on packages/e2e-tests/src/features/MultidelegationDelegatedFundsExtended.feature
> +
Unnecessary empty line

2024-01-23 07:51 UTC, wklos-iohk approved these changes

2024-01-23 10:37 UTC, oldGreg5 requested changes
There are 3 scenarios:
1. selecting delegated pool(single pool 100% delegated): 2 buttons 'manage deleg' and 'select for multi'
2. selecting delegated pool(multidelegation, this pool has <100% delegated): 3 buttons 'manage deleg', 'stake all on this pool' and 'select for multi'
3. selecting non delegated pool: 2 buttons 'stake all on this pool' and 'select for multi'

2024-01-24 11:27 UTC, oldGreg5 approved these changes

2024-01-24 13:08 UTC, merged