feat(staking,extension): Add your pools section of the Overview sub page
input-output-hk/lace pull request #85
Opened 2023-06-07 06:19 UTC by szymonmaslowski

# Checklist

- [x] JIRA - [\<link>](https://input-output.atlassian.net/browse/LW-6676)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

 - coppied the `StakingInfoCard` component from the extension
 - adjusted Staking Navigation component and enabled it to switch between two sub pages
 - composed the your pools seciton of the Staking/overview subpage with a mocked data
 - adjusted the staking components structure in the extension in order to properly consume new staking changes

## Testing

 - when `USE_MULTI_DELEGATION_STAKING` enabled new staking changes are rendered as a staking page in the extension app (see screenshots)
 - when `USE_MULTI_DELEGATION_STAKING` disabled new changes does not affect the current staking implementation in the extension

## Screenshots

<img width="1792" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/211526ff-ca20-44c9-a0fe-9918ec208308">
<img width="1792" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/7b44c318-eee6-48db-9654-8e66f7485170">

2023-06-07 11:57 UTC, mrcnk approved these changes

2023-06-10 18:24 UTC, szymonmaslowski commented on packages/staking/src/features/overview/staking-info-card/StakingInfoCard.tsx
> +const formatNumericValue = (val: number | string, suffix: number | string): React.ReactElement => (
I just copied it over to the staking package along with the whole staking info card implementation with a goal of limiting the number of adjustments for now. We will be anyway improving it by switching to toolkit components so that will be the time for eliminating that duplicate.

2023-06-12 12:15 UTC, renanvalentin requested changes

2023-06-12 12:15 UTC, renanvalentin commented on packages/ui/src/design-tokens/theme/context.ts
> +import { createContext, useContext } from 'react';
@szymonmaslowski can you rename it back to `theme.context.ts` to follow the existing convention of using `[file-name].[scope].[extension]`

2023-06-12 12:15 UTC, renanvalentin commented on packages/ui/src/design-tokens/theme/theme-provider.css.ts
> +  color: vars.colors.$lace_typography_main_color,
Setting the height and width to 100% might be a good idea to avoid CSS layout issues.

2023-06-12 16:16 UTC, szymonmaslowski commented on packages/ui/src/design-tokens/theme/theme-provider.css.ts
> +  color: vars.colors.$lace_typography_main_color,
IMO this should be a app's concern to apply a size properties if needed.
As a consumer of this package I would preffer to add needed styles instead of fighting styles, over which I have no controll, if they would conflict with the app's styling.

2023-06-13 12:52 UTC, przemyslaw-wlodek requested changes

2023-06-13 12:52 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/MultiDelegationStaking.tsx
> +// Disabling import/no-unresolved as it is not aware of the "exports" entry
Could you please link the GH issue instead of this comment? (or do both 🙏🏻)

2023-06-13 12:52 UTC, przemyslaw-wlodek commented on packages/staking/.ladle/components.tsx
> +import '../../../apps/browser-extension-wallet/src/styles/index.scss';
Can we use an alias or it needs additional setup which isn't worth in this case?

2023-06-13 12:52 UTC, przemyslaw-wlodek commented on packages/staking/.ladle/components.tsx
> +      <div id={'lace-app'}>{children}</div>
```suggestion
  const colorScheme = useMemo(() => globalState.theme === ThemeState.Light ? ThemeColorScheme.Light : ThemeColorScheme.Dark, [globalState.theme]);

  return (
    <ThemeProvider colorScheme={colorScheme}>
      <div id={'lace-app'}>{children}</div>
```

2023-06-13 12:52 UTC, przemyslaw-wlodek commented on packages/staking/.ladle/vite.config.ts
> +        root: './',
This one looks suspicious. I remember we had trouble with that.

2023-06-13 12:52 UTC, przemyslaw-wlodek commented on packages/staking/.ladle/vite.config.ts
> +      exclude: './**/*.scss',
Is it really needed? `eslint` shouldn't try to pick up scss extension, even with wildcard 🤔

2023-06-13 12:52 UTC, przemyslaw-wlodek commented on packages/staking/package.json
> +  },
Aren't they peerDeps?

2023-06-13 12:52 UTC, przemyslaw-wlodek commented on packages/staking/src/features/overview/staking-info-card/StakingInfoCard.tsx
> +  <div className={cn(styles.panel, { className, [styles.popupView!]: popupView })}>
Same here. Better to add at least `eslint-disable-next-line` if we don't want to address this now. I know it's gonna be replaced soon

2023-06-13 14:29 UTC, renanvalentin commented on packages/ui/src/design-tokens/theme/theme-provider.css.ts
> +  color: vars.colors.$lace_typography_main_color,
The height property inherits its size from the parent container. The following HTML structure could break the app:


```
html,
body {
  height: 100%;
  background: red;
}

.provider {
  background: blue;
}

.app {
  height: 100%;
  background: green;
}
```

![Screenshot 2023-06-13 at 11 27 06](https://github.com/input-output-hk/lace/assets/2846918/9022b2d7-e666-4bb9-89da-87dd2346e500)

As you can see, the `.app` doesn't take the whole viewport because `.provider` is missing the height property.

```
html,
body {
  height: 100%;
  background: red;
}

.provider {
  height: 100%;
  background: blue;
}

.app {
  height: 100%;
  background: green;
}
```

![Screenshot 2023-06-13 at 11 27 50](https://github.com/input-output-hk/lace/assets/2846918/e715efdb-6d98-4ff2-80f0-ddb9e018619f)

2023-06-13 14:29 UTC, renanvalentin commented on packages/ui/src/design-tokens/theme.context.tsx
Can you use `git move`? Otherwise, any open PR will have to resolve this conflict.

2023-06-13 14:32 UTC, renanvalentin commented on packages/ui/src/design-tokens/theme/theme-provider.component.tsx
> +      <div
One solution to the issue mentioned in the previous [comment](https://github.com/input-output-hk/lace/pull/85/files#r1228225921) is to use `useEffect` and apply the CSS class directly to the HTML or body class. This eliminates the need for an intermediary div container.

2023-06-13 19:38 UTC, szymonmaslowski commented on packages/ui/src/design-tokens/theme/theme-provider.css.ts
> +  color: vars.colors.$lace_typography_main_color,
I totally understand the problem and what I suggest is to let the consumer style the provider via className property. Sorry If I was not clear enough.
With having possibility to pass the className such problems are easily addressable so we don't have to predict what default styles are best for the consumer.

2023-06-13 20:03 UTC, szymonmaslowski commented on packages/ui/src/design-tokens/theme/theme-provider.component.tsx
> +      <div
That is also possible 😉 Both approaches (useEffect and className on provider) are valid for me. One advantage of className I see is that it is explicit. With useEffect it happens behind the consumer back.

2023-06-14 08:32 UTC, szymonmaslowski commented on packages/ui/src/design-tokens/theme.context.tsx
I used the `git mv` but at the same time had a changes to this file and git unfortunately treated it as a new file.
However I doubt there will be any conflicts to this file TBH. It is not likely that anybody will change anything in this file. Sorry, that was a mistake, but IMO it is not worth overriding the git history for that.

2023-06-14 08:57 UTC, szymonmaslowski commented on packages/ui/src/design-tokens/theme/theme-provider.css.ts
> +  color: vars.colors.$lace_typography_main_color,
@renanvalentin I added the `className` prop to the `ThemeProvider`

2023-06-14 09:38 UTC, mrcnk approved these changes

2023-06-15 13:41 UTC, renanvalentin commented on packages/ui/src/design-tokens/theme/theme-provider.component.tsx
> +      <div
As we discussed offline, we might be able to remove the container by using [createGlobalTheme](https://vanilla-extract.style/documentation/global-api/create-global-theme/)

```
export const light = createGlobalTheme('[data-lace-ui-color-schema="light"] :root', {
  color: {
    brand: 'blue'
  },
});

export const dark = createGlobalTheme('[data-lace-ui-color-schema="dark"] :root', {
  color: {
    brand: 'red'
  },
});
```

Changing the `[data-lace-ui-color-schema="dark"]` attribute in the HTML tag will result in different CSS variables.

2023-06-15 14:49 UTC, renanvalentin approved these changes

2023-06-15 21:14 UTC, merged