fix(extension): conway-era tx activiries line items
input-output-hk/lace pull request #860
Opened 2024-01-29 13:41 UTC by vetalcore

# Checklist

- [x] JIRA - [LW-9621](https://input-output.atlassian.net/browse/LW-9621)
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="1152" alt="Screenshot 2024-01-29 at 15 40 56" src="https://github.com/input-output-hk/lace/assets/7934077/6b85378d-675b-46ea-ad69-b62d440fd893">

2024-01-30 10:28 UTC, przemyslaw-wlodek requested changes
Just a few minor comments. Thank you Vit! 🤝

2024-01-30 10:28 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +// Assumes single procedure only
1. Is this comment necessary?
2. Are we ever going to support multiple procedures at once?
3. Comment might be more appropriate in place of usage, where you pass `proposalProcedures[0]`

2024-01-30 10:28 UTC, przemyslaw-wlodek commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.module.scss
> +  color: var(--data-green, #2cb67d) !important;
Do we need all these `!important`? 🙈

2024-01-30 10:28 UTC, przemyslaw-wlodek commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.module.scss
> +    fill: none;
Can we remove this and just base on the `currentColor` that is placed in SVGs?

2024-01-30 10:28 UTC, przemyslaw-wlodek commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx
> +  const isPopup = window.innerWidth <= BRAKEPOINT_POPUP;
Please use CSS breakpoint for this. If it would touch any part of the logic I'd suggest passing the boolean from the top (as we already have information if it's rendered in a popup context or not).

2024-01-30 11:12 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> -    case signedCertificateTypenames.includes(CertificateType.VoteDelegation):
would be removed, figma would be updated accordingly*

2024-01-30 11:14 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +// Assumes single procedure only
comment is still valid, huge tx refactoring epic is on it's way (not this pi cycle*) 
i'd suggest to keep it like it is

2024-01-30 11:14 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.module.scss
> +  color: var(--data-green, #2cb67d) !important;
yes, antd has some inner styles overriding this one

2024-01-30 11:16 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.module.scss
> +    fill: none;
it's done like that, but the icons themselves require some adjustments

2024-01-30 11:35 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/ActivityTypeIcon.tsx
> +  const isPopup = window.innerWidth <= BRAKEPOINT_POPUP;
resolved

2024-01-31 11:43 UTC, przemyslaw-wlodek approved these changes
🍻

2024-01-31 12:07 UTC, merged

2024-01-31 12:18 UTC, mchappell approved these changes

2024-02-01 15:53 UTC, vetalcore commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +          "AuthorizeCommitteeHotCertificate": "Authorise Committee",
resolved

2024-02-01 15:55 UTC, vetalcore commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +          "submitProposal": "Confirm Vote"
does not exist anymore