Feature/lw 9250 stake pools sort filter
input-output-hk/lace pull request #867
Opened 2024-01-30 23:02 UTC by tommayeliog

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-02-05 18:19 UTC, vetalcore submitted a review, later dismissed

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.css.ts
> +    backgroundColor: '#F9F9F9',
same colour for for both colour schemes?

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +import { ReactComponent as SortDirectionDescIcon } from '@lace/icons/dist/SortDirectionDescComponent';
please make sure that all the svgs do not contain any spaces around them

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +        label: 'Ticker name',
translations please

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +    <Card.Outlined style={{ width: 340 }}>
please use classes here

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +        {visibleSection === 'sorting' ? (
could we extract 'sorting' into some enum?

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/types.ts
> +export type SortOption = { label: string; value: string; icon: any; onIconClick: any };
icon should be of svg type?

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/types.ts
> +export type SortOption = { label: string; value: string; icon: any; onIconClick: any };
onIconClick seems to be of a function type?

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +        {visibleSection === 'sorting' ? (
you could probably transform VisibleSection into the enum

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +              onValueChange={(value) => onSortChange(value as SortField)}
why do you need `as SortField` here?

2024-02-05 18:19 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/SortAndFilter/utils.ts
> +  ...(length > 1 && {
something like `:not(:first-child)`?

2024-02-05 18:19 UTC, vetalcore commented on packages/ui/src/design-system/radio-button/radio-button.component.tsx
> +          isAnyOptionHasIcon ? cx.noGap : cx.gap,
```suggestion
          [cx.gap]: isAnyOptionHasIcon
```

2024-02-05 18:19 UTC, vetalcore commented on packages/ui/src/design-system/radio-button/radio-button.component.tsx
> +                    {React.createElement(icon)}
why do you need React.createElement here?

2024-02-05 18:19 UTC, vetalcore commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-item.component.tsx
> +import * as Typography from '../typography';
please fix

2024-02-06 13:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.stories.tsx
> +        {/* <SortAndFilter toggleSection="sorting" /> */}
why is this commented out?

2024-02-07 10:45 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.css.ts
> +    backgroundColor: '#F9F9F9',
The color has been removed from SortAndFilter component, because SelectGroup component should handle it internally. There is Figma design for White and Grey layouts. Grey layout is no developed and has to be done in a separate ticket.

2024-02-07 10:49 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +import { ReactComponent as SortDirectionDescIcon } from '@lace/icons/dist/SortDirectionDescComponent';
I think they are fine 24x24

2024-02-07 13:35 UTC, tommayeliog commented on packages/ui/src/design-system/radio-button/radio-button.component.tsx
> +                    {React.createElement(icon)}
That's not mine chage

2024-02-07 13:36 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +        {visibleSection === 'sorting' ? (
Unfortunately, we have to use a string, because ToggleButtonGoup will give use only string on onChange

2024-02-07 20:02 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/SortAndFilter/utils.ts
> +  ...(length > 1 && {
@przemyslaw-wlodek will help me with this issue

2024-02-07 20:03 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.css.ts
> +    backgroundColor: '#F9F9F9',
fixed to use theme, however on Storybook we can't see changes on Dark theme because of known issue with LocalThemeProvider

2024-02-07 20:05 UTC, tommayeliog commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-item.component.tsx
> +import * as Typography from '../typography';
@vetalcore I'm not sure what's the issue here

2024-02-08 10:53 UTC, mchappell requested changes

2024-02-08 10:53 UTC, mchappell commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +          <ToggleButtonGroup.Item value="sorting">Sorting</ToggleButtonGroup.Item>
Needs translation

2024-02-08 10:53 UTC, mchappell commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +        <Text.SubHeading weight="$bold">More options</Text.SubHeading>
Needs translation

2024-02-08 10:53 UTC, mchappell commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.tsx
> +          <ToggleButtonGroup.Item value="filtering">Filters</ToggleButtonGroup.Item>
needs translation

2024-02-08 10:53 UTC, mchappell commented on packages/staking/src/features/BrowsePools/SortAndFilter/SortAndFilter.css.ts
> +  borderBottomLeftRadius: 16,
```suggestion
  borderBottomLeftRadius: '$16',
``` ?

2024-02-08 10:53 UTC, mchappell commented on packages/ui/src/design-tokens/sx.css.ts
> +    borderTopLeftRadius: vars.radius,
You probably don't need this anymore as you've moved the radius into the component

2024-02-08 18:00 UTC, tommayeliog commented on packages/ui/src/design-tokens/sx.css.ts
> +    borderTopLeftRadius: vars.radius,
we are going to keep this for future use

2024-02-12 11:10 UTC, przemyslaw-wlodek approved these changes

2024-02-12 13:29 UTC, mchappell approved these changes

2024-02-21 16:51 UTC, merged