feat(extension): update conway era tx details to the latest figma
input-output-hk/lace pull request #868
Opened 2024-01-30 23:14 UTC by vetalcore

# Checklist

- [x] JIRA - [LW-9622](https://input-output.atlassian.net/browse/LW-9622)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Adjust common tx transformer and related components layout.

## Testing

Visual regression.

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-01-31 14:33 UTC, przemyslaw-wlodek approved these changes
GJ 🍻

2024-01-31 14:33 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +export enum CredentialTypeEnum {
No need to add `Enum` suffix :)

2024-01-31 14:33 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +              `${depositPaidInAda} ${cardanoCoin.symbol}`,
Like in the previous PR: Please double-check if we don't have a formatter for that 🙏🏻

2024-01-31 15:11 UTC, mchappell requested changes
Blocking merge until comments unresolved in https://github.com/input-output-hk/lace/pull/860 are moved across to this PR.

2024-02-01 15:24 UTC, vetalcore commented on apps/browser-extension-wallet/src/utils/tx-inspection.ts
> +export enum CredentialTypeEnum {
fixed

2024-02-01 15:33 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +              `${depositPaidInAda} ${cardanoCoin.symbol}`,
resolved

2024-02-01 15:33 UTC, vetalcore commented on packages/core/src/ui/components/ActivityDetail/components/DetailRowSubitems.tsx
> +/* eslint-disable no-magic-numbers */
resolved

2024-02-01 21:17 UTC, vetalcore commented
> Blocking merge until comments unresolved in #860 are moved across to this PR.

@mchappell comments have been resolved/pushed to sanchonet branch

2024-02-07 08:46 UTC, przemyslaw-wlodek approved these changes
Just a CI error to be fixed. ✅

2024-02-22 13:30 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/stores/slices/activity-detail-slice.ts
> +      ),
May not be very relevant here, but in general I'd suggest introducing a single `object` param when you have more than ~3 params. This gives you also order flexibility and you don't need to bother with optional properties.

```suggestion
      proposalProcedures: governanceProposalsTransformer({
        cardanoCoin,
        coinPrices,
        fiatCurrency,
        proposalProcedures: tx.body.proposalProcedures
      }),
```

2024-02-22 13:30 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +              // TODO: is it in Ada or lovelaces?
We need to clarify this before merging + we can use the common formatter if it's lovelaces (AFAIR)

2024-02-22 13:53 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +              // TODO: is it in Ada or lovelaces?
@mchappell how do i verify this one?

2024-02-26 10:31 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/activity/helpers/common-tx-transformer.ts
> +              // TODO: is it in Ada or lovelaces?
Lovelaces are usually represented as strings, so i'd assume this one is just an ada

2024-02-26 12:45 UTC, merged