feat(extension): lw-9268 add stake pools grid view
input-output-hk/lace pull request #877
Opened 2024-02-05 17:23 UTC by vetalcore

# Checklist

- [ ] [JIRA](https://input-output.atlassian.net/browse/LW-9268)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Use virtuoso lib to enable virtual scroll for staking table.
Create separate grid component by utilising VirtuosoGrid

## Testing

General staking flows regression is highly recommended

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-02-06 16:03 UTC, przemyslaw-wlodek requested changes
Very good job @vetalcore 💪🏻 I left some suggestions. Let's catch up 👍🏻

2024-02-06 16:03 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/Grid.tsx
> +      )),
You don't need `gridComponents` for advanced rendering. Seems like you only want to use [listClassName](https://virtuoso.dev/virtuoso-grid-api-reference/)

2024-02-06 16:08 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.css.ts
> +export const skeleton = recipe({
I may not be up to date with the latest requirements but I believe that the previous animation was signed off by Alan as good enough. You are mapping an advanced scenario to Recipe but this advanced scenario also includes animation and yours is static.

Since you've partially done that maybe it would be possible to include animation with this pattern 🤔

2024-02-06 16:48 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolCard/PoolMetric/PoolMetric.tsx
> +import { MetricType } from 'features/BrowsePools/StakePoolsTable';
resolved

2024-02-06 16:49 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolCard/PoolMetric/PoolMetric.tsx
> +const iconsByType: Partial<Record<MetricType, React.ReactNode>> = {
resolved

2024-02-06 16:54 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePoolsHeader.tsx
> +  const formattedPoolsCount = Number(poolsCount) === poolsCount ? formatLocaleNumber(poolsCount, 0) : 0;
done

2024-02-06 16:55 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePoolsHeader.tsx
> +  const formattedPoolsCount = Number(poolsCount) === poolsCount ? formatLocaleNumber(poolsCount, 0) : 0;
i kept the second one because formatLocaleNumber returns NaN as string*

2024-02-06 16:57 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolCard/SkatePoolCardProgressBar/StakePoolCardProgressBar.tsx
>    const percentageNumber = Number(percentage);
imho 0 is different that NA*

2024-02-06 17:00 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsTable/index.ts
> +export type { StakePoolsListRowProps } from './StakePoolsList/types';
done

2024-02-06 17:01 UTC, vetalcore commented on packages/staking/src/features/staking/StakingView.tsx
> +              <Box mt="$16">
i've left a [comment](https://www.figma.com/file/RPN3V4Et7hMbXkV5ZIF75i?node-id=30328:204249&mode=design#693446716)

2024-02-06 17:01 UTC, vetalcore commented on packages/ui/src/design-system/table/hooks.ts
> +      console.log(
removed

2024-02-06 17:02 UTC, vetalcore commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-item.css.ts
> +  width: '$20',
no, you've exported the svg from figma with outer paddings*

2024-02-06 17:04 UTC, vetalcore commented on packages/ui/src/design-system/table/hooks.ts
> +  const [initialItemsLimit, setInitialItemsLimit] = useState<
done

2024-02-06 17:04 UTC, vetalcore commented on packages/ui/src/design-system/table/hooks.ts
> +    if (containerRef.current !== null) {
done

2024-02-06 17:05 UTC, vetalcore commented on packages/ui/src/design-system/table/hooks.ts
> +  }, [rowHeight, containerRef]);
could you please elaborate a bit more how come that we are not handling it properly?

2024-02-06 17:05 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.tsx
> +    window.addEventListener('resize', debouncedGetNumberOfItemsInRow);
same as above

2024-02-06 17:07 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.tsx
> +    const result =
what would be the benefit of doing so?

2024-02-06 17:08 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/Grid.tsx
> +      )),
done

2024-02-07 08:57 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/SkatePoolCardProgressBar/StakePoolCardProgressBar.tsx
>    const percentageNumber = Number(percentage);
Yep, I agree 😄 but is it even possible that SDK will return a pool like that? I just wanted to retain consistency, so if we use capitalized `N/A` in other places as well then I'm 👌🏻 with it.

2024-02-07 09:02 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-item.css.ts
> +  width: '$20',
Let's catch up to discuss this. I believe Allan told me that 24 is the standard size and we are including the outer padding by default. I am not questioning if that approach is ok, but we need to double-check how the icon package does that now (maybe that has changed).

2024-02-07 09:04 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/table/hooks.ts
> +  }, [rowHeight, containerRef]);
I added this comment before I spotted that you handle the `resize` event in another place. So feel free to ignore it (I forgot to remove it).

2024-02-07 09:06 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.tsx
> +    const result =
I believe it could be: consistency, concise implementation, better readability. Let's chat if you don't see those benefits. I haven't used this package but I saw it should do the job.

2024-02-07 09:29 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.tsx
> +    window.addEventListener('resize', debouncedGetNumberOfItemsInRow);
I added side notes for inspiration, but the clue is that we should not add multiple `resize` handlers like this. We would need to create a common approach that bounds a single event listener and then just sends updates to "subscribers".

One of my recommendations (based on initial research) would be to use `ResizeObserver`.
Here you can check the benefits: [ResizeObserver: it's like document.onresize for elements](https://web.dev/articles/resize-observer)

Maybe you can find a better package but [use-resize-observer](https://github.com/ZeeCoder/use-resize-observer) seems popular (almost 3M downloads per month), the other popular competitor [react-resize-detector](https://github.com/maslianok/react-resize-detector) (~1.6M downloads per month). The former package is used by `storybook` and seems to be ~2x smaller than the latter.

Another recommendation would be to switch from thinking about window size to thinking about the container size, using [CSS container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_queries).

Let me know what you think 😄

2024-02-07 09:31 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.css.ts
> +export const skeleton = recipe({
Understood. I would need to play with it by myself to find a solution then. The last word here remains to the designers. If they're ok with it then I am as well 👍🏻

2024-02-07 11:20 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolCard/SkatePoolCardProgressBar/StakePoolCardProgressBar.tsx
>    const percentageNumber = Number(percentage);
for me the source of truth is the sdk itself, unless it says that the metrics we get from pool data are not optional, i would expect them to be optional, thats why i'd suggest to stick to 'N/A' as possible value

2024-02-07 12:45 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.tsx
> +    const result =
done

2024-02-07 12:58 UTC, vetalcore commented on packages/ui/src/design-system/toggle-button-group/toggle-button-group-item.css.ts
> +  width: '$20',
i've left a todo there, please attach a ticket if it needs further investigation

2024-02-12 15:25 UTC, mchappell requested changes

2024-02-12 15:25 UTC, mchappell commented on packages/staking/src/features/BrowsePools/types.ts
> +export enum MetricType {
Might be best to tie this to the SDK sortable types + exclude the ones we aren't using/displaying

2024-02-12 15:25 UTC, mchappell commented on packages/staking/src/features/BrowsePools/types.ts
> +export enum SortField {
We should reference the SDK property of the same name

2024-02-12 15:25 UTC, mchappell commented on packages/staking/src/features/BrowsePools/types.ts
> +export type StakePoolSortOptions = {
this property already exists in the SDK

2024-02-12 15:25 UTC, mchappell commented on packages/staking/src/features/BrowsePools/types.ts
> +export enum SortDirection {
the property `SortOrder` already exists in the SDK, suggest we use this so we can remove code

2024-02-13 00:09 UTC, przemyslaw-wlodek approved these changes
Any outstanding comments are to be fixed in the integration PR.

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/types.ts
> +export type StakePoolSortOptions = {
Covering in https://input-output.atlassian.net/browse/LW-9530

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/types.ts
> +export enum SortField {
Covering in https://input-output.atlassian.net/browse/LW-9530

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/types.ts
> +export enum MetricType {
Covering in https://input-output.atlassian.net/browse/LW-9530

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/StakePoolsTable/utils.tsx
> +export const hiddenColumns = [process.env.USE_ROS_STAKING_COLUMN !== 'true' && MetricType.apy].filter((c) => !!c);
should this be using ros now?

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.tsx
> +const gridCardHeight = 84;
```suggestion
const GRID_CARD_HEIGHT = 84;
```
for consistency as a top level const

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.css.ts
> +// this is temporary, until @lace/ui Grid component will accept responsive properties per breakpoint
Please link/create ticket that describes this

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolCellRenderer/StakePoolCellRenderer.tsx
> +  [MetricType.margin]: ({ value }) => <span>{typeof value === 'string' ? value : ''}%</span>,
```suggestion
  [MetricType.margin]: ({ value }) => <span>{typeof value === 'string' ? value : '-'}%</span>,
```
for consistency?

2024-02-14 08:50 UTC, mchappell commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCardSkeleton.tsx
> +  fadeScale?: 3 | 4 | 5;
is this the same prop as https://github.com/input-output-hk/lace/pull/877/files#diff-96f0ab91b9cb0adbe4750ff63c9a3ea7135073fcc96db08c30c42057eb291e3bR20 ? if so let's reference that here.

2024-02-14 11:17 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.css.ts
> +// this is temporary, until @lace/ui Grid component will accept responsive properties per breakpoint
Done

2024-02-14 11:17 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolsGrid/StakePoolsGrid.tsx
> +const gridCardHeight = 84;
Done

2024-02-14 13:05 UTC, mchappell approved these changes

2024-02-14 13:17 UTC, wklos-iohk approved these changes

2024-02-14 13:33 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsTable/StakePoolCellRenderer/StakePoolCellRenderer.tsx
> +  [MetricType.margin]: ({ value }) => <span>{typeof value === 'string' ? value : ''}%</span>,
Done

2024-02-14 13:34 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsTable/utils.tsx
> +export const hiddenColumns = [process.env.USE_ROS_STAKING_COLUMN !== 'true' && MetricType.apy].filter((c) => !!c);
This will be resolved in future PR.

2024-02-14 13:50 UTC, merged