feat: isolate network addresses between testnet
input-output-hk/lace pull request #88
Opened 2023-06-07 09:32 UTC by greatertomi

# Checklist

- [x] JIRA - LW-6813
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Previously, the address book content is shared between preview and preprod. This PR isolates the address book content based on the network. It uses `Cardano.NetworkMagics` instead of `Cardano.NetworkId`

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-07 10:32 UTC, rhyslbw approved these changes
Looks good to me, nice and clean!

2023-06-08 11:58 UTC, shawnbusuttil approved these changes

2023-06-13 11:10 UTC, rhyslbw requested changes
There was a bug with the storage preventing the same address to be saved across different networks. Please add a test that demonstrates it's now fixed.

2023-06-13 16:06 UTC, shawnbusuttil requested changes

2023-06-13 16:06 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/features/address-book/context/__test__/context.test.tsx
> +    network: 1
```suggestion
    network: Cardano.NetworkMagics.Preprod
```

2023-06-13 16:58 UTC, shawnbusuttil approved these changes
Good job!

2023-06-13 18:23 UTC, rhyslbw approved these changes
Sharing state between tests is a little concerning, but this is out of scope of the task, so it's just general feedback. Not only does it leave us susceptible to hidden test bugs, but it's also hard to grok the individual intent, since the whole suite must be considered to verify correctness.

2023-06-14 16:00 UTC, closed without merging