Feat/lw 9740 revamp create wallet screen
input-output-hk/lace pull request #890
Opened 2024-02-13 21:06 UTC by greatertomi

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-02-14 22:56 UTC, shawnbusuttil commented
Probably best to let the other one get merged first () or we create a branch to merge both tasks into. The reason is that I had to remove the legal stuff from the wallet setup as well due to the build not compiling from those things being flagged as unused.

2024-02-15 00:09 UTC, szymonmaslowski requested changes
Great job 👏 Besides a few comments I have also two questions, possibly to @vhulchenko-iohk:
1. What about bottom right corner links? WHas it decided to keep them?
<img width="349" alt="image" src="https://github.com/input-output-hk/lace/assets/9270461/6f507cdd-8f97-4884-9ce1-b8d6632f9651">

2. This PR adds two new posthog events. Are them confirmed with someone responsible for analytics? Do we even have any process around that?
```
LandingAnalyticsAgreeClick = 'landing | agree | click',
LandingAnalyticsRejectClick = 'landing | reject | click',
```

2024-02-15 09:13 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx
>            <Route path={`${path}/create`}>
I don't understand this.

2024-02-15 09:55 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +  const isAnalyticsAccepted = enhancedAnalyticsStatus === EnhancedAnalyticsOptInStatus.OptedIn;
Yes. `isAnalyticsAccepted` is used in at least three places within this component, This is the easiest way to reduce the need to do `enhancedAnalyticsStatus === EnhancedAnalyticsOptInStatus.OptedIn` repeatedly. I don't see the need to remove this simple abstraction, except it does have a side effect I can't see yet.

2024-02-15 09:56 UTC, vhulchenko-iohk commented
Hey @szymonmaslowski 

re your requests above

1. yes, confirmed with Legal. They want us to keep those links there.
2. the analytics events will go into a separate ticket, and yes, we have a specific naming policy to name user analytics events. If possible, let's remove the analytics events from this PR - we will add them later.

cc @greatertomi

2024-02-15 10:01 UTC, greatertomi commented on packages/common/src/ui/components/Banner/ConfirmationBanner.tsx
> +}: ConfirmationBannerProps): ReactPortal | undefined => {
Fixed on b7b8f95

2024-02-15 10:01 UTC, greatertomi commented on packages/common/src/ui/components/Banner/ConfirmationBanner.tsx
> +                Accept
Fixed on b7b8f95

2024-02-15 10:03 UTC, greatertomi commented on packages/common/src/ui/components/Banner/ConfirmationBanner.tsx
> +  showBanner = true
Fixed on b7b8f95

2024-02-15 10:04 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx
> +                <div>
Fixed on f5ba4cd

2024-02-15 10:04 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +      const analyticsOptInStatus =
Fixed on f5ba4cd

2024-02-15 10:04 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetup.tsx
> +            <ConfirmationBanner
Fixed on f5ba4cd

2024-02-15 13:50 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +  const isAnalyticsAccepted = enhancedAnalyticsStatus === EnhancedAnalyticsOptInStatus.OptedIn;
Fixed on 0dfe9d3

2024-02-27 17:07 UTC, szymonmaslowski requested changes
A few additional comments :wink:

2024-02-28 09:32 UTC, greatertomi commented on packages/core/src/ui/components/WalletSetupRevamp/wallet-steps-revamp.common.ts
> +export enum WalletSetupStepsRevamp {
Fixed on d10bf51

2024-02-28 09:33 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupMainPage.tsx
> +        <WalletSetupOptionsStep
Fixed on d10bf51

2024-02-28 16:24 UTC, danielmain requested changes
Just left small suggestions

2024-02-28 16:52 UTC, greatertomi commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "title": "Let's explore Web3 together",
This is the translation file.

2024-02-28 17:10 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +        onBack={() => onCancel()}
Fixed on 02f0788

2024-02-28 17:11 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupMainPage.tsx
> +    /* await analytics.setOptedInForEnhancedAnalytics(analyticsStatus);
On second thought, I un-commented this. What about if I turn `USE_POSTHOG_ANALYTICS` off? This whole stuff would be resolved soon, I don't see why we should remove this implementation since I would use it again.

2024-02-28 17:13 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupMainPage.tsx
> +    });
I changed the implementation of this and left comment [here](https://github.com/input-output-hk/lace/pull/890#discussion_r1506306509).

2024-02-28 18:16 UTC, danielmain commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +      "title": "Let's explore Web3 together",
ups sorry I am so stupid :(

2024-02-28 23:29 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupMainPage.tsx
> +    /* await analytics.setOptedInForEnhancedAnalytics(analyticsStatus);
We cannot set `USE_POSTHOG_ANALYTICS` to false because this will disable all posthog analytics on master. I guess we don't want to do that. We could do that only if the onboarding was the only feature using Posthog but I doubt that is the case.

On the other hand if we merge this code uncommented it will send some analytic events that are not confirmed with the product side so there will be a period of time with "trash" events - until we implement the target events. I agree about removing this completely and adding the commit hash with this implementation in the analytics ticket - it won't be lost. I also understand that you John feel more comfortable with keeping it, so Im also fine with commenting out, but my original suggestion was just to comment the last step, so just sending the analytics. The less commented code we have - the healthier the codebase is :wink:

2024-02-29 08:31 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupMainPage.tsx
> +    /* await analytics.setOptedInForEnhancedAnalytics(analyticsStatus);
Just commenting the last step leaves some unused variables with throw errors. Removed on dc3e8f8

2024-02-29 08:35 UTC, danielmain approved these changes
great job!

2024-03-04 12:00 UTC, merged