[LW-9742]: use new register screen for create wallet flow
input-output-hk/lace pull request #891
Opened 2024-02-14 12:13 UTC by shawnbusuttil

# Checklist

- [ ] JIRA - \<LW-9742>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-02-15 11:48 UTC, greatertomi requested changes

2024-02-15 11:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -import { passwordTranslationMap } from '../constants';
[This](https://github.com/input-output-hk/lace/blob/5a538ccd0914ce2f7dafb1436c556f0ec017a4ce/apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/constants.ts#L1) is no longer used, we should delete it.

2024-02-15 11:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -import { useExperimentsContext } from '@providers/ExperimentsProvider';
This should be removed because it was only used here.

2024-02-15 11:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -const isCombinedPasswordNameStepEnabled = process.env.USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT === 'true';
Should we not remove `USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT` env? I could not find anywhere else it was used.

2024-02-15 11:48 UTC, greatertomi commented on packages/core/src/ui/components/WalletSetup/wallet-steps.ts
> +    prev: WalletSetupSteps.Register,
We should update the [steps](https://github.com/input-output-hk/lace/blob/5a538ccd0914ce2f7dafb1436c556f0ec017a4ce/packages/core/src/ui/components/WalletSetup/wallet-steps.common.ts#L7-L8) here to reflect combining `Register` and `Password`.

2024-02-15 11:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +  const [isAnalyticsAccepted] = useState(false);
I don't see the point of having a state, without it's setter function

2024-02-15 11:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -  };
I removed this from the translation file on #890.

2024-02-15 11:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -    sendAnalytics(Events.WALLET_PASSWORD_NEXT, postHogOnboardingActions[setupType]?.WALLET_PASSWORD_NEXT_CLICK);
We should remove this from posthog [events](https://github.com/input-output-hk/lace/blob/29cdec25c984b80a457e7a20e14c9a171a981f34/apps/browser-extension-wallet/src/providers/AnalyticsProvider/analyticsTracker/events.ts#L30)

2024-02-15 11:48 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -    sendAnalytics(Events.WALLET_NAME_NEXT, postHogOnboardingActions[setupType]?.WALLET_NAME_NEXT_CLICK);
Same as this

2024-02-15 11:49 UTC, greatertomi commented
Also, the master branch has several changes, can you please update this branch?

2024-02-15 16:33 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -  };
So when we merge it to yours, it should self resolve no?

2024-02-15 16:37 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -import { useExperimentsContext } from '@providers/ExperimentsProvider';
Are we sure. Given the function of it, it seems like it can be handy in the future.

2024-02-15 16:39 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -const isCombinedPasswordNameStepEnabled = process.env.USE_COMBINED_PASSWORD_NAME_STEP_COMPONENT === 'true';
Good catch.

2024-02-15 16:43 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> +  const [isAnalyticsAccepted] = useState(false);
Removing.

2024-02-15 16:45 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -    sendAnalytics(Events.WALLET_PASSWORD_NEXT, postHogOnboardingActions[setupType]?.WALLET_PASSWORD_NEXT_CLICK);
Line 227 seems to be using it.

2024-02-15 16:47 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -    sendAnalytics(Events.WALLET_NAME_NEXT, postHogOnboardingActions[setupType]?.WALLET_NAME_NEXT_CLICK);
Hardware Wallet is still using this.

2024-02-20 09:43 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -import { useExperimentsContext } from '@providers/ExperimentsProvider';
How about if it is not needed in the future? Leaving codes that are not currently needed even though they could be used in the future leads to having lots of dead code.

I'll suggest we remove it, in the future we can re-add it when it is needed.

2024-02-20 09:45 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -  };
Since my PR won't be merged, I'll suggest removing this on this branch.

2024-02-28 12:01 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -  };
So I guess this is resolved.

2024-02-28 16:00 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -import { useExperimentsContext } from '@providers/ExperimentsProvider';
I get it but it is part of a larger file that is still used. So if that should be done, it should be in the scope of a larger cleanup involving the entire file.

2024-02-28 16:00 UTC, shawnbusuttil commented on packages/core/src/ui/components/WalletSetup/wallet-steps.ts
> +    prev: WalletSetupSteps.Register,
Removing this since both parties don't need it.

2024-02-29 09:42 UTC, greatertomi approved these changes

2024-03-01 10:41 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/WalletSetupWizard.tsx
> -import { useExperimentsContext } from '@providers/ExperimentsProvider';
Luckily, we have git, so if we need it we can grab it. But we do not hold nor maintain unused code 🙏🏻 
Please remove it @shawnbusuttil 🙇🏻 
Thank you 😊

2024-03-05 14:31 UTC, merged