Feat/lw 9709 prompt password when unlocking account
input-output-hk/lace pull request #901
Opened 2024-02-20 11:41 UTC by DominikGuzei

# Checklist

- [x] https://input-output.atlassian.net/browse/LW-9709
- [x] Screenshots added.

---

## Proposed solution

This PR implements the password prompt to enable and account.

## Screenshots

Password prompt:

![image](https://github.com/input-output-hk/lace/assets/172414/f70aa79b-31ca-409a-86b4-c8102cff4a42)

![image](https://github.com/input-output-hk/lace/assets/172414/88f5ccc9-6ee5-40c2-8bb2-f09f1189122e)

Incorrect password entered:

<img width="358" alt="Bildschirmfoto 2024-02-20 um 12 22 20" src="https://github.com/input-output-hk/lace/assets/172414/44b8e312-cad1-4e00-af56-49e97fc33b02">

2024-02-20 12:26 UTC, lucas-barros approved these changes
Great job, just left some minor suggestions.

2024-02-20 12:26 UTC, lucas-barros commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +  zIndex?: number;
It seems zIndex is not used

2024-02-20 12:26 UTC, lucas-barros commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +      <div data-testid="edit-account">
```suggestion
      <div data-testid="enable-account-password">
```

2024-02-20 12:26 UTC, lucas-barros commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/WalletAccounts.tsx
> +      {enableAccountPasswordPrompt.isOpen && (
Just a matter of keeping it consistent with the other dialogs
```suggestion
      {
      <EnableAccountPasswordPrompt
           open={enableAccountPasswordPrompt.isOpen}

```

2024-02-20 12:26 UTC, lucas-barros commented on packages/core/src/ui/hooks/useDialogWithData.ts
> +import { useState } from 'react';
Nice, I think we can replace `useAccountDataModal` with this generic one.

2024-02-20 13:35 UTC, DominikGuzei commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +      <div data-testid="edit-account">
resolved in 07217e0b6f72620278db73eae8f81939dc905664

2024-02-20 13:35 UTC, DominikGuzei commented on packages/core/src/ui/hooks/useDialogWithData.ts
> +import { useState } from 'react';
ah yeah, thanks - that's actually what i wanted to do 👍

2024-02-20 13:37 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/WalletAccounts.tsx
> +      {enableAccountPasswordPrompt.isOpen && (
@lucas-barros i will add a comment: there is actually a big difference between these two ways of doing it. The way you see here will ensure that the password in the dialog will not be "stored" while the accounts menu stays open (because the component is only rendered conditionally vs. passing a prop) … for the other drawers its not important

2024-02-20 13:44 UTC, lucas-barros commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/WalletAccounts.tsx
> +      {enableAccountPasswordPrompt.isOpen && (
Makes sense, thanks for clarifying.

2024-02-20 13:44 UTC, mkazlauskas requested changes

2024-02-20 13:44 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  password: string
Probably doesn't matter right now due to non-strict null checks, but it makes it easier to understand the code
```suggestion
  password?: string
```

2024-02-20 13:44 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  password?: string;
This has an advantage for security: you can overwrite the bytes in the byte array, but can't force GC to dispose a string. By converting the string to a byte array as early as possible, you have a better chance of removing the secret from memory earlier.
```suggestion
  passphrase?: Uint8Array;
```

2024-02-20 14:10 UTC, DominikGuzei commented on packages/core/src/ui/hooks/useDialogWithData.ts
> +import { useState } from 'react';
done in d7c1f9f7b58f1bb2f552c18bba8913350a4bb374

2024-02-20 14:27 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  password?: string;
done in 82a42907c63b1e8db4e81f2610257bd52a467436

2024-02-20 14:27 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/hooks/useWalletManager.ts
> +  password: string
done in 82a42907c63b1e8db4e81f2610257bd52a467436

2024-02-21 15:15 UTC, mkazlauskas commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +  password: string;
Do we really need this as a prop, since this component provides the password to onConfirm callback? Maybe we could entirely remove it from the state outside of this component?

```suggestion
```

2024-02-21 15:18 UTC, mkazlauskas commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +  onConfirm: (password: string) => void;
Same reason as in [my previous suggestion](https://github.com/input-output-hk/lace/pull/901#discussion_r1495848330) for useWalletManager change

```suggestion
  onConfirm: (passphrase: UInt8Array) => void;
```

2024-02-21 15:20 UTC, mkazlauskas commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +      onClose={onCancel}
I'm not sure whether this would make any difference for time in memory since the component is probably dismounted and useState variables dereferenced? but it might
```suggestion
      onClose={() => {
        onCancel();
        setCurrentPassword('');
      }}
```

2024-02-21 15:23 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/components/MainMenu/DropdownMenuOverlay/components/WalletAccounts.tsx
> +        : await addAccount({
We also need a popup for instructions to connect hardware device
```suggestion
        : enableAccountHardwarePrompt.open({ accountIndex, type: wallet.type })
```

2024-02-21 19:25 UTC, DominikGuzei commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +  password: string;
fixed in e384cc02a70d27b0e1d518293adf6e363f073698

2024-02-21 19:31 UTC, DominikGuzei commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +  onConfirm: (password: string) => void;
fixed in b80c193c7839186c6059b7703a5764cf39f37085

2024-02-21 19:31 UTC, DominikGuzei commented on packages/core/src/ui/components/Account/EnableAccountPasswordPrompt/EnableAccountPasswordPrompt.tsx
> +      onClose={onCancel}
fixed in b80c193c7839186c6059b7703a5764cf39f37085

2024-03-01 09:52 UTC, mkazlauskas approved these changes
Nice work! Just a suggestion for improving tests

2024-03-01 09:52 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/hooks/__tests__/useWalletManager.test.tsx
> +            passphrase: Buffer.from('passphrase1')
It would be better to add it as a property for in-memory object in `walletTypes`, so that it would run this with `passphrase: undefined` for hardware wallet tests
```suggestion
            passphrase
```

2024-03-01 10:49 UTC, DominikGuzei commented
@mkazlauskas @lucas-barros ready for a final code review (as scope was extended to cover the hardware wallets flow for enabling accounts)

2024-03-01 11:49 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/hooks/__tests__/useWalletManager.test.tsx
> +            passphrase: Buffer.from('passphrase1')
fixed in 1ee859149027bd295768778e4f04dfb13312ee98

2024-03-12 11:07 UTC, merged