feat: move pin extension notification to main screen
input-output-hk/lace pull request #902
Opened 2024-02-20 12:57 UTC by greatertomi

# Checklist

- [x] JIRA - LW-9747
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

move the pin extension notification from the final onboarding step to the main screen

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="519" alt="Screenshot 2024-02-20 at 13 52 47" src="https://github.com/input-output-hk/lace/assets/48496855/7f607d9c-6fb6-41e4-8b2e-58f7cb677ed2">

2024-02-23 08:58 UTC, szymonmaslowski approved these changes
💪

2024-02-23 09:23 UTC, szymonmaslowski commented
I think we should start counting 5 seconds after the user closes the dapp connector popup. Now the pin extension element is barely visible and probably will disappear before the user finishes reading the modal content. It would be good to have a generic mechanism checking if the screen is not covered otherwise there might be a different modal in the future covering this pin extension thing.
![image](https://github.com/input-output-hk/lace/assets/9270461/ace0c221-9a85-4969-927c-1579028d81c5)

The second thing I noticed is that this element covers entirely the account dropdown so the user has no possibility to interact with it. Maybe it could have a close button, or an indicator for when it is going to be hidden, similar to our toasts elements (see below).
![image](https://github.com/input-output-hk/lace/assets/9270461/abbaf2fd-dc51-4e5d-be04-7bd671cbde72)

cc: @vhulchenko-iohk

2024-02-23 09:56 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/PinExtension.module.scss
> +      color: var(--text-color-white, #ffffff) !important;
My heart bleeds seeing that 😭 But we cannot do anything about it because of [this piece of sh**](https://github.com/input-output-hk/lace/blob/0ccc47f6e55c9692d5509cf9d5f8f41cadee61be/apps/browser-extension-wallet/src/views/browser-view/features/settings/components/SettingsLayout.module.scss#L330) which impacts whole lace 😭 😭 😭

2024-02-23 10:12 UTC, shawnbusuttil approved these changes

2024-02-23 10:40 UTC, danielmain approved these changes
I left a question about the constant

2024-02-23 10:40 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +const PIN_EXTENSION_TIMEOUT = 5000;
can we move `PIN_EXTENSION_TIMEOUT` it same as `USE_DESKTOP_LAYOUT` in the envs?

2024-02-23 10:40 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/PinExtension.module.scss
> +      color: var(--text-color-white, #ffffff) !important;
Any possibility to address it on #lace-dev ?

2024-02-23 10:44 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +const PIN_EXTENSION_TIMEOUT = 5000;
I don't think it's the same as `USE_DESKTOP_LAYOUT`, besides the `PIN_EXTENSION_TIMEOUT` is only used in this component, I don't see the need to move it to an env file.

2024-02-23 10:46 UTC, greatertomi commented
> The second thing I noticed is that this element covers entirely the account dropdown so the user has no possibility to interact with it. Maybe it could have a close button, or an indicator for when it is going to be hidden, similar to our toasts elements (see below).

Is this important since the notification will close in 5s?

2024-02-23 11:14 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/PinExtension.module.scss
> +      color: var(--text-color-white, #ffffff) !important;
I asked Michael for a place where I could report that and waiting for the suggestion. Do you think it is worth raising it on our channel?

2024-02-23 11:25 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/PinExtension.module.scss
> +      color: var(--text-color-white, #ffffff) !important;
I don't know, but changing that could have app-wide effects. 😅

2024-02-23 14:52 UTC, vhulchenko-iohk commented
> I think we should start counting 5 seconds after the user closes the dapp connector popup. Now the pin extension element is barely visible and probably will disappear before the user finishes reading the modal content. It would be good to have a generic mechanism checking if the screen is not covered otherwise there might be a different modal in the future covering this pin extension thing. ![image](https://private-user-images.githubusercontent.com/9270461/307273301-ace0c221-9a85-4969-927c-1579028d81c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDAwMTcsIm5iZiI6MTcwODY5OTcxNywicGF0aCI6Ii85MjcwNDYxLzMwNzI3MzMwMS1hY2UwYzIyMS05YTg1LTQ5NjktOTI3Yy0xNTc5MDI4ZDgxYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMTQ0ODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YwZGJmMGJjYTU1NjlkNWZmMTUyMmI5YmExNWE2NjUyNWFmNzY2NzQ2ZWEyMzdjZDdkYTgyZTlkYzU1OWU3YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.stTwFf8Gi9zXmnY5JHSjOHLR-x_gIY-1kPG8B3AHHWk)
> 
> The second thing I noticed is that this element covers entirely the account dropdown so the user has no possibility to interact with it. Maybe it could have a close button, or an indicator for when it is going to be hidden, similar to our toasts elements (see below). ![image](https://private-user-images.githubusercontent.com/9270461/307274541-abbaf2fd-dc51-4e5d-be04-7bd671cbde72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3MDAwMTcsIm5iZiI6MTcwODY5OTcxNywicGF0aCI6Ii85MjcwNDYxLzMwNzI3NDU0MS1hYmJhZjJmZC1kYzUxLTRlNWQtYmUwNC03YmQ2NzFjYmRlNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjNUMTQ0ODM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2Y2YTJmZWE0ODEwZTMyYzc1YjAzZWU4M2RhZDVkNTNkMmVkNTI2YTM2ZWM3OTI1ZGUxNjk3ZDcxZDZhYzlmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.rL_fbuXVDVoGy3vcwna2Ut9ifx8eAyaPA9Q6YbAfRn4)
> 
> cc: @vhulchenko-iohk

Hey @szymonmaslowski, great points. Chatting with the UI/UX designer about them. If OK and agreed, I will have a separate Jira ticket to add these suggested changes. OK?

cc @greatertomi

2024-02-26 13:05 UTC, szymonmaslowski requested changes
One more small request 😉

2024-02-26 13:05 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +    };
We should not use `NodeJS.Timeout` type, as it is not a nodejs runtime. Please use `number` and `window.setTimeout` or consider this change:
```suggestion
    if (showDappBetaModal) return undefined;
    const timer = window.setTimeout(() => {
      setShowPinExtension(false);
    }, PIN_EXTENSION_TIMEOUT);
    return () => window.clearTimeout(timer);
```

2024-02-26 13:14 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +    };
Fixed on a80bda7. Took this approach to avoid the "eslint: consistent-return" 😅

2024-02-26 13:58 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +    };
But then, we would have to fix "ESLint: Do not use useless `undefined`.(unicorn/no-useless-undefined)", and `eslint --fix` automatically removes the undefined. 😄

2024-02-26 13:59 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +    };
I think disabling `eslint: consistent-return` would work perfectly in this case.

2024-02-26 14:37 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +    };
I don't like those `unicorn` rules. I noticed, they complicating the development...

2024-02-26 14:39 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/components/Layout/Layout.tsx
> +    };
I do really like unicorn rules. They generally make the code cleaner. :)

2024-02-28 10:04 UTC, emiride approved these changes
Works as expected. It is good to go.

2024-02-29 14:11 UTC, merged