Feat/lw 9250 lw 9393 browse pools sorting
input-output-hk/lace pull request #904
Opened 2024-02-21 14:29 UTC by tommayeliog

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-03-06 09:37 UTC, vetalcore requested changes

2024-03-06 09:37 UTC, vetalcore commented on apps/browser-extension-wallet/src/stores/slices/stake-pool-search-slice.ts
> +        ...(sort.field === 'ticker' ? { field: 'name' } : {})
```suggestion
        ...(sort.field === SortField.ticker ? { field: SortField.name } : {})
```
if these are available of course*

2024-03-06 09:37 UTC, vetalcore commented on apps/browser-extension-wallet/src/stores/slices/stake-pool-search-slice.ts
> +      // @ts-expect-error TODO remove when ticker sort is available
please attach jira ticket

2024-03-06 09:37 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.tsx
> +  field: 'ticker',
move to enum or add a todo saying it needs to be removed once sdk is updated?

2024-03-06 09:37 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx
> +    // TODO implement analytics for the new flow
do we still need this one?

2024-03-06 09:37 UTC, vetalcore commented on packages/cardano/src/ui/components/NetworkInfo/NetworkInfo.tsx
> +        TODO: uncomment when values are available. Remember that APY is deprecated. Please use ROS
could we attach a jira ticket here?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> +  // TODO consider moving to a single hydration/Setup step
please add jira ticket or remove

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> +        case 'cost':
what was the problem with using enums here?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> -      resetStakePools?.();
u sure this one is not needed?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCard.tsx
> +        value: 'ros',
what was the problem with using the unum here?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCardContainer.tsx
> +  // TODO move filters to the store + useBrowsePools when SDK is ready
please add a todo or remove

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/types.ts
> +  type: 'input' | 'select';
consider creating type?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolCard/PoolMetric/PoolMetric.tsx
> +  blocks: <CubeIcon className={styles.icon} />,
what was the problem with the enum here?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolCard/StakePoolCard.stories.tsx
> +const metricTypeOptions: SortField[] = [
wouldn't it be easier to use an enum here?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsList/config.tsx
> +// TODO move saturation-related logic to higher level e.g. features/staking, as it's not coupled with BrowsePools
please add jira ticket or remove the comment

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePools.tsx
> +      order: store.sortOrder ?? DEFAULT_SORT_OPTIONS.order,
could we have one without another?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/types.ts
> +// TODO remove 'ticker', when it's included in SortFieldSDK
please attach a ticket or remove

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/Drawer/preferences/StepPreferencesContent.tsx
> +      ros: ros ? String(ros) : undefined,
```suggestion
      ...ros && { ros: String(ros) },
```

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/staking/Setup/Setup.tsx
> +  // TODO: remove after we introduce a common hydration setter (cardanoCoin, browsePoolsView, currentPortfolio, view)
please add ticket or remove

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/staking/types.ts
> +export enum StakingPage {
do we have any other pages here?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/mapStakePoolToDisplayData.ts
> +    ros: metrics ? formatPercentages(metrics.ros.valueOf()) : '-',
is it possible to get rid of the fallback values?
imagine we need to replace all the `'-'` with `'n/a'` or similar, it's at least +1 place to change it

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/commands.ts
> +  // TODO: remove after we introduce a common hydration setter (cardanoCoin, browsePoolsView, currentPortfolio, view)
please add ticket or remove

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts
> +          SetBrowsePoolsView: handler<SetBrowsePoolsView, StateBrowsePools, StateBrowsePools>(
is there a way we could just have something like `setpreferences`?

2024-03-06 09:37 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/types.ts
> +// TODO consider using SDK type
please add ticket or remove

2024-03-06 09:37 UTC, vetalcore commented on packages/ui/src/design-system/table/table-row.component.tsx
> +  // TODO fix conflicting prettier and eslint configuration in @lace/ui
please add ticket or remove

2024-03-11 09:03 UTC, vetalcore requested changes

2024-03-11 09:03 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> +  const fetching = status === 'fetching';
could we plz have all the statuses in the enum?

2024-03-11 09:03 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCardContainer.tsx
> +  // TODO move filters to the store + useQueryStakePools when SDK is ready
please attach jira ticket

2024-03-11 09:03 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolsGrid/StakePoolsGrid.tsx
> +        <StakePoolsGridSkeleton columnCount={numberOfItemsPerRow || 3} rowCount={2} />
please extract into the const

2024-03-11 09:03 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
> +        // TODO add a common store hydration command
please attach jira ticket

2024-03-11 09:53 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/stores/slices/stake-pool-search-slice.ts
> +        ...(sort.field === 'ticker' ? { field: 'name' } : {})
Thank you. That's a valid comment, but we no longer have `enum` for this. We know how to transform `enum` to union-type but the other way around seems tricky or impossible (we haven't investigated this in-depth) and we prefer to reuse/extend the union from the SDK (for safety).

2024-03-11 10:15 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePoolsPersistence.tsx
> +        // TODO add a common store hydration command
Done

2024-03-11 10:19 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/stores/slices/stake-pool-search-slice.ts
> +      // @ts-expect-error TODO remove when ticker sort is available
Done, thanks

2024-03-11 10:19 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/table/table-row.component.tsx
> +  // TODO fix conflicting prettier and eslint configuration in @lace/ui
Done, thanks

2024-03-11 10:19 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.tsx
> +  field: 'ticker',
As above. It will remain a union.

2024-03-11 10:21 UTC, przemyslaw-wlodek commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakingContainer.tsx
> +    // TODO implement analytics for the new flow
There's an ongoing discussion between @mchappell and @jackrousian. For now we will keep it like this (in this PR)

2024-03-11 10:24 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolioStore/mapStakePoolToDisplayData.ts
> +    ros: metrics ? formatPercentages(metrics.ros.valueOf()) : '-',
Needs further discussion and a separate ticket. Probably we should use common `formatters` for this and have `null` values?

2024-03-11 10:33 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolioStore/stateMachine/processExpandedViewCases.ts
> +          SetBrowsePoolsView: handler<SetBrowsePoolsView, StateBrowsePools, StateBrowsePools>(
This will be solved at https://input-output.atlassian.net/browse/LW-9979. We need a common hydration logic and then a single command to update the store because there are many properties we persist somehow or require in the first step e.g. `cardanoCoin`, etc.

2024-03-11 10:41 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/StakePoolsGrid/StakePoolsGrid.tsx
> +        <StakePoolsGridSkeleton columnCount={numberOfItemsPerRow || 3} rowCount={2} />
Done

2024-03-11 10:43 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> +        case 'cost':
Same as above. It's an union based on SDK now

2024-03-11 10:54 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/StakePoolsGrid/StakePoolsGrid.tsx
> +        <StakePoolsGridSkeleton columnCount={numberOfItemsPerRow || 3} rowCount={2} />
Done

2024-03-11 10:59 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCardContainer.tsx
> +  // TODO move filters to the store + useQueryStakePools when SDK is ready
Done

2024-03-11 11:27 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> -      resetStakePools?.();
we tested it and it works fine without this.

2024-03-11 11:46 UTC, tommayeliog commented on packages/staking/src/features/BrowsePools/StakePoolsList/StakePoolListCell.tsx
> +  if (sortField === 'saturation' && stakePool.saturation && stakePool.saturation !== '-') {
Good idea, I've created a ticket for this

2024-03-11 12:09 UTC, przemyslaw-wlodek commented on packages/staking/src/features/store/delegationPortfolioStore/types.ts
> +// TODO consider using SDK type
Done, thanks

2024-03-11 12:10 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> -      resetStakePools?.();
Note: There's a new overlay when we switch the networks and I think it may unmount most of the layout until the network switch is done. So it's probably fixed as a side-effect of that.

2024-03-11 12:10 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCardContainer.tsx
> +  // TODO move filters to the store + useBrowsePools when SDK is ready
Done, thanks

2024-03-11 12:13 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/types.ts
> +  type: 'input' | 'select';
I think it's not necessary unless it's reused anywhere or makes anything easier. We can consider this if you think it's more elegant.

2024-03-11 12:28 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/StakePoolsList/config.tsx
> +// TODO move saturation-related logic to higher level e.g. features/staking, as it's not coupled with BrowsePools
This one should be solved when we rebase on top of the latest `main` where you unified this logic ❤️

2024-03-11 12:31 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/hooks/useBrowsePools.tsx
> +      order: store.sortOrder ?? DEFAULT_SORT_OPTIONS.order,
Based on the types we could (we have a flat structure in our store and there's no connection between them).

2024-03-11 12:34 UTC, przemyslaw-wlodek commented on packages/staking/src/features/BrowsePools/types.ts
> +// TODO remove 'ticker', when it's included in SortFieldSDK
Done, thanks!

2024-03-11 12:38 UTC, przemyslaw-wlodek commented on packages/staking/src/features/staking/Setup/Setup.tsx
> +  // TODO: remove after we introduce a common hydration setter (cardanoCoin, browsePoolsView, currentPortfolio, view)
Done, thanks!

2024-03-11 12:38 UTC, przemyslaw-wlodek commented on packages/staking/src/features/staking/types.ts
> +export enum StakingPage {
Nope. it's just more explicit and easier to understand having a Staking prefix.

2024-03-11 13:10 UTC, vetalcore commented on apps/browser-extension-wallet/src/stores/slices/stake-pool-search-slice.ts
> +        ...(sort.field === 'ticker' ? { field: 'name' } : {})
let's wait till our discussion in clack is resolved

2024-03-11 13:10 UTC, vetalcore commented on apps/browser-extension-wallet/src/views/browser-view/features/staking/components/StakePoolsTable/StakePoolsTable.tsx
> +  field: 'ticker',
let's wait till our discussion in clack is resolved

2024-03-11 13:10 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> +        case 'cost':
let's wait till our discussion in clack is resolved

2024-03-11 13:11 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePoolsPreferencesCard/BrowsePoolsPreferencesCard.tsx
> +        value: 'ros',
let's wait till our discussion in clack is resolved

2024-03-11 13:11 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/StakePoolCard/PoolMetric/PoolMetric.tsx
> +  blocks: <CubeIcon className={styles.icon} />,
let's wait till our discussion in clack is resolved

2024-03-11 13:12 UTC, vetalcore commented on packages/staking/src/features/store/delegationPortfolioStore/mapStakePoolToDisplayData.ts
> +    ros: metrics ? formatPercentages(metrics.ros.valueOf()) : '-',
sure, @przemyslaw-wlodek @tommayeliog would you be able to create another (techdebt related)ticket ?

2024-03-11 13:13 UTC, vetalcore commented on packages/staking/src/features/BrowsePools/BrowsePools.tsx
> +  const fetching = status === 'fetching';
let's wait till our discussion in clack is resolved

2024-03-12 12:59 UTC, vetalcore approved these changes

2024-03-12 14:31 UTC, vetalcore approved these changes

2024-03-14 12:09 UTC, vetalcore approved these changes

2024-03-22 14:30 UTC, wklos-iohk approved these changes

2024-03-22 14:30 UTC, mchappell approved these changes

2024-03-22 15:10 UTC, merged