feat: improve hardware wallet setup on onboarding flow
input-output-hk/lace pull request #909
Opened 2024-02-22 13:09 UTC by greatertomi

# Checklist

- [x] JIRA - LW-9809
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Update the account selection screen and remove the "name your wallet" step on the hardware wallet onboarding flow 

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="876" alt="Screenshot 2024-02-22 at 14 07 14" src="https://github.com/input-output-hk/lace/assets/48496855/5639ee4a-b2b4-4f6e-b67e-3ca4d36f99e2">

2024-02-23 10:00 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +  RevampedWalletSetupSelectAccountsStep
Consider keeping the component names the same. But only change the filename so then it's easier after we sync with multi wallet

2024-02-23 10:01 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +  RevampedWalletSetupSelectAccountsStep
Actually just changing the directory should be enough if we put everything in there.

2024-02-23 10:04 UTC, shawnbusuttil commented on packages/core/src/ui/components/RevampedWalletSetup/RevampedWalletSetupSelectAccountsStep.tsx
> +    [isNameValid, t]
Do we really need memo here? The error won't show anyway in the jsx if the name isn't valid.

2024-02-23 10:09 UTC, shawnbusuttil reviewed
Left a few comments.

2024-02-23 11:05 UTC, danielmain requested changes
Small change

2024-02-23 11:11 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +  RevampedWalletSetupSelectAccountsStep
Leaving the component name unchanged would through an error because 2 different components with the same name are exported. I tried this before, but didn't work.

2024-02-23 11:11 UTC, greatertomi commented on packages/core/src/ui/components/RevampedWalletSetup/RevampedWalletSetupSelectAccountsStep.tsx
> +    [isNameValid, t]
Copied this directly from the previous codebase, but would check this.

2024-02-23 11:42 UTC, shawnbusuttil commented on packages/core/src/ui/components/RevampedWalletSetup/RevampedWalletSetupSelectAccountsStep.tsx
> +    [isNameValid, t]
But this in plain english is saying "only store this variable if name is not valid". :S

2024-02-26 09:35 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/wallet-setup/components/HardwareWalletFlow.tsx
> +  RevampedWalletSetupSelectAccountsStep
Renamed the files on 74de25d

2024-02-26 09:36 UTC, greatertomi commented on packages/core/src/ui/components/RevampedWalletSetup/RevampedWalletSetupSelectAccountsStep.tsx
> +    [isNameValid, t]
Fixed on 6843ba4

2024-02-26 12:38 UTC, danielmain approved these changes
Great job @greatertomi

2024-02-28 11:06 UTC, oldGreg5 approved these changes

2024-02-29 14:13 UTC, merged