[UI Toolkit] Add color prop in typography components (Text) [LW-9760]
input-output-hk/lace pull request #916
Opened 2024-02-23 16:12 UTC by przemyslaw-wlodek

# Checklist

- [x] JIRA - \<link>
- [x] Screenshots added.

---

## Proposed solution
Introduce new prop `color` to our Typography components `<Text.*>` to remove redundant custom css styling.

## Testing
Should be mostly covered by Chromatic snapshots but please take a look at the real examples in the browser extension.

## Screenshots
<img width="1511" alt="image" src="https://github.com/input-output-hk/lace/assets/17825044/21511f73-a98f-4aff-8f15-d9fcee612a41">

2024-02-26 08:33 UTC, VanessaPC commented on packages/ui/src/design-system/profile-dropdown/profile-dropdown-wallet-card.component.tsx
> +        <Title color="secondary" data-testid={makeTestId(testId, '-title')}>
as a further improvement, we could probably put the types of button in an enum and export it, 
`export enum ButtonType = { primary, secondary...}` 
not sure what the scope of this ticket was though.

2024-02-26 09:48 UTC, vetalcore requested changes

2024-02-26 09:48 UTC, vetalcore commented on packages/ui/src/design-system/action-card/action-card.component.tsx
> -              className={cn({
please remove an import of classnames lib

2024-02-26 09:48 UTC, vetalcore commented on packages/ui/src/design-system/dialog/dialog-title.css.ts
> -  sx({
ditto

2024-02-26 09:48 UTC, vetalcore commented on packages/ui/src/design-system/file-upload/file-upload.component.tsx
> -              className={cn({
ditto

2024-02-26 10:17 UTC, vetalcore approved these changes

2024-02-26 10:32 UTC, VanessaPC commented on packages/ui/src/design-system/profile-dropdown/profile-dropdown-wallet-card.component.tsx
> +        <Title color="secondary" data-testid={makeTestId(testId, '-title')}>
After a huddle with @przemyslaw-wlodek I realised this is a text component, and that it's better to have the color exposed as it currently is, so ignore my suggestion.

2024-02-26 11:45 UTC, DominikGuzei commented on packages/ui/.eslintrc.js
> +    '@typescript-eslint/no-unused-vars': 'error',
can you give a little context about disabling this rule?

2024-02-26 12:15 UTC, tommayeliog requested changes

2024-02-26 12:15 UTC, tommayeliog commented on packages/ui/src/design-system/asset-input/ticker-button.component.tsx
> +    <Text.SubHeading weight="$bold" color="primary">
@przemyslaw-wlodek isn't it color="primary" by default?

2024-02-26 12:19 UTC, przemyslaw-wlodek commented on packages/ui/.eslintrc.js
> +    '@typescript-eslint/no-unused-vars': 'error',
I am enabling it 😄 It was just a warning before, and it doesn't stop me from committing this (commitlint gave thumbs up).

2024-02-26 12:20 UTC, tommayeliog requested changes

2024-02-26 12:20 UTC, tommayeliog commented on packages/ui/src/design-system/educational-card/educational-card-item.component.tsx
> +      <Text.Body.Large color="primary" weight="$semibold" className={cx.title}>
@przemyslaw-wlodek color="primary" is by default

2024-02-26 12:24 UTC, tommayeliog requested changes

2024-02-26 12:24 UTC, tommayeliog commented on packages/ui/src/design-system/file-upload/file-upload.component.tsx
> +                <Text.Body.Small color="primary" weight="$medium">
color="primary" is by default

2024-02-26 12:24 UTC, tommayeliog commented on packages/ui/src/design-system/profile-dropdown/accounts/profile-dropdown-account-item.component.tsx
> +          color="primary"
color="primary" is by default

2024-02-26 12:24 UTC, tommayeliog commented on packages/ui/src/design-system/profile-dropdown/profile-dropdown-wallet-card.component.tsx
> +            color="primary"
color="primary" is by default

2024-02-26 12:24 UTC, tommayeliog commented on packages/ui/src/design-system/scroll-area/scroll-area.stories.tsx
> +                <Text.Body.Normal color="primary">
color="primary" is by default

2024-02-26 12:29 UTC, tommayeliog approved these changes

2024-02-26 12:31 UTC, DominikGuzei commented on packages/ui/.eslintrc.js
> +    '@typescript-eslint/no-unused-vars': 'error',
ah sorry, my bad :D

2024-02-26 12:32 UTC, DominikGuzei approved these changes

2024-03-19 10:28 UTC, tommayeliog commented on packages/ui/src/design-system/text/text.stories.tsx
> +      <Divider my="$64" />
"Typography" story in Storybook does not match Figma's design from the link in JIRA.
I don't know if Figma was update after you started working on this story.

<img width="796" alt="Screenshot 2024-03-19 at 10 23 32" src="https://github.com/input-output-hk/lace/assets/143514860/48d0c230-5229-4199-80d8-7209f5f09bd8">

2024-04-24 09:57 UTC, merged