fix(staking): clicking on drift warning not working (popup) LW-9438
input-output-hk/lace pull request #918
Opened 2024-02-26 11:51 UTC by tommayeliog

# Checklist

- [ ] JIRA - \[https://input-output.atlassian.net/browse/LW-9438]<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Fixing a bug where popupView param wasn't passed on <StakingNotificationBanners /> for <OverviewPopup />
Affected banners that reads popupView: boolean are:
- for case pendingPortfolioModification
- <PortfolioDriftBanner />

After fixing it when you click on the drift banner on popup, expaned view has been loaded for Staking page.
It's different than the AC on Jira ticket, but discussed with @mchappell and we think that the probably expected result. (TBD)

## Testing
test both for expanded and popup views

## Screenshots

2024-02-26 12:17 UTC, przemyslaw-wlodek approved these changes

2024-02-26 12:25 UTC, vetalcore approved these changes

2024-02-28 13:22 UTC, vetalcore requested changes

2024-02-28 13:22 UTC, vetalcore commented on packages/staking/src/features/overview/hooks.ts
> +        type: onLoadAction as StakingLoadActions,
u could try to pass type into useSearchParams<>?

2024-02-29 21:07 UTC, vetalcore approved these changes

2024-03-01 12:31 UTC, wklos-iohk approved these changes

2024-03-04 13:34 UTC, merged