feat/lw-9804-multi-wallet-modal
input-output-hk/lace pull request #923
Opened 2024-02-28 12:45 UTC by greatertomi

# Checklist

- [x] JIRA - LW-9804
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

2024-02-29 17:28 UTC, shawnbusuttil commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/components/MultiAddressBalanceVisibleModal.tsx
> +      onConfirm={handleCloseModal}
```suggestion
      onConfirm={() =>  setShowMultiAddressModal(false)}
```

2024-02-29 19:37 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/components/MultiAddressBalanceVisibleModal.tsx
> +      onConfirm={handleCloseModal}
Why I did not make this inline is because analytics would be implemented within `handleCloseModal `

2024-03-01 11:38 UTC, shawnbusuttil approved these changes

2024-03-01 11:39 UTC, shawnbusuttil commented
Approved. But please resolve conflicts. 👍

2024-03-03 20:30 UTC, szymonmaslowski requested changes
I think those changes need to take into the consideration the pin extension popup which landed already in the integration branch.

2024-03-03 20:30 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/components/MultiAddressBalanceVisibleModal.tsx
> +import React, { ReactElement } from 'react';
I am not sure the multi-wallet directory is a good place for this modal as it is not really related to the multi-wallet flows. How about putting it in its own dir? I would call it `multi-address`

2024-03-06 16:19 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/components/MultiAddressBalanceVisibleModal.tsx
> +import React, { ReactElement } from 'react';
Fixed on f5592f5

2024-03-07 15:30 UTC, merged