[LW-9877] UI multi wallet issues 2
input-output-hk/lace pull request #927
Opened 2024-02-29 09:02 UTC by VanessaPC

# Checklist

- [x] JIRA - LW-9877
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution
-  updates popover text on duplicated accounts 
- updates tooltip on small screens 

## Testing
- run the app and try to add a duplicate account mnemonic or ledger.
- go to the accounts and hover over the enable ones. 

## Screenshots

<img width="328" alt="Screenshot 2024-02-29 at 08 56 44" src="https://github.com/input-output-hk/lace/assets/4052063/56d2f6c2-7d61-4395-8f9a-1e3fa2a701db">

2024-03-01 10:13 UTC, mkazlauskas requested changes

2024-03-01 10:13 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.tsx
> +          if (error.constructor.name === 'WalletConflictError') {
Original code used to work, isn't it? :thinking: 
It's better to check instanceof, because error class can be renamed or extended
```suggestion
```

2024-03-01 10:13 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/RestoreRecoveryPhrase.tsx
> +      if (error.constructor.name === 'WalletConflictError') {
```suggestion
      if (error instanceof WalletConflictError) {
```

2024-03-01 11:18 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/RestoreRecoveryPhrase.tsx
> +      onSubmit={() => onSubmitForm()}
```suggestion
onSubmit={onSubmitForm}
```

2024-03-01 11:19 UTC, DominikGuzei commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/RestoreRecoveryPhrase.tsx
> +      onChange={(mnemonic: string[]) => setMnemonic(mnemonic)}
```suggestion
onChange={setMnemonic}
```

2024-03-04 13:43 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.tsx
> +          if (error.constructor.name === 'WalletConflictError') {
I have not been able to see it work, I tested various times and check the constructor, meaning there is nothing that should break it or make it not work, and yet it doesn't. This is the only way the pop up would show.

2024-03-04 13:52 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/restore-wallet/steps/RestoreRecoveryPhrase.tsx
> +      onSubmit={() => onSubmitForm()}
updated

2024-03-04 17:08 UTC, DominikGuzei approved these changes

2024-03-05 12:41 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.tsx
> +          if (error.constructor.name === 'WalletConflictError') {
https://input-output.atlassian.net/browse/LW-9877 <- @ljagiela describes the behaviour I see with the code you suggest.

2024-03-06 15:01 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.tsx
> +          if (error.constructor.name === 'WalletConflictError') {
I found the issue: import from `dist/cjs` found it's way back. Fixed it in https://github.com/input-output-hk/lace/pull/927/commits/3c467321af9f39536bcde70509ed66be88856ab2

Probably a bad merge, please confirm @tomislavhoracek.

2024-03-06 15:02 UTC, mkazlauskas approved these changes
Nice work!

2024-03-06 15:28 UTC, VanessaPC commented on apps/browser-extension-wallet/src/views/browser-view/features/multi-wallet/MultiWallet.tsx
> +          if (error.constructor.name === 'WalletConflictError') {
Ah! I didn't know we had at some point fixed the issue with `dist/cjs` I have faced this issue in the past and thought it still unresolved. Thanks!

2024-03-07 16:18 UTC, merged