chore(extension): unify saturation related utils
input-output-hk/lace pull request #931
Opened 2024-03-01 11:06 UTC by vetalcore

# Checklist

- [ ] JIRA -[LW-9552](https://input-output.atlassian.net/browse/)
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-03-01 11:38 UTC, tommayeliog requested changes

2024-03-01 11:38 UTC, tommayeliog commented on packages/cardano/src/ui/util/pool-metrics.ts
> +  let result = SaturationLevels.Medium;
no need for result variable

suggested:
```
for (const [level, [min, max]] of Object.entries(saturationLevelsRangeMap) as Entries<
    typeof saturationLevelsRangeMap
  >) {
    if (inRange(saturation, min, max)) {
      return level;
    }
  }
  return SaturationLevels.Medium;
```

2024-03-01 13:15 UTC, vetalcore commented on packages/cardano/src/ui/util/pool-metrics.ts
> +  let result = SaturationLevels.Medium;
done

2024-03-01 13:23 UTC, tommayeliog approved these changes

2024-03-01 13:49 UTC, vetalcore commented on packages/staking/.storybook/__mocks__/cardano.ts
> +import { poolMetricsUtils } from '@lace/cardano';
@przemyslaw-wlodek any suggestions on how to make this one work? currently vite is aliasing  this import as well

2024-03-11 09:38 UTC, mchappell commented on packages/staking/src/features/overview/StakePoolSearch/StakePoolSearch.tsx
> +  const saturationTooltip =
can we convert this to a switch statement func for readability?

2024-03-11 10:01 UTC, vetalcore commented on packages/staking/src/features/overview/StakePoolSearch/StakePoolSearch.tsx
> +  const saturationTooltip =
done

2024-03-11 10:01 UTC, mchappell approved these changes

2024-03-11 10:29 UTC, merged