test(extension): refactor e2e initial staking test
input-output-hk/lace pull request #932
Opened 2024-03-01 16:40 UTC by ljagiela

2024-03-04 09:11 UTC, wklos-iohk requested changes

2024-03-04 09:11 UTC, wklos-iohk commented on packages/e2e-tests/src/fixture/walletRepositoryBuilder.ts
> +export const getWalletsFromRepository = async (): Promise<number> =>
Not sure if I understand it properly, but function name indicates that it returns wallets, but return type says that we would get only one element of Promise<number> which is misleading.

2024-03-04 09:11 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/stakingSteps.ts
> +Then(/^The Tx details are displayed for Staking (with|without) metadata$/, async (_ignored: 'with' | 'without') => {
Why do we ignore `with|without` parameter?

2024-03-08 12:07 UTC, ljagiela commented on packages/e2e-tests/src/features/e2e/StakingInitialFundsE2E.feature
> +    And I send back all tADA to the "WalletSendingAdaToStakingE2E" wallet
I don't thin it's worth it. If the test fails on one of the 1~20 steps the hook will fail anyways.

2024-03-08 12:15 UTC, ljagiela commented on packages/e2e-tests/src/steps/onboardingSteps.ts
>    await settingsExtendedPageObject.switchNetworkAndCloseDrawer('Preprod', 'extended');
this is legacy code. I don't think it's worth to take it form env, as this is new wallet and it depends on test Logic to which network we want to switch. I think it would make more sense to parametrise this step, but it can be handled separately.

2024-03-08 12:28 UTC, ljagiela commented on packages/e2e-tests/src/steps/stakingSteps.ts
> +Then(/^The Tx details are displayed for Staking (with|without) metadata$/, async (_ignored: 'with' | 'without') => {
this parameter should not be required anymore. I left it for the backwards compatibility and to keep sense of some tests. It might be improved in further tickets.

2024-03-08 14:21 UTC, wklos-iohk approved these changes

2024-03-08 14:58 UTC, bslabiak commented on packages/e2e-tests/src/fixture/walletRepositoryInitializer.ts
> +};
This method fits better to `localStorageInitializer` class

2024-03-08 15:04 UTC, bslabiak commented on packages/e2e-tests/src/features/e2e/StakingInitialFundsE2E.feature
> +    And I send back all tADA to the "WalletSendingAdaToStakingE2E" wallet
Do we really need this step for this scenario? It extending execution time, increasing number of transactions/syncing time in future. Feed source wallet 2 times with faucet should be enough

2024-03-08 15:31 UTC, bslabiak approved these changes

2024-03-08 15:55 UTC, merged