feat: move the register screen after the mnemonic screen for create and restore flow
input-output-hk/lace pull request #945
Opened 2024-03-11 17:20 UTC by greatertomi

# Checklist

- [x] JIRA - LW-10000
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

This PR moves the register screen after the mnemonic screen on the  create and restore onboarding flow

## Testing

Follow the normal onboarding flow

## Screenshots

<img width="918" alt="Screenshot 2024-03-11 at 18 22 07" src="https://github.com/input-output-hk/lace/assets/48496855/a86320e7-255d-4c48-a293-fa10d17430dc">

<img width="881" alt="Screenshot 2024-03-11 at 18 22 38" src="https://github.com/input-output-hk/lace/assets/48496855/17e92a17-76db-418d-8d65-a4530801f833">

2024-03-12 09:35 UTC, shawnbusuttil commented on packages/core/src/ui/components/WalletSetup/wallet-steps.ts
> -  [WalletSetupSteps.Create]: {
Doesn't create need to stay for the third step to exist?

2024-03-12 09:35 UTC, shawnbusuttil reviewed
Nice job. Left a question.

2024-03-13 23:55 UTC, szymonmaslowski commented on packages/core/src/ui/components/WalletSetup/wallet-steps.ts
> -  [WalletSetupSteps.Create]: {
I get this point of view that a simple enum would do, however, IMO since we have this structure already implemented I would not invest in rewriting it to an enum as it also gives a value. I like that it is separated from the view. If I was implementing that from scratch I would go with enum, but since we have it, I would keep it 😉

2024-03-14 09:20 UTC, greatertomi commented on packages/core/src/ui/components/WalletSetup/wallet-steps.ts
> -  [WalletSetupSteps.Create]: {
Same. It would keep the current linked list structure. It's more extensible incase there's a need to add more steps in the future.

2024-03-14 11:14 UTC, shawnbusuttil approved these changes

2024-03-15 07:10 UTC, szymonmaslowski requested changes
Goof Job. Left one comment.

2024-03-15 07:10 UTC, szymonmaslowski commented on packages/core/src/ui/lib/translations/en.json
> +      "enterWallet": "Enter wallet",
I guess those translations are supposed to be placed in the browser translations. Could you move them there? Otherwise, it will be inconsistent to have translations for a single step separate from others.

There is also a `walletSetupStep` key in this file that would be also worth moving.

2024-03-15 09:24 UTC, greatertomi commented on packages/core/src/ui/lib/translations/en.json
> +      "enterWallet": "Enter wallet",
There is no clear strategy for translations. I remember, there was a plan to move translations into their packages started by this https://github.com/input-output-hk/wallet-world/pull/1407, and that is why there is a translation file inside the core package.

I would move this step's translation into the browser's translation file since it differs from the rest, but there might be a need to move translations within their packages to avoid the unnecessary passing around of translation strings.

2024-03-15 10:40 UTC, greatertomi commented on packages/core/src/ui/lib/translations/en.json
> +      "enterWallet": "Enter wallet",
Moved the translations from `core` package on 691d532. 

I am doubtful about the importance of this change though as it affects multi-wallet codebase, and the discussion around if core should should be a UI library is something that should be done separately. I favour us leaving the translation file for this component the way it currently is. 🙂

2024-03-18 07:02 UTC, szymonmaslowski requested changes

2024-03-18 07:02 UTC, szymonmaslowski commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
>    }, [t, walletName]);
Please fix the warning about dependency array

2024-03-18 08:49 UTC, greatertomi commented on packages/core/src/ui/components/WalletSetup/WalletSetupNamePasswordStep/WalletSetupNamePasswordStep.tsx
> +    | 'enterWallet'
Fixed on 4c3020c

2024-03-18 08:59 UTC, szymonmaslowski approved these changes

2024-03-18 09:02 UTC, merged