fix(extension): delete all wallets in 'forgot password' flow
input-output-hk/lace pull request #947
Opened 2024-03-12 06:42 UTC by mkazlauskas

Forgot Password flow implementation was deleting the wallet and opening the Restore Wallet onboarding flow.

When we introduced multi-wallet, deleting the locked/active wallet left Lace in a faulty state, where it would still have other wallets remaining, but still locked with the passphrase of the deleted wallet.

# Checklist

- [x] JIRA - LW-10007
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

This fix deletes all wallets when user goes into Forgot Password flow.

## Testing

LW-10007

## Screenshots

No UI changes

2024-03-12 08:50 UTC, VanessaPC approved these changes
LGTM!

2024-03-12 10:50 UTC, DominikGuzei approved these changes

2024-03-12 13:01 UTC, rhyslbw requested changes

2024-03-12 14:06 UTC, mkazlauskas commented on apps/browser-extension-wallet/src/lib/translations/en.json
> +    "description": "By confirming this action we will unpair your wallets and request to input your mnemonic seed phrase.",
Removed the change to translations as we decided to disable the feature instead

2024-03-12 15:14 UTC, DominikGuzei approved these changes

2024-03-12 15:18 UTC, rhyslbw approved these changes

2024-03-13 10:34 UTC, ljagiela requested changes

2024-03-13 14:27 UTC, mkazlauskas commented on packages/e2e-tests/src/features/LockWalletPopup.feature
> +  @LW-3038 @Pending
Done in https://github.com/input-output-hk/lace/pull/947/commits/e0adf8192a5fc0b67567d0e64ad04a71ab1260a7

2024-03-13 14:40 UTC, ljagiela approved these changes

2024-03-13 16:12 UTC, merged