Feat/lw 9998 revamp e2e fixes
input-output-hk/lace pull request #949
Opened 2024-03-12 11:53 UTC by emiride

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-03-21 16:40 UTC, danielmain approved these changes

2024-03-21 16:44 UTC, greatertomi approved these changes

2024-03-22 08:50 UTC, wklos-iohk requested changes

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/onboarding/recoveryPhrasePage.ts
>    get mnemonicAutocompleteDropdown(): ChainablePromiseElement<WebdriverIO.Element> {
Unused code, are we missing some kind of verification for mnemonic dropdown?

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/onboarding/recoveryPhrasePage.ts
>    async getMnemonicAutocompleteOptionsValues(): Promise<string[]> {
as above

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/onboarding/recoveryPhrasePage.ts
>    private WATCH_VIDEO_LINK = '[data-testid="find-out-more-link"]';
as above

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/onboarding/recoveryPhrasePage.ts
> +  private COPY_TO_CLIPBOARD_BUTTON = '[data-testid="copy-to-clipboard"]';
Please use more meaningful ids like `copy-to-clipboard-button`

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/walletAddressPageAssert.ts
> +      await WalletAddressPage.drawerNavigationTitle.waitForStable();
Please remember that `waitForStable()` does not replace `waitForDisplayed()`, however it can be useful to make tests more stable.

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingWalletSetupPageAssert.ts
> +  async assertSeePasswordConfirmInput() {
Unused code

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingWalletSetupPageAssert.ts
> +    await walletSetupPage.walletNameInput.waitForDisplayed();
How about adding placeholder/default value verification?

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingWalletSetupPageAssert.ts
> +    await walletSetupPage.walletPasswordInput.waitForDisplayed();
How about adding placeholder/default value verification?

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingWalletSetupPageAssert.ts
> +    if (shouldSee) {
Missing verification for `shouldSee === false`

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingWalletSetupPageAssert.ts
> +    await this.assertNextButtonTextEquals(await t('package.core.walletNameAndPasswordSetupStep.enterWallet'));
Do we need to verify button label here? It's already done in `assertSeeEnterWalletButton()`

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingRecoveryPhrasePageAssert.ts
> +import recoveryPhrasePage from '../../elements/onboarding/recoveryPhrasePage';
There might be some overlap between this file and `onboardingMnemonicPageAssert.ts` please verify that.
I'd suggest to have separate POMs for both pages that are under `Recovery phrase` step in wallet creation flow.

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/assert/onboarding/onboardingRecoveryPhrasePageAssert.ts
> +    expect((await recoveryPhrasePage.mnemonicWords.length).toString()).to.equal(mnemonicWordsLength);
`String(...)` is a little bit safer than `.toString()`

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/onboardingSteps.ts
> +    switch (endPage) {
Please do not forget about adding `default` statement at the end of `switch...case`

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/pageobject/onboardingRevampPageObject.ts
> +    await clearInputFieldValue(inputs[inputNumber]);
Why do we need to clear the input field?

2024-03-22 08:50 UTC, wklos-iohk commented on packages/e2e-tests/src/pageobject/onboardingRevampPageObject.ts
> +      await clearInputFieldValue(mnemonicInputs[i]);
as above

2024-03-23 00:49 UTC, oldGreg5 commented on packages/e2e-tests/src/assert/onboarding/onboardingMainPageAssert.ts
> +      'By proceeding you agree to Lace’s Terms of Service and Privacy Policy'
It's a devs omission, we have a ticket for this [here](https://input-output.atlassian.net/browse/LW-10073), I added info about this tests changes that need to be done after it's resolved.

2024-03-23 00:51 UTC, oldGreg5 commented on packages/e2e-tests/src/assert/onboarding/onboardingMainPageAssert.ts
> +    expect(await OnboardingMainPage.agreementTermsOfServiceLink.getText()).to.equal('Terms of Service');
same

2024-03-23 00:52 UTC, oldGreg5 commented on packages/e2e-tests/src/assert/onboarding/onboardingMainPageAssert.ts
> +    expect(await OnboardingMainPage.agreementPrivacyPolicyLink.getText()).to.equal('Privacy Policy');
same

2024-03-23 00:59 UTC, oldGreg5 commented on packages/e2e-tests/src/assert/onboarding/onboardingCommonAssert.ts
> +    await this.commonOnboardingElements.stepTitle.waitForStable();
I only use it when it helps. Issue is when running on powerful enough PC locally in parallel then wdio sometimes tries to interact with an element that is visible but not interactable yet.

2024-03-23 01:09 UTC, oldGreg5 commented on packages/e2e-tests/src/pageobject/onboardingPageObject.ts
> +      await WalletCreationPage.mainLoaderText.waitForDisplayed({ timeout: 255_000, reverse: true });
Slow Preprod solely

2024-03-23 01:11 UTC, oldGreg5 commented on packages/e2e-tests/src/pageobject/settingsExtendedPageObject.ts
> +      await Modal.title.waitForDisplayed({ reverse: true, timeout: 220_000 });
Just slow Preprod again

2024-03-23 01:17 UTC, oldGreg5 commented on packages/e2e-tests/src/pageobject/settingsExtendedPageObject.ts
>    async multiAddressModalConfirm() {
It is shown now after restoring HD wallet, when wallet is loaded and wallet has used more than 1 payment address.

2024-03-24 22:50 UTC, emiride commented on packages/e2e-tests/src/assert/localStorageAssert.ts
> -    expect(JSON.parse(await localStorageManager.getItem('analyticsStatus'))).to.be.null;
I don't remember deleting this. What about you @oldGreg5 ?

2024-03-24 22:51 UTC, emiride commented on packages/e2e-tests/src/assert/onboarding/onboardingAllDonePageAssert.ts
> -class OnboardingAllDonePageAssert extends OnboardingCommonAssert {
I think we did that, there are no references to it in the project. Did you find some?

2024-03-24 22:55 UTC, emiride commented on packages/e2e-tests/src/assert/onboarding/onboardingCommonAssert.ts
>        await t('settings.legals.cookiePolicy')
I don't remember that we touched this. Furthermore, is this a relevant file where this is set:
https://github.com/input-output-hk/lace/blob/59f4ff75c2edaae6b7d282e7fb13d74ff8294151/apps/browser-extension-wallet/src/views/browser-view/components/Layout/WalletSetupLayout.tsx#L41C1-L68C11

2024-03-25 03:42 UTC, oldGreg5 commented on packages/e2e-tests/src/elements/onboarding/mnemonicInfoPage.ts
> +  private MNEMONIC_VIDEO_FRAME = '[data-testid="find-out-more-link"]';
This is actually dead code, I changed naming for the used one in recoveryPhrasePage

2024-03-25 08:18 UTC, emiride commented on packages/e2e-tests/src/assert/onboarding/onboardingAllDonePageAssert.ts
> -class OnboardingAllDonePageAssert extends OnboardingCommonAssert {
I deleted onboardingAllDonePage and resolved the references.

2024-03-25 08:19 UTC, emiride commented on packages/e2e-tests/src/assert/localStorageAssert.ts
> -    expect(JSON.parse(await localStorageManager.getItem('analyticsStatus'))).to.be.null;
We have put it back.

2024-03-25 11:35 UTC, merged