feat(ui): create <SideDrawer /> component
input-output-hk/lace pull request #95
Opened 2023-06-07 20:43 UTC by renanvalentin

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2023-06-12 22:36 UTC, szymonmaslowski requested changes

2023-06-12 22:36 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-content.css.ts
> +    zIndex: '$dialog',
I am an opponent of zIndexes 😛 In most cases we are able to develop components with no zIndexes usage, but instead using portals + stacking (later in the tree gets rendered above).
Usefull articles:
 - https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_positioned_layout/Understanding_z-index/Stacking_without_z-index
 - https://www.codegram.com/blog/stop-ab-using-z-index/
 - https://danielrotter.at/2020/04/08/avoid-z-index-whenever-possible.html

Can we by default go with not setting the zIndex and give a possibility through the API to enable it in case it would be necessary? Probably in the extension which is already using zIndexes broadly it will be ncecessary. But we are building here something fresh which should be flexible but not influenced by any bad design which zIndexes often tend to become. Of course there are technics to manage zIndexes, but if we can avoid it (and we can in majority of cases) why son't we do that?

2023-06-12 22:36 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-content-body.component.tsx
> +import type { ReactNode } from 'react';
Do you have a strong opion on including the `content` word in the file names? I am not convinced TBH... Maybe we could avoid this word, what do you think?

2023-06-12 22:36 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-content-headline.css.ts
> +    height: '1.5px',
Could you make sure this exceptional value is for sure required? There is no that much difference bewtween 1.5 and 2. So maybe we could stay with 2 which is defined in the spacing.

In case of the card component it turned out all the 1.5s could be changed to 2 and we achieved a standarisation 😉

2023-06-12 22:36 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-content.css.ts
> +globalStyle(`#storybook ${storybook}`, {
Please move it to a separate storybook related helper file and import in the stories that require it. Let's not pollute the drawer with unnecesary styles.

2023-06-12 22:36 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-overlay.css.ts
> +    animation: `${overlayShow} 150ms cubic-bezier(0.16, 1, 0.3, 1)`,
Should we have animations defined at the theme level? IMO we could have a comon set of animations to aply to different components in order to achieve a consistency.

2023-06-13 14:12 UTC, renanvalentin commented on packages/ui/src/design-system/side-drawer/side-drawer-content-headline.css.ts
> +    height: '1.5px',
I spoke with Elena and the UX team is implementing a 1.5px for border and separator.

2023-06-13 14:13 UTC, renanvalentin commented on packages/ui/src/design-system/side-drawer/side-drawer-content.css.ts
> +globalStyle(`#storybook ${storybook}`, {
To prevent the position fixed and enable display on storybook, I've created a new content-card component and extracted the styling.

2023-06-13 14:15 UTC, renanvalentin commented on packages/ui/src/design-system/side-drawer/side-drawer-overlay.css.ts
> +    animation: `${overlayShow} 150ms cubic-bezier(0.16, 1, 0.3, 1)`,
If the animation pops up again, I might think about doing something about it. But for now, it's okay to keep it within the overlay range.

2023-06-13 16:20 UTC, pczeglik-iohk approved these changes
To me it looks really good. I have nothing to point out. Thank you

2023-06-14 21:39 UTC, szymonmaslowski approved these changes
Looks good! I left a few minor comments.

2023-06-14 21:39 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-content.component.tsx
> +  zIndex,
Please confirm: The purpose of the `zIndex` prop here is to allow to render the `Content` component without the `Overlay` component, right?

2023-06-14 21:39 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-content-card.component.tsx
> +  ...props
There are no more props than the `children`

2023-06-14 21:39 UTC, szymonmaslowski commented on packages/ui/src/design-system/side-drawer/side-drawer-content-card.component.tsx
> +  <Box {...props} className={classNames(cx.container)}>
`classNames` is redundant here.

2023-06-15 11:40 UTC, przemyslaw-wlodek requested changes

2023-06-15 11:40 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-content-body.component.tsx
> +import type { ReactNode } from 'react';
For me it's better to be explicit, but I have another concern about why are we having a different **name** for the file and the main export of that file. It disables some nice refactoring features (poor DX)

2023-06-15 11:40 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-close.component.tsx
> +export const Close = ({ children }: Readonly<Props>): JSX.Element => (
Do we need this component? What's the benefit of wrapping it in our naming if it has just the `asChild` property? 🤔 

Or should we introduce our `NavigationButtons.Close` here?

```
      <Dialog.Close asChild>
        <NavigationButtons.Close onClick={onCloseClick} />
      </Dialog.Close>
```

2023-06-15 11:40 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-content-card.component.tsx
> +interface Props {
This may be a point to RFC but can we please name props according to their component names (`ContentCardProps`)? When we export components we should also export their props interfaces and then you need to rename them during re-exports which would be ugly. 😅

2023-06-15 11:40 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-content-header.component.tsx
> +  onCloseClick?: () => void;
Shouldn't this prop be required? We are always rendering the Close button.

2023-06-15 11:40 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-content-header.component.tsx
> +    </Box>
I think this should be part of the parent component which renders sub-components.

2023-06-15 11:40 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-content-headline.css.ts
> +    height: '1.5px',
@mrcnk had the same question and Elena agreed to round these values to 2px. I also asked UI/UX team to round them by default to all future designs. Can we please change it?

2023-06-15 11:40 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-overlay.css.ts
> +    animation: `${overlayShow} 150ms cubic-bezier(0.16, 1, 0.3, 1)`,
@mrcnk, you had some great ideas around that like using [framer-motion](https://www.framer.com/motion/). I think it's better to ignore the animation for now (MVP) than deliver the wrong approach which will spread around the codebase.

2023-06-15 12:18 UTC, renanvalentin commented on packages/ui/src/design-system/side-drawer/side-drawer-content-card.component.tsx
> +interface Props {
In this context, what is the purpose of exporting the Props interface? From my perspective, it doesn't seem necessary, so I suggest leaving it as is.

Regarding naming convention, it may become a bit noisy if there is no ESLINT rule in place to guard it, as personal preferences may come into play.

2023-06-15 12:30 UTC, renanvalentin commented on packages/ui/src/design-system/side-drawer/side-drawer-content-header.component.tsx
> +    </Box>
To ensure that the border is always displayed, it is important to include the `<Separator/>` in the `<Header/>`. Otherwise, the SideDrawer may be displayed without the border, which would be incorrect from a UI perspective.

```
<SideDrawer.Content>
    <SideDrawer.Header
      text="Label"
      onBackClick={onBackClick}
      onCloseClick={onCloseClick}
    />
    
    <SideDrawer.Body>
      <SideDrawer.Headline
        title="Section title"
        description="Lorem ipsum dolor sit amet quare id faciam."
      />
    </SideDrawer.Body>
```

2023-06-16 13:06 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-content-headline.css.ts
> +    height: '1.5px',
I see your comment. What I'm trying to say is that @mrcnk also spoke with the Design team and told them that using fractions in px values is likely an antipattern. Then I spoke with the Design team and confirmed that Elena will update all our designs to use 2px instead of 1.5px. So could you update it, please?

2023-06-16 13:13 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-content-header.component.tsx
> +    </Box>
Fine. I thought it was `Header` not `SideDrawerHeader` component.

2023-06-16 13:21 UTC, przemyslaw-wlodek commented on packages/ui/src/design-system/side-drawer/side-drawer-overlay.css.ts
> +    animation: `${overlayShow} 150ms cubic-bezier(0.16, 1, 0.3, 1)`,
That's just an idea and we can leave it as is but I will create a ticket for future investigation.

2023-06-16 13:21 UTC, renanvalentin commented on packages/ui/src/design-system/side-drawer/side-drawer-content-headline.css.ts
> +    height: '1.5px',
> I see your comment. What I'm trying to say is that @mrcnk also spoke with the Design team and told them that using fractions in px values is likely an antipattern. Then I spoke with the Design team and confirmed that Elena will update all our designs to use 2px instead of 1.5px. So could you update it, please?

It seems we have a miscommunication problem, my suggestion is to merge using 1.5px as per Figma and create a broader alignment with the UX team. 

If the UX team confirms and updates the designs to match the new spec, we go back and refactor it. It is unlikely this discussion will get sorted out in a few minutes and I want to merge before closing the sprint.

2023-06-16 13:49 UTC, przemyslaw-wlodek approved these changes

2023-06-16 19:13 UTC, merged