feat(staking): add default sorting for  browse pools [LW-10104]
input-output-hk/lace pull request #985
Opened 2024-03-25 16:23 UTC by tommayeliog

# Checklist

- [X] JIRA - [LW-10104](https://input-output.atlassian.net/browse/LW-10104)
- [-] Proper tests implemented
- [-] Screenshots added.

---

## Proposed solution
Utility function for default sorting exposed in BrowsePools feature.
On List view header click - if changing sort file, then using the new default sort order, otherwise reverse order.
On Sorting list (right-side) - if click on sort field - use the default sort order.

Legacy Staking supported as well 

## Testing
Please test legacy staking (hardware wallets)

## Screenshots
N/A

2024-03-25 16:30 UTC, mchappell requested changes
Looks great, just need a test in the staking package to show it as an example

2024-03-26 08:04 UTC, vetalcore approved these changes

2024-03-27 13:30 UTC, mchappell approved these changes

2024-04-03 12:49 UTC, mchappell requested changes

2024-04-04 12:09 UTC, mchappell approved these changes

2024-04-09 14:57 UTC, wklos-iohk approved these changes

2024-04-10 12:15 UTC, merged