feat: add search text box to tokens page
input-output-hk/lace pull request #986
Opened 2024-03-25 17:21 UTC by greatertomi

# Checklist

- [x] JIRA - LW-10022
- [ ] Proper tests implemented
- [x] Screenshots added.

---

## Proposed solution

Add search text box to tokens page

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

<img width="953" alt="Screenshot 2024-03-25 at 18 16 49" src="https://github.com/input-output-hk/lace/assets/48496855/17c4bf78-10d7-4cb7-9f3b-df8941e7fb47">

2024-03-28 16:25 UTC, danielmain requested changes
Vnery small suggestions

2024-03-28 16:25 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +  const handleSearch = (value: string) => {
can we use useCallback here?

2024-03-28 16:25 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +          onChange={(text) => handleSearch(text)}
This can be written like this:

`onChange={handleSearch}`

2024-03-28 16:25 UTC, danielmain commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +  return data.filter((item: any) =>
How much work to replace this any with a proper type? is not here IRow?

2024-04-02 09:00 UTC, szymonmaslowski requested changes
GJ 👍

2024-04-02 09:00 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +  return data.filter((item: any) =>
Why not just remove it? TS will infer the type.
```suggestion
  return data.filter((item) =>
```

2024-04-02 09:00 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +  const fields = ['name', 'policyId', 'fingerprint']; // Fields to search
Two suggestions here. Consider removing the comment because IMO it is obvious. Try adding `as const` at the end so then it helps TS recognize those values can be used as keys for the data.

```suggestion
  const fields = ['name', 'policyId', 'fingerprint'] as const;
```

2024-04-02 09:00 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +const SEARCH_ASSET_LENGTH = 10;
```suggestion
const MIN_ASSETS_COUNT_FOR_SEARCH = 10;
```

2024-04-02 09:00 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +      {currentAssets.total > 0 ? (
Suggestion: turn each ternary into two separate conditions. IMO now when you scroll down to the "else" markup its harder to locate the condition for which it gets rendered, and here it is even harder because there are two ternaries nested, it would be nicer if the condition was standing just before the markup.

```suggestion
      {currentAssets.total > 0 && (
```

2024-04-02 16:36 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +          onChange={(text) => handleSearch(text)}
Fixed on 55a094f

2024-04-02 16:36 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +  return data.filter((item: any) =>
Fixed on 55a094f

2024-04-02 16:37 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +  const fields = ['name', 'policyId', 'fingerprint']; // Fields to search
Fixed on 55a094f

2024-04-02 16:37 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +const SEARCH_ASSET_LENGTH = 10;
Fixed on 55a094f

2024-04-02 16:37 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +      {currentAssets.total > 0 ? (
Fixed on 55a094f

2024-04-03 08:08 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +  const handleSearch = (value: string) => {
I learned that the `handleSearch` function would re-render on `assetList`. 👍🏽 
Fixed on b3040f9.

2024-04-03 08:15 UTC, danielmain approved these changes
Great job!

2024-04-03 10:13 UTC, szymonmaslowski approved these changes
Leaving last comment. It is not a major one, so givin an approval already, but please adress it 😉

2024-04-03 10:13 UTC, szymonmaslowski commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +// eslint-disable-next-line complexity
Please reduce the complexity instead of suppressing the error 🙏 . You could extract `useMemo` functions to the top of the file.

Or you could extract whole hooks
```
const useIsPortfolioBalanceLoading = ({ isBalanceLoading, portfolioTotalBalance }) => useMemo(
    () => new BigNumber(portfolioTotalBalance).isNaN() || isBalanceLoading,
    [isBalanceLoading, portfolioTotalBalance]
  );
...
const isPortfolioBalanceLoading = useIsPortfolioBalanceLoading({ isBalanceLoading, portfolioTotalBalance });
```

2024-04-04 10:25 UTC, greatertomi commented on apps/browser-extension-wallet/src/views/browser-view/features/assets/components/AssetsPortfolio/AssetsPortfolio.tsx
> +// eslint-disable-next-line complexity
Improve AssetPortfolio component on 4060eae

2024-04-09 13:43 UTC, merged