Lw 10137 onboarding tech debt
input-output-hk/lace pull request #991
Opened 2024-03-26 16:26 UTC by emiride

# Checklist

- [ ] JIRA - \<link>
- [ ] Proper tests implemented
- [ ] Screenshots added.

---

## Proposed solution

Explain how does this PR solves the problem stated in JIRA ticket.
You can also enumerate different alternatives considered while approaching this task.

## Testing

Describe here, how the new implementation can be tested.
Provide link or briefly describe User Acceptance Criteria/Tests that need to be met

## Screenshots

Attach screenshots here if implementation involves some UI changes

2024-03-29 11:04 UTC, ljagiela requested changes

2024-03-29 11:04 UTC, ljagiela commented on packages/e2e-tests/src/features/analytics/AnalyticsForgotPassword.feature
> -    And I am on "Mnemonic verification" last page from "Forgot password" and filled all words
is it expected?

2024-03-29 11:04 UTC, ljagiela commented on packages/e2e-tests/src/elements/MainLoader.ts
> +  async waitUntilLoaderDisappears() {
I like it!

2024-04-01 07:35 UTC, emiride commented on packages/e2e-tests/src/elements/onboarding/mainPage.ts
> +  async restoreWallet(): Promise<void> {
I am completely fine with , that, it was part of onboardingPageObject and when trying to get rid of it, I moved it here. I will move it to steps.

2024-04-01 09:51 UTC, emiride commented on packages/e2e-tests/src/features/analytics/AnalyticsForgotPassword.feature
> -    And I am on "Mnemonic verification" last page from "Forgot password" and filled all words
This whole feature file is pending, so steps here will need to be changed altogether. During the refactoring this steps was removed from all other places, but only this one was left. To preserve what step was there I commented it out. @oldGreg5 is currently working on these analytics tests.

2024-04-01 09:52 UTC, emiride commented on packages/e2e-tests/src/elements/onboarding/mainPage.ts
> +  async restoreWallet(): Promise<void> {
OK in the meantime I actually did that, I just forgot to remove this method. Thanks for noticing.

2024-04-02 09:04 UTC, emiride commented on packages/e2e-tests/src/elements/onboarding/mainPage.ts
> +  async clickOnLegalLink(link: string, isMainPage = false): Promise<void> {
resolved

2024-04-02 09:24 UTC, ljagiela approved these changes

2024-04-02 13:33 UTC, wklos-iohk commented
Can we remove `OnboardingLegalPage.ts` and relevant usages of this page? It doesn't seem to be needed anymore

2024-04-02 15:11 UTC, wklos-iohk requested changes

2024-04-02 15:11 UTC, wklos-iohk commented on packages/e2e-tests/src/pageobject/onboardingPageObject.ts
Can you please try to move all necessary bits of code to respective POMs and get rid of this file?

2024-04-02 15:11 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/onboardingSteps.ts
> +// const validPassword = 'N_8J@bne87A';
Is this needed?

2024-04-02 15:11 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/onboardingSteps.ts
> +  OnboardingWalletSetupPage.clickEnterWalletButton();
Missing `await` keyword

2024-04-02 22:41 UTC, emiride commented on packages/e2e-tests/src/elements/onboarding/mainPage.ts
> +  async clickOnLegalLink(linkText: string, isMainPage = false): Promise<void> {
Completely agree, thanks for this

2024-04-03 13:51 UTC, emiride commented on packages/e2e-tests/src/elements/onboarding/recoveryPhrasePage.ts
> +  async clickHeaderToLooseFocus() {
fixed

2024-04-04 07:19 UTC, wklos-iohk commented on packages/e2e-tests/src/elements/MainLoader.ts
> +  get mainLoaderText() {
seems to be unused

2024-04-04 07:30 UTC, wklos-iohk commented on packages/e2e-tests/src/features/OnboardingRestoreWallet.feature
>    Scenario Outline: Restore Wallet - "Recovery phrase length page" restore <mnemonicLength> words happy path
We might need to update scenario titles, as there is no such page like `Recovery phrase length page`

2024-04-04 07:34 UTC, wklos-iohk commented on packages/e2e-tests/src/steps/multidelegationSteps.ts
> +const validPassword = 'N_8J@bne87A';
This variable has only one usage

2024-04-04 07:37 UTC, wklos-iohk approved these changes
LGTM!

Minor comments added, you may handle them in separate PR.

2024-04-04 07:37 UTC, merged